Repository erda-project/erda-ui, pull requests merged in 2021-06, with the labels that each got.

#270 upgrade case
  core/package-lock.json
  shell/app/common/__tests__/components/common-range-picker.test.tsx
  shell/app/common/__tests__/components/delete-confirm.test.tsx
  shell/app/common/__tests__/components/dropdown-select.test.tsx
  shell/app/common/__tests__/components/edit-field.test.tsx
  shell/app/common/__tests__/components/edit-list/edit-list.test.tsx
  shell/app/common/__tests__/components/key-value-table.test.tsx
  shell/app/common/__tests__/components/monitor/components/timeRangeSelector.test.tsx
  shell/app/common/__tests__/components/paging-table.test.tsx
  shell/app/common/components/edit-field.tsx
  shell/app/common/components/edit-list/edit-list.tsx
  shell/jest.config.js
  shell/package-lock.json
Labels: lgtm

#277 remove node command when invoke webpack build
  core/package.json
  shell/package.json
Labels: lgtm

#272 fix: scenes execute result error
  shell/app/modules/project/pages/auto-test/scenes.tsx
Labels: lgtm

#273 process analysis set default instance
  shell/app/modules/microService/monitor/service-list/pages/process.tsx
Labels: lgtm

#281 feature: add envs to dice.yml
  dice.yml
Labels: lgtm

#290 fix: fix the sidebar icon style problem
  cli/package.json
  shell/app/layout/pages/page-container/components/menu-head.scss
Labels: bug

#303 Hotfix: rendering chart with initial time in monitor
  shell/app/common/components/monitor/components/timeRangeSelector.tsx
Labels: lgtm

#311 feature: fix typo
  erda.yml
Labels: lgtm

#308 jest use pnpm
  .github/workflows/codecov.yml
  core/package-lock.json
  pnpm-lock.yaml
  shell/app/common/__tests__/components/protocol-selector.test.tsx
  shell/app/common/__tests__/containers/addon-resource.test.tsx
  shell/app/common/__tests__/containers/log-roller.test.tsx
  shell/app/common/__tests__/containers/monitor-chart-panel.test.tsx
  shell/app/common/containers/log-roller.tsx
  shell/jest.config.js
  shell/package-lock.json
  shell/package.json
Labels: lgtm

#304 refactor build process
  cli/bin/erda.ts
  cli/lib/build.ts
  cli/lib/copy.ts
  cli/lib/init.ts
  cli/lib/launcher.ts
  cli/lib/release.ts
  cli/lib/setup.ts
  cli/lib/util/env.ts
  cli/package.json
  core/.eslintrc.js
  core/package.json
  core/src/nusi/index.tsx
  core/tsconfig.json
  core/webpack.config.js
  core/webpack.development.js
  core/webpack.production.js
  modules/market/.gitignore
  modules/market/craco.config.js
  modules/market/package.json
  pnpm-lock.yaml
  scheduler/package.json
  scheduler/src/index.js
  setup.js
  shell/.eslintrc.js
  shell/app/common/__tests__/components/__snapshots__/loading-skeleton.test.tsx.snap
  shell/app/common/components/statement.tsx
  shell/app/config-page/components/table-group/table-group.tsx
  shell/app/config-page/debug.tsx
  shell/app/modules/microService/monitor/topology/pages/topology-dashboard/index.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
  shell/mf.config.js
  shell/package.json
  shell/tsconfig.json
  shell/webpack-dll.js
  shell/webpack.config.js
  shell/webpack.development.js
Labels: enhancement

#313 remove tag.error & pagination by fe
  shell/app/modules/microService/monitor/error-insight/pages/errors/error-overview.tsx
  shell/app/modules/microService/monitor/trace-insight/pages/trace-querier/trace-search.tsx
  shell/app/modules/microService/types/monitor.d.ts
Labels: lgtm

#324 feat: support issue kanban load more
  shell/app/common/components/contractive-filter.tsx
  shell/app/config-page/components/issue-kanban.tsx
Labels: lgtm

#322 feat: add input-select in configForm, prepare for new action
  shell/app/common/components/input-select/input-select.tsx
  shell/app/config-page/components/action-form.tsx
  shell/app/configForm/nusi-form/form-items/index.tsx
  shell/app/configForm/nusi-form/form-items/input-select.scss
  shell/app/configForm/nusi-form/form-items/input-select.tsx
  shell/app/configForm/nusi-form/form.tsx
  shell/app/yml-chart/common/action-config-form.tsx
Labels: lgtm

#334 feat: update log analysis and use case table content column style
  shell/app/modules/dataCenter/pages/log-query/index.scss
  shell/app/modules/dataCenter/pages/log-query/index.tsx
  shell/app/modules/project/pages/test-manage/case/columns/index.tsx
  shell/app/modules/project/pages/test-manage/components/case-table/index.tsx
Labels: lgtm

#341 cli update
  cli/lib/i18n.ts
  cli/lib/init.ts
  cli/lib/util/env.ts
  cli/package.json
  scheduler/package.json
Labels: enhancement

#340 testCase bug fix
  shell/app/modules/project/pages/test-manage/components/case-tree/index.tsx
Labels: lgtm

#348 fix: fix breadcrumb info error
  shell/app/modules/project/stores/project.tsx
Labels: approved, bugfix

#345 upgrade path-to-regexp
  .eslintrc.js
  core/package.json
  core/src/config.ts
  core/src/cube.ts
  core/src/framework/regist-router.tsx
  core/src/stores/route.ts
  core/tsconfig.json
  cspell.json
  package.json
  pnpm-lock.yaml
  scheduler/package.json
  shell/app/common/components/custom-filter.tsx
  shell/app/common/index.ts
  shell/app/interface/common.d.ts
  shell/app/interface/global.d.ts
  shell/app/modules/application/entry.js
  shell/app/modules/application/pages/ticket/index.tsx
  shell/app/modules/application/pages/ticket/ticket-detail.scss
  shell/app/modules/application/pages/ticket/ticket-detail.tsx
  shell/app/modules/application/pages/ticket/ticket-form.tsx
  shell/app/modules/application/pages/ticket/ticket-list.scss
  shell/app/modules/application/pages/ticket/ticket-list.tsx
  shell/app/modules/application/router.js
  shell/app/modules/application/services/ticket.ts
  shell/app/modules/application/stores/ticket.ts
  shell/app/modules/application/types/ticket.d.ts
  shell/app/modules/dataCenter/router.js
  shell/app/modules/org/pages/ticket/index.tsx
  shell/app/modules/org/pages/ticket/ticket-detail/index.tsx
  shell/package.json
Labels: approved

#338 feat: add fake runtime display
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/deploy/deploy.tsx
  shell/app/modules/application/pages/deploy/runtime-box.tsx
Labels: approved

#347 fix: not logout after exit org, update jump location
  shell/app/common/components/authorize-member-modal.tsx
  shell/app/common/components/members-table.tsx
  shell/app/common/stores/_member.ts
  shell/app/common/types/member.d.ts
Labels: bugfix, dop

#337 Hotfix/Tabs and Select style bug
  shell/app/common/components/edit-field.scss
  shell/app/modules/project/common/components/issue/edit-issue-drawer.scss
  shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
  shell/app/styles/antd-extension.scss
Labels: bugfix, dop

#352 feat: restore cpu chart in resource summary
  shell/app/modules/project/stores/resource.ts
Labels: approved, bugfix, feature

#350 feat: add project level app type
  shell/app/images/xmjyy.svg
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/application.tsx
  shell/app/modules/application/common/config.ts
  shell/app/modules/application/pages/settings/app-settings.tsx
  shell/app/modules/application/stores/application.tsx
  shell/app/modules/project/pages/apps/app-form.scss
  shell/app/modules/project/pages/apps/app-form.tsx
  shell/app/modules/project/pages/apps/app-type-select.scss
  shell/app/modules/project/pages/apps/app-type-select.tsx
Labels: approved, dop, feature

#354 Update wechat QRcode
  README.md
  docs/files/wechat.jpg
Labels: documentation

#355 cherry-pick pr
  shell/app/config-page/components/form-modal/form-modal.tsx
  shell/app/config-page/components/text/text.spec.d.ts
  shell/app/config-page/components/text/text.tsx
  shell/app/configForm/nusi-form/form-items/upload.tsx
  shell/app/org-home/pages/personal-home.mock.ts
Labels: approved, feature

#351 Chore: upgrade dashboard
  pnpm-lock.yaml
  shell/app/App.tsx
  shell/app/interface/global.d.ts
  shell/app/modules/dataCenter/pages/cloud-source/index.tsx
  shell/package.json
  shell/webpack.config.js
Labels: approved, refactor

#353 feat: hide application authorization when adding members in orgCenter
  shell/app/common/components/add-member-modal.tsx
Labels: feature

#359 add case for common comp
  shell/app/common/__tests__/components/edit-field.test.tsx
  shell/app/common/__tests__/components/layout.test.tsx
  shell/app/common/__tests__/components/setting-tabs.test.tsx
  shell/jest.config.js
  shell/test/setupJest.ts
Labels: approved, test

#356 fix: support show slow rpc panel
  erda.yml
  shell/app/modules/microService/monitor/monitor-common/components/chartFactory.tsx
  shell/app/modules/microService/monitor/service-insight/common/components/error-track-panel.tsx
  shell/app/modules/microService/monitor/service-insight/common/components/slow-track-panel.tsx
  shell/app/modules/microService/monitor/service-insight/services/index.ts
  shell/app/modules/microService/monitor/service-insight/stores/web.ts
Labels: bugfix, msp

#362 hide dataCenter for free users
  shell/app/layout/common/error-page.tsx
  shell/app/layout/pages/page-container/page-container.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/org-home/types/org.d.ts
Labels: dop, feature

#360 chore: update the way of import DC
  pnpm-lock.yaml
  shell/app/common/__tests__/components/edit-list/edit-list.test.tsx
  shell/app/common/__tests__/components/key-value-textarea.test.tsx
  shell/app/common/__tests__/utils/str-num-date.test.tsx
  shell/app/common/components/board-grid.tsx
  shell/app/common/services/dashboard.ts
  shell/app/modules/dataCenter/pages/cluster-manage/cluster-state.tsx
  shell/app/modules/microService/monitor/service-list/pages/index.tsx
  shell/app/modules/microService/monitor/service-list/pages/service-list-dashboard.tsx
  shell/app/modules/microService/monitor/service-list/pages/transaction.tsx
  shell/app/modules/microService/monitor/topology/pages/topology-dashboard/index.tsx
  shell/package.json
Labels: refactor

#365 fix: display complete name when hover it
  shell/app/layout/pages/page-container/components/header.tsx
  shell/app/modules/application/common/app-selector.tsx
  shell/app/modules/project/common/components/project-selector.tsx
Labels: bugfix, dop

#357 feat: update runtime service config directly
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/common/app-list-protocol.tsx
  shell/app/modules/runtime/pages/overview/components/resource-modal.tsx
  shell/app/modules/runtime/pages/overview/components/service-card.tsx
  shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
  shell/app/modules/runtime/pages/overview/containers/index.tsx
  shell/app/modules/runtime/stores/runtime.ts
  shell/app/modules/runtime/stores/service.ts
Labels: approved, dop, feature

#368 fix: fix service config update data
  shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
  shell/app/modules/runtime/types/service.d.ts
Labels: approved

#372 feat: pick runtime config from 1.0
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/common/app-list-protocol.tsx
  shell/app/modules/application/stores/application.tsx
  shell/app/modules/project/pages/test-manage/components/case-table/index.tsx
  shell/app/modules/project/stores/project.tsx
  shell/app/modules/runtime/pages/overview/components/resource-modal.tsx
  shell/app/modules/runtime/pages/overview/components/service-card.tsx
  shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
  shell/app/modules/runtime/pages/overview/containers/index.tsx
  shell/app/modules/runtime/stores/runtime.ts
  shell/app/modules/runtime/stores/service.ts
  shell/app/modules/runtime/types/service.d.ts
Labels: approved, dop, feature

#361 fix: bugs caused by Select upgrade to antd4.x
  core/src/nusi/fixed-select.tsx
Labels: approved, bugfix

#371 style: adjust the position of dataType panel in API design
  shell/app/modules/apiManagePlatform/pages/api-market/design/index.scss
  shell/app/modules/apiManagePlatform/pages/api-market/design/index.tsx
Labels: approved, dop

#373 fix: erda-ui i18n bugs caused by international text changed
  shell/app/config-page/components/api-editor/api-editor.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/addonPlatform/pages/common/configs.ts
  shell/app/modules/application/pages/build-detail/index.tsx
  shell/app/modules/dataCenter/common/alarm-strategy/index.tsx
  shell/app/modules/dataCenter/pages/cluster-manage/add-cluster-forms/cluster-type-modal.tsx
  shell/app/modules/dataCenter/pages/cluster-manage/deploy-cluster-forms/edit-table.tsx
  shell/app/modules/dcos/common/custom-label.tsx
  shell/app/modules/microService/monitor/topology/pages/service-mesh/circuit-breaker-form.tsx
  shell/app/modules/project/common/components/pipeline-manage/config-detail/pipeline-editor/case-node.tsx
  shell/app/modules/project/pages/third-service/components/config.tsx
  shell/app/modules/publisher/pages/artifacts/artifacts-form-modal.tsx
  shell/app/modules/publisher/pages/artifacts/artifacts-form-modals.tsx
Labels: bugfix

#375 refactor: remove enable_mpaas variable
  cli/lib/build.ts
  erda.yml
  nginx.conf.template
  shell/app/interface/global.d.ts
  shell/app/menus/util.ts
  shell/app/modules/project/pages/apps/app-form.tsx
  shell/dice.yml
Labels: dop, refactor

#378 Docs/international text modification
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/addonPlatform/pages/common/configs.ts
  shell/app/modules/application/pages/build-detail/index.tsx
  shell/app/modules/microService/pages/gateway/components/invoker-authorization.tsx
Labels: approved

#377 pick replace vip tips icon form pr#370
  shell/app/layout/common/error-page.tsx
  shell/app/static/empty-project.png
  shell/app/views/index.ejs
Labels: approved, feature

#369 fix: orgs list international bug
  shell/app/common/utils/str-num-date.tsx
Labels: approved, bugfix

#363 fix(common): fix menu active key bug
  shell/app/layout/pages/page-container/components/sub-sidebar.tsx
Labels: bugfix

#379 fix: bugs caused by international text changed
  shell/app/config-page/components/api-editor/api-editor.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/microService/pages/gateway/components/invoker-authorization.tsx
  shell/app/modules/project/pages/plan-detail/batch-processing/index.tsx
  shell/app/modules/runtime/stores/service.ts
Labels: bugfix

#364 feat(cmp): introduce service manage from fdp & refactor domain service
  core/src/nusi/fixed-select.tsx
  shell/app/common/index.ts
  shell/app/common/stores/loading.ts
  shell/app/common/utils/api-creator.ts
  shell/app/common/utils/axios-config.ts
  shell/app/common/utils/index.ts
  shell/app/interface/global.d.ts
  shell/app/layout/pages/page-container/page-container.tsx
  shell/app/modules/dataCenter/entry.js
  shell/app/modules/dataCenter/pages/domain-manage/index.tsx
  shell/app/modules/dataCenter/services/domain-manage.ts
  shell/app/modules/dataCenter/stores/domain-manage.ts
  shell/app/modules/dataCenter/types/domain-manage.d.ts
  shell/tsconfig.json
Labels: approved, cmp, feature, refactor

#376 introduce tailwind & setup husky pre-commit hook to prettier code
  .husky/.gitignore
  .husky/commit-msg
  .husky/pre-commit
  cli/package.json
  core/package.json
  core/postcss.config.js
  cspell.json
  modules/market/package.json
  package.json
  pnpm-lock.yaml
  scheduler/package.json
  shell/app/App.tsx
  shell/app/layout/pages/page-container/page-container.tsx
  shell/app/modules/dataCenter/pages/domain-manage/index.tsx
  shell/package.json
  shell/postcss.config.js
  shell/tailwind.config.js
  shell/webpack.config.js
Labels: approved, feature, refactor

#382 fix: fix runtime config tip
  shell/app/locales/en.json
  shell/app/locales/zh.json
Labels: bugfix, dop

#383 add case for common comp
  shell/app/common/__tests__/components/cards-layout.test.tsx
  shell/app/common/__tests__/components/filter-group/filter-group.test.tsx
  shell/app/common/__tests__/components/tree/edit-category.test.tsx
  shell/app/common/__tests__/components/tree/tree.test.tsx
Labels: approved, test

#380 feat: add import & export manual cases record
  shell/app/common/components/url-invite-modal.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/microService/pages/config-center/index.tsx
  shell/app/modules/microService/pages/log-analytics/index.tsx
  shell/app/modules/microService/services/configCenter.ts
  shell/app/modules/microService/stores/config-center.ts
  shell/app/modules/microService/types/config-center.d.ts
  shell/app/modules/project/pages/test-manage/case/header/export-file.tsx
  shell/app/modules/project/pages/test-manage/case/header/import-export-record.tsx
  shell/app/modules/project/pages/test-manage/case/manual-test.tsx
  shell/app/modules/project/services/test-case.ts
  shell/app/modules/project/stores/test-case.ts
  shell/app/modules/project/types/test.d.ts
Labels: dop, feature

#387 fix(release1.0): add edit-list select options title
  shell/app/common/components/edit-list/edit-list.tsx
Labels: approved, bugfix, dop

#384 fix(dop): add requestIdleCallback polyfill to support safari
  pnpm-lock.yaml
  shell/app/modules/application/pages/repo/components/file-diff.tsx
  shell/package.json
Labels: approved, bugfix, dop

#390 pick:fix repo PR diff file cannot expand issue
  shell/app/modules/application/pages/repo/components/file-diff.tsx
  shell/app/modules/application/stores/repo.ts
Labels: bugfix, dop

#388 fix(dop): fix repo PR diff file cannot expand issue
  shell/app/modules/application/pages/repo/components/file-diff.tsx
  shell/app/modules/application/stores/repo.ts
  shell/app/modules/application/types/repo.d.ts
Labels: bugfix, dop

#393 add placeholder in MemberSelector of related bugs From
  shell/app/modules/project/pages/test-manage/case/case-drawer/related-bugs.tsx
Labels: bugfix, dop

#394 fix(release1.0): update cpu min value / update form tip
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/runtime/pages/overview/components/resource-modal.tsx
Labels: bugfix, dop

#396 hidden token and userName when token is empty
  shell/app/modules/application/pages/repo/repo-tree.tsx
Labels: dop, feature

#397 refactor: add hasConfigAppAuth to MembersTable in project scope
  shell/app/common/components/add-member-modal.tsx
  shell/app/common/components/members-table.tsx
  shell/app/modules/project/pages/settings/components/project-settings.tsx
Labels: dop

#385 Hotfix/fixed select bugs
  core/src/nusi/fixed-select.tsx
  shell/app/charts/utils/regist.tsx
  shell/app/config-page/components/api-editor/api-editor.scss
  shell/app/modules/apiManagePlatform/pages/api-market/components/relation.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/design/property-field.tsx
  shell/app/modules/application/pages/build/build.tsx
  shell/app/modules/application/pages/deploy/deploy.tsx
  shell/app/modules/application/pages/release/release-list.tsx
  shell/app/modules/dataCenter/pages/domain-manage/index.tsx
  shell/app/modules/microService/monitor/service-list/pages/process.tsx
  shell/app/modules/microService/pages/gateway/containers/app-service-filter.tsx
  shell/app/modules/project/pages/third-service/components/config.tsx
  shell/app/modules/project/pages/ticket/index.tsx
  shell/app/yml-chart/common/out-params-drawer.tsx
Labels: approved, bugfix

#389 fix: compatibal select with antd 4
  shell/app/common/components/edit-list/edit-list.tsx
  shell/app/config-page/components/issue-kanban.tsx
  shell/app/configForm/nusi-form/form-items/select.tsx
Labels: approved, bugfix, dop

#395 feat: change LoadMore to Pagination in backlog
  shell/app/modules/project/pages/backlog/backlog.scss
  shell/app/modules/project/pages/backlog/backlog.tsx
  shell/app/modules/project/pages/backlog/issue-item.scss
  shell/app/modules/project/pages/backlog/issue-item.tsx
  shell/app/modules/project/stores/iteration.ts
Labels: approved, dop, feature

#399 pick hidden token and userName when token is empty (#396)
  shell/app/modules/application/pages/repo/repo-tree.tsx
Labels: approved, dop, feature

#401 Hotfix/kanban drag when hover operation icon
  shell/app/config-page/components/card/card.tsx
Labels: approved, bugfix, dop

#404 fix: add UC_PUBLIC_URL in erda.yml
  erda.yml
  shell/app/layout/pages/page-container/components/sidebar.tsx
Labels: bugfix

#402 add test case for common comp
  shell/app/common/__tests__/components/image-upload.test.tsx
  shell/app/common/__tests__/components/tree/tree.test.tsx
  shell/app/common/__tests__/components/user-info.test.tsx
  shell/app/common/__tests__/utils/api-creator.test.tsx
  shell/app/common/__tests__/utils/axios-config.test.tsx
  shell/app/common/__tests__/utils/go-to.test.tsx
  shell/app/common/__tests__/utils/index.test.tsx
  shell/app/common/__tests__/utils/query-string.test.tsx
  shell/app/common/components/image-upload.tsx
  shell/app/common/utils/index.ts
  shell/test/setupJest.ts
Labels: test

#403 fix: get clusterList and leftResources when edit project Modal
  shell/app/modules/org/pages/projects/create-project.tsx
  shell/app/modules/project/common/components/section-info-edit.tsx
  shell/app/modules/project/pages/settings/components/project-info.tsx
Labels: bugfix, dop

#400 fix(release1.0): fix vip addr incomplete
  shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
Labels: approved, bugfix

#405 Feature/upgrade service layer
  core/package.json
  core/src/service/api-creator.ts
  core/src/stores/user-map.ts
  core/webpack.config.js
  pnpm-lock.yaml
  shell/app/App.tsx
  shell/app/common/__tests__/utils/api-creator.test.tsx
  shell/app/common/__tests__/utils/axios-config.test.tsx
  shell/app/common/index.ts
  shell/app/common/stores/loading.ts
  shell/app/common/utils/api-creator.ts
  shell/app/common/utils/axios-config.ts
  shell/app/interface/global.d.ts
  shell/app/layout/pages/page-container/page-container.tsx
  shell/app/modules/addonPlatform/pages/jvm-profiler/analysis.tsx
  shell/app/modules/application/common/yml-editor/dice-editor.tsx
  shell/app/modules/dataCenter/pages/domain-manage/index.tsx
  shell/app/modules/dataCenter/services/domain-manage.ts
  shell/app/modules/msp/pages/gateway/containers/api-import.tsx
  shell/app/modules/project/pages/test-manage/components/meta-modal/index.tsx
  shell/tsconfig.json
Labels: refactor

#411 upgrade free user‘s permission
  shell/app/layout/pages/page-container/components/sidebar.tsx
  shell/app/modules/org/pages/setting/org-info.tsx
  shell/app/user/stores/_perm-project.ts
Labels: dop, feature

#412 fix: skip warning message when the user doesn't join any organization
  shell/app/layout/pages/page-container/components/sidebar.tsx
Labels: bugfix

#413 hotfix: nginx config / kanban loadMore
  nginx.conf.template
  shell/app/config-page/components/issue-kanban.tsx
Labels: bugfix

#417 fix: prevent getting stats without organization
  shell/app/layout/pages/message/message.tsx
  shell/app/layout/pages/page-container/components/sidebar.tsx
Labels: approved, bugfix

#415 feature: unified useMock to prevent mock data in production
  shell/app/config-page/index.tsx
  shell/app/config-page/mock/index.tsx
  shell/app/config-page/mock/project-list-protocol.mock.ts
  shell/app/modules/application/pages/pipeline/index.tsx
  shell/app/modules/dop/pages/projects/project-list-protocol.tsx
  shell/app/modules/edge/pages/application/index.tsx
  shell/app/modules/edge/pages/application/site-ip-manage.tsx
  shell/app/modules/edge/pages/application/site-manage.tsx
  shell/app/modules/edge/pages/resource/index.tsx
  shell/app/modules/edge/pages/setting/detail.tsx
  shell/app/modules/edge/pages/setting/index.tsx
  shell/app/modules/project/pages/auto-test/apis.tsx
  shell/app/modules/project/pages/auto-test/index.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
  shell/app/modules/project/pages/test-plan/auto-test-plan-detail/index.tsx
  shell/app/modules/project/pages/test-plan/test-plan-protocol.tsx
  shell/app/org-home/pages/create-org.tsx
Labels: approved, feature

#419 refactor: edge to ecp
  nginx.conf.template
  shell/app/App.tsx
  shell/app/common/utils/go-to.tsx
  shell/app/images/ecp.svg
  shell/app/layout/pages/page-container/components/menu-head.tsx
  shell/app/layout/pages/page-container/components/sidebar.tsx
  shell/app/layout/stores/layout.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/appCenter.tsx
  shell/app/menus/ecp.tsx
  shell/app/menus/edge.tsx
  shell/app/menus/index.ts
  shell/app/modules/application/pages/pipeline/index.tsx
  shell/app/modules/ecp/entry.js
  shell/app/modules/ecp/pages/application/index.tsx
  shell/app/modules/ecp/pages/application/site-ip-manage.tsx
  shell/app/modules/ecp/pages/application/site-manage.tsx
  shell/app/modules/ecp/pages/components/monitor-drawer.tsx
  shell/app/modules/ecp/pages/resource/index.tsx
  shell/app/modules/ecp/pages/resource/machine-manage.tsx
  shell/app/modules/ecp/pages/setting/detail.tsx
  shell/app/modules/ecp/pages/setting/index.tsx
  shell/app/modules/ecp/router.ts
  shell/app/modules/ecp/services/machine-manage.ts
  shell/app/modules/ecp/stores/machine-manage.ts
  shell/app/modules/ecp/types/machine-manage.d.ts
  shell/app/modules/project/pages/test-plan/auto-test-plan-detail/index.tsx
  shell/app/org-home/router.js
  shell/app/org-home/stores/org.tsx
  shell/app/user/stores/_perm-org.ts
Labels: ecp, refactor

#420 fix: hide icon that jump to personal home when the user is admin
  shell/app/layout/pages/page-container/components/sidebar.tsx
Labels: bugfix

#426 fix: some issue about that jump to personal home
  shell/app/layout/pages/message/message.tsx
  shell/app/layout/pages/page-container/components/sidebar.tsx
Labels: approved, bugfix

#424 feat: recover problem list
  shell/app/common/components/custom-filter.tsx
  shell/app/common/index.ts
  shell/app/interface/common.d.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/entry.js
  shell/app/modules/application/pages/problem/index.tsx
  shell/app/modules/application/pages/problem/problem-detail.scss
  shell/app/modules/application/pages/problem/problem-detail.tsx
  shell/app/modules/application/pages/problem/problem-form.tsx
  shell/app/modules/application/pages/problem/problem-list.scss
  shell/app/modules/application/pages/problem/problem-list.tsx
  shell/app/modules/application/router.js
  shell/app/modules/application/services/problem.ts
  shell/app/modules/application/stores/problem.ts
  shell/app/modules/application/types/problem.d.ts
Labels: approved, bugfix

#422 fix: update pipeline when single task is final status
  shell/app/modules/application/pages/pipeline/run-detail/config.tsx
  shell/app/modules/application/stores/build.ts
Labels: bugfix, dop

#427 cherry-pick upgrade free user‘s permission form (#411)
  shell/app/layout/pages/page-container/components/sidebar.tsx
  shell/app/modules/org/pages/setting/org-info.tsx
  shell/app/user/stores/_perm-project.ts
Labels: approved, auto-cherry-pick, dop, feature
