Repository erda-project/erda-ui, pull requests merged in 2021-07, with the labels that each got.

#429 fix: there is not a file path' in api in code repo
  shell/app/modules/application/stores/repo.ts
Labels: bugfix

#428 feat: export some interface for outer use
  core/src/service/api-creator.ts
Labels: feature

#431 feat: display multi-dimensions multi-values
  pnpm-lock.yaml
  shell/package.json
Labels: feature

#432 fix: bugs caused by Form upgrade and some other style bugs
  core/src/nusi/index.tsx
  shell/app/common/components/form-modal.tsx
  shell/app/common/components/load-more-selector.tsx
  shell/app/modules/application/pages/repo/repo-tree.tsx
  shell/app/modules/cmp/common/custom-alarm/index.tsx
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
  shell/app/modules/cmp/pages/cluster-manage/cloud-machine-form-modal.tsx
  shell/app/modules/cmp/pages/middleware-dashboard/scale-modal.tsx
  shell/app/modules/cmp/pages/tasks/task-list.tsx
  shell/app/styles/antd-extension.scss
Labels: bugfix

#433 feat: add proxy api in config page debug page
  shell/app/config-page/components/table-group/table-group.tsx
  shell/app/config-page/components/table/table.tsx
  shell/app/config-page/components/text/text.spec.d.ts
  shell/app/config-page/debug.tsx
  shell/app/config-page/index.tsx
  shell/app/config-page/mock/index.tsx
  shell/app/modules/dop/router.js
  shell/webpack.config.js
Labels: feature

#435 fix: clear branch info when app clear
  shell/app/common/components/load-more-selector.scss
  shell/app/common/components/load-more-selector.tsx
  shell/app/locales/zh.json
  shell/app/modules/application/pages/release/release-list.tsx
Labels: bugfix, dop

#437 fix: add log
  shell/webpack.config.js
Labels: bug

#438 fix: fix UI env key
  shell/webpack.config.js
Labels: bugfix

#439 fix: encrypted files cannot be downloaded
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/settings/components/app-variable-config.tsx
  shell/app/modules/application/pages/settings/components/variable-config-form.tsx
Labels: bugfix, dop

#436 Hotfix/bugs by form upgrade
  core/package.json
  core/src/common/interface.d.ts
  core/src/config/theme.js
  core/src/i18n.ts
  core/src/nusi/fixed-select.tsx
  core/src/nusi/index.tsx
  core/webpack.config.js
  core/webpack_ts.loader.js
  pnpm-lock.yaml
  shell/app/common/components/form-modal.tsx
  shell/app/common/components/members-table.tsx
  shell/app/config-page/components/api-editor/api-editor.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/common/app-table.tsx
  shell/app/modules/application/common/components/edit-stage.tsx
  shell/app/modules/application/pages/repo/repo-tree.tsx
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/application/pages/settings/components/app-notify/notify-config.tsx
  shell/app/modules/cmp/common/components/table-col.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
  shell/app/modules/cmp/pages/domain-manage/index.tsx
  shell/app/modules/dataCenter/common/alarm-record/index.tsx
  shell/app/modules/dataCenter/common/alarm-strategy/index.tsx
  shell/app/modules/dataCenter/pages/alarm-report/index.tsx
  shell/app/modules/dataCenter/pages/cluster-manage/cluster-list.tsx
  shell/app/modules/dataCenter/pages/domain-manage/index.tsx
  shell/app/modules/dataCenter/pages/log-analyze-rule/index.tsx
  shell/app/modules/dataCenter/pages/log-query/index.tsx
  shell/app/modules/dcos/pages/service-manager/mq-manager/group.tsx
  shell/app/modules/dcos/pages/service-manager/mq-manager/topic.tsx
  shell/app/modules/dcos/pages/service-manager/rds-manager/database.tsx
  shell/app/modules/dcos/pages/service-manager/rds-manager/rds-account.tsx
  shell/app/modules/msp/pages/gateway/containers/api-package.tsx
  shell/app/modules/project/pages/test-manage/case/columns/index.tsx
  shell/app/modules/project/pages/test-manage/components/case-table/index.tsx
  shell/app/styles/antd-extension.scss
  shell/jest.config.js
Labels: bugfix

#440 feat: upgrade dashboard to v.1.0.22
  pnpm-lock.yaml
  shell/package.json
Labels: bugfix, feature

#442 fix: bugs caused by Form and Collapse upgrade
  shell/app/config-page/components/table/table.scss
  shell/app/config-page/components/table/table.tsx
  shell/app/locales/zh.json
  shell/app/modules/application/common/components/deployments-field.tsx
  shell/app/modules/application/common/components/edit-service.tsx
  shell/app/modules/application/common/components/resource-field.tsx
  shell/app/modules/publisher/pages/artifacts/artifacts-form-modals.tsx
  shell/app/styles/antd-extension.scss
Labels: approved, bugfix

#444 fix: fix form bugs
  core/src/cube.ts
  shell/app/common/components/render-form.tsx
  shell/app/modules/application/common/components/edit-service.tsx
  shell/app/modules/application/pages/problem/index.tsx
  shell/app/modules/cmp/pages/networks/vpc/vpc-form-modal.tsx
  shell/app/yml-chart/common/pipeline-node-drawer.tsx
Labels: approved, bugfix

#443 add test case for common comp
  shell/app/common/__tests__/components/batch-authorize-member-modal.test.tsx
  shell/app/common/__tests__/components/custom-filter.test.tsx
  shell/app/common/__tests__/components/filter.test.tsx
  shell/app/common/__tests__/components/log/download-log-modal.test.tsx
  shell/app/common/__tests__/components/log/log-roller.test.tsx
  shell/app/common/__tests__/components/members-table.test.tsx
Labels: approved, test

#441 docs: update README
  README.md
  package.json
Labels: documentation

#445 feat(common): refact header to avoid react warning
  shell/app/common/types/route.d.ts
  shell/app/layout/pages/page-container/components/header.tsx
Labels: refactor

#447 fix: fix form key
  shell/app/modules/org/pages/projects/create-project.tsx
  shell/app/modules/project/pages/apps/app-form.tsx
  shell/app/modules/project/pages/settings/components/project-rollback.tsx
  shell/app/yml-chart/common/pipeline-node-drawer.tsx
Labels: approved, bugfix

#434 Feat/add api-service-generator to cli
  .gitignore
  cli/bin/erda.ts
  cli/lib/service-generator.ts
  cli/package.json
  shell/app/interface/global.d.ts
Labels: cli

#449 fix: jump to app list instead of DevOps page
  shell/app/layout/common/error-page.tsx
  shell/app/layout/locales/en.json
  shell/app/layout/locales/zh.json
  shell/app/user/stores/permission.ts
Labels: bugfix, dop

#448 fix: form item value not update
  shell/app/modules/application/pages/repo/components/branch-select.tsx
  shell/app/modules/application/pages/repo/components/repo-editor.tsx
  shell/app/modules/application/pages/repo/components/source-target-select.scss
  shell/app/modules/application/pages/repo/mr-detail.scss
  shell/app/modules/application/pages/repo/repo-tree.tsx
Labels: bugfix

#450 fix: fix Form.Item children wrap
  core/package.json
  pnpm-lock.yaml
  shell/app/layout/pages/page-container/components/sidebar.tsx
  shell/app/modules/application/pages/release/release-list.tsx
  shell/app/modules/cmp/pages/networks/common/components/cidr-input.tsx
Labels: approved, bugfix

#452 fix(cmp): fix alarm chart layout
  shell/app/modules/cmp/pages/alarm-analyze/index.tsx
Labels: bugfix, cmp

#453 Hotfix: display percentage normally
  shell/app/charts/components/monitor-chart-new.jsx
  shell/app/modules/msp/monitor/monitor-common/components/resource-usage/config.ts
Labels: bugfix

#446 feat: add new scenes config page support
  shell/app/common/components/contractive-filter.tsx
  shell/app/common/components/load-more-selector.scss
  shell/app/common/components/load-more-selector.tsx
  shell/app/config-page/components/button/button.tsx
  shell/app/config-page/components/table/render-types.tsx
  shell/app/config-page/components/table/table.scss
  shell/app/config-page/components/table/table.tsx
  shell/app/config-page/components/text/text.spec.d.ts
  shell/app/config-page/mock.tsx
  shell/app/config-page/mock/crud.mock.ts
  shell/app/config-page/mock/index.tsx
  shell/app/config-page/mock/project-list-protocol.mock.ts
Labels: approved, feature

#454 Fix: some form not switch when field change
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/cmp/pages/alarm-report/index.tsx
  shell/app/modules/msp/pages/gateway/containers/api-package-create.tsx
Labels: bugfix

#455 fix: fix form key error
  shell/app/modules/project/pages/settings/components/project-cluster.tsx
  shell/app/modules/project/pages/settings/components/project-rollback.tsx
Labels: approved, bugfix

#456 fix: bugs caused by Form upgrade
  shell/app/modules/application/common/components/edit-stage.tsx
  shell/app/modules/application/pages/repo/repo-tree.tsx
  shell/app/modules/application/pages/settings/components/app-certificate-reference.tsx
  shell/app/modules/cmp/common/custom-alarm/index.tsx
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
  shell/app/modules/cmp/pages/cluster-manage/deploy-cluster-forms/docker-form.tsx
  shell/app/modules/cmp/pages/cluster-manage/deploy-cluster-forms/nodes-form.tsx
  shell/app/modules/cmp/pages/cluster-manage/deploy-cluster-forms/platform-form.tsx
  shell/app/modules/cmp/pages/cluster-manage/deploy-cluster-forms/storage-form.tsx
  shell/app/modules/dcos/pages/purchase-cluster/purchase-cluster.tsx
  shell/app/modules/dcos/pages/purchase-resource/index.tsx
  shell/app/modules/org/pages/certificate/index.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
  shell/app/modules/project/pages/third-service/components/config.tsx
  shell/app/modules/publisher/pages/artifacts/artifacts-form-modal.tsx
  shell/app/yml-chart/common/pipeline-node-drawer.tsx
Labels: approved, bugfix

#460 fix: fix alaram strategy table
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
  shell/app/modules/project/pages/third-service/components/third-addon-form.tsx
Labels: bugfix

#462 fix the copy icon error in runtime page
  pnpm-lock.yaml
  shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
Labels: approved, bugfix

#461 Hotfix: search org in dropdown
  shell/app/config-page/components/dropdown-select/dropdown-select.tsx
Labels: approved, bugfix

#463 fix: breadcrumb jump error
  shell/app/modules/ecp/pages/resource/machine-manage.tsx
Labels: approved, bugfix

#459 show case whole dirName
  shell/app/modules/project/pages/test-manage/components/case-table/index.tsx
Labels: bugfix, dop

#465 fix: repo commits bugs
  shell/app/modules/application/pages/repo/repo-commit.tsx
  shell/app/modules/application/pages/repo/repo-tag.tsx
Labels: approved, bugfix

#466 fix: runtime style bugs
  shell/app/common/components/log/log-roller.scss
  shell/app/modules/runtime/pages/overview/components/domain-modal.scss
  shell/app/modules/runtime/pages/overview/components/domain-modal.tsx
Labels: bugfix

#464 fix: fix yaml error tip
  shell/app/common/components/members-table.tsx
  shell/app/common/utils/index.ts
  shell/app/modules/application/common/yml-editor/pipeline-editor.tsx
  shell/app/modules/application/pages/repo/components/add-pipelineyml.tsx
  shell/app/modules/application/pages/repo/components/repo-editor.tsx
  shell/app/modules/application/pages/settings/app-settings.tsx
  shell/app/yml-chart/pipeline-editor.tsx
Labels: approved, bugfix

#472 Hotfix: don't get commit list when no branch
  shell/app/modules/application/pages/repo/repo-commit.tsx
Labels: bugfix, dop

#471 fix: audit log DateRangePicker width
  shell/app/modules/org/pages/safety/index.tsx
Labels: bugfix

#470 fix table render when unsort
  shell/app/common/components/log/log-roller.scss
  shell/app/modules/project/pages/test-manage/components/case-table/index.tsx
Labels: bugfix, dop

#469 fix: pod table add tooltip
  shell/app/modules/runtime/common/components/pod-table.tsx
  shell/app/styles/antd-extension.scss
Labels: bugfix

#468 fix: expand case set
  shell/app/modules/project/pages/test-manage/components/case-tree/index.tsx
Labels: bugfix, dop

#467 fix: test plan edit bug
  shell/app/modules/project/pages/test-plan/plan-modal.tsx
Labels: bugfix

#473 trigger codecov workflow only ts/tsx file changed
  .github/workflows/codecov.yml
Labels: test

#474 fix: personal news improvement bugs
  shell/app/layout/stores/message.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/pages/gateway/containers/api-package.tsx
  shell/app/modules/project/common/components/issue/issue-drawer.scss
  shell/app/modules/project/common/components/issue/subscribers-selector.tsx
Labels: bugfix

#475 fix publisher switcher error
  shell/app/modules/org/pages/setting/org-info.tsx
Labels: approved, bugfix, dop

#476 fix: msp api-package-detail filter bug
  shell/app/modules/msp/pages/gateway/containers/api-package-detail.tsx
Labels: approved, bugfix

#477 fix: bugs caused by Form upgrade
  shell/app/configForm/form/form.tsx
Labels: bugfix

#478 fix: repo add tag bug
  shell/app/modules/application/pages/repo/repo-tag.tsx
Labels: bugfix

#480 fix: fix pipeline action form
  shell/app/common/components/authorize-member-modal.tsx
  shell/app/common/components/edit-field.tsx
  shell/app/modules/application/common/components/edit-stage.scss
  shell/app/modules/project/common/components/issue/issue-drawer.tsx
  shell/app/yml-chart/common/pipeline-node-drawer.tsx
Labels: approved, bugfix

#479 fix: failed to add certificate
  shell/app/modules/org/pages/certificate/index.tsx
Labels: approved, bugfix

#482 fix: fix old pipeline action form
  shell/app/common/components/edit-field.tsx
  shell/app/yml-chart/common/pipeline-node-drawer.tsx
Labels: approved, bugfix

#481 fix(dop): fix custom text field can't edit issue
  shell/app/common/components/edit-field.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
Labels: approved, bugfix, dop

#483 chore: reduce ui resource request
  erda.yml
  shell/app/modules/msp/pages/gateway/containers/api.scss
Labels: bugfix

#484 Hotfix/resolve the pr problem
  shell/app/modules/org/pages/certificate/index.tsx
Labels: bugfix

#486 fix: fix vpc form
  shell/app/modules/cmp/common/components/table-col.tsx
  shell/app/modules/cmp/pages/networks/vpc/vpc-form-modal.tsx
Labels: approved, bugfix

#487 Feat: remove ant tab overwrite style
  shell/app/styles/antd-extension.scss
  shell/app/styles/util.scss
Labels: feature

#485 fix: follower-style-bugs
  shell/app/modules/cmp/pages/domain-manage/index.tsx
  shell/app/modules/project/common/components/issue/issue-drawer.scss
  shell/app/modules/project/common/components/issue/subscribers-selector.tsx
Labels: approved, bugfix

#488 fix: calendar picker style bug
  shell/app/common/components/contractive-filter.scss
  shell/app/common/components/filter-group/filter-group.scss
  shell/app/config-page/components/table/table.scss
Labels: bugfix

#491 upgrade market publicPath
  modules/market/craco.config.js
Labels: bugfix

#489 Hotfix/test case tree style bug
  shell/app/modules/apiManagePlatform/pages/api-market/design/index.scss
  shell/app/modules/project/pages/test-manage/components/case-tree/index.scss
Labels: bugfix

#493 fix: fix config sheet pipeline drawer
  shell/app/configForm/editor/form-preview.tsx
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/pipeline-manage/config-detail/pipeline-editor/case-yml-graphic-editor.scss
Labels: bugfix

#494 fix: api-package table operates column fixed
  shell/app/common/components/paging-table.jsx
  shell/app/modules/msp/pages/gateway/containers/api-package.tsx
Labels: approved, bugfix

#490 fix: orgCenter project-list table columns overlap
  shell/app/modules/org/pages/projects/project-list.tsx
Labels: bugfix

#423 Feature/cmp cluster import
  cli/package.json
  core/package.json
  core/src/service/api-creator.ts
  cspell.json
  pnpm-lock.yaml
  scheduler/src/index.js
  shell/app/common/__tests__/components/operation-bar.test.tsx
  shell/app/common/components/copy.tsx
  shell/app/common/components/render-formItem.tsx
  shell/app/common/constants.ts
  shell/app/common/utils/style-constants.ts
  shell/app/images/microService-project-icon.png
  shell/app/images/no-cluster.png
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
  shell/app/modules/cmp/pages/cluster-manage/cloud-machine-form-modal.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
  shell/app/modules/cmp/pages/cluster-manage/index.tsx
  shell/app/modules/cmp/pages/domain-manage/index.tsx
  shell/app/modules/cmp/services/cluster.ts
  shell/app/modules/cmp/services/machine.ts
  shell/app/modules/cmp/stores/cluster.ts
  shell/app/modules/dcos/pages/cluster-dashboard/index.tsx
  shell/app/modules/dcos/stores/dashboard.ts
  shell/jest.config.js
  shell/package.json
  shell/tailwind.config.js
Labels: approved, cmp, feature

#495 fix app logo failed to load
  modules/market/src/pages/download.tsx
Labels: bugfix, dop

#496 Hotfix: setValue in form of custom alarm strategy
  shell/app/modules/cmp/common/custom-alarm/index.tsx
Labels: bugfix, cmp

#497 fix: Api list render
  shell/app/common/__tests__/components/lazy-render.test.tsx
  shell/app/common/components/lazy-render.tsx
Labels: bugfix, dop

#498 fix: fix edit field
  shell/app/common/components/edit-field.tsx
  shell/app/common/components/img-holder.tsx
  shell/app/config-page/components/button/button.tsx
  shell/app/modules/project/common/components/issue/subscribers-selector.tsx
Labels: bugfix

#499 Hotfix: recover translation in topology
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/monitor/topology/pages/topology/link-text.tsx
Labels: approved, bugfix, msp

#501 remove tag.error & pagination by fe
  shell/app/modules/msp/monitor/error-insight/pages/errors/error-overview.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
  shell/app/modules/msp/types/monitor.d.ts
Labels: bugfix, msp

#502 fix: click 'my approval' in menu of dop
  shell/app/common/utils/go-to.tsx
Labels: approved, bugfix, dop

#505 fix select cannot be fully displayed
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
Labels: approved, bugfix, cmp

#507 fix: followers internationalization bugs
  shell/app/locales/zh.json
Labels: bugfix

#508 modify msp error analysis
  shell/app/common/components/tags-column.tsx
  shell/app/modules/msp/monitor/error-insight/pages/errors/error-card.tsx
  shell/app/modules/msp/monitor/error-insight/pages/errors/error-detail.tsx
  shell/app/modules/msp/monitor/error-insight/pages/errors/error-overview.tsx
  shell/app/modules/msp/monitor/error-insight/services/errors.ts
  shell/app/modules/msp/monitor/error-insight/stores/error.ts
  shell/app/modules/msp/monitor/error-insight/types/index.d.ts
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
  shell/app/modules/msp/monitor/trace-insight/services/trace-querier.ts
  shell/app/modules/msp/monitor/trace-insight/stores/trace-querier.ts
  shell/app/modules/msp/monitor/trace-insight/types/index.d.ts
  shell/app/modules/msp/services/trace.ts
  shell/app/modules/msp/stores/trace.ts
  shell/app/modules/msp/types/monitor.d.ts
Labels: approved, feature, msp

#511 import cluster feature
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
  shell/tailwind.config.js
Labels: approved, cmp, feature

#513 fix: gantt date style bug
  shell/app/config-page/components/table/table.scss
Labels: bugfix

#514 fix: fix rumtime deploy workspace error
  shell/app/modules/application/pages/deploy/deploy.tsx
Labels: bugfix

#515 Hotfix: hide preview button in custom alarm modal
  shell/app/modules/cmp/common/custom-alarm/index.tsx
Labels: bugfix, cmp

#519 fix: fix repo file path
  shell/app/modules/application/pages/repo/components/repo-file.tsx
Labels: approved

#521 fix: backlog add item style bug
  shell/app/common/components/edit-field.scss
  shell/app/common/components/load-more-selector.scss
  shell/app/modules/project/pages/backlog/issue-item.scss
  shell/app/styles/antd-extension.scss
Labels: approved, bugfix

#525 fix: issue table icon style bug
  shell/app/styles/antd-extension.scss
Labels: approved, bugfix

#523 fix: personal news improvement style bugs
  shell/app/layout/pages/message/message.scss
  shell/app/layout/pages/message/message.tsx
Labels: approved, bugfix

#524 adjust data to params
  shell/app/modules/msp/monitor/trace-insight/services/trace-querier.ts
Labels: bugfix, msp

#529 fix: issues drawer style bugs
  shell/app/common/components/edit-field.scss
  shell/app/styles/antd-extension.scss
Labels: approved, bugfix

#531 Chore: modify ENABLE_BIGDATA to false
  erda.yml
Labels: refactor

#537 fix: fix project-level app menu / runtime detail empty error
  shell/app/config-page/components/button/button.tsx
  shell/app/menus/application.tsx
  shell/app/modules/application/stores/build.ts
Labels: bugfix

#532 fix: message button double-click unselected text
  shell/app/layout/pages/page-container/components/sidebar.tsx
Labels: bugfix

#539 fix: operate-history-interface-fail
  shell/app/modules/cmp/pages/cluster-manage/operation-history.tsx
  shell/app/modules/cmp/services/cluster.ts
  shell/app/modules/cmp/stores/cluster.ts
Labels: bugfix

#534 fix: message unread count interface remove delay
  shell/app/layout/pages/message/message.tsx
Labels: bugfix

#536 fix: fix pagination with onShowSizeChange
  core/src/nusi/index.tsx
  shell/app/common/__tests__/components/img-holder.test.tsx
  shell/app/common/__tests__/components/search-table-manage.test.tsx
  shell/app/common/components/custom-filter.tsx
  shell/app/common/components/paging-table.jsx
  shell/app/common/components/search-table-manage.scss
  shell/app/common/components/search-table-manage.tsx
  shell/app/common/index.ts
  shell/app/config-page/components/list/list.tsx
  shell/app/config-page/components/table/table.tsx
  shell/app/modules/application/common/components/table-drawer.tsx
  shell/app/modules/application/pages/repo/repo-backup.tsx
  shell/app/modules/cmp/pages/domain-manage/index.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-status-list.tsx
  shell/app/modules/msp/pages/common/table-filter-manage.tsx
  shell/app/modules/msp/pages/log-analytics/index.tsx
  shell/app/modules/project/pages/backlog/backlog.tsx
  shell/app/modules/project/pages/iteration/table.tsx
  shell/app/modules/project/pages/ticket/index.tsx
Labels: bugfix

#538 fix: fix perm editor style
  shell/app/user/common/perm-editor/perm-editor.scss
Labels: bugfix

#546 fix: milestone drawer table memberSelect width bug
  shell/app/modules/project/common/components/issue/issue-relation.tsx
Labels: approved, bugfix

#548 fix: member-table operate column fixed right
  shell/app/common/components/members-table.tsx
Labels: approved, bugfix

#549 upgrade trace detail api
  shell/app/modules/msp/monitor/external-insight/pages/affairs/affairs.tsx
  shell/app/modules/msp/monitor/service-insight/pages/database/database.tsx
  shell/app/modules/msp/monitor/service-insight/pages/web/web.tsx
  shell/app/modules/msp/monitor/trace-insight/common/utils/traceConvert.ts
  shell/app/modules/msp/monitor/trace-insight/pages/trace-detail/components/trace-detail.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-detail.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search-detail.tsx
  shell/app/modules/msp/monitor/trace-insight/services/trace-detail.ts
  shell/app/modules/msp/monitor/trace-insight/services/trace-querier.ts
  shell/app/modules/msp/monitor/trace-insight/stores/trace-detail.ts
  shell/app/modules/msp/monitor/trace-insight/stores/trace-querier.ts
  shell/app/modules/msp/monitor/trace-insight/types/index.d.ts
  shell/app/modules/msp/services/trace.ts
  shell/app/modules/msp/stores/trace.ts
Labels: feature, msp

#535 cluster import minor change
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
  shell/tailwind.config.js
Labels: cmp, feature

#555 Release/1.1 merge cmp master code
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
  shell/tailwind.config.js
Labels: cmp

#554 feat(cmp): add fixed submit value
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
Labels: cmp, feature

#553 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: feature

#556 fix: pipeline edit style bug
  shell/app/modules/application/pages/repo/repo-tree.scss
Labels: approved, bugfix

#557 feat(dop): add refresh icon when detect newly import case
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/test-manage/case/header/import-export-record.tsx
  shell/app/modules/project/pages/test-manage/case/manual-test.tsx
  shell/app/modules/project/types/test.d.ts
Labels: dop, feature

#560 fix: jump out when click link and getBuildRuntimeDetail when in the page
  shell/app/modules/application/pages/build-detail/index.tsx
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/stores/build.ts
Labels: bugfix, dop

#561 fix: message-list style bug
  shell/app/layout/pages/message/message.scss
Labels: approved, bugfix

#565 fix: backlog style bugs
  shell/app/modules/project/pages/backlog/issue-item.tsx
  shell/app/styles/antd-extension.scss
Labels: bugfix

#568 fix: update param of request in alarm records of msp
  shell/app/modules/cmp/types/alarm-record.d.ts
  shell/app/modules/msp/monitor/alarm-record/stores/alarm-record.ts
Labels: msp

#571 Fix: trim Invitation code, add default text for release version
  shell/app/layout/common/invite-to-org.tsx
  shell/app/modules/application/pages/release/components/release-detail-edit.tsx
  shell/app/modules/project/common/components/section-info-edit.tsx
Labels: bugfix, dop

#574 fix: select global style bug
  shell/app/common/components/edit-field.scss
  shell/app/modules/project/pages/backlog/issue-item.scss
  shell/app/styles/antd-extension.scss
Labels: bugfix

#552 feat: add config page support [groupSelector / tagsColumn / memberSelector]
  shell/app/common/__tests__/components/tags-row.test.tsx
  shell/app/common/components/contractive-filter.scss
  shell/app/common/components/contractive-filter.tsx
  shell/app/common/components/load-more-selector.tsx
  shell/app/common/components/tags-column.tsx
  shell/app/common/components/tags-row.scss
  shell/app/common/components/tags-row.tsx
  shell/app/common/index.ts
  shell/app/config-page/components/table/render-types.tsx
  shell/app/config-page/components/table/table.scss
  shell/app/config-page/components/table/table.spec.d.ts
  shell/app/config-page/components/table/table.tsx
  shell/app/config-page/components/tabs/tabs.scss
  shell/app/config-page/components/tabs/tabs.tsx
  shell/app/config-page/mock.tsx
  shell/app/config-page/mock/cmp.mock.ts
  shell/app/modules/cmp/pages/computing/ecs/index.tsx
  shell/app/modules/dcos/pages/machine-manager/machine-table.tsx
  shell/app/modules/dcos/pages/service-manager/rds.tsx
  shell/app/modules/ecp/pages/resource/machine-manage.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
  shell/app/modules/project/pages/milestone/milestone-item.tsx
Labels: approved, feature

#577 fix jump error
  pnpm-lock.yaml
  shell/app/modules/msp/monitor/trace-insight/pages/trace-detail/components/trace-detail.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-detail.tsx
  shell/package.json
Labels: approved, bugfix, msp

#579 fix: fix statistics detail request / autoRefresh timeout
  shell/app/config-page/components/button/button.tsx
  shell/app/config-page/index.tsx
  shell/app/modules/publisher/pages/statistics/detail.tsx
Labels: approved, bugfix

#558 fix: recent import and export records remove interval
  shell/app/modules/project/pages/test-manage/case/header/export-file.tsx
  shell/app/modules/project/pages/test-manage/case/header/import-export-record.tsx
  shell/app/modules/project/pages/test-manage/case/manual-test.tsx
Labels: approved, bugfix

#583 fix: update interface of getAlertTypes
  shell/app/modules/msp/monitor/monitor-alarm/services/alarm-strategy.ts
Labels: msp

#582 fix: error list style bug
  shell/app/modules/publisher/pages/error-report/index.tsx
  shell/app/styles/antd-extension.scss
Labels: bugfix

#584 fix: table icon style bug
  shell/app/config-page/components/table/table.scss
  shell/app/styles/antd-extension.scss
Labels: bugfix

#587 fix: fix repo file path error
  shell/app/modules/application/pages/repo/components/file-diff.tsx
Labels: bugfix

#589 Hotfix/table icon style bug
  shell/app/config-page/components/table/table.scss
Labels: approved, bugfix

#590 Hotfix/error list style bug
  shell/app/modules/publisher/pages/error-report/index.tsx
  shell/app/styles/antd-extension.scss
Labels: bugfix

#572 fix: message style change
  shell/app/layout/pages/message/message.scss
Labels: bugfix

#586 fix: custom-alarm bug caused by Form upgrade
  shell/app/common/components/render-formItem.tsx
Labels: approved, bugfix

#593 fix table-chart click event
  shell/app/modules/msp/monitor/service-list/pages/index.tsx
Labels: bugfix, msp

#595 fix: fix breadcrumb / forbidden space request
  shell/app/layout/pages/page-container/components/header.tsx
  shell/app/modules/project/stores/project.tsx
Labels: bugfix

#597 chore: upgrade 'immer' in core
  core/package.json
  pnpm-lock.yaml
Labels: approved, core

#599 fix: bugs caused by Form upgrade
  shell/app/common/components/render-formItem.tsx
  shell/app/modules/cmp/common/custom-alarm/index.tsx
Labels: bugfix

#569 fix: import success message change
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/test-manage/case/header/import-file.tsx
Labels: bugfix

#598 Fix: refactor deprecated get inner state by ref
  shell/app/layout/common/invite-to-org.tsx
  shell/app/modules/application/pages/build-detail/index.tsx
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
Labels: bugfix, dop

#545 Feature/auto UI test
  .gitignore
  pnpm-lock.yaml
  shell/auto_test/README.md
  shell/auto_test/fixtures.ts
  shell/auto_test/global-setup.ts
  shell/auto_test/login.spec.ts
  shell/auto_test/playwright.config.ts
  shell/auto_test/tests/admin/audit.spec.ts
  shell/auto_test/tests/admin/cluster-manage.spec.ts
  shell/auto_test/tests/admin/global-config.spec.ts
  shell/auto_test/tests/admin/org-manage.spec.ts
  shell/auto_test/tests/admin/user-manage.spec.ts
  shell/auto_test/tests/dop/layout.spec.ts
  shell/auto_test/tests/pages/user-manage.ts
  shell/auto_test/util.ts
  shell/package.json
Labels: feature

#606 getTraceDetailContent return content in trance querier
  shell/app/modules/msp/monitor/external-insight/pages/affairs/affairs.tsx
  shell/app/modules/msp/monitor/service-insight/pages/database/database.tsx
  shell/app/modules/msp/monitor/service-insight/pages/web/web.tsx
  shell/app/modules/msp/monitor/trace-insight/common/utils/traceConvert.ts
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.tsx
  shell/app/modules/msp/monitor/trace-insight/stores/trace-querier.ts
Labels: bugfix, msp

#605 Fix: add release deployment type
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/runtime/common/components/deployment-table.tsx
Labels: bugfix, dop

#604 fix: fix table style
  shell/app/modules/dcos/pages/machine-manager/machine-table.tsx
  shell/app/styles/antd-extension.scss
  shell/app/styles/app.scss
Labels: bugfix

#612 feat: delete terminal colonySoldier url
  nginx.conf.template
  shell/app/modules/cmp/types/cluster.d.ts
  shell/app/modules/dcos/common/containers/terminal.jsx
  shell/app/modules/dcos/pages/machine-manager/machine-table.tsx
  shell/app/modules/runtime/services/log.ts
  shell/app/modules/runtime/stores/log.ts
Labels: cmp, feature

#607 fix(common): merge code
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
Labels: bugfix

#608 fix: international, table style and message style bugs
  shell/app/common/components/render-formItem.tsx
  shell/app/layout/pages/page-container/components/sidebar.scss
  shell/app/layout/pages/page-container/components/sidebar.tsx
  shell/app/locales/zh.json
  shell/app/modules/msp/monitor/status-insight/pages/status/status.tsx
  shell/app/modules/msp/pages/gateway/containers/api-package-detail.tsx
Labels: bugfix

#613 fix: input style in API design
  shell/app/modules/apiManagePlatform/pages/api-market/design/index.scss
  shell/app/styles/antd-extension.scss
Labels: approved, bugfix, dop

#620 fix: choose color in label setting
  shell/app/modules/project/pages/settings/components/project-label.tsx
Labels: approved, bugfix, dop

#618 fix: my-approve table style bug
  shell/app/modules/application/pages/deploy-list/deploy-list.tsx
Labels: approved, bugfix

#619 upgrade trace detail api reponse
  shell/app/modules/msp/monitor/trace-insight/common/utils/traceConvert.ts
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-history-list.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
  shell/app/modules/msp/monitor/trace-insight/services/trace-detail.ts
  shell/app/modules/msp/monitor/trace-insight/services/trace-querier.ts
  shell/app/modules/msp/monitor/trace-insight/stores/trace-detail.ts
  shell/app/modules/msp/monitor/trace-insight/stores/trace-querier.ts
  shell/app/modules/msp/monitor/trace-insight/types/index.d.ts
  shell/app/modules/msp/services/trace.ts
  shell/app/modules/msp/stores/trace.ts
Labels: feature, msp

#603 feat(dop): remove import operator check
  shell/app/modules/project/pages/test-manage/case/header/import-export-record.tsx
  shell/app/modules/project/pages/test-manage/case/manual-test.tsx
Labels: dop, feature

#626 fix: fix terminal api (not patch to 1.1)
  shell/app/modules/dcos/common/containers/terminal.jsx
Labels: bugfix

#616 fix: addon table style bug
  shell/app/modules/cmp/pages/middleware-dashboard/index.tsx
Labels: approved, bugfix

#627 fix: fix table style
  shell/app/common/components/authorize-member-modal.tsx
  shell/app/modules/application/pages/deploy-list/deploy-list.tsx
  shell/app/styles/antd-extension.scss
  shell/app/styles/app.scss
Labels: approved, bugfix

#631 fix: followers component show bug
  shell/app/modules/project/common/components/issue/subscribers-selector.tsx
Labels: approved, bugfix

#614 fix: api-package edit form bug
  shell/app/modules/msp/pages/gateway/containers/api-limits.tsx
  shell/app/modules/msp/pages/gateway/containers/api-package-create.tsx
Labels: bugfix

#636 Fix/api example error
  shell/app/common/components/erda-icon/erda-icon.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/design/basic-params-config.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/design/datatype-config.tsx
Labels: bugfix

#638 fix(dop): fix repo compare detail missing issue
  shell/app/modules/application/pages/repo/components/compare-detail.tsx
  shell/app/modules/application/pages/repo/mr-detail.tsx
Labels: bugfix, dop

#639 fix upload certificate cannot show filename
  shell/app/modules/org/pages/certificate/index.tsx
Labels: bugfix, dop

#644 fix: issues dropdown font color
  shell/app/common/components/contractive-filter.scss
  shell/app/common/components/contractive-filter.tsx
Labels: approved, bugfix

#643 fix(cmp): add cluster type icon & don't open command drawer when edit cluster config
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
  shell/app/modules/cmp/pages/cluster-manage/index.tsx
  shell/app/views/index.ejs
Labels: bugfix, cmp

#647 fix: cluster list style bug
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
Labels: bugfix

#642 fix: orgCenter project-list columns increase width
  shell/app/modules/org/pages/projects/project-list.tsx
Labels: bugfix

#646 fix: calendar style bug
  shell/app/common/components/filter-group/filter-group.scss
Labels: bugfix

#648 fix: message center style bug
  shell/app/layout/pages/message/message.scss
Labels: bugfix

#645 select cannot be fully displayed
  shell/app/modules/cmp/common/alarm-strategy/index.scss
  shell/app/modules/cmp/common/custom-alarm/index.scss
  shell/app/modules/cmp/common/custom-alarm/index.tsx
  shell/app/modules/msp/pages/gateway/containers/api-package-create.scss
Labels: bugfix, msp
