Repository erda-project/erda-ui, pull requests merged in 2021-11, with the labels that each got.

#1761 fix(msp): front-end monitor summary card style bug in small screen page
  shell/app/modules/msp/monitor/browser-insight/pages/summary/summary.tsx
Labels: approved, bugfix

#1765 fix: add chart container tip style
  shell/app/common/components/card-container/index.tsx
Labels: dop, approved, bugfix

#1764 fix(dop): test case scenes page change to compatible with api design …
  shell/app/config-page/components/api-editor/api-editor.tsx
Labels: approved, bugfix

#1769 fix(dop): project clusters list unification of digital accuracy and w…
  shell/app/modules/project/pages/settings/components/project-cluster.tsx
Labels: approved, bugfix

#1773 feat: pageNum to pageNo
  shell/app/modules/application/stores/build.ts
  shell/app/modules/application/types/build.d.ts
  shell/app/modules/cmp/pages/cluster-manage/cluster-workload-detail.tsx
  shell/app/modules/project/services/auto-test-case.ts
  shell/app/modules/project/services/test-plan.ts
Labels: approved

#1772 fix: upgrade dashboard to fix get chart data failed
  pnpm-lock.yaml
  shell/package.json
Labels: approved

#1770 fix: project list sort by memory and cpu quota
  shell/app/modules/org/common/audit-render.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
Labels: bugfix

#1768 Feat/alarm classification and notify channel
  locales/en.json
  locales/zh.json
  shell/app/interface/common.d.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/stores/notify-group.ts
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
  shell/app/modules/cmp/common/alarm-strategy/notify-strategy-select.tsx
  shell/app/modules/cmp/common/alarm-strategy/trigger-condition-select.tsx
  shell/app/modules/cmp/services/alarm-strategy.ts
  shell/app/modules/cmp/stores/alarm-strategy.ts
  shell/app/modules/cmp/types/alarm-strategy.d.ts
  shell/app/modules/msp/alarm-manage/alarm-strategy/services/alarm-strategy.ts
  shell/app/modules/msp/alarm-manage/alarm-strategy/stores/alarm-strategy.ts
  shell/app/modules/org/pages/setting/notice-channel.tsx
  shell/app/modules/org/pages/setting/org-setting.tsx
  shell/app/modules/org/services/notice-channel.ts
  shell/app/modules/org/types/notice-channel.d.ts
Labels: feature, msp, cmp, approved

#1778 fix: fix confiig-page button confirm placement
  shell/app/config-page/components/button/button.tsx
Labels: approved, bugfix

#1763 refactor(common): change sorting style and layout of Table
  shell/app/antd-overwrite/table/index.scss
  shell/app/antd-overwrite/table/index.tsx
Labels: refactor, approved

#1777 fix: update org update template
  shell/app/modules/org/common/audit-templates.json
Labels: approved

#1780 fix: did not display correspond service name from service list page
  shell/app/modules/msp/env-overview/service-list/pages/service-name-select.tsx
Labels: approved, bugfix

#1782 fix: upgrade dashboard to v1.0.44
  pnpm-lock.yaml
  shell/package.json
Labels: approved

#1784 chore: bump version v1.4
  core/package.json
  package.json
  scheduler/package.json
  shell/app/menus/cmp.tsx
  shell/app/menus/dop.tsx
  shell/app/modules/msp/stores/micro-service.tsx
  shell/package.json
Labels: chore

#1785 fix: fix refresh list after k8s detail delete
  shell/app/config-page/index.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-pod-detail.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-workload-detail.tsx
Labels: cmp, approved, bugfix

#1790 fix(dop): project clusters list unification of digital accuracy and w…
  shell/app/modules/project/pages/settings/components/project-cluster.tsx
Labels: bugfix

#1791 fix(common): table sorter style bug in config page
  shell/app/antd-overwrite/table/index.tsx
Labels: bugfix

#1792 Hotfix/handle axios error
  shell/app/common/utils/axios-config.ts
  shell/app/error-handler.jsx
  shell/webpack.config.js
Labels: bugfix

#1794 fix(msp): trace insight request method error
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.tsx
Labels: approved, bugfix

#1798 fix: download iconpark files to local static directory
  cli/lib/local-icon.ts
  cli/package.json
Labels: bugfix

#1795 feat: add i18n to set benchmark log in log context
  shell/app/locales/en.json
  shell/app/locales/zh.json
Labels: feature

#1804 fix: fix mobil init pipeline error
  shell/app/config-page/components/file-tree/file-tree.tsx
  shell/app/modules/application/pages/pipeline/pipeline-detail.tsx
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/pages/pipeline/run-detail/index.tsx
  shell/app/modules/project/pages/apps/app-form.tsx
Labels: dop, bugfix

#1809 fix: should not match more than one iconpark url
  cli/lib/local-icon.ts
  cli/package.json
Labels: bugfix

#1805 fix(cmp): adding token management to EDAs cluster
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
Labels: cmp, approved, bugfix

#1808 fix: fix config-page srcoll error
  shell/app/config-page/index.tsx
Labels: bugfix

#1788 Actively monitor related bugs
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
Labels: msp, approved, bugfix

#1803 fix: get real createdTime in trace-querier
  shell/app/modules/msp/monitor/trace-insight/stores/trace-querier.ts
Labels: approved, bugfix

#1814 fix(common): table style bug caused by antd version upgrade
  shell/app/styles/antd-extension.scss
Labels: bugfix

#1815 resolve conflict about msp-bugfix
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
Labels: msp, approved, bugfix

#1816 fix: process env not work
  shell/webpack.config.js
Labels: bugfix

#1820 fix: there is displaying loading status when request is completed
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.tsx
Labels: approved, bugfix

#1818 feat(msp): unified front-end monitoring style
  shell/app/modules/msp/monitor/browser-insight/pages/domain/domain.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/page/page.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/position/position.tsx
  shell/app/modules/msp/monitor/monitor-common/components/sort-list/sub-tab.tsx
Labels: msp, approved

#1821 fix(dop): fix mysql account inParams and goto link
  shell/app/common/utils/go-to.tsx
  shell/app/modules/addonPlatform/pages/mysql/account.tsx
  shell/app/modules/addonPlatform/pages/mysql/consumer.tsx
Labels: dop, bugfix

#1819 fix(msp): remove dashboard form topology & remove cart footer click e…
  shell/app/modules/msp/env-overview/topology/pages/topology/components/topology-ele.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/node-item.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/topology.tsx
Labels: refactor, approved

#1827 feat: add copy component in config-page
  shell/app/config-page/components/copy/copy.mock.ts
  shell/app/config-page/components/copy/copy.spec.d.ts
  shell/app/config-page/components/copy/copy.tsx
  shell/app/config-page/components/index.tsx
  shell/app/config-page/debug.tsx
Labels: feature

#1829 fix(msp): compatible with old data, si redirects to transaction
  shell/app/common/utils/go-to.tsx
  shell/app/modules/msp/pages/transfer/si.tsx
  shell/app/modules/msp/router.ts
Labels: approved, bugfix

#1831 refactor: rename copy to copyButton component in config-page
  shell/app/config-page/components/copy-button/copy-button.mock.ts
  shell/app/config-page/components/copy-button/copy-button.spec.d.ts
  shell/app/config-page/components/copy-button/copy-button.tsx
  shell/app/config-page/components/index.tsx
Labels: refactor

#1835 feat(msp): service overview topology hidden
  shell/app/modules/msp/env-overview/service-list/pages/overview.tsx
Labels: msp, approved

#1839 fix(msp): repair link query time filtering
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
Labels: msp, approved, bugfix

#1837 fix(msp): replace monitor alarm page
  shell/app/common/utils/go-to.tsx
  shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
  shell/app/modules/msp/monitor/topology/index.js
  shell/app/modules/msp/monitor/topology/pages/transfer/si.tsx
Labels: msp, bugfix

#1838 fix(msp): set default dashboard type base on url
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
Labels: approved, bugfix

#1830 Solution: when adding and editing the monitoring body as x-www-form-urlencoded, enter the key in the body and then enter the value, and the parameter position will change
  shell/app/common/components/key-value-table/index.tsx
  shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
Labels: msp, approved, bugfix

#1844 fix: fix addon form change field error
  shell/app/menus/dop.tsx
  shell/app/modules/project/pages/third-service/components/third-addon-form.tsx
Labels: dop, approved, bugfix

#1841 feat(msp): add no services guide
  shell/app/common/components/intro/index.tsx
  shell/app/common/index.ts
  shell/app/common/utils/go-to.tsx
  shell/app/images/intro.png
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-overview/service-list/pages/anomaly.tsx
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/env-overview/service-list/pages/no-services-holder.tsx
  shell/app/modules/msp/env-overview/service-list/pages/overview.tsx
  shell/app/modules/msp/env-overview/service-list/pages/process.tsx
  shell/app/modules/msp/env-overview/service-list/pages/service-name-select.tsx
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology-dashboard/index.tsx
Labels: feature, msp, approved

#1713 Automated testing of organizational settings
  shell/auto_test/fixtures.ts
  shell/auto_test/tests/org/organization-settings.spec.ts
Labels: approved, test

#1850 fix: fix copy button error
  shell/app/config-page/components/copy-button/copy-button.tsx
Labels: approved, bugfix

#1845 fix(common): project quota edit optimization
  shell/app/modules/project/common/components/section-info-edit.tsx
  shell/app/modules/project/pages/settings/components/project-info.tsx
Labels: approved, bugfix

#1852 fix(common): project quota field name rename
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/org/common/cluster-quota.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/project/pages/settings/components/project-cluster.tsx
  shell/app/modules/project/pages/settings/components/project-settings.tsx
Labels: approved, bugfix

#1860 fix: fix config-page modal visible
  shell/app/config-page/components/modal/modal.tsx
Labels: approved, bugfix

#1862 The request body under the active monitoring exception check is changed to the response body
  shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
Labels: msp, approved, bugfix

#1856 fix: add mysql account switching status tip
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/addonPlatform/pages/common/components/addon-cards.tsx
  shell/app/modules/addonPlatform/types/addon.d.ts
  shell/app/modules/application/pages/deploy/runtime-box.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: dop, approved, bugfix

#1865 Hotfix/pick failed pr to add bug template
  shell/app/modules/project/common/issue-config.ts
Labels: dop, bugfix

#1868 Fix: revert import overwrite antd component style
  shell/babel.config.js
Labels: bugfix

#1863 fix: fix grid overflow error
  shell/app/config-page/components/grid/grid.tsx
Labels: approved, bugfix

#1857 Feat: update alarm classification api and modify alarm strategy from modal to new page
  core/src/types/shell.d.ts
  locales/en.json
  locales/zh.json
  shell/app/common/types/route.d.ts
  shell/app/interface/global.d.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
  shell/app/modules/cmp/common/alarm-strategy/notify-strategy-select.tsx
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
  shell/app/modules/cmp/common/alarm-strategy/trigger-condition-select.tsx
  shell/app/modules/cmp/pages/alarm-strategy/cmp-stratege.tsx
  shell/app/modules/cmp/router.ts
  shell/app/modules/cmp/services/alarm-strategy.ts
  shell/app/modules/cmp/stores/alarm-strategy.ts
  shell/app/modules/cmp/types/alarm-strategy.d.ts
  shell/app/modules/msp/alarm-manage/alarm-strategy/index.js
  shell/app/modules/msp/alarm-manage/alarm-strategy/pages/alarm-index/msp-strategy.tsx
  shell/app/modules/msp/alarm-manage/alarm-strategy/services/alarm-strategy.ts
  shell/app/modules/msp/alarm-manage/alarm-strategy/stores/alarm-strategy.ts
Labels: feature, approved

#1870 feat: upgrade dashboard to v2.0.0
  pnpm-lock.yaml
  shell/package.json
Labels: feature, approved

#1871 fix: missing table and select style in bablel config
  shell/babel.config.js
  shell/webpack.config.js
Labels: bugfix

#1867 refactor(common): table optimization
  locales/en.json
  locales/zh.json
  shell/app/common/components/form-builder/fields.tsx
  shell/app/common/components/table/index.scss
  shell/app/common/components/table/index.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/org/router.ts
  shell/app/styles/_color.scss
  shell/app/views/index.ejs
  shell/index.html
Labels: refactor, approved

#1855 V1.4.1: go to log analysis from the deployment center with applica…
  shell/app/modules/runtime/pages/overview/components/index.tsx
Labels: feature, msp, approved

#1872 feat: add tip to application/member statistics in project-list
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/org/pages/projects/project-list.tsx
Labels: approved, bugfix

#1873 feat: update project menu
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/project.tsx
  shell/app/modules/project/stores/project.tsx
Labels: feature, dop, approved

#1876 fix(msp): use the Web Worker to process topology metadata
  shell/app/modules/msp/env-overview/topology/pages/topology/components/data-handler.worker.ts
  shell/app/modules/msp/env-overview/topology/pages/topology/components/topology-ele.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/components/topology-utils-v2.tsx
Labels: msp, approved, bugfix

#1877 fix: MQ page collapse
  pnpm-lock.yaml
  shell/app/modules/msp/env-overview/service-list/pages/anomaly.tsx
  shell/app/modules/msp/env-overview/service-list/pages/process.tsx
  shell/app/modules/msp/env-overview/service-list/pages/service-list-dashboard.tsx
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
  shell/package.json
Labels: approved, bugfix

#1875 fix(msp): Process the data when actively monitoring the headers update
  shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
Labels: msp, approved, bugfix

#1880 fix: MQ page collapse
  pnpm-lock.yaml
  shell/app/modules/msp/env-overview/service-list/pages/anomaly.tsx
  shell/app/modules/msp/env-overview/service-list/pages/process.tsx
  shell/app/modules/msp/env-overview/service-list/pages/service-list-dashboard.tsx
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
  shell/package.json
Labels: approved, bugfix

#1881 fix: update cmp menu / resource rank
  locales/en.json
  locales/zh.json
  shell/app/common/components/table/index.scss
  shell/app/common/components/table/index.tsx
  shell/app/common/utils/go-to.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/cmp.tsx
  shell/app/modules/cmp/router.ts
  shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx
  shell/app/modules/dcos/types/dashboard.d.ts
Labels: feature, cmp, approved

#1882 add audit for mysql account
  shell/app/modules/org/common/audit-templates.json
Labels: approved

#1883 fix(msp): When actively monitoring and modifying the format of the body, the window will pop up only when there is data
  shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
Labels: msp, approved, bugfix

#1888 feat: search rule name
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
Labels: feature

#1886 fix: fix mysql addon support tenant / test env params length
  shell/app/common/components/k-v-pair/index.tsx
  shell/app/modules/project/pages/test-env/test-env-detail.tsx
  shell/app/modules/project/pages/test-report/download.tsx
  shell/app/modules/project/pages/third-service/components/third-addon-form.tsx
Labels: dop, approved, bugfix

#1890 fix typo
  shell/app/modules/org/common/audit-templates.json
Labels: approved, bugfix

#1887 refactor(common): table optimization
  locales/en.json
  locales/zh.json
  shell/app/common/components/filter/base-filter.tsx
  shell/app/common/components/form-builder/fields.tsx
  shell/app/common/components/table/index.scss
  shell/app/common/components/table/index.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/org/router.ts
  shell/app/styles/_color.scss
  shell/app/views/index.ejs
  shell/index.html
Labels: refactor

#1892 feat: pick cmp menu / resource rank to 1.4
  locales/en.json
  locales/zh.json
  shell/app/common/components/table/index.scss
  shell/app/common/components/table/index.tsx
  shell/app/common/utils/go-to.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/cmp.tsx
  shell/app/modules/cmp/router.ts
  shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx
  shell/app/modules/dcos/types/dashboard.d.ts
Labels: feature

#1893 fix: fix resource rank table style(pick from 1.4)
  locales/zh.json
  shell/app/common/components/table/index.scss
  shell/app/common/components/table/index.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx
  shell/app/modules/dcos/types/dashboard.d.ts
Labels: cmp, approved, bugfix

#1894 fix: fix setting tabs scroll / project setting number fixed
  shell/app/common/components/setting-tabs/index.tsx
  shell/app/modules/project/pages/settings/components/project-cluster.tsx
Labels: dop, approved, bugfix

#1898 feat: add sort drag list tag
  shell/app/common/components/file-editor/index.tsx
  shell/app/common/components/sort-drag-group-list/index.tsx
  shell/app/config-page/debug.tsx
Labels: dop, approved

#1900 fix(dop): project edit failed bug
  shell/app/common/components/form-modal/index.tsx
  shell/app/modules/project/pages/settings/components/project-info.tsx
Labels: approved, bugfix

#1902 fix: fix dice yml addon form plan field
  shell/app/locales/zh.json
  shell/app/modules/application/common/components/create-add-on.tsx
Labels: dop, approved, bugfix

#1904 Refactor/org center project detail optimization 1.4
  locales/en.json
  locales/zh.json
  shell/app/common/components/boot-prompt/index.scss
  shell/app/common/components/boot-prompt/index.tsx
  shell/app/common/components/confirm-delete/index.tsx
  shell/app/common/components/filter/base-filter.tsx
  shell/app/common/components/members-table/index.tsx
  shell/app/common/components/panel/index.scss
  shell/app/common/components/panel/index.tsx
  shell/app/common/components/table/index.scss
  shell/app/common/components/table/index.tsx
  shell/app/common/index.ts
  shell/app/modules/application/pages/settings/app-settings.scss
  shell/app/modules/application/pages/settings/app-settings.tsx
  shell/app/modules/org/common/card/index.scss
  shell/app/modules/org/common/card/index.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/org/pages/projects/settings/info/index.tsx
  shell/app/modules/org/pages/projects/settings/member/index.tsx
  shell/app/modules/org/router.ts
  shell/app/styles/_color.scss
  shell/app/views/index.ejs
  shell/index.html
  shell/theme-color.js
Labels: refactor

#1905 fix: add manual test plan table filter
  shell/app/modules/project/pages/test-plan/test-plan.tsx
Labels: dop, approved, bugfix

#1907 refactor(common): bootPrompt optimization
  shell/app/common/components/boot-prompt/index.tsx
Labels: refactor, approved

#1910 fix: fix dop menus and pageName
  shell/app/locales/zh.json
  shell/app/menus/project.tsx
  shell/app/modules/cmp/router.ts
  shell/app/modules/dcos/router.ts
  shell/app/modules/org/router.ts
  shell/app/modules/project/router.ts
  shell/app/modules/project/stores/project.tsx
Labels: approved, bugfix

#1909 fix(msp): use the Web Worker to process topology metadata (#1876)
  shell/app/modules/msp/env-overview/topology/pages/topology/components/data-handler.worker.ts
  shell/app/modules/msp/env-overview/topology/pages/topology/components/topology-ele.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/components/topology-utils-v2.tsx
Labels: msp, bugfix

#1912 fix(common): in project quota edit, front-end control tip display
  locales/en.json
  locales/zh.json
  shell/app/modules/org/common/cluster-quota.tsx
  shell/app/modules/org/pages/projects/create-project.tsx
  shell/app/modules/project/pages/settings/components/project-info.tsx
Labels: approved, bugfix

#1913 Add auto test space update audit template
  shell/app/modules/org/common/audit-templates.json
Labels: feature, approved

#1916 fix(common): project-detail-quota-data-repeat-bug
  shell/app/common/components/panel/index.tsx
Labels: approved, bugfix

#1915 fix: fix resource rank icon style
  shell/app/common/components/table/index.scss
  shell/app/common/components/table/index.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.scss
  shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx
  shell/app/styles/_color.scss
Labels: approved, bugfix

#1922 fix: fix project info edit style
  shell/app/modules/org/pages/projects/settings/info/index.tsx
Labels: approved, bugfix

#1924 Hotfix/project logo
  shell/app/menus/project.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/org/pages/projects/settings/info/index.tsx
  shell/app/modules/org/pages/setting/notice-channel.tsx
Labels: bugfix

#1925 fix(msp): show the guide page based on the project type
  shell/app/common/components/intro/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-overview/service-list/pages/no-services-holder.tsx
Labels: msp, approved, bugfix

#1927 Refactor/add default export component name
  shell/app/App-vite.tsx
  shell/app/common/components/boot-prompt/index.tsx
  shell/app/common/components/log-roller/index.tsx
  shell/app/common/utils/marked.ts
  shell/app/config-page/components/alert/alert.tsx
  shell/app/config-page/components/breadcrumb/breadcrumb.tsx
  shell/app/config-page/components/dropdown/dropdown.tsx
  shell/app/config-page/components/edit-list/edit-list.tsx
  shell/app/config-page/components/grid/grid.tsx
  shell/app/config-page/components/info-preview/info-preview.tsx
  shell/app/config-page/components/input-select/input-select.tsx
  shell/app/config-page/components/input/input.tsx
  shell/app/config-page/components/linear-distribution/linear-distribution.tsx
  shell/app/config-page/components/markdown-editor/markdown-editor.tsx
  shell/app/config-page/components/modal/modal.tsx
  shell/app/config-page/components/panel/panel.tsx
  shell/app/config-page/components/popover/popover.tsx
  shell/app/config-page/components/radio/radio.tsx
  shell/app/config-page/components/split-page/split-page.tsx
  shell/app/config-page/components/tabs/tabs.tsx
  shell/app/config-page/components/tags/tags.tsx
  shell/app/config-page/components/tree-select/tree-select.tsx
  shell/app/config-page/debug.tsx
  shell/app/configForm/nusi-form/form-test.tsx
  shell/app/error-handler.jsx
  shell/app/layout/common/invite-to-org.tsx
  shell/app/layout/pages/page-container/components/globalNavigation/index.tsx
  shell/app/modules/addonPlatform/pages/common/components/create-log.tsx
  shell/app/modules/addonPlatform/pages/jvm-profiler/analysis.tsx
  shell/app/modules/addonPlatform/pages/jvm-profiler/jvm-overview.tsx
  shell/app/modules/org/pages/projects/settings/info/index.tsx
  shell/vite.config.js
Labels: chore

#1929 Hotfix/import range picker
  shell/app/modules/cmp/pages/alarm-report/report-records/index.tsx
  shell/app/modules/project/pages/iteration/iteration-modal.tsx
  shell/app/modules/project/pages/ticket/index.tsx
Labels: approved, bugfix

#1928 fix(cmp): resource rank table optimization
  locales/en.json
  locales/zh.json
  shell/app/common/components/table/index.scss
  shell/app/common/components/table/index.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx
  shell/app/modules/org/common/cluster-quota.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/org/pages/projects/settings/info/index.tsx
Labels: approved, bugfix

#1932 feat(common): all default export components provide names
  cli/lib/local-icon.ts
  cli/lib/util/gen-version.ts
  shell/app/modules/addonPlatform/pages/mysql/account.tsx
  shell/app/modules/addonPlatform/pages/mysql/consumer.tsx
  shell/app/modules/cmp/pages/alarm-record/detail.tsx
  shell/app/modules/cmp/pages/alarm-record/index.tsx
  shell/app/modules/cmp/pages/alarm-report/custom-dashboard/custom-dashboard.tsx
  shell/app/modules/cmp/pages/alarm-report/custom-dashboard/index.tsx
  shell/app/modules/cmp/pages/alarm-report/index.tsx
  shell/app/modules/cmp/pages/alarm-report/report-records/index.tsx
  shell/app/modules/cmp/pages/alarm-strategy/cmp-stratege.tsx
  shell/app/modules/cmp/pages/alarm-strategy/index.tsx
  shell/app/modules/cmp/pages/cloud-accounts/index.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-nodes-detail.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-pod-detail.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-workload-detail.tsx
  shell/app/modules/cmp/pages/computing/ecs/index.tsx
  shell/app/modules/cmp/pages/custom-alarm/index.tsx
  shell/app/modules/cmp/pages/storage/oss/index.tsx
  shell/app/modules/cmp/pages/tasks/job.tsx
  shell/app/modules/ecp/pages/resource/machine-manage.tsx
  shell/app/modules/msp/alarm-manage/alarm-record/index.ts
  shell/app/modules/msp/alarm-manage/alarm-record/pages/detail.tsx
  shell/app/modules/msp/alarm-manage/alarm-record/pages/index.tsx
  shell/app/modules/msp/alarm-manage/alarm-strategy/pages/alarm-index/index.tsx
  shell/app/modules/msp/alarm-manage/alarm-strategy/pages/alarm-index/msp-strategy.tsx
  shell/app/modules/msp/alarm-manage/alarm-strategy/pages/custom-alarm/index.tsx
  shell/app/modules/msp/env-overview/service-list/pages/anomaly.tsx
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/env-overview/service-list/pages/overview.tsx
  shell/app/modules/msp/env-overview/service-list/pages/process.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
  shell/app/modules/msp/pages/micro-service/switch-env.tsx
  shell/app/modules/msp/query-analysis/custom-dashboard/index.ts
  shell/app/modules/msp/query-analysis/custom-dashboard/pages/custom-dashboard.tsx
  shell/app/modules/msp/query-analysis/custom-dashboard/pages/index.tsx
  shell/app/modules/org/pages/projects/settings/member/index.tsx
  shell/app/modules/project/pages/auto-test/scenes-import-record.tsx
  shell/app/modules/project/pages/issue/all.tsx
  shell/app/modules/project/pages/issue/bug.tsx
  shell/app/modules/project/pages/issue/requirement.tsx
  shell/app/modules/project/pages/issue/task.tsx
  shell/app/modules/project/pages/settings/components/project-label.tsx
  shell/app/modules/project/pages/test-report/create.tsx
  shell/app/modules/project/pages/test-report/index.tsx
  shell/app/modules/publisher/pages/error-report/detail.tsx
Labels: feature, approved

#1933 fix(common): org center project detail go to dop and back bug
  shell/app/modules/project/stores/project.tsx
Labels: approved, bugfix

#1935 Hotfix/update projects menu name
  locales/zh.json
  shell/app/modules/application/pages/build-detail/pipeline-log.tsx
  shell/app/modules/org/pages/projects/settings.tsx
Labels: approved, bugfix

#1940 Hotfix/pick menu name
  locales/zh.json
  shell/app/modules/application/pages/build-detail/pipeline-log.tsx
  shell/app/modules/org/pages/projects/settings.tsx
Labels: bugfix

#1939 fix: fix resource rank table style
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/cmp/common/addon-detail/resource.tsx
  shell/app/modules/dcos/common/config.js
  shell/app/modules/dcos/pages/cluster-dashboard/instance-list.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx
  shell/app/modules/dcos/stores/dashboard.ts
Labels: cmp, approved, bugfix

#1936 fix(common): project detail style optimization
  shell/app/common/components/members-table/index.tsx
  shell/app/common/components/table/index.scss
  shell/app/common/components/table/index.tsx
  shell/app/modules/org/common/card/index.scss
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/org/pages/projects/settings/info/index.tsx
Labels: approved, bugfix

#1937 fix(msp): The active monitoring page assigns the URL attribute in the config returned by the interface to the URL
  shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
Labels: msp, approved, bugfix

#1946 fix: pick fix from master
  shell/app/menus/project.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/org/pages/projects/settings/info/index.tsx
Labels: bugfix

#1947 fix(common): project management list boot prompt change
  locales/en.json
  locales/zh.json
  shell/app/modules/org/pages/projects/project-list.tsx
Labels: approved, bugfix

#1945 Fix: display tooltip of trace waterfalls flow
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/trace-header.tsx
Labels: approved, bugfix

#1950 fix(common): table td desc optimization
  shell/app/common/components/table/index.tsx
Labels: bugfix

#1953 fix(common): table operate column optimization
  shell/app/common/components/table/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx
Labels: bugfix

#1955 feat(1.4.1): add auto test case import in new protocol
  shell/app/modules/project/pages/auto-test/index.tsx
Labels: feature, dop, approved

#1952 chore: upgrade dashboard to v2.0..0
  pnpm-lock.yaml
  shell/package.json
Labels: approved, chore

#1938 feat: optimize notice channel
  locales/en.json
  locales/zh.json
  shell/app/common/constants.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/org/pages/setting/notice-channel.tsx
  shell/app/modules/org/pages/setting/org-setting.tsx
  shell/app/modules/org/services/notice-channel.ts
  shell/app/modules/org/types/notice-channel.d.ts
Labels: feature, approved

#1956 fix: fix dice yaml addon form plan field
  shell/app/modules/application/common/components/create-add-on.tsx
Labels: dop, bugfix

#1959 fix(common): filter style unified
  shell/app/common/components/filter/base-filter.tsx
Labels: bugfix

#1859 Manage automated testing in the background
  shell/auto_test/fixtures.ts
  shell/auto_test/tests/org/audit-log.spec.ts
  shell/auto_test/tests/org/deployment-logging.spec.ts
  shell/auto_test/tests/org/matters-related.spec.ts
  shell/auto_test/tests/org/member-management.spec.ts
  shell/auto_test/tests/org/mobile-development-management.spec.ts
  shell/auto_test/tests/org/organization-information.spec.ts
  shell/auto_test/tests/org/organization-manage.spec.ts
  shell/auto_test/tests/org/organization-settings.spec.ts
Labels: approved, test

#1958 feat(msp): remove service-insight
  shell/app/modules/msp/env-overview/topology/router.ts
  shell/app/modules/msp/monitor/service-insight/common/components/error-track-panel.tsx
  shell/app/modules/msp/monitor/service-insight/common/components/instanceSelector.tsx
  shell/app/modules/msp/monitor/service-insight/common/components/siRenderFactory.tsx
  shell/app/modules/msp/monitor/service-insight/common/components/slow-track-panel.scss
  shell/app/modules/msp/monitor/service-insight/common/components/slow-track-panel.tsx
  shell/app/modules/msp/monitor/service-insight/common/components/tab-right.scss
  shell/app/modules/msp/monitor/service-insight/common/components/tab-right.tsx
  shell/app/modules/msp/monitor/service-insight/common/components/track-expand-table.tsx
  shell/app/modules/msp/monitor/service-insight/common/utils/index.ts
  shell/app/modules/msp/monitor/service-insight/pages/cache/cache.tsx
  shell/app/modules/msp/monitor/service-insight/pages/cache/config/apiConfig.ts
  shell/app/modules/msp/monitor/service-insight/pages/cache/config/chartMap.ts
  shell/app/modules/msp/monitor/service-insight/pages/database/config/apiConfig.ts
  shell/app/modules/msp/monitor/service-insight/pages/database/config/chartMap.ts
  shell/app/modules/msp/monitor/service-insight/pages/database/database.tsx
  shell/app/modules/msp/monitor/service-insight/pages/index.tsx
  shell/app/modules/msp/monitor/service-insight/pages/jvms/config/apiConfig.ts
  shell/app/modules/msp/monitor/service-insight/pages/jvms/config/chartMap.ts
  shell/app/modules/msp/monitor/service-insight/pages/jvms/jvms.tsx
  shell/app/modules/msp/monitor/service-insight/pages/nodes/config/apiConfig.ts
  shell/app/modules/msp/monitor/service-insight/pages/nodes/config/chartMap.ts
  shell/app/modules/msp/monitor/service-insight/pages/nodes/nodes.tsx
  shell/app/modules/msp/monitor/service-insight/pages/overview/config/apiConfig.ts
  shell/app/modules/msp/monitor/service-insight/pages/overview/config/chartMap.ts
  shell/app/modules/msp/monitor/service-insight/pages/overview/overview.scss
  shell/app/modules/msp/monitor/service-insight/pages/overview/overview.tsx
  shell/app/modules/msp/monitor/service-insight/pages/rpc/config/apiConfig.ts
  shell/app/modules/msp/monitor/service-insight/pages/rpc/config/chartMap.ts
  shell/app/modules/msp/monitor/service-insight/pages/rpc/rpc.tsx
  shell/app/modules/msp/monitor/service-insight/pages/web/config/apiConfig.ts
  shell/app/modules/msp/monitor/service-insight/pages/web/config/chartMap.ts
  shell/app/modules/msp/monitor/service-insight/pages/web/web.tsx
  shell/app/modules/msp/monitor/service-insight/router.ts
  shell/app/modules/msp/monitor/service-insight/services/common.ts
  shell/app/modules/msp/monitor/service-insight/services/index.ts
  shell/app/modules/msp/monitor/service-insight/stores/common.ts
  shell/app/modules/msp/monitor/service-insight/stores/database.ts
  shell/app/modules/msp/monitor/service-insight/stores/web.ts
  shell/app/modules/msp/monitor/service-insight/types/index.d.ts
  shell/tsconfig-webpack.json
  shell/tsconfig.json
  shell/vite.config.js
  shell/webpack.config.js
Labels: feature, msp, approved

#1964 fix(common): fix post put api carry extra query string issue
  core/src/service/index.ts
Labels: approved, bugfix

#1963 Fix: fix i18n about notice channel
  shell/app/modules/org/pages/setting/notice-channel.tsx
  shell/app/modules/org/pages/setting/org-setting.scss
  shell/app/modules/org/pages/setting/org-setting.tsx
Labels: approved, bugfix

#1961 feat(msp): The parameter tenantid is added to the three interfaces of add monitoring, edit monitoring and monitoring list in the active monitoring page
  shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
  shell/app/modules/msp/monitor/status-insight/stores/status.ts
  shell/app/modules/msp/monitor/status-insight/types/index.d.ts
Labels: msp, approved

#1962 fix(common): org center style optimization
  shell/app/common/components/members-table/index.tsx
  shell/app/common/components/table/index.scss
  shell/app/common/components/table/index.tsx
  shell/app/layout/pages/page-container/components/side-navigation.tsx
  shell/app/layout/pages/page-container/components/sub-sidebar.scss
  shell/app/locales/zh.json
  shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx
  shell/app/modules/org/common/card/index.scss
  shell/app/modules/org/common/card/index.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/org/pages/projects/settings/info/index.tsx
Labels: approved, bugfix

#1969 fix(msp): The URL of monitoring details also needs to be retrieved from config
  shell/app/modules/msp/monitor/status-insight/pages/status/status-detail.tsx
  shell/app/modules/msp/monitor/status-insight/types/index.d.ts
Labels: msp, approved, bugfix

#1968 fix(common): project quota are displayed in different order
  shell/app/modules/org/pages/projects/settings/info/index.tsx
Labels: approved, bugfix

#1967 fix(common): resource rank table and members table optimization
  shell/app/common/components/members-table/index.tsx
  shell/app/common/components/table/index.scss
  shell/app/common/components/table/index.tsx
  shell/app/common/utils/index.ts
  shell/app/layout/pages/page-container/components/sidebar.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: approved, bugfix

#1978 fix(common): hotfix to downgrade react to 16
  core/package.json
  modules/market/package.json
  pnpm-lock.yaml
  shell/package.json
Labels: bugfix

#1977 fix: the project owner view app doesn't have permission
  locales/en.json
  locales/zh.json
  shell/app/common/utils/go-to.tsx
  shell/app/layout/common/error-page.scss
  shell/app/layout/common/error-page.tsx
  shell/app/user/stores/permission.ts
  shell/app/user/types/user.d.ts
Labels: bugfix

#1976 refactor: fix some warning problems
  cspell.json
  shell/app/App-vite.tsx
  shell/app/App.tsx
  shell/app/common/components/contractive-filter/index.tsx
  shell/app/layout/pages/page-container/components/sidebar.tsx
  shell/app/modules/project/pages/apps/app-form.tsx
  shell/app/modules/project/pages/ticket/index.tsx
  shell/vite.config.js
  shell/webpack.config.js
Labels: bugfix

#1982 Refactor/update extra module files development structrue
  .gitignore
  shell/app/App.tsx
  shell/app/interface/global.d.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/cmp/common/components/log-tag-selector.scss
  shell/app/modules/cmp/common/components/log-tag-selector.tsx
  shell/app/modules/cmp/entry.js
  shell/app/modules/extra/entry.js
  shell/app/modules/msp/entry.js
  shell/app/modules/msp/pages/zkproxy/governance.scss
  shell/app/modules/msp/pages/zkproxy/governance.tsx
  shell/app/modules/msp/pages/zkproxy/node-list.scss
  shell/app/modules/msp/pages/zkproxy/node-list.tsx
  shell/app/modules/msp/router.ts
  shell/app/modules/msp/services/log-analyze.ts
  shell/app/modules/msp/stores/log-analyze.ts
  shell/app/modules/msp/types/log-analyze.d.ts
  shell/webpack.config.js
Labels: refactor

#1983 feat: update cmp container menu
  locales/en.json
  locales/zh.json
  shell/app/common/utils/go-to.tsx
  shell/app/interface/global.d.ts
  shell/app/layout/pages/page-container/components/sub-sidebar.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/cmp.tsx
  shell/app/modules/cmp/common/cluster-terminal/xterm-binary.tsx
  shell/app/modules/cmp/common/cluster-terminal/xterm-channel.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-event-log.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-nodes-detail.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-nodes.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-pod-detail.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-pods.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-selector.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-terminal.scss
  shell/app/modules/cmp/pages/cluster-container/cluster-terminal.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-workload-detail.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-workload.tsx
  shell/app/modules/cmp/pages/cluster-container/index.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-detail.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
  shell/app/modules/cmp/pages/cluster-manage/config.tsx
  shell/app/modules/cmp/router.ts
  shell/app/modules/cmp/stores/cluster.ts
  shell/app/modules/dcos/pages/cluster-dashboard/index.tsx
  shell/app/modules/dcos/pages/mount-list/mount-list.scss
  shell/app/modules/dcos/pages/mount-list/mount-list.tsx
  shell/app/modules/dcos/pages/purchase-cluster/purchase-cluster.scss
  shell/app/modules/dcos/pages/purchase-cluster/purchase-cluster.tsx
  shell/app/views/index.ejs
  shell/index.html
  shell/theme-color.js
Labels: feature, cmp, approved

#1985 Merge 1.3-hotfix to 1.3
  shell/app/common/components/authorize-member-modal.tsx
  shell/app/common/utils/go-to.tsx
  shell/app/modules/application/common/components/create-add-on.tsx
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/components/data-handler.worker.ts
  shell/app/modules/msp/env-overview/topology/pages/topology/components/topology-ele.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/components/topology-utils-v2.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-history-list.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.tsx
  shell/app/modules/msp/monitor/trace-insight/stores/trace-querier.ts
  shell/app/modules/msp/pages/transfer/si.tsx
  shell/app/modules/msp/router.js
Labels: bugfix

#1984 fix: fix test case table select all
  shell/app/modules/project/stores/test-case.ts
Labels: dop, approved, bugfix

#1975 refactor(common): table component code optimization
  shell/app/common/components/members-table/index.tsx
  shell/app/common/components/table/index.tsx
  shell/app/common/components/table/interface.ts
  shell/app/common/components/table/table-config.tsx
  shell/app/common/components/table/table-footer.tsx
  shell/app/config-page/components/table/render-types.tsx
  shell/app/config-page/components/table/table.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/org/pages/setting/notice-channel.tsx
Labels: refactor, approved

#1987 feat(org): add apply for column in approval table
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/org/pages/approval/index.tsx
Labels: feature, approved

#1986 fix(msp): fix defects related to active monitoring
  shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
Labels: msp, approved, bugfix

#1991 Fix the value problem of the URL of the event of losing focus in the editing and monitoring params of the active monitoring page
  shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
Labels: msp, approved, bugfix

#1995 fix(common): project quota percent adjusted synchronously with the ba…
  shell/app/modules/org/common/cluster-quota.tsx
  shell/app/modules/org/pages/projects/settings/info/index.tsx
  shell/app/modules/project/pages/settings/components/project-cluster.tsx
Labels: approved, bugfix

#1979 refactor && fix markdown issue
  cspell.json
  pnpm-lock.yaml
  shell/app/common/__tests__/components/markdown-editor/index.test.tsx
  shell/app/common/components/edit-field/index.tsx
  shell/app/common/components/markdown-editor/editor.scss
  shell/app/common/components/markdown-editor/editor.tsx
  shell/app/common/components/markdown-editor/index.scss
  shell/app/common/components/markdown-editor/index.tsx
  shell/app/config-page/components/markdown-editor/markdown-editor.spec.d.ts
  shell/app/config-page/components/markdown-editor/markdown-editor.tsx
  shell/app/config-page/docs/markdown-editor.spec.md
  shell/app/modules/application/pages/problem/problem-detail.tsx
  shell/app/modules/application/pages/problem/problem-form.tsx
  shell/app/modules/application/pages/repo/components/file-diff.tsx
  shell/app/modules/application/pages/repo/components/mr-comments.tsx
  shell/app/modules/cmp/common/custom-alarm/index.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
  shell/package.json
Labels: refactor, approved, bugfix

#1994 fix(dop): api design edit bug
  shell/app/modules/apiManagePlatform/pages/api-market/design/basic-params-config.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/design/datatype-config.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/design/index.tsx
Labels: approved, bugfix

#1999 fix: alarm compatible with old data
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
  shell/app/modules/org/pages/setting/notice-channel.tsx
Labels: approved, bugfix

#2000 Feat: remove useless license check logic and redirect logic
  shell/app/App-vite.tsx
  shell/app/App.tsx
  shell/app/images/gqct.png
  shell/app/layout/pages/page-container/dice-license.scss
  shell/app/layout/pages/page-container/dice-license.tsx
  shell/app/layout/pages/page-container/page-container.tsx
  shell/app/layout/services/index.ts
  shell/app/layout/stores/layout.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/user/services/user.ts
  shell/app/user/stores/index.ts
Labels: feature

#1996 refactor(common): table add hide header and adjust line height
  shell/app/common/components/table/index.scss
  shell/app/common/components/table/index.tsx
Labels: approved, bugfix

#2004 fix(dop): in runtimes container monitor, memory limit display bug
  shell/app/charts/components/monitor-chart-new.jsx
Labels: approved, bugfix

#2003 Update auto test space templates
  shell/app/modules/org/common/audit-templates.json
Labels: feature, approved

#2005 Feature/replace xhr with fetch to simplify init user info logic
  scheduler/package.json
  scheduler/src/filters/not-found.filter.ts
  shell/app/views/index.ejs
  shell/app/views/init.js
  shell/index.html
  shell/webpack.config.js
Labels: refactor, approved

#2007 fix: upgrade dashboard to v2.0.1
  pnpm-lock.yaml
  shell/app/modules/msp/env-overview/service-list/pages/service-list-dashboard.tsx
  shell/package.json
Labels: approved, bugfix

#2008 fix(common): announcement were not updated when organizations switched
  shell/app/config-page/components/dropdown-select/dropdown-select.tsx
  shell/app/org-home/pages/personal-home.tsx
Labels: approved, bugfix

#2010 fix: upgrade dashboard to v2.0.1
  pnpm-lock.yaml
  shell/app/modules/msp/env-overview/service-list/pages/service-list-dashboard.tsx
  shell/package.json
Labels: approved, bugfix

#2017 (Manual cherry-pick)refactor && fix markdown issue (#1979)
  cspell.json
  pnpm-lock.yaml
  shell/app/common/__tests__/components/markdown-editor/index.test.tsx
  shell/app/common/components/edit-field/index.tsx
  shell/app/common/components/markdown-editor/editor.scss
  shell/app/common/components/markdown-editor/editor.tsx
  shell/app/common/components/markdown-editor/index.scss
  shell/app/common/components/markdown-editor/index.tsx
  shell/app/config-page/components/markdown-editor/markdown-editor.spec.d.ts
  shell/app/config-page/components/markdown-editor/markdown-editor.tsx
  shell/app/config-page/docs/markdown-editor.spec.md
  shell/app/modules/application/pages/problem/problem-detail.tsx
  shell/app/modules/application/pages/problem/problem-form.tsx
  shell/app/modules/application/pages/repo/components/file-diff.tsx
  shell/app/modules/application/pages/repo/components/mr-comments.tsx
  shell/app/modules/cmp/common/custom-alarm/index.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
  shell/package.json
Labels: auto-cherry-pick

#2018 fix: fix config page overflow style
  shell/app/config-page/index.tsx
Labels: approved, bugfix

#2021 fix: remove VMS channel and SMS & VMS switch
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
  shell/app/modules/cmp/common/alarm-strategy/notify-strategy-select.tsx
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
  shell/app/modules/cmp/services/cluster.ts
  shell/app/modules/cmp/stores/cluster.ts
Labels: bugfix

#2024 fix: remove VMS channel and SMS & VMS switch
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
  shell/app/modules/cmp/common/alarm-strategy/notify-strategy-select.tsx
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
  shell/app/modules/cmp/services/cluster.ts
  shell/app/modules/cmp/stores/cluster.ts
Labels: bugfix

#2023 fix: display groups in notification object(msp & cmp)
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
Labels: bugfix

#2030 Fix: Pick 1.4.1 to 1.5-alpha1
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
  shell/app/modules/cmp/common/alarm-strategy/notify-strategy-select.tsx
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
  shell/app/modules/cmp/services/cluster.ts
  shell/app/modules/cmp/stores/cluster.ts
Labels: auto-cherry-pick

#2029 fix: front-end monitor page collapse
  shell/app/charts/components/monitor-chart-new.jsx
Labels: bugfix

#2033 feat(msp): adjust the msp menu
  shell/app/layout/pages/page-container/components/sub-sidebar.tsx
  shell/app/layout/pages/page-container/page-container.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/alarm-manage/alarm-strategy/index.js
  shell/app/modules/msp/config.tsx
  shell/app/modules/msp/env-overview/router.ts
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/topology.tsx
  shell/app/modules/msp/pages/micro-service-overview/index.tsx
  shell/app/modules/msp/stores/gateway.ts
  shell/app/modules/msp/stores/micro-service.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, msp, approved
