Repository erda-project/erda-ui, pull requests merged in 2021-09, with the labels that each got.

#1040 feat(scheduler): add dev referer in case open api upgrade
  scheduler/src/proxy.ts
Labels: scheduler

#1035 Feature/message center one key all read
  shell/app/layout/pages/message/message.tsx
  shell/app/layout/services/message.ts
  shell/app/layout/stores/message.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
Labels: feature

#1037 feat(dop): disable create label directly in issue detail drawer
  shell/app/common/utils/go-to.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
Labels: feature, dop

#1038 fix(dop): add timer to loop get pipeline status until websocket is stable
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
Labels: dop, bugfix

#1041 Feature/title will not be updated without changes
  shell/app/common/components/edit-field.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
Labels: feature

#1039 move time select to common
  shell/app/common/__tests__/components/custom-filter.test.tsx
  shell/app/common/__tests__/components/tiled-filter.test.tsx
  shell/app/common/__tests__/components/time-select/common.test.tsx
  shell/app/common/__tests__/components/time-select/time-select.test.tsx
  shell/app/common/components/members-table.tsx
  shell/app/common/components/time-select/common.ts
  shell/app/common/components/time-select/time-select.scss
  shell/app/common/components/time-select/time-select.tsx
  shell/app/common/index.ts
  shell/app/common/stores/monitorCommon.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/cmp/common/custom-dashboard/custom-dashboard.tsx
  shell/app/modules/cmp/stores/_common-custom-dashboard.ts
  shell/app/modules/msp/components/time-select.tsx
Labels: msp, test

#1045 fix: cluster list operate more btn style bug
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
Labels: bugfix

#1033 add translation
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/cmp/pages/cluster-manage/delete-cluster-modal.tsx
Labels: cmp, approved

#1043 Feature/remove ali cloud gateway
  shell/app/modules/msp/services/gateway.ts
  shell/app/modules/msp/stores/gateway.ts
  shell/app/modules/msp/types/gateway.d.ts
  shell/app/modules/project/pages/third-service/components/addon-modal.tsx
  shell/app/modules/project/pages/third-service/components/config.tsx
  shell/app/modules/project/pages/third-service/components/instance-form.tsx
Labels: feature, approved

#1048 rename columns name & modify dataIndex
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
Labels: approved

#1050 fix: api-design change branch after search bug
  shell/app/modules/apiManagePlatform/pages/api-market/design/index.tsx
Labels: approved, bugfix

#1051 feat(dop): enhance filter condition in backlog
  shell/app/common/components/contractive-filter.tsx
  shell/app/modules/project/pages/backlog/backlog.tsx
  shell/app/modules/project/types/issue-workflow.d.ts
  shell/app/styles/antd-extension.scss
Labels: feature, dop, approved

#1042 add limit for trace detail
  shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
  shell/app/modules/msp/services/topology-service-analyze.ts
  shell/app/modules/msp/stores/topology-service-analyze.ts
Labels: feature, msp

#1049 feat: version-list of publisher add aab file download button
  shell/app/modules/publisher/pages/artifacts/version-list.tsx
  shell/app/modules/publisher/types/publisher.d.ts
Labels: feature

#1036 fix: test case template internationalization
  shell/app/modules/project/pages/test-manage/case/header/import-file.tsx
  shell/app/static/usecase_model_en.xlsx
  shell/app/static/usecase_model_en.xmind
  shell/app/static/usecase_model_zh.xlsx
  shell/app/static/usecase_model_zh.xmind
Labels: approved, bugfix

#1053 add limit for trace detail & remove pagination (#1042)
  shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
  shell/app/modules/msp/services/topology-service-analyze.ts
  shell/app/modules/msp/stores/topology-service-analyze.ts
Labels: feature, msp

#1054 fix: fix typo
  shell/app/config-page/components/table/table.tsx
  shell/app/modules/msp/stores/micro-service.tsx
Labels: bugfix

#1055 fix: replace lookbehind in regular expression
  shell/app/modules/cmp/common/utils.ts
Labels: approved, bugfix

#1056 fix: api-design content-type text change
  shell/app/modules/apiManagePlatform/configs.ts
Labels: bugfix

#1052 feat: table style adjustment
  core/src/nusi/wrapped-table.tsx
  shell/app/styles/antd-extension.scss
Labels: feature, approved

#1057 feat(scheduler): introduce winston to handle log process
  cspell.json
  pnpm-lock.yaml
  scheduler/.gitignore
  scheduler/package.json
  scheduler/src/filters/error-catch.filter.ts
  scheduler/src/main.ts
  scheduler/src/middlewares/guard.middleware.ts
  scheduler/src/proxy.ts
  scheduler/src/util.ts
Labels: scheduler, refactor, approved

#1064 feat: my-publisher version-list add aab Tab
  shell/app/modules/publisher/pages/artifacts/version-list.tsx
Labels: feature, approved

#1062 feat: add page of MQ call
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
Labels: feature, msp

#1067 feat: api-design empty page text change
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/apiManagePlatform/pages/api-market/design/api-doc-tree.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/design/index.tsx
Labels: feature, approved

#1068 feat(dop): move the dashboard under the project collaboration
  shell/app/locales/zh.json
  shell/app/menus/project.tsx
  shell/app/modules/project/router.js
  shell/app/modules/project/tabs.tsx
Labels: feature, dop

#1065 fix: pipeline style bug in Safari
  shell/app/yml-chart/chart/config.ts
Labels: bugfix

#1063 fix: pipeline and issue page update bug when page go back
  shell/app/config-page/index.tsx
  shell/app/modules/application/pages/pipeline/index.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
Labels: approved, bugfix

#1070 fix: admin member table missing delete operation
  scheduler/package.json
  shell/app/common/components/members-table.tsx
  shell/app/user/stores/_perm-org.ts
Labels: admin, bugfix

#1060 fix: pipeline log height is not 100%
  shell/app/common/components/log/log-roller.scss
  shell/app/modules/application/pages/pipeline/run-detail/build-log.tsx
Labels: bugfix

#1069 fix: back to valid parent path after delete repo file
  shell/app/modules/application/pages/repo/components/repo-file-container.tsx
Labels: dop, approved, bugfix

#1073 fix: audit renderer scope not match backend key
  shell/app/modules/org/common/audit-render.tsx
Labels: bugfix

#1071 fix: markdown editor can not input Chinese in Safari
  pnpm-lock.yaml
  shell/package.json
Labels: dop, approved, bugfix

#1074 feat: api-design allow external repo
  shell/app/modules/apiManagePlatform/pages/api-market/design/index.tsx
Labels: feature

#1076 feat: add mq call page
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
Labels: feature, msp

#1072 feat: add contractive filter quick delete
  shell/app/common/components/contractive-filter.scss
  shell/app/common/components/contractive-filter.tsx
Labels: feature, approved

#1078 feat: add permission page i18n
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/user/common/perm-editor/perm-table.tsx
  shell/app/user/stores/_perm-app.ts
  shell/app/user/stores/_perm-org.ts
  shell/app/user/stores/_perm-project.ts
  shell/app/user/stores/_perm-sys.ts
Labels: feature, dop, approved

#1077 Hotfix/test plan drawer related bugs table too wide
  shell/app/modules/project/pages/plan-detail/pass-and-next.scss
  shell/app/modules/project/pages/test-manage/case/case-drawer/related-bugs.tsx
Labels: approved, bugfix

#1075 fix style issue & add missing fields
  shell/app/common/components/contractive-filter.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/backlog/backlog.tsx
  shell/app/modules/project/pages/backlog/issue-item.tsx
Labels: dop, approved, bugfix

#1080 fix: search by topic field in mq page
  shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
Labels: approved, bugfix

#1081 fix: remove cluster state page
  shell/app/common/utils/go-to.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/cmp/pages/cluster-manage/cluster-state.scss
  shell/app/modules/cmp/pages/cluster-manage/cluster-state.tsx
  shell/app/modules/cmp/router.js
  shell/app/modules/cmp/services/cluster.ts
  shell/app/modules/cmp/stores/cluster.ts
  shell/app/modules/dcos/pages/cluster-dashboard/groupTabs.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/index.tsx
Labels: approved, bugfix

#1084 fix: persional-home style bug in Safari
  shell/app/config-page/components/container/container.scss
Labels: approved, bugfix

#1082 add permission page i18n
  .gitignore
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/user/stores/_perm-msp.ts
  shell/app/user/stores/_perm-project.ts
Labels: feature, msp

#1086 fix: update style, fix subSearch by topic and i18n was covered
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
Labels: msp, bugfix

#1088 fix: remove cluster state page
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/cmp/pages/cluster-manage/cluster-state.scss
  shell/app/modules/cmp/pages/cluster-manage/cluster-state.tsx
  shell/app/modules/cmp/services/cluster.ts
  shell/app/modules/cmp/stores/cluster.ts
  shell/app/modules/dcos/pages/cluster-dashboard/groupTabs.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/index.tsx
Labels: cmp, bugfix

#1079 style: optimize style of build detail page
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.scss
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
Labels: dop, approved

#1089 fix: add runtime audit template
  shell/app/modules/org/common/audit-templates.json
Labels: feature, dop

#1083 fix: fix k8s dashboard styles bugs
  shell/app/common/components/tags-row.scss
  shell/app/common/components/tags-row.tsx
  shell/app/config-page/components/chart/chart.spec.d.ts
  shell/app/config-page/components/chart/chart.tsx
  shell/app/config-page/components/table/table.spec.d.ts
  shell/app/config-page/components/table/table.tsx
  shell/app/config-page/debug.scss
  shell/app/config-page/debug.tsx
  shell/app/config-page/mock/k8s-nodes.mock.ts
  shell/app/modules/dop/router.js
  shell/app/user/stores/_perm-project.ts
Labels: approved, bugfix

#1044 Microservice access configuration docking
  shell/app/common/utils/axios-config.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-setting/configuration/index.scss
  shell/app/modules/msp/env-setting/configuration/index.tsx
  shell/app/modules/msp/env-setting/configuration/type-select.scss
  shell/app/modules/msp/env-setting/configuration/type-select.tsx
  shell/app/modules/msp/pages/configuration/index.tsx
  shell/app/modules/msp/router.js
  shell/app/modules/msp/services/configuration.ts
  shell/app/modules/msp/stores/micro-service.tsx
  shell/app/modules/msp/types/configuration.d.ts
Labels: feature, msp, approved

#1091 filter role in msp project
  shell/app/common/__tests__/components/contractive-filter.test.tsx
  shell/app/common/__tests__/components/tags-row.test.tsx
  shell/app/common/components/contractive-filter.tsx
  shell/app/common/components/members-table.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/config.tsx
  shell/app/modules/msp/monitor/browser-insight/index.js
  shell/app/modules/org/pages/projects/settings.tsx
Labels: msp, approved, bugfix

#1092 feat: modify i18n and update image about MQ
  shell/app/images/resources/rocketmq.png
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
Labels: msp, approved

#1090 fix: fix un exist branch page loop request error
  shell/app/common/components/load-more.tsx
  shell/app/layout/stores/message.ts
  shell/app/modules/application/pages/repo/repo-commit.tsx
  shell/app/modules/application/pages/repo/repo-tree.tsx
  shell/app/modules/application/stores/dataTask.ts
  shell/app/modules/application/stores/repo.ts
  shell/app/modules/publisher/stores/publisher.ts
Labels: dop, approved, bugfix

#1093 fix: modify style of waterfall flow in trace detail
  shell/app/modules/msp/monitor/trace-insight/pages/trace-detail/components/trace-detail.scss
  shell/app/modules/msp/monitor/trace-insight/pages/trace-detail/components/trace-detail.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-detail.scss
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-detail.tsx
Labels: msp, bugfix

#1096 hide application in msp project
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
  shell/app/modules/msp/alarm-manage/alarm-strategy/pages/alarm-index/index.tsx
Labels: msp, approved

#1097 feat(msp): change the border style
  shell/app/modules/msp/env-setting/configuration/index.tsx
Labels: feature, msp, approved

#1098 style: table header should not be wrapped
  shell/app/styles/antd-extension.scss
Labels: approved, bugfix

#1101 fix: add complexity to bug issue
  shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
Labels: dop, approved, bugfix

#1100 Add audit template for test plan archive and issue state
  shell/app/modules/org/common/audit-templates.json
Labels: feature, dop, approved

#1094 docs: add technology stack and architecture introduction
  README.md
  docs/introduction_en.md
  docs/introduction_zh.md
Labels: documentation

#1104 fix: request slow trace without lastest time
  shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
Labels: approved, bugfix

#1106 fix: show view config button in addon card only in project scope
  shell/app/modules/addonPlatform/pages/common/components/addon-cards.tsx
  shell/app/modules/application/pages/deploy/runtime-box.tsx
  shell/app/modules/msp/monitor/status-insight/index.js
Labels: bugfix

#1107 fix: update the readme content of erda-ui/cli
  cli/README.md
  cli/package.json
Labels: approved

#1103 feat(cmp): change k8s cluster manage form prompt
  shell/app/common/constants.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
Labels: cmp, approved

#1095 refactor: remove external dice-env and custom-lodash
  scheduler/src/app.module.ts
  scheduler/src/controllers/env.controller.ts
  scheduler/src/filters/not-found.filter.ts
  scheduler/src/proxy.ts
  shell/app/common/constants.ts
  shell/app/config-page/components/table/table.tsx
  shell/app/external/custom-lodash.js
  shell/app/external/env.ts
  shell/app/interface/global.d.ts
  shell/app/layout/pages/page-container/components/sidebar.tsx
  shell/app/modules/apiManagePlatform/pages/access-manage/detail/authorization-user.tsx
  shell/app/modules/apiManagePlatform/pages/client/list/index.tsx
  shell/app/modules/ecp/pages/application/index.tsx
  shell/app/modules/project/pages/apps/app-form.tsx
  shell/app/views/index.ejs
  shell/jest.config.js
  shell/jest.config.local.js
  shell/pipeline.yml
  shell/tools/gen-lodash.js
  shell/tsconfig.json
  shell/webpack.config.js
Labels: refactor

#1111 fix: scheduler type check error
  scheduler/src/proxy.ts
Labels: approved, bugfix

#1110 feat: international text comparision
  shell/tools/comparison.js
Labels: feature, approved

#1108 fix msp dashboard url
  shell/app/common/utils/go-to.tsx
  shell/app/modules/cmp/common/alarm-record/index.tsx
  shell/app/modules/cmp/common/custom-dashboard/custom-dashboard.tsx
  shell/app/modules/cmp/common/custom-dashboard/index.tsx
Labels: msp, approved

#1109 fix: test-plan-drawer-folder-name-too-long
  shell/app/modules/project/pages/test-manage/case/case-drawer/index.scss
  shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
Labels: approved, bugfix

#1113 fix: fix k8s bugs
  shell/app/common/components/contractive-filter.tsx
  shell/app/common/components/tags-row.scss
  shell/app/config-page/components/contractive-filter/contractive-filter.tsx
  shell/app/config-page/components/table/render-types.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-detail.tsx
  shell/app/modules/cmp/router.js
Labels: bugfix

#1105 feat(msp): add loading status and change the button position
  shell/app/modules/msp/env-setting/configuration/index.tsx
  shell/app/modules/msp/services/configuration.ts
  shell/app/modules/msp/types/configuration.d.ts
Labels: feature, msp, approved

#1112 fix(dop): runtime service errors maybe empty
  scheduler/src/filters/not-found.filter.ts
  shell/app/modules/runtime/pages/overview/components/service-card.tsx
Labels: dop, bugfix

#1114 replace time select
  scheduler/src/main.ts
  shell/app/common/components/contractive-filter.tsx
  shell/app/common/components/time-select/common.ts
  shell/app/common/components/time-select/time-select.scss
  shell/app/common/components/time-select/time-select.tsx
  shell/app/common/index.ts
  shell/app/common/stores/monitorCommon.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/cmp/common/custom-dashboard/custom-dashboard.tsx
  shell/app/modules/cmp/stores/_common-custom-dashboard.ts
  shell/app/modules/msp/components/time-select.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/ajax/ajax.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/browser/browser.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/comparative/comparative.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/domain/domain.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/exception/exception.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/geography-china/geography-china.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/overview/overview.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/page/page.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/position/position.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/script/script.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/summary/summary.tsx
  shell/app/modules/msp/monitor/error-insight/pages/errors/error-filters.tsx
  shell/app/modules/msp/monitor/error-insight/pages/errors/error-overview.tsx
  shell/app/modules/msp/monitor/monitor-common/components/chartFactory.tsx
  shell/app/modules/msp/monitor/monitor-common/components/sort-list/sortFactory.tsx
  shell/app/modules/msp/monitor/service-list/pages/anomaly.tsx
  shell/app/modules/msp/monitor/service-list/pages/index.tsx
  shell/app/modules/msp/monitor/service-list/pages/overview.tsx
  shell/app/modules/msp/monitor/service-list/pages/process.tsx
  shell/app/modules/msp/monitor/service-list/pages/service-list-dashboard.tsx
  shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
  shell/app/modules/msp/monitor/topology/pages/topology-dashboard/index.tsx
  shell/app/modules/msp/monitor/topology/pages/topology/topology.tsx
  shell/app/modules/msp/monitor/trace-insight/components/duration.tsx
  shell/app/modules/msp/monitor/trace-insight/components/trace-filter.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
  shell/app/modules/msp/monitor/trace-insight/services/trace-querier.ts
  shell/app/modules/msp/monitor/trace-insight/types/index.d.ts
  shell/app/modules/msp/pages/micro-service/overview.tsx
  shell/app/modules/msp/stores/trace.ts
  shell/app/modules/msp/types/monitor.d.ts
Labels: feature, msp

#1116 fix topology params name
  shell/app/modules/msp/env-overview/topology/pages/topology/topology.tsx
Labels: msp, bugfix

#1115 fix: modify the content displaying in transaction
  pnpm-lock.yaml
  shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
  shell/app/styles/antd-extension.scss
  shell/package.json
Labels: approved, bugfix

#1119 fix: fix duration is decimal
  shell/app/modules/msp/monitor/trace-insight/components/duration.tsx
Labels: approved, bugfix

#1121 fix(dop): duplicate Chinese words in Safari when edit issue
  pnpm-lock.yaml
  shell/app/common/components/edit-field.tsx
  shell/package.json
Labels: dop, bugfix

#1118 fix: fix k8s resource monitor chart in pod/node detail
  shell/app/common/components/tags-row.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/cmp/common/cluster-terminal/index.tsx
  shell/app/modules/cmp/common/cluster-terminal/xterm-channel.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-nodes-detail.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-pod-detail.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-terminal.tsx
  shell/app/modules/project/pages/test-plan/plan-modal.tsx
  shell/app/modules/project/pages/test-plan/test-plan.tsx
  shell/app/modules/project/stores/test-plan.ts
Labels: cmp, bugfix

#1120 fix(admin): fix none admin user in admin route permission issue
  shell/app/App.tsx
  shell/app/org-home/stores/org.tsx
Labels: admin, bugfix

#1117 add comparison build script
  cli/bin/erda.ts
  cli/lib/comparison-build.ts
  cli/package.json
Labels: refactor, approved

#1124 fix: input width of modal in dashboard
  pnpm-lock.yaml
  shell/package.json
Labels: approved, bugfix

#1127 fix: add uc in pnpm workspace
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: bugfix

#1130 fix: fix uc build error
  modules/uc/.env
  modules/uc/.gitignore
  modules/uc/package-lock.json
  modules/uc/yarn.lock
  shell/app/config-page/components/table/render-types.tsx
Labels: bugfix

#1122 feat: wrapped-table add actions Api
  core/package.json
  core/src/common/interface.d.ts
  core/src/nusi/wrapped-table.scss
  core/src/nusi/wrapped-table.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
Labels: feature, approved

#1129 fix: file-tree node could not be moved and tree style bug
  shell/app/config-page/components/file-tree/file-tree.scss
  shell/app/config-page/components/file-tree/file-tree.tsx
  shell/app/styles/antd-extension.scss
Labels: approved, bugfix

#1128 add log query for deployment
  shell/app/common/containers/log-roller.tsx
  shell/app/layout/pages/page-container/components/sidebar.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/application.tsx
  shell/app/modules/cmp/common/components/log-tag-selector.tsx
  shell/app/modules/runtime/common/logs/components/container-log.jsx
  shell/app/modules/runtime/common/logs/components/log-filter.tsx
Labels: feature, msp

#1131 fix(msp): msp swich-environment problem
  shell/app/common/utils/go-to.tsx
Labels: msp, approved, bugfix

#1123 chore: fix package security alerts
  core/package.json
  modules/uc/package.json
  pnpm-lock.yaml
  shell/package.json
Labels: approved, chore

#1132 fix: fix old action form error
  shell/app/yml-chart/common/pipeline-node-drawer.tsx
  shell/app/yml-chart/pipeline-editor.tsx
Labels: dop, approved, bugfix

#1134 pick contractive-filter from v1.3
  shell/app/config-page/components/contractive-filter/contractive-filter.tsx
Labels: bugfix

#1135 fix: data-bank config-sheet tree drag bug
  shell/app/common/__tests__/components/tree/tree.test.tsx
  shell/app/common/components/tree/tree.tsx
Labels: approved, bugfix

#1139 fix: add uc test addr / fix router in cmp
  erda.yml
  shell/app/common/utils/go-to.tsx
  shell/app/config-page/components/table/table.scss
  shell/app/modules/cmp/router.js
  shell/app/styles/antd-extension.scss
Labels: bugfix

#1138 add log query for deployment (#1128)
  shell/app/common/containers/log-roller.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/application.tsx
  shell/app/modules/cmp/common/components/log-tag-selector.tsx
  shell/app/modules/runtime/common/logs/components/container-log.jsx
  shell/app/modules/runtime/common/logs/components/log-filter.tsx
Labels: approved

#1136 fix: compile error caused by latest postcss version
  modules/uc/package.json
  pnpm-lock.yaml
Labels: bugfix

#1140 fix: delete test uc addr
  erda.yml
Labels: approved, bugfix

#1148 feat: optimize waterfall flow page
  shell/app/common/utils/go-to.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/monitor/external-insight/pages/affairs/affairs.tsx
  shell/app/modules/msp/monitor/service-insight/pages/database/database.tsx
  shell/app/modules/msp/monitor/service-insight/pages/web/web.tsx
  shell/app/modules/msp/monitor/service-list/index.ts
  shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
  shell/app/modules/msp/monitor/trace-insight/index.js
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-detail-new.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph.scss
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search-detail.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-status-viewer.tsx
  shell/app/modules/msp/monitor/trace-insight/stores/trace-querier.ts
  shell/app/modules/msp/monitor/trace-insight/types/index.d.ts
  shell/app/modules/msp/stores/trace.ts
Labels: feature

#1146 Hotfix/msp swich-environment problem
  shell/app/modules/msp/stores/micro-service.tsx
Labels: msp, approved, bugfix

#1150 feat(msp): add translation
  shell/app/modules/msp/env-setting/configuration/index.tsx
Labels: msp

#1151 fix: fix uc dep
  modules/uc/package.json
  modules/uc/src/router.tsx
  pnpm-lock.yaml
Labels: dop, bugfix

#1154 fix(msp): msp switch-environment problem
  shell/app/common/utils/go-to.tsx
Labels: msp, approved, bugfix

#1156 default 10 minutes for v1.2
  shell/app/modules/runtime/common/logs/components/log-filter.tsx
Labels: feature

#1157 default 10 minutes
  shell/app/modules/runtime/common/logs/components/log-filter.tsx
Labels: feature, approved

#1161 fix(scheduler): remove fdp mask
  cli/lib/build.ts
  scheduler/src/proxy.ts
  scheduler/src/util.ts
Labels: scheduler, approved, bugfix

#1159 fix(dop): discard issue edit change not work
  shell/app/common/components/edit-field.tsx
  shell/app/common/components/markdown-editor/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
Labels: dop, bugfix

#1164 feat(dop): support use last execute cluster in project pipeline
  shell/app/modules/project/common/components/pipeline-manage/common/config-env-selector.tsx
Labels: feature, dop

#1163 fix(dop): markdown edit field not save content
  shell/app/common/components/edit-field.tsx
Labels: dop, bugfix

#1165 feat: add env variable to enable edge computing platform or not
  erda.yml
  scheduler/src/filters/not-found.filter.ts
  shell/app/App.tsx
  shell/app/interface/global.d.ts
  shell/app/layout/pages/page-container/components/sidebar.tsx
  shell/app/org-home/router.js
Labels: feature

#1158 fix: fix k8s terminal set size
  shell/app/common/components/tiled-filter.scss
  shell/app/common/components/tiled-filter.tsx
  shell/app/config-page/components/table/render-types.tsx
  shell/app/configForm/editor/form-preview.tsx
  shell/app/modules/cmp/common/cluster-terminal/xterm-channel.tsx
Labels: cmp, bugfix

#1167 fix(common): remove thread-loader to fix build crash issue
  shell/webpack.config.js
Labels: bugfix

#1170 show api design
  shell/app/menus/application.tsx
Labels: dop

#1176 fix(dop): pick markdown edit field not save content to 1.3
  shell/app/common/components/edit-field.tsx
Labels: dop, bugfix

#1171 fix: id filter add number validator in my approve
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/deploy-list/deploy-list.tsx
Labels: approved, bugfix

#1173 modify msp modal style
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-setting/configuration/index.tsx
Labels: msp, approved

#1175 add see detail permission
  shell/app/modules/msp/env-setting/configuration/index.tsx
Labels: msp, approved

#1187 fix: uc proxy
  modules/uc/src/common/utils.ts
  modules/uc/src/locales/en.json
  modules/uc/src/locales/zh.json
  modules/uc/src/pages/registration/index.tsx
  scheduler/src/proxy.ts
Labels: bugfix

#1174 fix: no permission page restriction maximum of six user names are all…
  shell/app/common/utils/index.ts
  shell/app/user/stores/permission.ts
Labels: approved, bugfix

#1177 fix: add tiled filter dropdown select
  shell/app/common/components/tiled-filter.tsx
Labels: approved, bugfix

#1183 feat: add cp chart dashboard
  shell/app/config-page/components/chart-dashboard/chart-dashboard.spec.d.ts
  shell/app/config-page/components/chart-dashboard/chart-dashboard.tsx
  shell/app/config-page/components/index.tsx
  shell/app/config-page/config-page.d.ts
Labels: feature, approved

#1186 fix(dop): fix manual test filter issue
  shell/app/modules/project/pages/test-plan/test-plan.tsx
  shell/app/modules/project/stores/test-plan.ts
Labels: dop, approved, bugfix

#1189 fix: fix refresh test plan list after edit
  shell/app/modules/addonPlatform/pages/common/components/addon-detail-drawer.tsx
  shell/app/modules/project/pages/test-plan/test-plan.tsx
Labels: dop, approved, bugfix

#1182 feat(common): remove clean script, use clean webpack plugin instead
  core/package.json
  core/webpack.config.js
  modules/market/craco.config.js
  modules/market/package.json
  modules/uc/craco.config.js
  modules/uc/package.json
  pnpm-lock.yaml
  shell/package.json
  shell/webpack.config.js
Labels: refactor, approved

#1190 feat: support epic type in audit template renderer
  shell/app/modules/org/common/audit-render.tsx
Labels: feature, approved

#1197 fix: fix uc proxy/password valid /
  modules/uc/package.json
  modules/uc/src/common/utils.ts
  modules/uc/src/locales/en.json
  modules/uc/src/locales/zh.json
  pnpm-lock.yaml
  scheduler/src/proxy.ts
Labels: bugfix

#1185 Modify redundant code in modal
  shell/app/modules/msp/env-setting/configuration/index.tsx
Labels: msp, approved

#1195 update test case
  shell/app/common/__tests__/components/edit-field.test.tsx
  shell/app/common/__tests__/components/tags-row.test.tsx
  shell/app/common/__tests__/utils/index.test.tsx
Labels: test

#1178 fix: data bank config sheet tree drag and style bug
  shell/app/common/components/tree/tree.scss
  shell/app/common/components/tree/tree.tsx
  shell/app/config-page/components/file-tree/file-tree.scss
  shell/app/modules/project/common/components/pipeline-manage/index.scss
Labels: approved, bugfix

#1198 fix(dop): issue workflow not update after edit, update style
  scheduler/src/filters/error-catch.filter.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/org/common/audit-render.tsx
  shell/app/modules/org/pages/projects/issue-field-setting-modal.scss
  shell/app/modules/org/pages/projects/issue-field-setting-modal.tsx
  shell/app/modules/project/common/components/issue-workflow-setting-modal.scss
  shell/app/modules/project/common/components/issue-workflow-setting-modal.tsx
  shell/app/modules/project/common/components/issue-workflow.tsx
  shell/app/modules/project/pages/backlog/backlog.tsx
  shell/app/modules/project/pages/issue/component/table-view.tsx
  shell/app/modules/project/pages/ticket/index.tsx
  shell/app/modules/project/stores/issue-workflow.ts
  shell/app/modules/project/stores/project.tsx
Labels: dop, bugfix

#1208 fix: remove useless nusi code
  core/src/nusi/index.tsx
Labels: bugfix

#1200 fix: wrapped table action column add divider
  core/src/nusi/wrapped-table.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
Labels: bugfix

#1211 fix: fix project-pipeline pageNo change error
  shell/app/modules/project/common/components/pipeline-manage/run-detail/record-list.tsx
  shell/app/modules/project/services/auto-test-case.ts
Labels: dop, approved, bugfix

#1205 fix: fix k8s style bugs
  shell/app/common/components/tags-row.scss
  shell/app/common/components/tags-row.tsx
  shell/app/common/components/tiled-filter.scss
  shell/app/config-page/components/chart/chart.scss
  shell/app/config-page/components/chart/chart.spec.d.ts
  shell/app/config-page/components/chart/chart.tsx
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-terminal.tsx
  shell/app/modules/cmp/router.js
  shell/app/modules/dcos/pages/cluster-dashboard/index.tsx
Labels: bug, cmp, approved

#1207 refactor(common): entirely remove fdp mask
  cli/lib/build.ts
  shell/app/common/utils/go-to.tsx
  shell/app/layout/pages/page-container/components/menu-head.tsx
  shell/app/layout/pages/page-container/components/sidebar.tsx
  shell/app/layout/stores/layout.ts
  shell/app/menus/appCenter.tsx
  shell/app/org-home/stores/org.tsx
  shell/webpack.config.js
Labels: refactor, approved

#1216 fix: cluster list operate more btn wrong limitNum bug
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
Labels: approved, bugfix

#1212 fix: tree width too wide bug
  shell/app/common/__tests__/components/tree/tree.test.tsx
  shell/app/common/components/tree/tree.scss
  shell/app/common/components/tree/tree.tsx
Labels: approved, bugfix

#1219 feat(msp): Access configuration page interface modification parameters
  shell/app/modules/msp/env-setting/configuration/index.tsx
  shell/app/modules/msp/types/configuration.d.ts
Labels: msp, approved

#1226 feat: copy table cell in dashboard
  pnpm-lock.yaml
  shell/package.json
Labels: approved

#1227 feat: unified chart theme in dashboard and chart
  shell/app/charts/theme.js
  shell/app/common/components/board-grid.tsx
  shell/app/config-page/utils.tsx
Labels: feature

#1221 replace all timeSelector in msp
  shell/app/common/stores/monitorCommon.ts
  shell/app/modules/cmp/stores/_common-custom-dashboard.ts
  shell/app/modules/msp/env-overview/topology/pages/topology-dashboard/index.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/topology.tsx
  shell/app/modules/msp/monitor/api-insight/common/components/filterNav.tsx
  shell/app/modules/msp/monitor/api-insight/pages/indices/index.tsx
  shell/app/modules/msp/monitor/application-insight/common/components/tab-right.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/page/page.tsx
  shell/app/modules/msp/monitor/external-insight/common/components/tab-right.tsx
  shell/app/modules/msp/monitor/gateway-ingress/common/components/tab-right.tsx
  shell/app/modules/msp/monitor/mobile-insight/pages/ajax/ajax.tsx
  shell/app/modules/msp/monitor/mobile-insight/pages/app/app.tsx
  shell/app/modules/msp/monitor/mobile-insight/pages/browser/browser.tsx
  shell/app/modules/msp/monitor/mobile-insight/pages/comparative/comparative.tsx
  shell/app/modules/msp/monitor/mobile-insight/pages/geography/geography-china.tsx
  shell/app/modules/msp/monitor/mobile-insight/pages/overview/overview.tsx
  shell/app/modules/msp/monitor/mobile-insight/pages/page/page.tsx
  shell/app/modules/msp/monitor/mobile-insight/pages/position/position.tsx
  shell/app/modules/msp/monitor/mobile-insight/pages/script/script.tsx
  shell/app/modules/msp/monitor/monitor-common/components/appGroupSelector.tsx
  shell/app/modules/msp/monitor/monitor-common/components/moduleSelector.tsx
  shell/app/modules/msp/monitor/monitor-common/components/top-tab-right.tsx
  shell/app/modules/msp/monitor/service-insight/common/components/instanceSelector.tsx
  shell/app/modules/msp/monitor/service-insight/common/components/tab-right.tsx
Labels: feature, msp

#1233 fix the bug that log time repeated
  shell/app/modules/runtime/common/logs/components/container-log.jsx
Labels: bugfix

#1235 hotfix(dop): Error analysis and statistics big market interface display problem
  shell/app/modules/publisher/pages/artifacts/artifacts-detail.tsx
Labels: dop, bugfix

#1234 Feature/adjust core files name
  core/src/service/index.ts
  shell/app/App.tsx
  shell/app/common/components/filter-group/filter-group.scss
  shell/app/common/utils/go-to.tsx
  shell/tsconfig.json
Labels: refactor

#1206 refactor: replace Nusi Title
  core/src/common/components/title.scss
  core/src/common/components/title.tsx
  core/src/nusi/index.tsx
Labels: refactor

#1224 refactor: replace Nusi Panel
  core/package.json
  core/src/common/components/panel.tsx
  core/src/nusi/index.tsx
Labels: refactor

#1230 fix: fix k8s styles
  shell/app/common/components/tags-row.scss
  shell/app/common/components/tags-row.tsx
  shell/app/common/components/tiled-filter.tsx
  shell/app/config-page/components/api-editor/api-editor.tsx
  shell/app/config-page/components/table/table.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/index.scss
  shell/app/modules/dcos/pages/cluster-dashboard/index.tsx
Labels: bugfix

#1239 fix: fix cp table change page error
  shell/app/config-page/components/table/table.tsx
  shell/app/layout/pages/page-container/components/sidebar.tsx
Labels: dop, bugfix

#1202 refactor: replace Nusi FormBuilder
  core/package.json
  core/src/common/components/form-builder/fields.tsx
  core/src/common/components/form-builder/form-builder.tsx
  core/src/common/components/form-builder/index.tsx
  core/src/common/components/form-builder/readonly-field.tsx
  core/src/common/components/form-builder/search-form.scss
  core/src/common/components/form-builder/search-form.tsx
  core/src/common/interface.d.ts
  core/src/nusi/index.tsx
  shell/app/config-page/components/api-resource/resource-summary.tsx
  shell/app/config-page/components/api-resource/resource.tsx
  shell/app/config-page/components/api-resource/response-config.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/apiManagePlatform/pages/api-market/design/basic-params-config.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/design/datatype-config.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/design/property-field.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/design/summary.tsx
  shell/app/modules/application/pages/deploy-list/deploy-list.tsx
Labels: refactor

#1237 refactor: replace Nusi Popover
  core/src/nusi/index.tsx
  shell/app/common/components/tree/tree.tsx
  shell/app/config-page/components/file-tree/file-tree.tsx
Labels: refactor

#1231 feat: optimize trace detail waterfall
  shell/app/common/components/time-select/common.ts
  shell/app/common/components/time-select/time-select.tsx
  shell/app/common/stores/monitorCommon.ts
  shell/app/common/utils/go-to.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-overview/service-list/index.ts
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
  shell/app/modules/msp/monitor/external-insight/pages/affairs/affairs.tsx
  shell/app/modules/msp/monitor/service-insight/pages/database/database.tsx
  shell/app/modules/msp/monitor/service-insight/pages/web/web.tsx
  shell/app/modules/msp/monitor/trace-insight/index.js
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-detail-new.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.scss
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/span-time-info.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/span-title-info.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/trace-detail-info.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/trace-header.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/utils.ts
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search-detail.scss
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search-detail.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-status-viewer.tsx
  shell/app/modules/msp/monitor/trace-insight/stores/trace-querier.ts
  shell/app/modules/msp/monitor/trace-insight/types/index.d.ts
  shell/app/modules/msp/services/index.ts
  shell/app/modules/msp/stores/trace.ts
  shell/app/styles/antd-extension.scss
  shell/tailwind.config.js
Labels: feature

#1243 fix: delete useless env UC_PUBLIC_URL
  erda.yml
Labels: bugfix

#1248 fix(msp): fix the bug that log time repeated
  shell/app/modules/runtime/common/logs/components/container-log.jsx
Labels: bugfix

#1246 fix core webpack config
  core/webpack.config.js
Labels: core, chore

#1245 fix: organization starts with ta
  nginx.conf.template
  shell/app/common/components/time-select/common.ts
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx
Labels: bugfix
