Repository erda-project/erda-ui, pull requests merged in 2021-08, with the labels that each got.

#807 fix pipeline failed issue when only build community version
  cli/lib/build.ts
  cli/package.json
Labels: bugfix, cli

#808 Fix: alarm state icon color
  shell/app/modules/cmp/common/alarm-state.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/groupTabs.tsx
Labels: approved, bugfix

#809 support create microService governance project
  core/src/service/api-creator.ts
  cspell.json
  shell/app/common/__tests__/components/key-value-editor.test.tsx
  shell/app/common/__tests__/components/log/download-log-modal.test.tsx
  shell/app/common/components/class-wrap.tsx
  shell/app/common/components/erda-icon/erda-icon.tsx
  shell/app/common/utils/go-to.tsx
  shell/app/layout/pages/page-container/components/menu-head.scss
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/appCenter.tsx
  shell/app/menus/msp.tsx
  shell/app/modules/msp/config.ts
  shell/app/modules/msp/pages/configuration/index.tsx
  shell/app/modules/msp/pages/configuration/type-select.scss
  shell/app/modules/msp/pages/configuration/type-select.tsx
  shell/app/modules/msp/pages/micro-service/entry.scss
  shell/app/modules/msp/pages/micro-service/entry.tsx
  shell/app/modules/msp/pages/micro-service/overview.tsx
  shell/app/modules/msp/pages/micro-service/project-list.tsx
  shell/app/modules/msp/pages/micro-service/switch-env.tsx
  shell/app/modules/msp/router.js
  shell/app/modules/msp/services/configuration.ts
  shell/app/modules/msp/services/index.ts
  shell/app/modules/msp/stores/micro-service.tsx
  shell/app/modules/msp/types/configuration.d.ts
  shell/app/modules/msp/types/index.d.ts
  shell/app/modules/org/pages/projects/create-project.scss
  shell/app/modules/org/pages/projects/create-project.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/org/pages/projects/settings.tsx
  shell/app/modules/project/pages/settings/components/project-info.tsx
  shell/app/modules/project/types/project.d.ts
  shell/app/views/index.ejs
Labels: approved, feature, msp

#811 add timeselect on msp overview
  shell/app/modules/msp/pages/micro-service/overview.tsx
Labels: approved, feature, msp

#812 fix: custom-addon edit bug
  shell/app/modules/project/pages/third-service/components/instance-form.tsx
  shell/app/modules/project/pages/third-service/components/third-addon-form.tsx
Labels: bugfix

#743 iconfont transfered to iconpark
  shell/app/common/components/back-to-top.tsx
  shell/app/common/components/confirm-delete.tsx
  shell/app/common/components/contractive-filter.scss
  shell/app/common/components/contractive-filter.tsx
  shell/app/common/components/dropdown-select.tsx
  shell/app/common/components/erda-icon/erda-icon.tsx
  shell/app/common/components/image-upload.tsx
  shell/app/common/components/menu-popover.tsx
  shell/app/common/components/sort-drag-list.tsx
  shell/app/common/components/tree/edit-category.tsx
  shell/app/config-page/components/dropdown-select/dropdown-select.scss
  shell/app/config-page/components/dropdown-select/dropdown-select.tsx
  shell/app/layout/pages/page-container/components/menu-head.scss
  shell/app/modules/application/common/app-selector.tsx
  shell/app/modules/application/common/components/goto-commit.tsx
  shell/app/modules/application/pages/build-detail/pipeline-log.tsx
  shell/app/modules/application/pages/deploy/deploy.tsx
  shell/app/modules/application/pages/deploy/runtime-box.tsx
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/pages/pipeline/run-detail/pipeline-log.tsx
  shell/app/modules/application/pages/repo/components/repo-file-container.tsx
  shell/app/modules/application/pages/repo/components/repo-nav.tsx
  shell/app/modules/application/pages/repo/repo-branch.scss
  shell/app/modules/application/pages/repo/repo-branch.tsx
  shell/app/modules/application/pages/repo/repo-commit.tsx
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/cmp/pages/alarm-report/index.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/case-api.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
  shell/app/modules/project/pages/test-manage/case/manual-test.tsx
  shell/app/modules/publisher/pages/artifacts/version-list.tsx
  shell/app/views/index.ejs
  shell/app/yml-chart/pipeline-editor.tsx
Labels: approved, refactor

#816 feat(cmp): the node name is displayed in the labeling function
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/dcos/pages/machine-manager/tag-form.tsx
Labels: cmp

#820 fix: trace debug body textarea style bug
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.scss
Labels: approved, bugfix

#821 fix: restore escaped quotes in log content
  shell/app/common/components/log/log-content.tsx
  shell/app/common/components/runtime/simple-log-roller.tsx
  shell/app/interface/global.d.ts
  shell/app/modules/runtime/common/logs/components/container-log.jsx
Labels: bugfix

#818 add breadcrumb and refactor switch env
  shell/app/common/__tests__/components/menu-popover.test.tsx
  shell/app/common/components/erda-icon/erda-icon.tsx
  shell/app/layout/stores/breadcrumb.ts
  shell/app/modules/msp/pages/micro-service/project-list.tsx
  shell/app/modules/msp/pages/micro-service/switch-env.tsx
  shell/app/modules/msp/router.js
  shell/app/modules/msp/services/index.ts
  shell/app/modules/msp/stores/micro-service.tsx
  shell/app/modules/org/pages/projects/create-project.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/org/pages/projects/settings.tsx
  shell/app/modules/project/pages/settings/components/project-info.tsx
  shell/app/modules/project/types/project.d.ts
  shell/app/views/index.ejs
Labels: feature, msp

#815 Delete extra code and modify color name
  shell/app/common/components/dropdown-select.tsx
  shell/app/common/components/erda-icon/erda-icon.tsx
  shell/app/common/components/image-upload.tsx
  shell/app/common/components/tree/edit-category.tsx
  shell/app/modules/application/pages/build-detail/pipeline-log.tsx
  shell/app/modules/application/pages/deploy/deploy.tsx
  shell/app/modules/application/pages/deploy/runtime-box.tsx
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/pages/pipeline/run-detail/pipeline-log.tsx
  shell/app/modules/application/pages/repo/components/repo-file-container.tsx
  shell/app/modules/application/pages/repo/repo-branch.scss
  shell/app/modules/application/pages/repo/repo-branch.tsx
  shell/app/modules/application/pages/repo/repo-commit.tsx
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/case-api.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
  shell/app/modules/project/pages/test-manage/case/manual-test.tsx
  shell/app/yml-chart/pipeline-editor.tsx
Labels: approved, refactor

#802 feat: update pipeline log style
  shell/app/modules/application/common/components/pipeline-node.tsx
  shell/app/modules/application/pages/build-detail/pipeline-chart/pipeline-node.tsx
  shell/app/modules/application/pages/pipeline/run-detail/pipeline-chart/pipeline-node.tsx
Labels: dop, feature

#819 draft: replace Nusi Select with Antd
  core/src/nusi/index.tsx
  shell/app/common/components/tree/tree.tsx
  shell/app/config-page/components/select-pro/select-pro.tsx
  shell/app/modules/apiManagePlatform/components/select-pro.scss
  shell/app/modules/apiManagePlatform/components/select-pro.tsx
Labels: refactor

#803 draft: replace Nusi Alert with Antd
  core/src/nusi/index.tsx
  shell/app/common/components/add-member-modal.tsx
  shell/app/common/components/menu-popover.tsx
  shell/app/common/components/url-invite-modal.tsx
  shell/app/modules/apiManagePlatform/pages/access-manage/edit/index.tsx
  shell/app/modules/application/pages/build-detail/index.tsx
  shell/app/modules/application/pages/deploy/deploy.tsx
  shell/app/modules/application/pages/deploy/runtime-box.tsx
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/pages/repo/components/add-pipelineyml.tsx
  shell/app/modules/application/pages/repo/components/source-target-select.tsx
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
  shell/app/modules/cmp/pages/computing/ecs/index.tsx
  shell/app/modules/cmp/pages/middleware-dashboard/scale-modal.tsx
  shell/app/modules/dcos/pages/service-manager/mq-manager/group.tsx
  shell/app/modules/dcos/pages/service-manager/mq-manager/topic.tsx
  shell/app/modules/org/pages/projects/create-project.tsx
  shell/app/modules/org/pages/setting/block-network.tsx
  shell/app/modules/project/pages/addon/custom-config.tsx
  shell/app/modules/project/pages/apps/app-form.tsx
  shell/app/modules/project/pages/milestone/milestone-item.tsx
  shell/app/modules/project/pages/test-env/test-env.tsx
Labels: refactor

#822 fix request errors when page back
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/monitor/topology/pages/topology-dashboard/index.tsx
  shell/app/modules/msp/monitor/topology/pages/topology/topology.tsx
  shell/app/modules/msp/pages/micro-service/project-list.tsx
  shell/app/modules/msp/pages/micro-service/switch-env.tsx
Labels: bugfix, msp

#826 remove the api that query monitor instance
  shell/app/modules/msp/monitor/error-insight/pages/errors/error-overview.tsx
  shell/app/modules/msp/monitor/monitor-overview/services/monitor-overview.ts
  shell/app/modules/msp/monitor/monitor-overview/stores/monitor-overview.ts
  shell/app/modules/msp/monitor/monitor-overview/types/index.d.ts
  shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
Labels: feature, msp

#825 fix: the size of ticket Table change
  shell/app/modules/project/pages/ticket/index.tsx
Labels: bugfix

#814 draft: replace Nusi Anchor with Antd
  core/src/nusi/index.tsx
  shell/app/common/components/details-panel.scss
  shell/app/common/components/details-panel.tsx
  shell/app/modules/apiManagePlatform/components/select-pro.tsx
Labels: approved, refactor

#823 Replace class with classname and adjust the icon position
  shell/app/common/components/back-to-top.tsx
  shell/app/common/components/contractive-filter.tsx
  shell/app/common/components/erda-icon/erda-icon.tsx
  shell/app/common/components/sort-drag-list.tsx
  shell/app/common/components/tree/edit-category.tsx
  shell/app/modules/application/common/components/goto-commit.tsx
  shell/app/modules/application/pages/build-detail/pipeline-log.tsx
  shell/app/modules/application/pages/deploy/deploy.tsx
  shell/app/modules/application/pages/deploy/runtime-box.scss
  shell/app/modules/application/pages/deploy/runtime-box.tsx
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/pages/pipeline/run-detail/pipeline-log.tsx
  shell/app/modules/application/pages/repo/components/repo-file-container.tsx
  shell/app/modules/application/pages/repo/repo-branch.tsx
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/case-api.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
  shell/app/modules/project/pages/test-manage/case/manual-test.tsx
  shell/app/modules/publisher/pages/artifacts/version-list.tsx
  shell/app/yml-chart/pipeline-editor.tsx
Labels: refactor

#830 fix: when create file, submit message is required
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/repo/components/repo-editor.tsx
Labels: approved, bugfix

#834 fix: issue type maybe undefined some time
  shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/stores/issues.ts
Labels: bugfix, dop

#827 fix: deploy create releaseId select style bug
  shell/app/common/components/details-panel.tsx
  shell/app/common/components/load-more-selector.tsx
  shell/app/common/components/log/log-content.tsx
  shell/app/common/components/runtime/simple-log-roller.tsx
Labels: approved, bugfix

#828 fix(dop): fix icon style unnormal
  shell/app/modules/project/pages/plan-detail/status-toggle.scss
  shell/app/modules/project/pages/plan-detail/status-toggle.tsx
Labels: bugfix

#837 replace the request method for updating tenant
  shell/app/modules/msp/services/index.ts
  shell/app/modules/project/pages/settings/components/project-info.tsx
Labels: msp

#840 add edas cluster operations & fix inline form wrap issue
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
  shell/app/styles/antd-extension.scss
Labels: approved, bugfix, cmp

#846 fix(dop): fix invalid date issue
  shell/app/modules/runtime/common/components/pod-table.tsx
Labels: bugfix

#844 refactor: replace Nusi Avatar and Tag with Antd
  core/src/nusi/index.tsx
  core/src/nusi/wrapped-tag.tsx
  shell/app/styles/antd-extension.scss
Labels: refactor

#852 refactor: replace Nusi Tooltip with Antd
  core/src/nusi/index.tsx
  shell/app/styles/antd-extension.scss
Labels: refactor

#855 fix project card style
  shell/app/modules/org/pages/projects/create-project.tsx
Labels: dop

#853 feat: update markdown editor interaction and style
  pnpm-lock.yaml
  shell/app/common/components/markdown-editor/index.scss
  shell/app/common/components/markdown-editor/index.tsx
  shell/app/modules/project/common/components/issue/comment-box.tsx
  shell/package.json
Labels: feature

#863 fix: fix project service form error
  shell/app/modules/project/pages/third-service/components/addon-modal.tsx
  shell/app/modules/project/pages/third-service/components/instance-form.tsx
Labels: bugfix, dop

#861 fix(cmp): add content trim
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
Labels: bugfix, cmp

#860 fix create pr error
  shell/app/modules/application/pages/repo/components/source-target-select.tsx
Labels: approved, bugfix, dop

#854 fix request occasional error
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/application/pages/settings/components/app-notify/index.scss
  shell/app/modules/application/pages/settings/components/app-notify/notify-config.tsx
  shell/app/modules/cmp/common/alarm-strategy/index.scss
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
  shell/app/modules/cmp/common/custom-alarm/index.tsx
  shell/app/modules/msp/stores/micro-service.tsx
Labels: bugfix, msp

#859 feat: add project level pipeline action request params
  shell/app/modules/application/common/yml-editor/pipeline-editor.tsx
  shell/app/modules/application/pages/pipeline/index.tsx
  shell/app/modules/application/pages/pipeline/scope-config.tsx
  shell/app/yml-chart/common/pipeline-node-drawer.tsx
Labels: approved, dop, feature

#862 fix: encode some character error with encodeURI
  shell/app/common/__tests__/components/img-holder.test.tsx
  shell/app/common/components/img-holder.tsx
Labels: approved, bugfix

#871 refactor: replace Nusi Breadcrumb with Antd
  core/src/nusi/index.tsx
  shell/app/config-page/components/breadcrumb/breadcrumb.tsx
Labels: refactor

#869 fix table rowkey
  shell/app/modules/dcos/pages/machine-manager/machine-table.tsx
Labels: dop, bugfix

#873 fix the bug that projectId is missing when query app
  shell/app/modules/cmp/common/components/log-tag-selector.tsx
Labels: msp, bugfix

#877 fix: nginx.conf change
  nginx.conf.template
Labels: bugfix

#880 fix: pipeline node label change
  shell/app/yml-chart/common/pipeline-node-drawer.tsx
Labels: bugfix

#878 fix tab interaction
  shell/app/modules/dcos/pages/cluster-dashboard/groupTabs.tsx
Labels: cmp

#874 refactor: replace Nusi Card with Antd
  core/src/nusi/index.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-common-panel.tsx
  shell/app/styles/antd-extension.scss
Labels: refactor

#872 fix: adjust style of radio in create organization modal
  shell/app/configForm/nusi-form/form-items/radio.scss
  shell/app/configForm/nusi-form/form-items/radio.tsx
  shell/tailwind.config.js
Labels: bugfix

#886 change the replicas in production
  erda.yml
Labels: approved, bugfix

#889 clear project info when leave mspDetail
  shell/app/modules/msp/stores/micro-service.tsx
Labels: msp

#882 feat(cmp): add cluster detail content text conversion
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-detail.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
Labels: feature, cmp

#804 style: add emptyHolder to dataSource page
  shell/app/config-page/components/image/image.scss
  shell/app/modules/project/pages/data-source/index.tsx
Labels: dop, approved

#848 add testcase for formModal
  pnpm-lock.yaml
  shell/app/common/__tests__/components/class-wrap.test.tsx
  shell/app/common/__tests__/components/color-label.test.tsx
  shell/app/common/__tests__/components/contractive-filter.test.tsx
  shell/app/common/__tests__/components/erda-icon/erda-icon.test.tsx
  shell/app/common/__tests__/components/filter-group/filter-group.test.tsx
  shell/app/common/__tests__/components/form-modal.test.tsx
  shell/app/common/__tests__/components/key-value-editor.test.tsx
  shell/app/common/__tests__/components/member-selector.test.tsx
  shell/app/common/__tests__/components/operate-btn.test.tsx
  shell/app/common/__tests__/components/tags-row.test.tsx
  shell/app/common/components/class-wrap.tsx
  shell/app/common/components/color-label.scss
  shell/app/common/components/color-label.tsx
  shell/app/common/components/form-modal.tsx
  shell/app/common/components/tags-row.tsx
  shell/app/common/index.ts
  shell/package.json
  shell/test/setupJest.ts
  shell/tools/testcase-checker.js
Labels: approved, test

#893 fix copy doesn't work in trace page
  shell/app/common/__tests__/components/img-holder.test.tsx
  shell/app/common/components/json-checker.tsx
Labels: msp, approved, bugfix

#892 feat(msp): add reset-button
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-history-list.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.tsx
Labels: feature, msp, approved

#857 fix: trace debug add params style bug
  shell/app/common/components/key-value-table.tsx
  shell/app/styles/app.scss
Labels: approved, bugfix

#899 Hotfix: modify key of option to id in strategy
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
Labels: cmp, bugfix

#902 fix(1.2): fix issue releations error
  shell/app/modules/project/common/components/issue/issue-relation.tsx
Labels: dop, bugfix

#903 fix: fix issue relation error
  shell/app/modules/project/common/components/issue/issue-relation.tsx
Labels: dop, bugfix

#839 fix: backlog table pagination style bug
  shell/app/modules/project/pages/backlog/backlog.scss
Labels: approved, bugfix

#906 always show search input
  shell/app/modules/application/pages/repo/repo-branch.tsx
Labels: approved

#910 fix(1.2): fix repo file delete error
  shell/app/common/utils/str-num-date.tsx
  shell/app/modules/application/pages/repo/components/repo-file-container.tsx
  shell/app/modules/application/stores/repo.ts
Labels: dop, approved, bugfix

#912 fix: fix pipeline action form init error
  shell/app/yml-chart/common/pipeline-node-drawer.tsx
Labels: dop, bugfix

#907 Fix: modify the tab to IP address in container monitor
  shell/app/modules/runtime/common/components/slide-panel-tabs.tsx
Labels: dop, approved

#895 Refactor/replace nusi tree with antd
  core/src/common/interface.d.ts
  shell/app/common/__tests__/components/tree/tree.test.tsx
  shell/app/common/components/tree/file-tree.scss
  shell/app/common/components/tree/tree.tsx
  shell/app/config-page/components/file-tree/file-tree.scss
  shell/app/config-page/components/file-tree/file-tree.tsx
Labels: refactor, approved

#914 fix: add version tag
  shell/app/layout/pages/page-container/components/sidebar.scss
  shell/app/layout/pages/page-container/components/sidebar.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
Labels: feature, approved

#917 feat(cmp): hide register command when cluster registered
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
Labels: feature, cmp, approved, bugfix

#918 fix: fix app select style
  shell/app/modules/project/pages/apps/app-type-select.scss
  shell/app/modules/project/pages/apps/app-type-select.tsx
Labels: bugfix

#904 fix: init optimize
  core/src/history.ts
  core/src/index.tsx
  core/webpack.config.js
  shell/app/App.tsx
  shell/app/common/__tests__/components/addon-settings.test.tsx
  shell/app/common/__tests__/components/custom-filter.test.tsx
  shell/app/common/__tests__/components/error-boundary.test.tsx
  shell/app/common/__tests__/components/filter-group/filter-group.test.tsx
  shell/app/common/__tests__/components/setting-tabs.test.tsx
  shell/app/common/__tests__/utils/go-to.test.tsx
  shell/app/common/__tests__/utils/query-string.test.tsx
  shell/app/common/utils/axios-config.ts
  shell/app/common/utils/go-to.tsx
  shell/app/layout/pages/page-container/components/sidebar.tsx
  shell/app/modules/application/pages/repo/repo-branch.tsx
  shell/app/org-home/stores/org.tsx
  shell/app/user/stores/index.ts
  shell/app/views/init.js
  shell/tsconfig.json
Labels: feature, approved

#916 fix: fix branch compare source target position
  shell/app/modules/application/pages/repo/components/source-target-select.tsx
Labels: approved, bugfix

#927 remove the items-center of case-drawer
  shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
Labels: dop, bugfix

#896 feat(common): replace nginx
  .cz-config.js
  Dockerfile
  cli/lib/build.ts
  cli/lib/release.ts
  cli/lib/util/env.ts
  cspell.json
  install-cli.js
  local_Dockerfile
  nginx.conf.template
  package.json
  pnpm-lock.yaml
  scheduler/package.json
  scheduler/src/app.module.ts
  scheduler/src/controllers/env.controller.ts
  scheduler/src/controllers/health.controller.ts
  scheduler/src/controllers/legacy-route.controller.ts
  scheduler/src/controllers/market.controller.ts
  scheduler/src/controllers/version.controller.ts
  scheduler/src/filters/error-catch.filter.ts
  scheduler/src/filters/not-found.filter.ts
  scheduler/src/main.ts
  scheduler/src/middlewares/guard.middleware.ts
  scheduler/src/proxy.ts
  scheduler/src/util.ts
  shell/mf.config.js
Labels: scheduler, refactor, approved

#929 fix: choose chart type before saving in dashboard
  pnpm-lock.yaml
  shell/package.json
Labels: approved, bugfix

#931 Release/1.2 add install cli script
  install-cli.js
  package.json
Labels: refactor, approved

#933 fix: fix md button show error
  shell/app/common/components/markdown-editor/index.scss
  shell/app/common/components/markdown-editor/index.tsx
Labels: approved, bugfix

#934 fix: fix menu i18n
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/appCenter.tsx
  shell/app/menus/index.ts
  shell/app/menus/util.ts
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
Labels: bugfix

#936 chore: unified package version
  core/package.json
  package.json
  scheduler/package.json
  shell/package.json
Labels: chore

#937 fix style in en mode
  shell/app/modules/cmp/pages/account-guidance/index.scss
Labels: cmp, approved, bugfix

#938 fix: upgrade dashboard to v1.0.25
  pnpm-lock.yaml
  shell/package.json
Labels: approved, bugfix

#940 fix: page crash in problem detail page
  shell/app/modules/application/pages/problem/problem-detail.tsx
Labels: dop, bugfix

#944 fix(common): rollback set history config
  core/src/index.tsx
Labels: bugfix

#945 Feature: init optimize 1.2
  core/src/history.ts
  core/src/index.tsx
  core/webpack.config.js
  shell/app/App.tsx
  shell/app/common/__tests__/components/error-boundary.test.tsx
  shell/app/common/__tests__/utils/query-string.test.tsx
  shell/app/common/utils/axios-config.ts
  shell/app/common/utils/go-to.tsx
  shell/app/layout/pages/page-container/components/sidebar.tsx
  shell/app/org-home/stores/org.tsx
  shell/app/user/stores/index.ts
  shell/app/views/init.js
  shell/tsconfig.json
Labels: refactor

#943 disable ability to create msp projects
  shell/app/modules/org/pages/projects/create-project.tsx
Labels: feature, msp, approved

#950 fix: add tooltip to pipeline record status
  shell/app/common/types/pipeline.d.ts
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/pages/pipeline/run-detail/pipeline-chart/index.tsx
  shell/app/modules/application/types/build.d.ts
Labels: dop, bugfix

#952 Hotfix/manual test table style
  shell/app/modules/project/pages/test-manage/case/manual-test.tsx
  shell/app/modules/project/pages/test-manage/components/case-table/index.tsx
  shell/app/modules/project/pages/test-manage/components/case-tree/index.tsx
  shell/app/modules/project/pages/test-manage/components/case-tree/utils.ts
Labels: dop, bugfix

#956 fix: add css dc namespace to FormBuilder
  pnpm-lock.yaml
  shell/package.json
Labels: bugfix

#947 fix: in add tag form, source type change bug after submit
  shell/app/modules/application/pages/repo/repo-tag.tsx
Labels: approved, bugfix

#949 feat: use root domain in invite url
  shell/app/common/components/members-table.tsx
  shell/app/common/constants.ts
Labels: feature

#955 fix: update repository address regexp
  shell/app/modules/project/pages/apps/app-form.tsx
Labels: dop, bugfix

#954 fix: add css dc namespace to FormBuilder
  pnpm-lock.yaml
  shell/package.json
Labels: approved, bugfix

#959 feat: add dashboard auit template
  shell/app/modules/org/common/audit-templates.json
Labels: feature, approved

#948 test(dop): add case for deploy
  cspell.json
  shell/auto_test/fixtures.ts
  shell/auto_test/tests/dop/deploy.spec.ts
Labels: approved, test

#961 fix(common): add purple to safelist
  shell/tailwind.config.js
Labels: approved, bugfix

#963 fix: fix version
  shell/package.json
Labels: bugfix

#966 fix: Select in nusi Form width style bug
  shell/app/styles/antd-extension.scss
Labels: approved, bugfix

#965 fix: page-container Card style bug
  shell/app/layout/pages/page-container/page-container.tsx
Labels: bugfix

#971 fix: Select in nusi Form width style bug
  shell/app/styles/antd-extension.scss
Labels: bugfix

#972 fix: view public organization is not found
  shell/app/org-home/stores/org.tsx
Labels: bugfix

#976 feat: update architecture diagram
  docs/files/architecture.jpg
  shell/README.md
Labels: refactor

#977 feat: support render newline in audit template
  shell/app/modules/org/pages/safety/index.tsx
Labels: feature

#979 feat: add pipeline auto test
  pnpm-lock.yaml
  shell/auto_test/fixtures.ts
  shell/auto_test/tests/dop/pipeline.spec.ts
  shell/package.json
Labels: approved, test

#980 fix(scheduler): fix websocket 403 issue
  core/package.json
  core/src/utils/ws.ts
  pnpm-lock.yaml
  scheduler/src/main.ts
  scheduler/src/proxy.ts
  shell/package.json
Labels: scheduler, bugfix

#981 fix: fix history listen execute twice
  core/src/history.ts
  core/webpack.config.js
  shell/app/App.tsx
  shell/app/common/__tests__/components/error-boundary.test.tsx
  shell/app/common/__tests__/utils/query-string.test.tsx
  shell/app/common/utils/go-to.tsx
  shell/tsconfig.json
Labels: bugfix

#982 fix: fix history listen execute twice
  core/src/history.ts
  core/webpack.config.js
  shell/app/App.tsx
  shell/app/common/__tests__/components/error-boundary.test.tsx
  shell/app/common/__tests__/utils/query-string.test.tsx
  shell/app/common/utils/go-to.tsx
  shell/tsconfig.json
Labels: bugfix

#983 fix: fix history compare
  core/src/history.ts
Labels: approved, bugfix

#964 add case for app
  pnpm-lock.yaml
  shell/auto_test/fixtures.ts
  shell/auto_test/tests/admin/user-manage.spec.ts
  shell/auto_test/tests/dop/app/app-config.spec.ts
  shell/auto_test/tests/dop/app/app-manage.spec.ts
  shell/auto_test/tests/dop/app/branch-rule.spec.ts
  shell/auto_test/tests/dop/app/notify.spec.ts
  shell/auto_test/tests/dop/app/private-config.spec.ts
  shell/auto_test/tests/dop/deploy.spec.ts
  shell/auto_test/tests/dop/layout.spec.ts
  shell/auto_test/tests/dop/pipeline.spec.ts
  shell/auto_test/tests/dop/project-manage.spec.ts
  shell/auto_test/tests/pages/app-manage.ts
  shell/auto_test/tests/pages/base.ts
  shell/auto_test/tests/pages/notify.ts
  shell/auto_test/tests/pages/project-manage.ts
  shell/auto_test/tests/pages/user-manage.ts
  shell/auto_test/tests/pages/variable-config.ts
Labels: approved, test

#978 add UI test
  shell/auto_test/fixtures.ts
  shell/auto_test/tests/dop/branches.spec.ts
  shell/auto_test/tests/dop/merge-requests.spec.ts
Labels: approved, test

#984 fix: fix admin login api error
  shell/app/App.tsx
  shell/app/common/utils/axios-config.ts
  shell/app/modules/project/pages/apps/app-form.tsx
  shell/app/user/stores/index.ts
Labels: approved, bugfix

#985 fix(1.2): fix admin login api error
  shell/app/App.tsx
  shell/app/common/utils/axios-config.ts
  shell/app/modules/project/pages/apps/app-form.tsx
  shell/app/user/stores/index.ts
Labels: bugfix

#988 feat: auto test of commit history and souce
  shell/auto_test/fixtures.ts
  shell/auto_test/tests/dop/history.spec.ts
  shell/auto_test/tests/dop/repo.spec.ts
Labels: approved

#990 fix: fix file tree select none
  shell/app/config-page/components/file-tree/file-tree.spec.d.ts
  shell/app/config-page/components/file-tree/file-tree.tsx
Labels: bugfix

#989 fix: open terminal which is crashed in deploy center
  shell/app/modules/runtime/pages/overview/components/service-card.tsx
Labels: dop, bugfix

#993 fix: fix file tree select none
  shell/app/config-page/components/file-tree/file-tree.spec.d.ts
  shell/app/config-page/components/file-tree/file-tree.tsx
Labels: bugfix

#994 feat: add confirmation when issue-drawer esc keydown
  shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
  shell/app/modules/project/common/components/issue/issue-drawer.tsx
Labels: bugfix

#987 fix: convert unit which is week or day to hour in dashboard
  pnpm-lock.yaml
  shell/package.json
Labels: cmp, approved, bugfix

#992 fix: Increase the width of issue-relation-table
  shell/app/modules/project/common/components/issue/issue-relation.tsx
Labels: approved, bugfix

#986 add case for code-quality
  shell/app/views/index.ejs
  shell/auto_test/fixtures.ts
  shell/auto_test/tests/dop/add-ticket.spec.ts
  shell/auto_test/tests/dop/app/app-manage.spec.ts
  shell/auto_test/tests/dop/sonar-test.spec.ts
  shell/auto_test/tests/dop/unit-test.spec.ts
Labels: approved, test

#995 remove unused packages
  cli/package.json
  core/package.json
  modules/market/package.json
  pnpm-lock.yaml
  scheduler/package.json
  shell/package.json
Labels: refactor

#1000 fix: convert unit which is week or day to hour in dashboard
  pnpm-lock.yaml
  shell/package.json
Labels: cmp, bugfix

#998 fix: fix freshMan url redirect
  shell/app/org-home/stores/org.tsx
Labels: bugfix

#999 feat: update pipeline task api
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/services/build.ts
  shell/app/modules/application/stores/build.ts
  shell/app/modules/application/types/build.d.ts
Labels: feature, dop

#991 fix: file-tree style bug caused by Tree upgrade
  shell/app/modules/project/common/components/pipeline-manage/index.scss
Labels: approved, bugfix

#1001 feat: collect all doc url
  shell/app/common/__tests__/constants.test.tsx
  shell/app/common/constants.ts
  shell/app/common/utils/go-to.tsx
  shell/app/layout/pages/page-container/components/sidebar.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/index.tsx
  shell/app/modules/msp/stores/micro-service.tsx
  shell/app/modules/project/pages/settings/components/project-cluster.tsx
Labels: feature, approved

#1003 feat(scheduler): parse org from req url
  scheduler/src/proxy.ts
Labels: refactor, approved

#1006 fix(scheduler): get orgin url from request.originUrl
  scheduler/src/proxy.ts
Labels: bugfix

#1007 fix(market): rollback package dependency change
  modules/market/package.json
  pnpm-lock.yaml
Labels: approved, bugfix

#1004 fix: Re add about layout script
  shell/app/views/index.ejs
Labels: bugfix

#1020 fix: upgrade dashboard to version 1.0.28
  pnpm-lock.yaml
  shell/package.json
Labels: bugfix

#1018 fix: fix i18n about Modal footer
  pnpm-lock.yaml
  shell/package.json
Labels: bugfix

#1022 Feature/api design load file tree logic change
  shell/app/modules/apiManagePlatform/pages/api-market/design/api-doc-tree.tsx
Labels: feature, approved

#1023 fix relative time calculation method
  shell/app/modules/msp/components/time-select.tsx
  shell/app/modules/msp/monitor/topology/pages/topology-dashboard/index.tsx
Labels: msp

#1026 feat: update erda config protocol api
  shell/app/common/services/index.ts
Labels: feature, dop, approved

#1029 fix: i18n built-in dashboard
  pnpm-lock.yaml
  shell/package.json
Labels: bugfix

#1030 add sorting method for trace detail
  shell/app/common/components/use-hooks.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
  shell/app/modules/msp/services/topology-service-analyze.ts
  shell/app/modules/msp/stores/topology-service-analyze.ts
  shell/app/modules/msp/types/topology-service-analyze.d.ts
Labels: feature, msp

#1027 feat: action show multiple instances log
  shell/app/common/types/pipeline.d.ts
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/pages/pipeline/run-detail/build-log.tsx
Labels: feature

#1021 upgrade trace filter conditions
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/monitor/trace-insight/components/duration.tsx
  shell/app/modules/msp/monitor/trace-insight/components/trace-filter.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
  shell/app/modules/msp/monitor/trace-insight/services/trace-querier.ts
  shell/app/modules/msp/monitor/trace-insight/types/index.d.ts
  shell/app/modules/msp/stores/trace.ts
  shell/app/modules/msp/types/monitor.d.ts
Labels: feature, msp

#1024 feat: add pipeline link in project-level-app pipeline detail
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/pages/pipeline/run-detail/pipeline-chart/pipeline-node.tsx
Labels: feature, dop

#1032 add sorting method for trace detail (#1030)
  shell/app/common/components/use-hooks.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
  shell/app/modules/msp/services/topology-service-analyze.ts
  shell/app/modules/msp/stores/topology-service-analyze.ts
  shell/app/modules/msp/types/topology-service-analyze.d.ts
Labels: feature, msp

#1028 fix: fix file editor data exceed
  shell/app/common/components/file-editor.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
Labels: bugfix
