Repository erda-project/erda-ui, pull requests merged in 2021-12, with the labels that each got.

#2176 feat: use font roboto for english and number
  shell/app/static/DIN Alternate Bold.ttf
  shell/app/static/roboto-regular.ttf
  shell/app/styles/app.scss
  shell/app/views/css.js
  shell/index.html
  shell/vite.config.js
Labels: feature

#2175 fix: modify i18n about delete in alarm strategy list
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
Labels: bugfix

#2173 upgrade table in msp
  shell/app/common/components/board-grid/index.tsx
  shell/app/modules/cmp/common/custom-dashboard/index.tsx
  shell/app/modules/cmp/types/dashboard-model.d.ts
  shell/app/modules/msp/env-setting/configuration/index.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
  shell/app/modules/msp/stores/log-analyze.ts
  shell/app/modules/msp/types/gateway.d.ts
  shell/app/modules/msp/types/monitor.d.ts
Labels: feature, msp

#2178 fix(dop): project quota list display scroll
  shell/app/modules/project/pages/settings/components/project-cluster.tsx
Labels: bugfix

#2174 feat(dop): dop gantt left tree expand and create issue button
  shell/app/config-page/components/gantt/gantt.scss
  shell/app/config-page/components/gantt/gantt.spec.d.ts
  shell/app/config-page/components/gantt/gantt.tsx
  shell/app/config-page/components/gantt/utils.ts
  shell/app/config-page/mock/crud.mock.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/issue/plan/index.scss
  shell/app/modules/project/pages/issue/plan/index.tsx
Labels: feature

#2180 adjust animation speed and amplitude
  shell/app/modules/msp/pages/micro-service/overview.scss
Labels: approved, bugfix

#2181 Hotfix/dop gantt left tree style optimization and expand bug
  shell/app/common/components/contractive-filter/index.tsx
  shell/app/config-page/components/gantt/gantt.scss
  shell/app/config-page/components/gantt/gantt.tsx
  shell/app/modules/project/pages/issue/plan/index.scss
  shell/app/modules/project/pages/issue/plan/index.tsx
Labels: bugfix

#2185 adjust msp project list style
  shell/app/modules/msp/pages/micro-service/overview.scss
  shell/app/modules/msp/pages/micro-service/overview.tsx
Labels: feature, msp

#2188 fix(common): table columns config cannot be hidden entirely
  shell/app/common/components/table/table-config.tsx
Labels: approved, bugfix

#2189 Feature/new custom alert component
  shell/app/common/components/boot-prompt/index.scss
  shell/app/common/components/boot-prompt/index.tsx
  shell/app/common/components/erda-alert/index.scss
  shell/app/common/components/erda-alert/index.tsx
  shell/app/common/components/erda-icon/index.tsx
  shell/app/common/index.ts
  shell/app/config-page/components/alert/alert.mock.ts
  shell/app/config-page/components/alert/alert.spec.d.ts
  shell/app/config-page/components/alert/alert.tsx
  shell/app/config-page/components/text-group/text-group.mock.ts
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/org/pages/projects/settings/member/index.tsx
  shell/app/styles/_color.scss
Labels: feature, approved

#2187 feat(dop): issue detail add inclusion relation and start time
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/pages/backlog/issue-item.tsx
  shell/app/modules/project/services/issue.ts
  shell/app/modules/project/stores/issues.ts
  shell/app/modules/project/types/issue.d.ts
Labels: feature, approved

#2190 Feature/show last two characters for Chinese user name
  shell/app/config-page/components/table/render-types.tsx
  shell/app/layout/pages/page-container/components/globalNavigation/userMenu.tsx
  shell/app/modules/project/common/components/issue/subscribers-selector.tsx
  shell/app/modules/project/pages/issue/component/table-view.tsx
  shell/app/modules/project/pages/issue/plan/index.tsx
Labels: feature

#2191 Feat/use getAvatarChars in member selector
  shell/app/common/components/member-selector/index.tsx
Labels: feature

#2192 fix: dop gantt tree user
  shell/app/modules/project/pages/issue/plan/index.tsx
Labels: dop, approved, bugfix

#2194 Feat: export config page components mock data as default
  shell/app/common/__tests__/utils/str-num-date.test.tsx
  shell/app/common/utils/index.ts
  shell/app/common/utils/str-num-date.tsx
  shell/app/config-page/components/bar-chart/bar-chart.mock.ts
  shell/app/config-page/components/container/container.mock.ts
  shell/app/config-page/components/contractive-filter/contractive-filter.mock.ts
  shell/app/config-page/components/copy-button/copy-button.mock.ts
  shell/app/config-page/components/dropdown-select/dropdown-select.mock.ts
  shell/app/config-page/components/form-modal/form-modal.mock.ts
  shell/app/config-page/components/info-preview/info-preview.mock.ts
  shell/app/config-page/components/input-select/input-select.mock.ts
  shell/app/config-page/components/sort-drag-group/sort-drag-group.mock.ts
  shell/app/config-page/components/tree-select/tree-select.mock.ts
  shell/app/config-page/mock/gallery.tsx
Labels: feature

#2193 fix(dop): cancel include tasks drag in issue detail
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/pages/backlog/issue-item.tsx
Labels: bugfix

#2195 fix: not show operation when action is empty
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
Labels: bugfix

#2196 feature: gantt node open detail
  shell/app/config-page/components/gantt/components/gantt/task-gantt.tsx
  shell/app/config-page/components/gantt/components/grid/grid-body.tsx
  shell/app/config-page/components/gantt/gantt.tsx
  shell/app/config-page/components/gantt/helpers/date-helper.ts
  shell/app/config-page/components/gantt/utils.ts
  shell/app/config-page/mock/index.tsx
  shell/app/modules/project/pages/issue/plan/index.tsx
Labels: feature, dop

#2198 Feat: modify style of issue kanban
  shell/app/common/components/icon/index.tsx
  shell/app/common/components/tags-row/index.tsx
  shell/app/common/components/tags/index.scss
  shell/app/common/components/tags/index.tsx
  shell/app/common/constants.ts
  shell/app/config-page/components/issue-kanban.scss
  shell/app/config-page/components/issue-kanban.tsx
  shell/app/config-page/components/kanban-card/card.scss
  shell/app/config-page/components/kanban-card/card.spec.d.ts
  shell/app/config-page/components/kanban-card/card.tsx
  shell/app/modules/project/common/components/issue/issue-config.tsx
  shell/app/modules/project/common/components/issue/issue-icon.tsx
  shell/app/modules/project/pages/settings/components/project-label.scss
  shell/app/modules/project/pages/settings/components/project-label.tsx
  shell/app/styles/_color.scss
  shell/app/views/index.ejs
  shell/index.html
  shell/tailwind.config.js
  shell/theme-color.js
Labels: feature, dop

#2199 fix: fix gantt date error
  shell/app/config-page/components/gantt/components/calendar/calendar.tsx
  shell/app/config-page/components/gantt/components/grid/grid-body.tsx
  shell/app/config-page/components/gantt/helpers/date-helper.ts
Labels: dop, bugfix

#2200 fix: issue include click to detail
  shell/app/common/components/edit-field/index.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/pages/backlog/issue-item.tsx
Labels: dop, approved, bugfix

#2201 fix: fix gantt date count error
  shell/app/config-page/components/gantt/helpers/date-helper.ts
  shell/app/modules/project/tabs.tsx
Labels: dop, approved, bugfix

#2202 fix: fix date helper
  shell/app/config-page/components/gantt/helpers/date-helper.ts
Labels: dop, approved, bugfix

#2203 Feature/gantt performance optimize
  cspell.json
  shell/app/common/components/text-block-info/index.tsx
  shell/app/config-page/components/gantt/components/calendar/calendar.scss
  shell/app/config-page/components/gantt/components/calendar/calendar.tsx
  shell/app/config-page/components/gantt/components/gantt/gantt.scss
  shell/app/config-page/components/gantt/components/gantt/gantt.tsx
  shell/app/config-page/components/gantt/components/gantt/task-gantt.tsx
  shell/app/config-page/components/gantt/components/grid/grid-body.tsx
  shell/app/config-page/components/gantt/components/other/horizontal-scroll.scss
  shell/app/config-page/components/gantt/components/other/horizontal-scroll.tsx
  shell/app/config-page/components/gantt/components/other/scroll.scss
  shell/app/config-page/components/gantt/components/other/scroll.tsx
  shell/app/config-page/components/gantt/components/other/vertical-scroll.scss
  shell/app/config-page/components/gantt/components/task-item/bar/bar-date-handle.tsx
  shell/app/config-page/components/gantt/components/task-item/bar/bar-display.tsx
  shell/app/config-page/components/gantt/components/task-item/bar/bar.scss
  shell/app/config-page/components/gantt/components/task-item/bar/bar.tsx
  shell/app/config-page/components/gantt/components/task-item/milestone/milestone.tsx
  shell/app/config-page/components/gantt/components/task-item/project/project.tsx
  shell/app/config-page/components/gantt/components/task-item/task-item.tsx
  shell/app/config-page/components/gantt/components/task-list/task-list.tsx
  shell/app/config-page/components/gantt/gantt.tsx
  shell/app/config-page/components/gantt/helpers/bar-helper.ts
  shell/app/config-page/components/gantt/types/gantt-task-actions.ts
Labels: feature, approved

#2204 fix cascader unavailable
  pnpm-lock.yaml
  shell/app/modules/project/pages/backlog/backlog.tsx
  shell/package.json
Labels: msp, approved, bugfix

#2206 style: display avatar and not show loadMore when dragging in kanban
  shell/app/config-page/components/issue-kanban.tsx
Labels: dop, approved, bugfix

#2207 fix: k8s pod detail prev log error
  shell/app/modules/cmp/pages/cluster-container/cluster-pod-detail.tsx
Labels: cmp, approved, bugfix

#2205 feat: gantt calendar use transform instead of width to prevent performance issue
  shell/app/config-page/components/gantt/components/calendar/calendar.scss
  shell/app/config-page/components/gantt/components/calendar/calendar.tsx
  shell/app/config-page/components/gantt/components/gantt/gantt.tsx
Labels: feature, approved

#2211 fix: fix gant style
  shell/app/config-page/components/gantt/components/calendar/calendar.tsx
  shell/app/config-page/components/gantt/components/gantt/gantt.tsx
  shell/app/config-page/components/gantt/components/gantt/task-gantt.tsx
  shell/app/config-page/components/gantt/utils.ts
  shell/app/modules/project/pages/issue/plan/index.tsx
Labels: dop, approved, bugfix

#2210 fix(dop): fix can't comment on new line issue
  shell/app/modules/application/pages/repo/components/file-diff.tsx
Labels: dop, approved, bugfix

#2212 fix: fix avatar
  shell/app/modules/project/pages/issue/plan/index.tsx
Labels: approved

#2214 fix(common): progress display bug in table and clusters list style bug
  shell/app/config-page/components/list-new/list-new.tsx
  shell/app/config-page/components/table/render-types.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx
Labels: approved, bugfix

#2213 Center menuicon when folding
  shell/app/layout/pages/page-container/components/sub-sidebar.tsx
  shell/app/menus/project.tsx
Labels: approved, bugfix

#2216 fix: normal branch name display
  shell/app/modules/application/pages/repo/repo-branch.tsx
Labels: dop, approved, bugfix

#2217 fix(dop): issue detail enlarged image is not fully displayed
  shell/app/common/components/edit-field/index.tsx
Labels: approved, bugfix

#2215 fix(common): hidden replace show to decide whether to display table c…
  shell/app/common/components/table/index.tsx
  shell/app/common/components/table/interface.ts
  shell/app/common/components/table/table-config.tsx
Labels: approved, bugfix

#2209 feat(dop): issues table optimization
  shell/app/common/components/erda-icon/index.tsx
  shell/app/common/components/icon/index.tsx
  shell/app/common/index.ts
  shell/app/config-page/components/table/render-types.tsx
  shell/app/config-page/components/table/table.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
Labels: feature, approved

#2219 Feat: add vms and email in notice channel
  locales/en.json
  locales/zh.json
  shell/app/common/constants.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/application/pages/settings/components/app-notify/notify-config.tsx
  shell/app/modules/application/services/notify.ts
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
  shell/app/modules/cmp/pages/alarm-report/index.tsx
  shell/app/modules/org/pages/setting/notice-channel.tsx
  shell/app/modules/org/services/notice-channel.ts
Labels: feature, msp, approved

#2220 fix: gantt calendar error / add time range error
  shell/app/common/components/menu/index.tsx
  shell/app/config-page/components/gantt/components/calendar/calendar.tsx
  shell/app/config-page/components/gantt/components/gantt/gantt.tsx
  shell/app/config-page/components/gantt/components/grid/grid-body.tsx
  shell/app/config-page/components/gantt/components/task-item/bar/bar.scss
  shell/app/config-page/components/gantt/components/task-item/bar/bar.tsx
  shell/app/config-page/components/gantt/components/task-item/task-item.tsx
  shell/app/config-page/components/gantt/gantt.tsx
  shell/app/config-page/mock/crud.mock.ts
  shell/app/layout/pages/page-container/components/header.scss
  shell/app/modules/project/pages/issue/plan/index.tsx
  shell/app/modules/project/tabs.tsx
Labels: dop, approved, bugfix

#2224 fix: api editor button style
  shell/app/config-page/components/api-editor/api-editor.tsx
  shell/app/modules/application/pages/settings/app-settings.tsx
Labels: approved, bugfix

#2227 fix: fix gantt tree node style
  shell/app/config-page/components/gantt/gantt.tsx
  shell/app/modules/project/pages/issue/plan/index.tsx
Labels: dop, approved, bugfix

#2226 fix: modify table in notice channel
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/org/pages/setting/notice-channel.tsx
Labels: approved, bugfix

#2218 fix(dop): issue detail inclusion optimization
  shell/app/modules/project/common/components/issue/issue-relation.tsx
Labels: approved, bugfix

#2222 fix(common): notice change bug when orgs were changed
  shell/app/org-home/pages/personal-home.tsx
  shell/app/org-home/stores/org.tsx
Labels: approved, bugfix

#2223 fix(common): table text overflow bug
  shell/app/config-page/components/table/render-types.tsx
Labels: approved, bugfix

#2231 fix(dop): issue detail inclusion add state
  shell/app/common/components/list/index.scss
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/pages/backlog/issue-item.tsx
  shell/app/modules/project/types/issue.d.ts
Labels: approved, bugfix

#2232 style: add highlight animation to card after dragging successful in kanban
  shell/app/config-page/components/issue-kanban.scss
  shell/app/config-page/components/issue-kanban.tsx
  shell/app/config-page/components/kanban-card/card.tsx
Labels: feature, dop, approved

#2230 feat(msp): Service list page
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/env-overview/service-list/pages/service-list.scss
  shell/app/modules/msp/env-overview/service-list/router.ts
  shell/app/modules/msp/pages/micro-service-overview/index.tsx
  shell/app/modules/msp/services/service-list.ts
Labels: feature, msp, approved

#2233 feat(msp): transform call time
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/addon-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/api-gateway-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/external-service-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/services-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx
Labels: feature, msp, approved

#2234 feat: update project type name
  shell/app/common/utils/go-to.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/project.tsx
  shell/app/modules/msp/pages/micro-service/overview.tsx
  shell/app/modules/org/pages/projects/create-project.tsx
  shell/app/modules/project/pages/issue/task-summary.scss
  shell/app/modules/project/pages/issue/task-summary.tsx
Labels: feature, dop, approved

#2235 feat: update project measure tab text
  locales/zh.json
  shell/app/modules/project/tabs.tsx
Labels: feature, approved

#2237 add git-sync & pipeline.yml for CI
  .github/workflows/git-sync.yml
  pipeline.yml
Labels: chore

#2236 fix(dop): ticket turn to issue bug
  shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
  shell/app/modules/project/common/components/issue/issue-icon.tsx
Labels: approved, bugfix

#2238 add rps for topology
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/addon-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/api-gateway-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/common-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/external-service-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/services-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/progress/hexagon.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/utils/index.ts
  shell/app/modules/msp/env-overview/topology/types/topology.d.ts
Labels: msp, approved

#2239 fix(dop): issue table bug
  shell/app/config-page/components/table/render-types.tsx
Labels: approved, bugfix

#2241 fix: move some logic to prevent circular import
  shell/app/modules/org/stores/announcement.ts
  shell/app/org-home/stores/org.tsx
Labels: approved, bugfix

#2242 fix(msp): perfect service list page
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/env-overview/service-list/pages/service-list.scss
  shell/app/views/index.ejs
Labels: msp, approved, bugfix

#2245 validate serviceIds before request
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
Labels: msp, approved, bugfix

#2246 fix: remove repeat for name
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/common-node.tsx
Labels: msp, approved, bugfix

#2244 fix msp router
  shell/app/common/utils/go-to.tsx
  shell/app/modules/msp/env-overview/router.ts
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/api-gateway-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/common-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/external-service-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/index.scss
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/services-node.tsx
  shell/app/modules/msp/env-overview/topology/router.ts
Labels: approved, bugfix

#2247 fix(dop): issue table complexity icon display bug
  shell/app/common/components/icon/index.tsx
Labels: bugfix

#2249 fix: msp project with applicationId in service overview
  shell/app/modules/msp/env-overview/service-list/pages/service-list-dashboard.tsx
Labels: approved, bugfix

#2257 fix(dop): issue table filter close icon color bug
  shell/app/common/components/contractive-filter/index.scss
Labels: approved, bugfix

#2255 fix(dop): issue table state selector options bug
  shell/app/config-page/components/table/render-types.tsx
Labels: approved, bugfix

#2251 feat: service-list bugfix
  shell/app/common/components/pagination/index.tsx
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
Labels: msp, approved, bugfix

#2252 fix: modify color in kanban
  shell/app/common/components/tags/index.scss
  shell/app/config-page/components/issue-kanban.scss
  shell/app/config-page/components/issue-kanban.tsx
Labels: dop, approved

#2258 feat: move header tabs align with page title
  shell/app/common/components/menu/index.tsx
  shell/app/layout/pages/page-container/components/header.scss
  shell/app/layout/pages/page-container/components/header.tsx
  shell/app/layout/pages/page-container/components/shell/index.scss
  shell/app/layout/pages/page-container/components/sub-sidebar.scss
  shell/app/layout/stores/layout.ts
  shell/app/modules/application/pages/quality/index.tsx
  shell/app/modules/project/tabs.tsx
  shell/app/styles/_mixin.scss
  shell/app/styles/app.scss
Labels: feature, approved

#2253 fix(common): table td height adjustment
  shell/app/config-page/components/table/render-types.tsx
  shell/app/config-page/components/table/table.scss
Labels: approved, bugfix

#2248 fix: adjust import order
  shell/app/App-vite.tsx
  shell/app/App.tsx
Labels: approved, bugfix

#2250 fix: clear page protocol interval timer when unmount
  shell/app/config-page/index.tsx
Labels: dop, approved, bugfix

#2254 Hotfix/update task measurement page style
  shell/app/charts/theme.js
  shell/app/common/components/erda-alert/index.tsx
  shell/app/config-page/components/container/container.spec.d.ts
  shell/app/config-page/components/container/container.tsx
  shell/app/config-page/components/simple-chart/simple-chart.tsx
  shell/app/config-page/components/text-block-group/text-block-group.scss
  shell/app/config-page/components/text-block-group/text-block-group.tsx
  shell/app/modules/project/pages/issue/task-summary.tsx
Labels: approved, bugfix

#2256 Highlight upstream and downstream nodes in the topology
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-overview/router.ts
  shell/app/modules/msp/env-overview/topology/pages/topology/component/floating-edge/index.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/addon-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/api-gateway-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/common-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/external-service-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/index.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/services-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/utils/index.ts
  shell/app/modules/msp/env-overview/topology/types/topology.d.ts
Labels: feature, msp, approved

#2259 fix(common): get announcements list at initialization
  shell/app/org-home/stores/org.tsx
Labels: approved, bugfix

#2262 fix(msp): average throughput does not wrap
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
Labels: msp, approved, bugfix

#2260 feat: gantt new style /gantt reload
  shell/app/config-page/components/gantt/components/calendar/calendar.scss
  shell/app/config-page/components/gantt/components/calendar/calendar.tsx
  shell/app/config-page/components/gantt/components/gantt/gantt.scss
  shell/app/config-page/components/gantt/components/gantt/gantt.tsx
  shell/app/config-page/components/gantt/components/gantt/task-gantt.tsx
  shell/app/config-page/components/gantt/components/grid/grid-body.tsx
  shell/app/config-page/components/gantt/components/grid/grid.scss
  shell/app/config-page/components/gantt/components/other/scroll.tsx
  shell/app/config-page/components/gantt/components/task-item/bar/bar.scss
  shell/app/config-page/components/gantt/components/task-item/bar/bar.tsx
  shell/app/config-page/components/gantt/components/task-item/project/project.scss
  shell/app/config-page/components/gantt/components/task-item/project/project.tsx
  shell/app/config-page/components/gantt/components/task-item/task-item.tsx
  shell/app/config-page/components/gantt/components/task-item/task-list.scss
  shell/app/config-page/components/gantt/components/task-list/task-list.scss
  shell/app/config-page/components/gantt/components/task-list/task-list.tsx
  shell/app/config-page/components/gantt/gantt.spec.d.ts
  shell/app/config-page/components/gantt/gantt.tsx
  shell/app/config-page/components/gantt/helpers/bar-helper.ts
  shell/app/config-page/components/gantt/utils.ts
  shell/app/config-page/index.tsx
  shell/app/config-page/mock/crud.mock.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/issue/plan/index.tsx
  shell/app/styles/_color.scss
  shell/app/views/index.ejs
  shell/index.html
  shell/theme-color.js
Labels: feature, dop

#2261 feat(msp): disable scroll scaling
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/common-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/index.scss
  shell/app/modules/msp/env-overview/topology/pages/topology/index.tsx
Labels: feature, msp, approved

#2263 Hotfix/fix refresh data
  shell/app/config-page/components/container/container.scss
  shell/app/config-page/components/gantt/utils.ts
  shell/app/styles/util.scss
Labels: approved, bugfix

#2264 fix: top button group position when notice exist
  shell/app/config-page/components/text-block-group/text-block-group.tsx
  shell/app/layout/pages/page-container/page-container.scss
Labels: dop, approved, bugfix

#2265 fix radio solid button style
  shell/app/styles/antd-extension.scss
Labels: approved, bugfix

#2266 fix: header tab menu style
  shell/app/layout/pages/page-container/components/header.scss
Labels: approved, bugfix

#2267 chore: add more cache directories in pipeline
  pipeline.yml
  shell/app/common/components/contractive-filter/index.tsx
  shell/app/config-page/components/container/container.tsx
  shell/app/config-page/components/issue-kanban.scss
Labels: bugfix, chore

#2269 Hotfix: gantt hover arrow
  shell/app/config-page/components/gantt/components/calendar/calendar.tsx
  shell/app/config-page/components/gantt/components/gantt/gantt.tsx
  shell/app/config-page/components/gantt/components/gantt/task-gantt-content.tsx
  shell/app/config-page/components/gantt/components/gantt/task-gantt.tsx
  shell/app/config-page/components/gantt/components/grid/grid-body.tsx
  shell/app/config-page/components/gantt/components/grid/grid.scss
  shell/app/config-page/components/gantt/components/task-item/task-item.tsx
  shell/app/config-page/components/gantt/helpers/date-helper.ts
  shell/app/modules/project/pages/issue/plan/index.tsx
Labels: dop, approved, bugfix

#2274 fix: remove application id from service overview
  shell/app/modules/msp/env-overview/service-list/pages/service-list-dashboard.tsx
Labels: approved, bugfix

#2275 fix duplicate requsest
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
Labels: msp, approved, bugfix

#2272 fix service chart style
  shell/app/charts/theme.js
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
Labels: approved, bugfix

#2208 iconpark-transfer
  pnpm-lock.yaml
  shell/app/App-vite.tsx
  shell/app/App.tsx
  shell/app/layout/pages/page-container/components/side-navigation.tsx
  shell/app/modules/project/common/components/issue/issue-config.tsx
  shell/app/modules/project/common/components/issue/subscribers-selector.tsx
  shell/app/modules/project/pages/settings/components/project-label.tsx
  shell/babel.config.js
  shell/mf.config.js
  shell/package.json
Labels: feature, approved

#2268 feat(common): add card list and refactor msp overview
  shell/app/common/components/card-list/index.tsx
  shell/app/common/index.ts
  shell/app/modules/msp/pages/micro-service/overview.tsx
  shell/app/styles/_color.scss
  shell/app/styles/util.scss
Labels: feature, approved

#2270 fix(dop): issue detail complexity add icon
  shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
  shell/app/modules/project/common/components/issue/issue-config.tsx
Labels: approved, bugfix

#2271 fix(dop): issue table reload button bug
  shell/app/common/components/table/index.tsx
  shell/app/config-page/index.tsx
Labels: approved, bugfix

#2273 fix: enlarge the corresponding click image in issue drawer
  shell/app/common/components/edit-field/index.tsx
  shell/app/layout/stores/layout.ts
Labels: dop, approved, bugfix

#2278 feat: modify tip of creating app name
  locales/zh.json
Labels: approved, bugfix

#2282 feat: reorder chart theme color, update dataZoom style
  locales/en.json
  locales/zh.json
  shell/app/charts/theme.js
  shell/app/config-page/components/chart/chart.tsx
  shell/app/config-page/components/simple-chart/simple-chart.tsx
  shell/app/styles/_color.scss
Labels: feature, dop

#2285 fix: wrap environment variables with quotes
  scheduler/src/filters/not-found.filter.ts
Labels: approved, bugfix

#2277 fix: duplicate concat list in table group
  shell/app/config-page/components/table-group/table-group.tsx
Labels: approved, bugfix

#2286 fix analyzeRule scope id
  shell/app/modules/msp/stores/log-analyze.ts
Labels: msp, bugfix

#2280 refactor: use new table component in MSP
  locales/en.json
  locales/zh.json
  shell/app/common/components/table/index.scss
  shell/app/common/components/table/table-config.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/application/pages/settings/components/app-notify/notify-config.tsx
  shell/app/modules/application/stores/notify-group.ts
  shell/app/modules/application/types/common-notify-group.d.ts
  shell/app/modules/cmp/common/alarm-record/detail.tsx
  shell/app/modules/cmp/common/alarm-record/index.tsx
  shell/app/modules/cmp/common/alarm-state.tsx
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
  shell/app/modules/cmp/common/custom-alarm/index.tsx
  shell/app/modules/cmp/pages/alarm-report/index.tsx
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
  shell/app/modules/msp/monitor/status-insight/pages/status/past-incidents.tsx
  shell/app/modules/msp/monitor/status-insight/pages/status/status-detail.tsx
  shell/app/modules/msp/monitor/status-insight/pages/status/status.tsx
  shell/app/modules/msp/monitor/status-insight/types/index.d.ts
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx
Labels: feature, approved

#2287 feat(msp): optimize service list
  shell/app/common/components/card-list/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/services/service-list.ts
  shell/app/modules/msp/types/service.d.ts
Labels: approved

#2291 add topology overview and topology analysis
  .gitignore
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/extra/entry.js
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/floating-edge/connection-line.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/addon-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/api-gateway-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/common-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/external-service-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/index.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/services-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-detail.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-overview.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/index.scss
  shell/app/modules/msp/env-overview/topology/pages/topology/index.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/utils/index.ts
  shell/app/modules/msp/env-overview/topology/types/topology.d.ts
  shell/app/modules/msp/services/service-list.ts
  shell/app/views/index.ejs
  shell/index.html
  shell/theme-color.js
Labels: feature, msp, approved

#2292 Feature/update chart data zoom filter color and text color
  shell/app/charts/theme.js
  shell/tailwind.config.js
  shell/theme-color.js
Labels: feature, approved

#2293 feat: add issue tabs in all issues
  shell/app/common/components/radio-tabs/index.scss
  shell/app/common/components/radio-tabs/index.tsx
  shell/app/common/index.ts
  shell/app/common/utils/query-string.tsx
  shell/app/config-page/components/index.tsx
  shell/app/config-page/components/radio-tabs/radio-tabs.mock.ts
  shell/app/config-page/components/radio-tabs/radio-tabs.spec.d.ts
  shell/app/config-page/components/radio-tabs/radio-tabs.tsx
  shell/app/config-page/config-page.d.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/issue/all.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
  shell/app/modules/project/tabs.tsx
Labels: feature, dop, approved

#2295 style: modify style of tooltip in chart
  pnpm-lock.yaml
  shell/app/charts/components/monitor-chart-new.jsx
  shell/app/charts/components/pie-chart.jsx
  shell/package.json
Labels: msp, approved, bugfix

#2290 fix: can not create mobile app when there is no cluster in the project
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/common/config.ts
  shell/app/modules/project/pages/apps/app-form.tsx
  shell/app/modules/project/pages/apps/app-type-select.scss
  shell/app/modules/project/pages/apps/app-type-select.tsx
Labels: approved, bugfix

#2294 adjust legend style
  shell/app/charts/components/echarts.jsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-detail.tsx
Labels: feature, msp, approved

#2298 fix(common): table dropdown menu item bug
  shell/app/config-page/components/table/render-types.tsx
Labels: approved, bugfix

#2296 Feature/new configurable filter
  shell/app/common/components/configurable-filter/config-selector.tsx
  shell/app/common/components/configurable-filter/index.scss
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/common/components/render-form-item/index.tsx
  shell/app/common/components/tags/index.tsx
  shell/app/common/index.ts
  shell/app/config-page/components/common.spec.d.ts
  shell/app/config-page/components/configurable-filter/configurable-filter.mock.ts
  shell/app/config-page/components/configurable-filter/configurable-filter.spec.d.ts
  shell/app/config-page/components/configurable-filter/configurable-filter.tsx
  shell/app/config-page/components/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/issue/issue-protocol.tsx
  shell/app/styles/_color.scss
  shell/app/views/index.ejs
  shell/index.html
  shell/theme-color.js
Labels: feature, approved

#2297 fix category criteria
  shell/app/charts/components/echarts.jsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-detail.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-overview.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/utils/index.ts
Labels: approved

#2301 fix: revert issue tabs
  shell/app/modules/project/pages/issue/all.tsx
  shell/app/modules/project/tabs.tsx
Labels: approved, bugfix

#2302 fix: remove-extra-character
  shell/app/views/index.ejs
Labels: approved, bugfix

#2305 fix(common): select options display bug
  shell/app/common/components/render-form-item/index.tsx
Labels: approved, bugfix

#2304 feat: unify issue state
  shell/app/charts/components/echarts.jsx
  shell/app/charts/theme.js
  shell/app/common/components/badge/index.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/alarm-record.tsx
  shell/app/modules/project/common/components/issue-workflow-setting-modal.tsx
  shell/app/modules/project/common/components/issue-workflow.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
  shell/app/modules/project/common/components/issue/issue-config.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/common/components/issue/issue-state.tsx
  shell/app/modules/project/common/components/workflow-state-form.tsx
  shell/app/modules/project/common/config.js
  shell/app/modules/project/common/issue-config.ts
  shell/app/modules/project/pages/backlog/issue-item.tsx
  shell/app/modules/project/pages/issue/component/table-view.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/related-bugs.tsx
  shell/app/modules/project/pages/ticket/index.tsx
Labels: feature, dop, approved

#2306 fix(common): configurable filter style optimization
  shell/app/common/components/configurable-filter/index.scss
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/config-page/components/configurable-filter/configurable-filter.spec.d.ts
Labels: bugfix

#2303 fix(common): configurable filter bug
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/config-page/components/configurable-filter/configurable-filter.spec.d.ts
  shell/app/config-page/components/configurable-filter/configurable-filter.tsx
  shell/app/config-page/components/kanban/kanban.tsx
  shell/app/config-page/page-render.tsx
Labels: bugfix

#2299 fix(common): table pagination bug
  shell/app/common/components/table/index.tsx
Labels: approved, bugfix

#2308 fix(common): configurable filter optimization
  shell/app/common/components/configurable-filter/index.scss
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: approved, bugfix

#2310 fix(common): configurable filter placeholder bug
  shell/app/common/components/configurable-filter/index.scss
  shell/app/common/components/configurable-filter/index.tsx
Labels: bugfix

#2312 fix(common): configurable filter bug
  shell/app/common/components/configurable-filter/index.tsx
Labels: approved, bugfix

#2313 fix(common): select options display bug in form
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/common/components/render-form-item/index.tsx
Labels: approved, bugfix

#2314 fix: fix issue dnd provider error
  shell/app/common/components/render-form-item/index.tsx
  shell/app/layout/pages/page-container/page-container.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
Labels: dop, approved, bugfix

#2315 clear search input when switch service type
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
Labels: msp

#2317 fix: fix configurable filter save error
  shell/app/common/components/configurable-filter/config-selector.tsx
  shell/app/config-page/components/configurable-filter/configurable-filter.tsx
Labels: feature, dop, approved

#2316 fix service overview style
  shell/app/modules/msp/env-overview/service-list/pages/overview-new.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-detail.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-overview.scss
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-overview.tsx
Labels: msp, approved

#2318 fix(common): configurable filter bug
  shell/app/common/components/configurable-filter/index.tsx
Labels: approved, bugfix

#2319 fix(common): configurable filter display bug after filter
  shell/app/common/components/configurable-filter/index.tsx
Labels: approved, bugfix

#2320 fix(common): configurable filter display bug after filter
  shell/app/common/components/configurable-filter/index.tsx
Labels: approved, bugfix

#2321 fix(common): table header style bug in multi-line
  shell/app/common/components/table/index.scss
Labels: approved, bugfix

#2323 fix: fix kanban style
  shell/app/modules/project/pages/issue/board.tsx
Labels: dop, approved, bugfix

#2324 fix(common): configurable filter tags select style bug
  shell/app/common/components/configurable-filter/index.scss
  shell/app/common/components/configurable-filter/index.tsx
Labels: bugfix

#2325 fix(common): configurable filter clear text position bug
  shell/app/common/components/configurable-filter/index.scss
Labels: bugfix

#2326 fix(common): configurable filter cursor style bug
  shell/app/common/components/configurable-filter/index.scss
Labels: bugfix

#2322 Hotfix/configurable filter logic of popover close change
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/common/components/table/index.scss
Labels: approved, bugfix

#2327 fix(common): date range optimization
  shell/app/common/components/render-form-item/index.tsx
Labels: approved, bugfix

#2328 fix(common): configurable filter tags select dropdown bug
  shell/app/common/components/render-form-item/index.tsx
Labels: bugfix

#2329 fix(common): table select row bug
  shell/app/common/components/table/index.tsx
Labels: approved, bugfix

#2333 fix(common): date range select start time optimization
  shell/app/common/components/render-form-item/index.tsx
Labels: bugfix

#2332 fix(common): page error after jump from api-market detail
  shell/app/modules/apiManagePlatform/pages/api-market/detail/index.tsx
Labels: approved, bugfix

#2331 fix: valueOptions is empty when operator is match or notMatch can not be saved
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
Labels: msp, approved, bugfix

#2330 fix: hide email and phone columns of members table
  shell/app/common/components/members-table/index.tsx
Labels: approved, bugfix

#2337 fix: issue download error
  shell/app/config-page/components/kanban/kanban.tsx
  shell/app/config-page/index.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
  shell/app/modules/project/pages/issue/board.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
Labels: dop, approved, bugfix

#2336 fixed msp online bugs
  shell/app/config-page/components/top-n/index.tsx
  shell/app/config-page/components/top-n/top-n.mock.ts
  shell/app/config-page/components/top-n/top-n.spec.d.ts
  shell/app/config-page/mock/data-rank.mock.ts
  shell/app/modules/msp/env-overview/router.ts
  shell/app/modules/msp/env-overview/service-list/pages/overview-new.tsx
  shell/app/modules/msp/env-overview/service-list/router.ts
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/index.tsx
Labels: approved

#2334 fix: not display cursor after selection
  shell/app/common/components/edit-field/index.tsx
Labels: dop, approved, bugfix

#2335 fix: can add workflow when data is empty
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/issue-workflow-setting-modal.tsx
Labels: dop, approved, bugfix

#2339 topology is scaled to 0.6 by default
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/index.tsx
Labels: feature, msp, approved

#2311 Feature/base list common component
  shell/app/common/components/base-list/index.scss
  shell/app/common/components/base-list/index.spec.d.ts
  shell/app/common/components/base-list/index.tsx
  shell/app/common/components/base-list/list-item.tsx
  shell/app/common/components/pagination/index.tsx
  shell/app/common/index.ts
  shell/app/config-page/components/base-list/base-list.mock.ts
  shell/app/config-page/components/base-list/base-list.spec.d.ts
  shell/app/config-page/components/base-list/base-list.tsx
  shell/app/config-page/components/index.tsx
  shell/app/config-page/components/list/list.tsx
  shell/app/config-page/config-page.d.ts
  shell/app/config-page/page-render.tsx
Labels: feature, approved

#2289 feat: add user profile component
  locales/en.json
  locales/zh.json
  shell/app/common/__tests__/components/user-profile/user-profile.test.tsx
  shell/app/common/components/user-profile/index.scss
  shell/app/common/components/user-profile/index.tsx
  shell/app/common/index.ts
  shell/app/config-page/components/index.tsx
  shell/app/config-page/components/user-profile/user-profile.mock.ts
  shell/app/config-page/components/user-profile/user-profile.spec.d.ts
  shell/app/config-page/components/user-profile/user-profile.tsx
Labels: feature, approved

#2341 feat: add scale card component
  shell/app/config-page/components/index.tsx
  shell/app/config-page/components/scale-card/scale-card.mock.ts
  shell/app/config-page/components/scale-card/scale-card.scss
  shell/app/config-page/components/scale-card/scale-card.spec.d.ts
  shell/app/config-page/components/scale-card/scale-card.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, approved

#2344 Feature/scene empty holder
  shell/app/common/components/empty-holder/index.scss
  shell/app/common/components/empty-holder/index.tsx
  shell/app/config-page/components/scale-card/scale-card.scss
  shell/app/config-page/components/scale-card/scale-card.tsx
  shell/app/static/empty-holder/create-app.svg
  shell/app/static/empty-holder/create-project.svg
  shell/app/static/empty-holder/star-app.svg
  shell/app/static/empty-holder/star-project.svg
  shell/app/static/empty-holder/upload.svg
Labels: feature, approved

#2343 fix: hide email and label columns of member table
  shell/app/common/components/members-table/index.tsx
Labels: approved, bugfix

#2342 feat: modify route about service analysis
  shell/app/common/utils/go-to.tsx
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/env-overview/service-list/router.ts
Labels: msp, approved, bugfix

#2348 topology optimization
  shell/app/common/use-hooks.tsx
  shell/app/modules/msp/env-overview/service-list/pages/overview-new.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/floating-edge/index.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/addon-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/api-gateway-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/common-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/index.scss
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/services-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/progress/hexagon.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/progress/index.scss
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-detail.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/index.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/utils/index.ts
  shell/app/modules/msp/env-overview/topology/types/topology.d.ts
  shell/app/styles/util.scss
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, msp, approved

#2349 fix: trace detail go back to transaction in service monitor
  shell/app/common/utils/go-to.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search-detail.tsx
Labels: approved, bugfix
