Repository erda-project/erda-ui, pull requests merged in 2022-01, with the labels that each got.

#2485 fix: add min height to global logo wrap
  shell/app/layout/pages/page-container/components/navigation/index.tsx
Labels: bugfix

#2486 fix(dop): project release breadcrumb bug
  shell/app/modules/project/router.tsx
Labels: approved, bugfix

#2488 Hotfix/gantt filter style
  shell/app/config-page/components/gantt/components/calendar/calendar.scss
  shell/app/modules/project/pages/issue/gantt/index.scss
  shell/app/modules/project/pages/issue/gantt/index.tsx
Labels: dop, bugfix

#2494 feat: only show top 10 at most in personal home
  shell/app/common/components/user-profile/index.tsx
  shell/app/org-home/pages/active-rank/index.tsx
Labels: feature

#2473 fix(dop): add release version duplicate verification
  shell/app/common/components/pagination/index.tsx
  shell/app/modules/project/pages/release/components/application-detail.tsx
  shell/app/modules/project/pages/release/components/form.tsx
  shell/app/modules/project/pages/release/components/project-detail.tsx
  shell/app/modules/project/services/release.ts
Labels: bugfix

#2491 Hotfix/unify filter input border style when focus
  shell/app/common/components/contractive-filter/index.scss
  shell/app/common/components/contractive-filter/index.tsx
  shell/app/common/components/table/index.scss
  shell/app/styles/_color.scss
  shell/app/styles/antd-extension.scss
Labels: bugfix

#2498 feat: update filter to tab in iteration
  shell/app/modules/project/pages/homepage/index.tsx
  shell/app/modules/project/pages/iteration/table.tsx
Labels: feature, dop

#2501 fix(msp): modify style of tooltip in trace-detail
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/span-title-info.tsx
Labels: bugfix

#2492 fix(cmp): clusters list reload after add or delete
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
  shell/app/modules/cmp/pages/cluster-manage/index.tsx
Labels: bugfix

#2508 Fix: logo wrap height style
  shell/app/common/components/table/index.scss
  shell/app/layout/pages/page-container/components/navigation/index.tsx
Labels: bugfix

#2510 fix: with the same route, close message site when click navigation item
  shell/app/layout/pages/page-container/components/navigation/index.tsx
Labels: approved, bugfix

#2512 fix(common): websocket bug in http protocol
  shell/app/modules/apiManagePlatform/api-ws.ts
Labels: bugfix

#2511 fix: open target issue in gantt page
  shell/app/common/components/filter/index.tsx
  shell/app/configForm/form/form.tsx
  shell/app/configForm/form/utils.ts
  shell/app/modules/dcos/pages/cluster-dashboard/resources-usage-trend.tsx
  shell/app/modules/org/pages/certificate/index.tsx
  shell/app/modules/org/pages/safety/index.tsx
  shell/app/modules/project/pages/issue/gantt/index.tsx
  shell/app/styles/antd-extension.scss
Labels: bugfix

#2495 feat: line chart supports data drill-down
  shell/app/config-page/components/line-graph/index.tsx
  shell/app/modules/msp/components/time-select.tsx
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
Labels: feature, msp, approved

#2515 feat: add eslint error for deprecated function
  .eslintrc.js
  package.json
  pnpm-lock.yaml
  shell/app/common/components/custom-filter/index.tsx
Labels: bugfix

#2516 style(common): modify modal to center position
  shell/app/App-vite.tsx
  shell/app/App.tsx
Labels: feature

#2517 feat: adjust card style
  shell/app/modules/msp/env-overview/service-list/pages/overview.tsx
  shell/app/modules/project/pages/issue/task-summary.tsx
Labels: feature, dop, msp

#2520 Feature/move env position
  erda.yml
Labels: chore

#2521 fix: hidden markdown when click cancel button
  shell/app/modules/application/pages/repo/components/compare-detail.tsx
  shell/app/modules/application/pages/repo/components/file-diff.tsx
Labels: dop, bugfix

#2524 fix: compatible with empty list
  shell/app/config-page/components/top-n/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
Labels: feature, msp, approved

#2522 feat(dop): applications list optimization
  shell/app/modules/project/pages/apps/app-list.tsx
  shell/app/modules/project/router.tsx
Labels: feature, approved

#2525 style: add edit button in markdown
  shell/app/modules/project/pages/homepage/index.scss
  shell/app/modules/project/pages/homepage/readme-markdown.tsx
Labels: dop, approved, bugfix

#2528 feat: add card border style animation
  shell/app/config-page/components/card/card.scss
  shell/app/styles/_color.scss
Labels: feature

#2519 feat(dop): project release add by upload file
  shell/app/common/utils/go-to.tsx
  shell/app/images/upload_empty.svg
  shell/app/interface/common.d.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/release/components/application-detail.tsx
  shell/app/modules/project/pages/release/components/form.tsx
  shell/app/modules/project/pages/release/release-protocol.tsx
  shell/app/modules/project/router.tsx
  shell/app/modules/project/services/release.ts
  shell/app/styles/antd-extension.scss
Labels: feature

#2534 feat: update personal contribute item background color
  shell/app/config-page/components/card/card.scss
  shell/app/modules/application/common/app-selector.tsx
  shell/app/modules/project/common/components/project-selector.tsx
  shell/app/org-home/pages/personal-contribute/index.tsx
Labels: bugfix

#2535 fix: fix bug when switch tabs without using the latest time
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
Labels: msp, approved, bugfix

#2538 fix(dop): resources table sort bug
  shell/app/common/components/table/index.tsx
Labels: bugfix

#2542 fix: card border animation speed
  shell/app/config-page/components/card/card.scss
Labels: approved, bugfix

#2544 fix(common): list tooltip display bug
  shell/app/config-page/utils.tsx
Labels: approved, bugfix

#2547 fix: remove input border under contractive filter
  shell/app/common/components/contractive-filter/index.scss
Labels: bugfix

#2550 fix: app list style under project level
  shell/app/common/components/base-list/index.scss
  shell/app/config-page/components/card/card.scss
  shell/app/modules/project/pages/apps/app-list.scss
  shell/app/modules/project/pages/apps/app-list.tsx
Labels: approved, bugfix

#2552 fix: certificate fields can not contain space
  locales/en.json
  locales/zh.json
  shell/app/config-page/components/card/card.scss
  shell/app/config-page/components/table/v2/table.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/org/pages/certificate/index.tsx
Labels: bugfix

#2553 fix(common): table select row bug
  shell/app/config-page/components/table/render-types.tsx
  shell/app/config-page/components/table/table.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
Labels: approved, bugfix

#2557 feat: adjust margin
  shell/app/modules/msp/env-overview/service-list/pages/overview.tsx
Labels: feature, msp, approved

#2559 fix(common): fdp display on menu according to environment
  shell/app/menus/appCenter.tsx
  shell/app/org-home/pages/personal-home.tsx
Labels: approved, bugfix

#2558 fix(dop): issue backlog list page error after row click
  shell/app/modules/project/common/components/issue/issue-relation.tsx
Labels: approved, bugfix

#2564 fix: mistake skip build when cache is empty in integration env pipeline issue
  cli/lib/check-build-status.ts
  cli/package.json
Labels: cli, approved, bugfix

#2567 feat: add land page
  locales/en.json
  locales/zh.json
  shell/app/App-vite.tsx
  shell/app/App.tsx
  shell/app/common/utils/go-to.tsx
  shell/app/images/land-spring.jpg
  shell/app/layout/common/error-page.tsx
  shell/app/layout/pages/page-container/layout.scss
  shell/app/layout/pages/page-container/layout.tsx
  shell/app/layout/pages/page-container/page-container.tsx
  shell/app/layout/router.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/org-home/pages/land/index.scss
  shell/app/org-home/pages/land/index.tsx
  shell/app/org-home/router.ts
  shell/app/org-home/stores/org.tsx
  shell/app/user/stores/index.ts
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, approved

#2568 fix(common): project release detail herf bug in safety log
  shell/app/modules/org/common/audit-templates.json
Labels: approved, bugfix

#2566 feat: api version list use new table
  shell/app/modules/apiManagePlatform/pages/api-market/detail/components/api-body/index.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/detail/index.tsx
Labels: feature, dop, approved

#2569 feat: slow call detail
  shell/app/common/components/contractive-filter/index.tsx
  shell/app/common/components/duration/duration.scss
  shell/app/common/components/duration/index.tsx
  shell/app/common/index.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-overview/service-list/pages/transaction-detail.tsx
  shell/app/modules/msp/env-overview/service-list/pages/transaction.scss
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search-detail.scss
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
Labels: feature, msp

#2570 fix(dop): project release upload file type change
  shell/app/modules/project/pages/release/components/form.tsx
Labels: bugfix

#2571 fix(dop): project release detail formal btn display bug
  shell/app/modules/project/pages/release/components/project-detail.tsx
Labels: approved, bugfix

#2572 fix(dop): project release create release by upload file remove changelog
  shell/app/modules/project/pages/release/components/form.tsx
  shell/app/modules/project/router.tsx
Labels: approved, bugfix

#2574 fix: land page org can not click
  shell/app/org-home/pages/land/index.tsx
Labels: bugfix

#2576 fix: update land page text
  shell/app/layout/common/error-page.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/org-home/pages/land/index.tsx
Labels: bugfix

#2573 fix(dop): project release applications list pageSize bug
  shell/app/modules/project/stores/release.ts
Labels: approved, bugfix

#2578 feat: add apply organization button in land page
  scheduler/src/filters/not-found.filter.ts
  shell/app/common/components/configurable-filter/config-selector.tsx
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/common/components/erda-icon/index.tsx
  shell/app/common/components/list-select/index.tsx
  shell/app/common/components/load-more-selector/index.tsx
  shell/app/common/components/render-form-item/index.tsx
  shell/app/layout/pages/page-container/components/announcement/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/release/release-protocol.tsx
  shell/app/org-home/pages/land/index.tsx
  shell/theme-color.js
Labels: feature

#2579 fix(common): fix useState/useData doesnt render all components issue
  core/src/service/index.ts
Labels: core, approved, bugfix

#2580 fix(dop): project release upload file text change
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/release/components/form.tsx
Labels: approved, bugfix

#2582 feat: remove freshman page
  shell/app/common/utils/go-to.tsx
  shell/app/layout/router.tsx
  shell/app/org-home/stores/org.tsx
Labels: feature, approved

#2583 fix: react-use is not a core dependencies
  core/src/service/index.ts
Labels: core, bugfix

#2584 fix: truncate if text too long
  shell/app/org-home/pages/land/index.tsx
Labels: bugfix

#2585 fix: not send env to client
  scheduler/src/filters/not-found.filter.ts
Labels: bugfix

#2581 feat: tidy theme color
  pnpm-lock.yaml
  shell/app/charts/components/echarts.jsx
  shell/app/common/__tests__/components/input-select/input-select.test.tsx
  shell/app/common/components/base-list/list-item.tsx
  shell/app/common/components/contractive-filter/index.tsx
  shell/app/common/components/edit-field/index.tsx
  shell/app/common/components/erda-icon/index.tsx
  shell/app/common/components/image-upload/index.tsx
  shell/app/common/components/input-select/index.tsx
  shell/app/common/components/list/list-item.tsx
  shell/app/common/components/radio-tabs/index.tsx
  shell/app/common/components/sort-drag-group-list/index.tsx
  shell/app/common/components/table-actions/index.tsx
  shell/app/common/components/tree-category/edit-category.tsx
  shell/app/config-page/components/gantt/components/calendar/calendar.tsx
  shell/app/config-page/components/list/list.tsx
  shell/app/config-page/components/radio/radio.tsx
  shell/app/config-page/components/table/render-types.tsx
  shell/app/config-page/components/table/v2/table.tsx
  shell/app/config-page/utils.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/design/api-doc-tree.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/detail/components/api-preview-2.0.tsx
  shell/app/modules/application/common/components/goto-commit.tsx
  shell/app/modules/application/pages/build-detail/index.tsx
  shell/app/modules/application/pages/build-detail/pipeline-log.tsx
  shell/app/modules/application/pages/deploy/deploy.tsx
  shell/app/modules/application/pages/deploy/runtime-box.tsx
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/pages/pipeline/run-detail/pipeline-log.tsx
  shell/app/modules/application/pages/repo/components/repo-file-container.tsx
  shell/app/modules/application/pages/repo/components/repo-nav.tsx
  shell/app/modules/application/pages/repo/repo-branch.tsx
  shell/app/modules/application/pages/repo/repo-commit.tsx
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/application/pages/test/test-list.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-selector.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/env-overview/service-list/pages/service-name-select.tsx
  shell/app/modules/msp/env-setting/configuration/type-select.tsx
  shell/app/modules/msp/pages/micro-service/overview.tsx
  shell/app/modules/org/common/cluster-quota.tsx
  shell/app/modules/project/pages/issue/board.tsx
  shell/app/modules/project/pages/plan-detail/status-toggle.tsx
  shell/app/modules/project/pages/release/components/application-detail.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/case-api.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
  shell/app/modules/project/pages/test-manage/case/header/import-export-record.tsx
  shell/app/modules/project/pages/test-manage/case/manual-test.tsx
  shell/app/modules/publisher/pages/artifacts/artifacts-detail.tsx
  shell/app/theme-color.mjs
  shell/app/yml-chart/pipeline-editor.tsx
  shell/config/theme.js
  shell/package.json
  shell/postcss.config.mjs
  shell/tailwind.config.mjs
  shell/vite.config.js
  shell/webpack.config.js
Labels: refactor

#2586 feat: msp resource monitor
  shell/app/config-page/components/bubble-graph/index.tsx
  shell/app/config-page/components/grid/grid.tsx
  shell/app/config-page/components/line-graph/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-overview/service-list/pages/process.tsx
  shell/app/modules/msp/env-overview/service-list/pages/service-name-select.tsx
  shell/app/modules/msp/env-overview/service-list/router.ts
  shell/app/modules/msp/services/topology-service-analyze.ts
  shell/app/modules/msp/stores/topology-service-analyze.ts
  shell/app/modules/msp/types/topology-service-analyze.d.ts
Labels: feature, msp, approved

#2587 fix: fix self-test problems
  shell/app/config-page/components/bubble-graph/index.tsx
  shell/app/config-page/components/grid/grid.spec.d.ts
  shell/app/config-page/components/grid/grid.tsx
  shell/app/config-page/components/line-graph/index.tsx
  shell/app/modules/msp/env-overview/service-list/pages/process.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
Labels: feature, msp, approved

#2588 feat: add creator column
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
  shell/app/modules/cmp/common/custom-alarm/index.tsx
  shell/app/modules/cmp/common/custom-dashboard/index.tsx
  shell/app/modules/msp/env-setting/configuration/index.tsx
Labels: feature, msp

#2589 feat: hidden node when value is 0
  shell/app/config-page/components/bubble-graph/index.tsx
Labels: feature, msp

#2591 feat: remove public org setting and code
  locales/en.json
  locales/zh.json
  shell/app/layout/pages/page-container/components/navigation/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/org/pages/setting/org-info.tsx
  shell/app/org-home/pages/land/index.tsx
  shell/app/org-home/pages/org-selector.tsx
  shell/app/org-home/stores/org.tsx
  shell/app/org-home/types/org.d.ts
  shell/auto_test/tests/org/organization-information.spec.ts
Labels: feature

#2592 fix: update release audit template
  shell/app/modules/org/common/audit-templates.json
Labels: approved, bugfix

#2594 fix: fix base list reload
  shell/app/config-page/components/base-list/base-list.tsx
Labels: bugfix

#2595 feat: add empty holder
  shell/app/modules/msp/env-overview/service-list/pages/process.tsx
  shell/app/modules/msp/types/topology-service-analyze.d.ts
Labels: feature, msp, approved

#2596 feat: land page logout
  shell/app/layout/pages/page-container/components/navigation/index.scss
  shell/app/layout/pages/page-container/components/navigation/index.tsx
  shell/app/layout/pages/page-container/components/navigation/user-menu.scss
  shell/app/layout/pages/page-container/components/navigation/user-menu.tsx
  shell/app/layout/pages/page-container/components/navigation/userMenu.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/org-home/pages/land/index.tsx
  shell/app/theme-color.mjs
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, approved

#2597 feat: add front monitor
  shell/app/config-page/components/grid/grid.spec.d.ts
  shell/app/config-page/components/grid/grid.tsx
  shell/app/config-page/components/line-graph/index.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/overview/overview.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, msp, approved

#2598 fix: user menu style
  shell/app/layout/pages/page-container/components/navigation/user-menu.scss
  shell/app/layout/pages/page-container/components/navigation/user-menu.tsx
  shell/app/org-home/pages/land/index.tsx
Labels: bugfix

#2599 feat: project pipeline
  shell/app/common/stores/file-tree.tsx
  shell/app/common/utils/go-to.tsx
  shell/app/config-page/components/table/render-types.tsx
  shell/app/config-page/components/table/table.tsx
  shell/app/config-page/components/table/v2/table.tsx
  shell/app/config-page/components/table/v2/utils.tsx
  shell/app/config-page/utils.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/project.tsx
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/stores/build.ts
  shell/app/modules/project/pages/pipelines/components/basic.tsx
  shell/app/modules/project/pages/pipelines/components/form.tsx
  shell/app/modules/project/pages/pipelines/components/logs.tsx
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
  shell/app/modules/project/pages/pipelines/index.scss
  shell/app/modules/project/pages/pipelines/index.tsx
  shell/app/modules/project/router.tsx
  shell/app/modules/project/services/pipeline.tsx
  shell/app/modules/project/tabs.tsx
Labels: feature, approved

#2602 fix: fix project deploy table page no error
  shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx
  shell/app/modules/project/pages/deploy/add-deploy/index.tsx
  shell/app/modules/project/pages/deploy/deploy-config/index.tsx
  shell/app/modules/project/pages/deploy/deploy-config/list-edit.tsx
  shell/app/modules/project/pages/deploy/deploy-config/text-edit.tsx
  shell/app/modules/project/pages/deploy/deploy-detail/index.tsx
Labels: dop, approved, bugfix

#2601 fix(dop): menu text change
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/project.tsx
Labels: approved, bugfix

#2604 fix(dop): menu text change
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/project.tsx
Labels: approved, bugfix

#2605 feat: adjust bubble size
  shell/app/config-page/components/bubble-graph/index.tsx
Labels: feature, msp, approved

#2603 fix: user logout is unavailable
  shell/app/config-page/components/card/card.scss
  shell/app/config-page/components/card/card.spec.d.ts
  shell/app/config-page/components/card/card.tsx
  shell/app/layout/pages/page-container/components/navigation/user-menu.tsx
  shell/app/modules/project/pages/issue/board.tsx
  shell/app/org-home/pages/personal-home.tsx
Labels: bugfix

#2600 feat: import and export project template
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/org/pages/projects/add-project.tsx
  shell/app/modules/org/pages/projects/create-project.tsx
  shell/app/modules/org/pages/projects/import-project-template.scss
  shell/app/modules/org/pages/projects/import-project-template.tsx
  shell/app/modules/org/pages/projects/import-project.tsx
  shell/app/modules/org/pages/projects/operation-project-record.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/org/router.ts
  shell/app/modules/org/services/project-list.ts
  shell/app/modules/org/types/project-list.d.ts
  shell/app/modules/project/pages/deploy/deploy-config/list-edit.tsx
Labels: feature

#2606 fix(dop): pipeline execute detail display bug
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/stores/build.ts
Labels: approved, bugfix

#2608 fix(common): pagination btn hover style bug
  shell/app/common/components/pagination/index.scss
  shell/app/common/components/pagination/index.tsx
  shell/app/common/components/table/index.scss
Labels: approved, bugfix

#2607 feat: optimize the refresh button style
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/env-overview/service-list/pages/overview.tsx
Labels: feature, msp, approved

#2613 fix: fix project deploy styles
  locales/zh.json
  shell/app/common/components/base-list/index.tsx
  shell/app/common/components/contractive-filter/index.tsx
  shell/app/common/components/simple-tabs/index.scss
  shell/app/common/components/simple-tabs/index.tsx
  shell/app/config-page/components/base-list/base-list.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/common/app-selector.tsx
  shell/app/modules/application/pages/settings/components/variable-config-form.tsx
  shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx
  shell/app/modules/project/pages/deploy/add-deploy/index.tsx
  shell/app/modules/project/pages/deploy/config.ts
  shell/app/modules/project/pages/deploy/deploy-config/index.tsx
  shell/app/modules/project/pages/deploy/deploy-config/list-edit.tsx
  shell/app/modules/project/pages/deploy/deploy-config/text-edit.tsx
  shell/app/modules/project/pages/deploy/deploy-detail/index.tsx
  shell/app/modules/project/pages/deploy/index.tsx
  shell/app/modules/project/services/deploy.ts
  shell/app/modules/project/types/deploy.d.ts
  shell/app/org-home/pages/personal-home.tsx
Labels: dop, approved, bugfix

#2612 feat: add trace duration tips
  shell/app/common/components/contractive-filter/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
Labels: feature, msp, approved

#2609 fix(dop): issue attention btn dropdown style bug
  shell/app/modules/project/common/components/issue/subscribers-selector.tsx
Labels: approved, bugfix

#2610 feat(dop): project pipeline management detail
  shell/app/common/components/pagination/index.scss
  shell/app/config-page/components/table/render-types.tsx
  shell/app/config-page/components/table/v2/utils.tsx
  shell/app/modules/application/pages/pipeline/config-detail/index.tsx
  shell/app/modules/project/pages/apps/app-list.tsx
  shell/app/modules/project/pages/pipelines/components/form.tsx
  shell/app/modules/project/pages/pipelines/components/logs.tsx
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
  shell/app/modules/project/pages/pipelines/index.scss
  shell/app/modules/project/pages/pipelines/index.tsx
  shell/app/modules/project/router.tsx
  shell/app/modules/project/services/pipeline.tsx
Labels: feature, approved

#2614 feat: update project home and breadcrumb style
  shell/app/layout/pages/page-container/components/header.scss
  shell/app/layout/pages/page-container/components/header.tsx
  shell/app/layout/pages/page-container/components/shell/index.tsx
  shell/app/layout/pages/page-container/components/sidebar/index.scss
  shell/app/locales/zh.json
  shell/app/modules/project/pages/deploy/index.tsx
  shell/app/modules/project/pages/homepage/index.scss
  shell/app/modules/project/pages/homepage/index.tsx
  shell/app/modules/project/pages/homepage/readme-markdown.tsx
Labels: feature

#2615 feat: fix trace params
  shell/app/config-page/components/bubble-graph/index.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
Labels: feature, msp

#2617 fix: import and export project template
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/org/pages/projects/create-project.tsx
  shell/app/modules/org/pages/projects/import-project-template.tsx
  shell/app/modules/org/pages/projects/operation-project-record.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/org/types/project-list.d.ts
Labels: approved, bugfix

#2619 feat(dop): project pipeline style optimization
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/pipelines/components/form.tsx
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
  shell/app/modules/project/pages/pipelines/index.tsx
Labels: feature

#2620 fix(dop): project pipeline interface change
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/modules/project/pages/pipelines/components/form.tsx
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
Labels: bugfix

#2621 feat: add project deploy menu tabs
  shell/app/common/components/badge/index.tsx
  shell/app/common/components/base-list/index.scss
  shell/app/common/components/base-list/list-item.tsx
  shell/app/common/components/menu/index.tsx
  shell/app/common/components/render-form-item/index.tsx
  shell/app/common/utils/go-to.tsx
  shell/app/configForm/nusi-form/form.tsx
  shell/app/interface/global.d.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx
  shell/app/modules/project/pages/deploy/add-deploy/release-list.tsx
  shell/app/modules/project/pages/deploy/config.ts
  shell/app/modules/project/pages/deploy/deploy-config/index.tsx
  shell/app/modules/project/pages/deploy/deploy-config/list-edit.tsx
  shell/app/modules/project/pages/deploy/deploy-config/text-edit.tsx
  shell/app/modules/project/pages/deploy/deploy-detail/index.tsx
  shell/app/modules/project/pages/deploy/index.tsx
  shell/app/modules/project/router.tsx
  shell/app/modules/project/tabs.tsx
  shell/app/modules/runtime/pages/overview/components/index.tsx
  shell/app/modules/runtime/pages/overview/components/info.tsx
  shell/app/modules/runtime/stores/runtime.ts
  shell/app/modules/runtime/types/runtime.d.ts
  shell/app/styles/antd-extension.scss
Labels: feature, dop, approved

#2622 style: modify the style of drawer
  shell/app/modules/org/pages/projects/operation-project-record.tsx
  shell/app/styles/antd-extension.scss
Labels: feature, approved

#2624 fix: date range picker translation in filter
  core/src/index.tsx
  core/src/stores/route.ts
  shell/app/common/components/contractive-filter/index.tsx
  shell/app/common/components/table/index.scss
  shell/app/modules/msp/env-overview/service-list/pages/service-list.scss
  shell/app/modules/org/common/card/index.scss
  shell/app/modules/project/pages/apps/app-list.scss
  shell/app/modules/project/pages/apps/app-list.tsx
  shell/app/modules/project/pages/issue/gantt/index.tsx
  shell/app/styles/_color.scss
Labels: bugfix

#2623 feat: hidden summary、location analysis、geography
  shell/app/config-page/components/bubble-graph/index.tsx
  shell/app/config-page/components/line-graph/index.tsx
  shell/app/modules/msp/env-overview/service-list/pages/transaction.scss
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-detail.tsx
  shell/app/modules/msp/monitor/browser-insight/router.ts
  shell/app/styles/antd-extension.scss
Labels: feature, msp

#2625 fix: fix project deploy config style
  shell/app/common/components/base-list/list-item.tsx
  shell/app/common/components/simple-tabs/index.scss
  shell/app/common/components/table/index.tsx
  shell/app/common/components/table/interface.ts
  shell/app/common/components/table/table-config.tsx
  shell/app/config-page/components/card/card.tsx
  shell/app/config-page/utils.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/deploy/add-deploy/index.tsx
  shell/app/modules/project/pages/deploy/deploy-config/index.tsx
  shell/app/modules/project/pages/deploy/deploy-config/list-edit.tsx
  shell/app/modules/project/pages/deploy/deploy-config/text-edit.tsx
  shell/app/modules/project/pages/deploy/deploy-detail/index.tsx
  shell/app/modules/project/pages/deploy/index.tsx
  shell/app/modules/project/tabs.tsx
  shell/app/styles/util.scss
  shell/app/views/index.ejs
  shell/index.html
Labels: dop, bugfix

#2626 fix: revert old project pipeline
  shell/app/modules/project/pages/pipelines/old-pipeline.tsx
  shell/app/modules/project/router.tsx
Labels: bugfix

#2630 fix: fix project create deploy style
  locales/en.json
  locales/zh.json
  shell/app/common/components/simple-tabs/index.scss
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/deploy/add-deploy/add-release.scss
  shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx
  shell/app/modules/project/pages/deploy/add-deploy/index.tsx
  shell/app/modules/project/pages/deploy/deploy-config/index.tsx
  shell/app/modules/project/pages/deploy/deploy-config/text-edit.tsx
  shell/app/modules/project/pages/deploy/deploy-detail/index.tsx
  shell/app/modules/project/pages/deploy/index.tsx
  shell/app/modules/project/types/deploy.d.ts
  shell/app/views/index.ejs
  shell/index.html
Labels: dop, approved, bugfix

#2628 feat: update markdown render style
  shell/app/common/components/markdown-editor/editor.scss
  shell/app/layout/pages/page-container/components/header.scss
  shell/app/modules/project/pages/apps/app-list.tsx
Labels: dop, approved, bugfix

#2627 feat: update audit template(msp and cmp modules)
  shell/app/modules/org/common/audit-templates.json
Labels: feature, approved

#2632 fix: fix deploy tab change error
  shell/app/modules/project/pages/deploy/deploy-config/index.tsx
  shell/app/modules/project/pages/deploy/index.tsx
Labels: dop, approved, bugfix

#2633 feat: update project pipeline route
  shell/app/modules/project/router.tsx
Labels: feature, approved

#2634 fix(dop): applications list scroll bar bug
  shell/app/modules/project/pages/apps/app-list.tsx
Labels: approved, bugfix

#2636 fix: fix deploy config add in line
  shell/app/modules/project/pages/deploy/deploy-config/list-edit.tsx
Labels: dop, approved, bugfix

#2629 fix(dop): project release edit style bug。。
  shell/app/modules/project/pages/release/components/application-detail.tsx
  shell/app/modules/project/pages/release/components/form.tsx
Labels: approved, bugfix

#2637 fix: revert table header bg color
  shell/app/common/components/base-list/index.tsx
  shell/app/common/components/table/index.scss
  shell/app/modules/msp/env-overview/service-list/pages/service-list.scss
  shell/app/modules/org/common/card/index.scss
  shell/app/org-home/pages/personal-home.scss
  shell/app/styles/_color.scss
Labels: approved, bugfix

#2639 fix: add deploy detail table search
  shell/app/modules/project/pages/deploy/deploy-detail/index.tsx
Labels: dop, approved, bugfix

#2640 fix: remove my application list menu
  shell/app/common/components/radio-tabs/index.scss
  shell/app/menus/dop.tsx
  shell/app/menus/project.tsx
  shell/app/modules/project/pages/deploy/deploy-config/index.tsx
Labels: approved, bugfix

#2641 fix: fix placeholder
  shell/app/modules/project/pages/deploy/add-deploy/index.tsx
  shell/app/modules/project/pages/deploy/deploy-config/index.tsx
  shell/app/modules/project/pages/deploy/deploy-config/list-edit.tsx
  shell/app/modules/project/pages/deploy/deploy-detail/index.tsx
Labels: dop, approved, bugfix

#2638 fix(dop): project pipeline style optimization
  shell/app/common/utils/go-to.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/project.tsx
  shell/app/modules/project/pages/pipelines/index.tsx
  shell/app/modules/project/router.tsx
  shell/app/modules/project/tabs.tsx
Labels: approved, bugfix

#2642 fix: fix app selector height
  shell/app/modules/project/pages/deploy/add-deploy/add-release.scss
Labels: approved, bugfix

#2643 fix(dop): dop page name optimization
  shell/app/modules/project/router.tsx
Labels: approved, bugfix

#2645 fix: project runtime auth
  shell/app/modules/project/pages/deploy/deploy-config/index.tsx
  shell/app/modules/project/pages/deploy/deploy-config/list-edit.tsx
  shell/app/modules/project/pages/deploy/deploy-detail/index.tsx
  shell/app/modules/runtime/stores/runtime.ts
Labels: dop, bugfix

#2646 fix: fix admin entry auth error
  shell/app/layout/pages/page-container/components/navigation/user-menu.tsx
Labels: approved, bugfix

#2644 feat: add bg and title
  shell/app/config-page/components/title/title.spec.d.ts
  shell/app/config-page/components/title/title.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/overview/overview.tsx
Labels: feature, msp, approved

#2647 feat: update data structure about token
  shell/app/modules/msp/env-setting/configuration/index.tsx
  shell/app/modules/org/common/audit-templates.json
Labels: approved, bugfix

#2653 fix(common): invite to org page throw error
  shell/app/org-home/pages/active-rank/index.tsx
  shell/app/org-home/pages/personal-contribute/index.tsx
Labels: bugfix

#2652 feat(common): config table text td add tooltip
  shell/app/config-page/components/table/v2/utils.tsx
Labels: feature

#2651 fix(dop): project pipeline detail link bug
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
Labels: bugfix

#2650 fix(dop): project pipeline branch list interface change
  shell/app/modules/project/pages/pipelines/components/form.tsx
  shell/app/modules/project/services/pipeline.tsx
Labels: bugfix

#2657 fix(dop): project pipeline logs detail close button
  shell/app/modules/project/pages/pipelines/components/logs.tsx
Labels: approved, bugfix

#2649 fix(dop): project pipeline apps list status display bug
  shell/app/modules/project/pages/pipelines/components/form.tsx
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
  shell/app/modules/project/pages/pipelines/index.tsx
Labels: approved, bugfix

#2654 fix(common): config table header background color optimization
  shell/app/common/components/table/index.scss
  shell/app/common/components/table/index.tsx
  shell/app/common/components/table/table-config.tsx
  shell/app/common/components/table/table-footer.tsx
  shell/app/modules/project/router.tsx
Labels: bugfix

#2655 fix(common): configurable filter display bug when receiving null
  shell/app/common/components/render-form-item/index.tsx
Labels: approved, bugfix

#2658 feat: partial render config page
  shell/app/config-page/index.tsx
Labels: feature

#2656 feat: notify group add params
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/msp/env-overview/service-list/pages/process.tsx
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
Labels: feature, msp

#2660 fix: fix cmp container drawer style
  shell/app/modules/cmp/pages/cluster-container/cluster-nodes-detail.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-nodes.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-pod-detail.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-pods.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-workload-detail.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-workload.tsx
Labels: cmp, bugfix

#2664 fix(common): org home display optimization when org name too long
  shell/app/common/components/dropdown-select-new/index.tsx
Labels: approved, bugfix

#2662 fix(dop): project release detail yml file display bug
  shell/app/modules/project/pages/release/components/application-detail.tsx
Labels: approved, bugfix

#2663 fix(dop): project pipeline name rules change
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/pipelines/components/form.tsx
Labels: approved, bugfix

#2648 fix(dop): project pipeline table filter bug
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
  shell/app/modules/project/pages/pipelines/index.tsx
Labels: approved, bugfix

#2669 feat: remove filter by front
  shell/app/modules/msp/env-overview/service-list/pages/overview.tsx
Labels: feature, msp

#2659 fix(common): in config page, radio tabs value change by state
  shell/app/common/components/radio-tabs/index.tsx
Labels: approved, bugfix

#2661 fix: select display in table
  shell/app/modules/cmp/common/custom-alarm/index.tsx
  shell/app/modules/org/pages/projects/settings/info/index.scss
  shell/app/modules/org/pages/projects/settings/info/index.tsx
  shell/app/modules/project/pages/homepage/index.tsx
Labels: approved, bugfix

#2673 fix: align logo and user avatar in land page
  shell/app/modules/project/pages/issue/gantt/index.tsx
  shell/app/org-home/pages/land/index.tsx
Labels: approved, bugfix

#2678 fix: fix personal star app cancel error
  shell/app/config-page/components/card/card.tsx
Labels: dop, bugfix

#2680 fix(dop): project pipeline create pipeline optimization
  shell/app/modules/project/pages/pipelines/components/form.scss
  shell/app/modules/project/pages/pipelines/components/form.tsx
  shell/app/modules/project/services/pipeline.tsx
Labels: approved, bugfix

#2670 feat: remove color in constants
  shell/app/common/constants.ts
  shell/app/common/utils/index.ts
  shell/app/config-page/components/bubble-graph/index.tsx
  shell/app/config-page/components/line-graph/index.tsx
  shell/app/config-page/components/top-n/index.tsx
  shell/app/config-page/components/top-n/top-n.mock.ts
  shell/app/config-page/mock/mock.tsx
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/env-overview/service-list/pages/overview.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/overview/overview.tsx
  shell/app/modules/project/pages/settings/components/project-label.tsx
  shell/app/theme-color.mjs
  shell/tailwind.config.mjs
Labels: feature, approved

#2691 feat(common): add enterprise-ui service
  erda.yml
Labels: feature, approved

#2692 fix(common): config page inParams update bug
  shell/app/config-page/index.tsx
Labels: approved, bugfix

#2690 feat: add project deploy update
  locales/en.json
  locales/zh.json
  shell/app/common/components/base-list/list-item.tsx
  shell/app/common/components/pagination/index.tsx
  shell/app/common/components/panel/index.tsx
  shell/app/common/components/radio-tabs/index.tsx
  shell/app/common/components/table/index.tsx
  shell/app/config-page/components/base-list/base-list.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/deploy/add-deploy/index.tsx
  shell/app/modules/project/pages/deploy/deploy-detail/index.tsx
  shell/app/modules/project/pages/deploy/index.scss
  shell/app/modules/project/pages/deploy/index.tsx
  shell/app/modules/project/services/deploy.ts
  shell/app/modules/project/tabs.tsx
  shell/app/modules/project/types/deploy.d.ts
  shell/app/styles/antd-extension.scss
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, dop, refactor, approved

#2689 fix(dop): project release create disabled button style bug
  shell/app/modules/project/pages/release/release-protocol.tsx
Labels: approved, bugfix

#2681 fix(dop): project release put application in front of project
  shell/app/common/utils/go-to.tsx
  shell/app/modules/project/tabs.tsx
Labels: approved, bugfix

#2687 fix: remove file style in importing project
  shell/app/modules/org/pages/projects/import-project-template.scss
  shell/app/modules/org/pages/projects/import-project-template.tsx
  shell/app/modules/org/pages/projects/settings/info/index.scss
  shell/app/modules/org/pages/projects/settings/info/index.tsx
Labels: approved, bugfix

#2693 fix: fix whether isK8S logic
  shell/app/modules/msp/stores/micro-service.tsx
  shell/app/modules/msp/types/index.d.ts
Labels: msp, approved, bugfix

#2701 fix: fix personal page error
  shell/app/config-page/components/base-list/base-list.tsx
Labels: dop, approved, bugfix

#2702 fix: revert config page partial update
  shell/app/config-page/index.tsx
Labels: approved, bugfix

#2703 fix: revert config page partial update
  shell/app/config-page/index.tsx
Labels: bugfix

#2704 feat(common): fix proxy static file issue
  scheduler/src/proxy.ts
Labels: feature, scheduler, approved

#2705 feat: add config page partial update
  shell/app/config-page/index.tsx
Labels: feature, approved

#2706 fix: fix deploy runtime selectable error
  shell/app/common/components/base-list/list-item.tsx
  shell/app/config-page/page-render.tsx
Labels: dop, approved, bugfix

#2708 fix(dop): create project pipeline add icon
  shell/app/modules/project/pages/pipelines/components/form.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: approved, bugfix

#2709 fix(dop): create project pipeline add icon
  shell/app/modules/project/pages/pipelines/components/form.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: bugfix

#2711 fix: fix cicds config api error
  shell/app/modules/application/stores/pipeline-config.ts
Labels: dop, approved, bugfix

#2717 feat: modify audit template
  shell/app/modules/org/common/audit-templates.json
Labels: approved

#2719 feat: merge project addon to deploy center
  locales/en.json
  locales/zh.json
  shell/app/common/utils/go-to.tsx
  shell/app/menus/project.tsx
  shell/app/modules/apiManagePlatform/pages/access-manage/edit/index.tsx
  shell/app/modules/project/pages/data-source/index.tsx
  shell/app/modules/project/router.tsx
  shell/app/modules/project/tabs.tsx
  shell/app/user/stores/_perm-project.ts
Labels: dop, refactor
