Repository erda-project/erda-ui, pull requests merged in 2022-05, with the labels that each got.

#3441 feat: runtime container log fallback v2
  shell/app/common/services/index.ts
  shell/app/common/stores/common.ts
  shell/app/modules/runtime/common/logs/components/container-log.tsx
Labels: feature, dop, approved

#3442 fix:(cli): keep pnpm version to 6.x
  Dockerfile
  cli/lib/init-online.ts
  cli/package.json
Labels: cli, approved, bugfix

#3445 fix: runtime container log first query params
  shell/app/modules/runtime/common/logs/components/container-log.tsx
Labels: approved, bugfix

#3446 fix: i18n confirm to deletion -> confirm to delete
  locales/en.json
  locales/zh.json
  shell/app/common/components/delete-confirm/index.tsx
  shell/app/common/components/tags-row/index.tsx
  shell/app/common/components/tags/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/apiManagePlatform/pages/api-market/components/api-resource/resource.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/design/basic-params-config.tsx
  shell/app/modules/project/common/components/issue/issue-drawer.tsx
  shell/app/modules/project/pages/backlog/issue-item.tsx
  shell/app/modules/project/pages/homepage/index.tsx
  shell/app/modules/project/pages/iteration/table.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/case-api.tsx
  shell/app/modules/runtime/pages/overview/components/domain-modal.tsx
Labels: approved, bugfix

#3447 fix: fix runtime container log fallback request params
  shell/app/modules/runtime/common/logs/components/container-log.tsx
Labels: bugfix

#3449 fix: fix cmp service request error
  shell/app/modules/cmp/router.ts
  shell/app/modules/dcos/pages/service-manager/index.tsx
  shell/app/modules/dcos/services/service.ts
Labels: cmp, approved, bugfix

#3448 fix(msp): fix fetch log params
  shell/app/common/components/log-roller/index.tsx
Labels: msp, approved, bugfix

#3451 fix(cmp): overview services table pageSize change bug
  shell/app/modules/dcos/pages/cluster-dashboard/instance-list.tsx
Labels: cmp, bugfix

#3454 fix(dop): mobile safety management table reload bug
  shell/app/common/components/crud-table/index.tsx
Labels: dop, bugfix

#3444 feat: related issue name inline edit
  shell/app/modules/project/pages/backlog/issue-item.scss
  shell/app/modules/project/pages/backlog/issue-item.tsx
Labels: feature, dop

#3458 fix: fix runtime log params
  shell/app/modules/runtime/common/logs/components/container-log.tsx
Labels: bugfix

#3459 feat(dop): runtime fast switch
  shell/app/modules/project/common/components/runtime-selector.scss
  shell/app/modules/project/common/components/runtime-selector.tsx
  shell/app/modules/project/services/deploy.ts
  shell/app/modules/project/tabs.tsx
  shell/app/modules/project/types/deploy.d.ts
  shell/app/modules/runtime/stores/runtime.ts
Labels: feature, dop

#3461 fix(msp): add instance status
  shell/app/modules/msp/env-overview/service-list/pages/index.scss
  shell/app/modules/msp/env-overview/service-list/pages/process.tsx
Labels: msp, bugfix

#3462 fix(dop): ticket detail style bug
  shell/app/common/components/edit-field/index.tsx
Labels: dop, bugfix

#3460 fix(dop): runtime detail breadcrumb bug
  shell/app/modules/application/router.ts
  shell/app/modules/project/router.tsx
Labels: dop, bugfix

#3464 fix:(scheduler):fix health check api
  erda.yml
  scheduler/src/proxy.ts
Labels: bug, scheduler, approved, bugfix

#3463 feat: i18n in admin & i18n in dop
  locales/en.json
  locales/zh.json
  shell/app/common/components/add-member-modal/add-member-modal.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/apiManagePlatform/pages/access-manage/components/config.tsx
  shell/app/modules/apiManagePlatform/pages/access-manage/detail/authorization-user.tsx
  shell/app/modules/apiManagePlatform/pages/access-manage/detail/index.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/design/api-publish-modal.tsx
  shell/app/modules/apiManagePlatform/pages/client/components/config.tsx
  shell/app/modules/apiManagePlatform/pages/client/detail/index.tsx
  shell/app/modules/application/pages/repo/components/repo-editor.tsx
  shell/app/modules/application/pages/settings/app-settings.tsx
  shell/app/modules/extra/entry.js
  shell/app/modules/org/pages/announcement/index.tsx
  shell/app/modules/org/pages/approval/index.tsx
  shell/app/modules/org/pages/projects/create-project.tsx
  shell/app/modules/org/pages/projects/issue-field-manage.tsx
  shell/app/modules/org/pages/projects/issue-field-modal.tsx
  shell/app/modules/org/pages/projects/settings/info/index.tsx
  shell/app/modules/org/pages/safety/index.tsx
  shell/app/modules/org/pages/setting/block-network.tsx
  shell/app/modules/org/pages/setting/notice-channel.tsx
  shell/app/modules/org/pages/setting/org-info.tsx
  shell/app/modules/org/pages/setting/org-setting.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
  shell/app/modules/project/common/components/issue/issue-config.tsx
  shell/app/modules/project/common/issue-config.ts
  shell/app/modules/project/pages/apps/app-form.tsx
  shell/app/modules/project/pages/backlog/backlog.tsx
  shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx
  shell/app/modules/project/pages/deploy/add-deploy/index.tsx
  shell/app/modules/project/pages/settings/components/project-settings.tsx
  shell/app/modules/project/pages/test-env/test-env-detail.tsx
  shell/app/modules/project/pages/test-env/test-env.tsx
  shell/app/modules/project/pages/test-manage/case/import-export.tsx
  shell/app/modules/project/router.tsx
  shell/auto_test/tests/org/organization-manage.spec.ts
Labels: feature, approved

#3456 feat: update i18next from ^17.0.13 to ^21.6.16 in core
  core/package.json
  pnpm-lock.yaml
Labels: feature, approved

#3465 fix(common): fix pipeline issue
  cli/package.json
  pipeline.yml
Labels: approved, bugfix

#3466 fix(common): add cli log
  cli/lib/util/env.ts
Labels: approved, bugfix

#3467 fix(cli): fix lock issue
  pnpm-lock.yaml
Labels: cli, approved, bugfix

#3468 fix: i18n nsSeparator fail
  core/src/i18n.ts
Labels: approved, bugfix

#3469 fix: fix land page button style
  shell/app/org-home/pages/land/index.tsx
Labels: approved, bugfix

#3471 fix(scheduler): fix scheduler build issue
  .npmrc
  modules/components/.npmrc
  modules/components/package.json
  package.json
  pnpm-lock.yaml
  scheduler/package.json
Labels: scheduler, approved, bugfix

#3472 fix(common): fix build issue
  core/package.json
  package.json
  pipeline.yml
  pnpm-lock.yaml
  shell/package.json
Labels: approved, bugfix

#3470 feat: i18n in msp/config
  .github/workflows/codecov.yml
  locales/en.json
  locales/zh.json
  shell/app/common/components/key-value-editor/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-setting/configuration/index.tsx
Labels: feature

#3473 feat(common): change antd version
  pnpm-lock.yaml
  shell/package.json
Labels: approved, bugfix

#3474 fix(common): fix build issue
  package.json
  pnpm-lock.yaml
Labels: approved, bugfix

#3475 feat(common): remove log
  cli/lib/util/env.ts
  cspell.json
  package.json
  pipeline.yml
Labels: feature, approved, chore

#3478 chore(common): rollback code due to preinstall has bug
  package.json
  pipeline.yml
Labels: approved

#3479 fix(common): fix antd style issue
  modules/components/package.json
  pnpm-lock.yaml
  shell/package.json
Labels: approved, bugfix

#3477 feat(dop): runtime resource config scale add tip
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/runtime/pages/overview/components/resource-modal.tsx
Labels: feature, dop

#3476 feat: i18n in msp
  .github/workflows/codecov.yml
  locales/en.json
  locales/zh.json
  shell/app/common/components/common-range-picker/__tests__/index.test.tsx
  shell/app/common/components/common-range-picker/index.tsx
  shell/app/common/components/monitor/__tests__/components/timeRangeSelector.test.tsx
  shell/app/common/components/monitor/components/timeRangeSelector.tsx
  shell/app/common/components/pure-log-roller/download-log-modal.tsx
  shell/app/common/components/time-select/__tests__/time-select.test.tsx
  shell/app/common/components/time-select/time-select.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/application/pages/settings/components/app-notify/notify-config.tsx
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
  shell/app/modules/cmp/common/alarm-strategy/notify-strategy-select.tsx
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
  shell/app/modules/cmp/common/custom-alarm/index.tsx
  shell/app/modules/cmp/common/custom-dashboard/index.tsx
  shell/app/modules/cmp/pages/alarm-report/index.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-terminal.tsx
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
  shell/app/modules/cmp/pages/cluster-manage/cloud-machine-form-modal.tsx
  shell/app/modules/dop/pages/form-editor/components/api-test.tsx
  shell/app/modules/dop/pages/projects/apply-unblock-modal.tsx
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-overview.tsx
  shell/app/modules/msp/monitor/browser-insight/common/utils/index.ts
  shell/app/modules/msp/monitor/browser-insight/pages/ajax/config/chartMap.ts
  shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
  shell/app/modules/msp/monitor/status-insight/pages/status/constants.ts
  shell/app/modules/msp/monitor/status-insight/pages/status/status-detail.tsx
  shell/app/modules/msp/monitor/status-insight/pages/status/status.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.tsx
  shell/app/modules/msp/pages/micro-service/overview.tsx
  shell/app/modules/org/pages/projects/settings/info/index.tsx
  shell/app/modules/org/pages/setting/org-info.tsx
  shell/app/modules/project/common/components/scan-rule.tsx
  shell/app/modules/project/pages/backlog/iteration-item.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/case-api.tsx
  shell/app/modules/publisher/pages/publisher-manage/publisher-form-modal.tsx
  shell/app/modules/publisher/pages/publisher-manage/publisher-info.tsx
  shell/app/modules/runtime/common/logs/components/log-filter.tsx
Labels: feature, approved

#3480 fix: do not open issue detail when issue not found
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
Labels: dop, bugfix

#3483 fix: redo shell/app/modules/extra/entry.js
  shell/app/modules/extra/entry.js
Labels: approved, bugfix

#3482 fix(msp): fix i18n issue
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
Labels: msp, approved, bugfix

#3484 feat(dop): mr detail header add app name
  shell/app/modules/application/router.ts
  shell/app/modules/application/tabs.tsx
Labels: feature, dop

#3486 feat(dop): app quality test list add view coverage report operation
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/test/coverage-report.tsx
  shell/app/modules/application/pages/test/test-list.tsx
Labels: feature, dop, approved

#3487 feat(dop): commit detail header add app name
  shell/app/modules/application/router.ts
Labels: feature, dop

#3488 fix: fix missing header from node request
  scheduler/src/filters/not-found.filter.ts
Labels: approved, bugfix

#3491 fix: fix land sysAdmin page without admin access
  shell/app/App.tsx
  shell/app/org-home/stores/org.tsx
Labels: approved, bugfix

#3489 feat(dop): add dev workflow
  locales/en.json
  locales/zh.json
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/common/components/table/interface.ts
  shell/app/config-page/components/tabs/tabs.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/repo/components/compare-detail.tsx
  shell/app/modules/project/common/components/branch-rule.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/issue-drawer.tsx
  shell/app/modules/project/common/components/issue/issue-icon.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/common/components/workflow/index.tsx
  shell/app/modules/project/common/components/workflow/issue-workflow.tsx
  shell/app/modules/project/common/components/workflow/mr-workflow.tsx
  shell/app/modules/project/common/components/workflow/steps/add-flow.tsx
  shell/app/modules/project/common/components/workflow/steps/base-step.tsx
  shell/app/modules/project/common/components/workflow/steps/code.tsx
  shell/app/modules/project/common/components/workflow/steps/index.tsx
  shell/app/modules/project/common/components/workflow/steps/pipeline.tsx
  shell/app/modules/project/common/components/workflow/steps/temp-merge.tsx
  shell/app/modules/project/common/config.ts
  shell/app/modules/project/pages/backlog/issue-item.tsx
  shell/app/modules/project/pages/settings/components/project-settings.tsx
  shell/app/modules/project/pages/settings/components/project-workflow.tsx
  shell/app/modules/project/services/project-workflow.ts
  shell/app/styles/antd-extension.scss
Labels: feature, dop

#3495 fix(common): fix antd version
  pnpm-lock.yaml
  shell/package.json
Labels: approved, bugfix

#3496 fix(dop): fix field name
  shell/app/modules/project/pages/settings/components/project-workflow.tsx
Labels: dop, bugfix

#3494 feat(dop): app runtimes fast switch
  shell/app/modules/application/tabs.tsx
  shell/app/modules/project/common/components/runtime-selector.tsx
  shell/app/modules/project/services/deploy.ts
Labels: feature, dop

#3497 fix(msp): display notify method when edit strategy
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
Labels: msp, approved, bugfix

#3499 fix(dop): project pipeline add form bug
  shell/app/modules/project/common/components/pipeline-new/form.tsx
Labels: dop, approved, bugfix

#3500 fix(dop): project release list operations style bug
  shell/app/config-page/components/table/render-types.tsx
  shell/app/config-page/components/table/v2/utils.tsx
Labels: dop, bugfix

#3502 chore: update components module config
  .gitignore
  modules/components/.umirc.ts
  modules/components/package.json
  modules/components/public/favicon.ico
Labels: chore

#3504 fix(dop): rollback list style bug
  shell/app/modules/runtime/common/components/deployment-table.tsx
Labels: dop, approved, bugfix

#3503 feat: i18n in admin & msp after checking
  locales/en.json
  locales/zh.json
  shell/app/common/components/time-select/__tests__/time-select.test.tsx
  shell/app/common/components/time-select/__tests__/utils.test.tsx
  shell/app/common/components/time-select/utils.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/deploy-list/deploy-list.tsx
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
  shell/app/modules/cmp/pages/pod-detail/index.tsx
  shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
  shell/app/modules/msp/monitor/status-insight/pages/status/status-detail.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx
  shell/app/modules/msp/pages/micro-service/overview.tsx
  shell/app/modules/org/pages/approval/index.tsx
  shell/app/modules/org/pages/setting/notice-channel.tsx
Labels: feature

#3506 feat(dop): remove mr score
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/repo/components/mr-comments.tsx
  shell/app/modules/application/pages/repo/mr-detail.tsx
Labels: feature, dop

#3507 fix: i18n plurals usage (replace {count} with {num})
  locales/en.json
  locales/zh.json
  shell/app/common/components/time-select/utils.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
Labels: approved, bugfix

#3512 fix(dop): hide "select existing" and "new purchase" of addon
  shell/app/modules/project/pages/third-service/components/instance-form.tsx
Labels: dop, approved, bugfix

#3513 feat: hide pipeline pre check warning
  shell/app/common/types/pipeline.d.ts
  shell/app/modules/application/pages/build-detail/index.tsx
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/types/build.d.ts
  shell/app/modules/project/common/components/pipeline-new/detail/execute.tsx
  shell/app/modules/project/pages/plan-detail/test-record/pipeline-detail.tsx
Labels: feature, dop, approved

#3510 feat: remove useless tip in project list
  locales/en.json
  locales/zh.json
  shell/app/modules/org/pages/projects/project-list.tsx
Labels: feature, approved

#3509 chore: decrease pipeline cpu usage
  pipeline.yml
Labels: approved, chore

#3508 feat: remove viewport meta to force show pc layout in mobile
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, approved

#3515 chore: bump version
  .github/prlint.json
  VERSION
Labels: approved

#3511 feat: I18n in cmp
  locales/en.json
  locales/zh.json
  shell/app/common/components/monitor/__tests__/monitor-chart-panel.test.tsx
  shell/app/common/components/monitor/monitor-chart-panel.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/cmp/common/components/instance-operation.tsx
  shell/app/modules/cmp/common/components/machine-form-modal.tsx
  shell/app/modules/cmp/common/components/set-tag-form.tsx
  shell/app/modules/cmp/common/custom-alarm/index.tsx
  shell/app/modules/cmp/pages/account-guidance/index.tsx
  shell/app/modules/cmp/pages/alarm-report/index.tsx
  shell/app/modules/cmp/pages/cloud-source/index.tsx
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/aliCloud-container-cluster-form.tsx
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/aliCloud-erdc-form.tsx
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/aliCloud-preview.tsx
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-type-modal.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
  shell/app/modules/cmp/pages/cluster-manage/config.tsx
  shell/app/modules/cmp/pages/cluster-manage/token-manage-modal.tsx
  shell/app/modules/cmp/pages/computing/ecs/index.tsx
  shell/app/modules/cmp/pages/middleware-dashboard/index.tsx
  shell/app/modules/cmp/pages/networks/vpc/index.tsx
  shell/app/modules/cmp/pages/networks/vsw/index.tsx
  shell/app/modules/cmp/pages/storage/oss/index.tsx
  shell/app/modules/cmp/pages/tasks/task-list.tsx
  shell/app/modules/dcos/common/label-selector.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/alarm-record.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/index.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/instance-list.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/machine-detail.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/machineTabs.tsx
  shell/app/modules/dcos/pages/machine-manager/machine-table.tsx
  shell/app/modules/dcos/pages/machine-manager/tag-form.tsx
  shell/app/modules/dcos/pages/service-manager/index.tsx
  shell/app/modules/dcos/pages/service-manager/mq-manager/group.tsx
  shell/app/modules/dcos/pages/service-manager/mq-manager/topic.tsx
  shell/app/modules/dcos/pages/service-manager/mq.tsx
  shell/app/modules/dcos/pages/service-manager/rds.tsx
  shell/app/modules/dcos/pages/service-manager/redis.tsx
  shell/app/modules/project/pages/test-report/create.tsx
  shell/app/modules/project/pages/test-report/download.tsx
  shell/app/yml-chart/common/in-params-drawer.tsx
Labels: feature, approved

#3501 feature: refactor uc
  modules/uc/craco.config.js
  modules/uc/package.json
  modules/uc/src/common/components/container.tsx
  modules/uc/src/common/components/form-input.tsx
  modules/uc/src/common/i18n.ts
  modules/uc/src/common/index.ts
  modules/uc/src/common/utils.ts
  modules/uc/src/common/utils.tsx
  modules/uc/src/images/default-user.svg
  modules/uc/src/images/edit.svg
  modules/uc/src/index.js
  modules/uc/src/locales/en.json
  modules/uc/src/locales/zh.json
  modules/uc/src/ory/errors.ts
  modules/uc/src/ory/flow.tsx
  modules/uc/src/ory/index.tsx
  modules/uc/src/ory/node.tsx
  modules/uc/src/ory/utils.tsx
  modules/uc/src/pages/login/index.tsx
  modules/uc/src/pages/recovery/index.tsx
  modules/uc/src/pages/registration/index.tsx
  modules/uc/src/pages/setting/index.tsx
  modules/uc/src/router.tsx
  modules/uc/src/services/uc.tsx
  modules/uc/src/store/uc.ts
  modules/uc/src/types/uc.d.ts
  package.json
  pnpm-lock.yaml
  shell/app/modules/org/pages/projects/settings/info/index.tsx
  shell/app/user/stores/index.ts
Labels: feature, refactor, approved

#3517 feat(dop): project pipeline add disable operation
  shell/app/common/types/pipeline.d.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/pipeline/run-detail/pipeline-chart/pipeline-node.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/pipeline-node.tsx
  shell/app/yml-chart/chart/yml-chart.tsx
  shell/app/yml-chart/common/pipeline-graphic-editor.tsx
  shell/app/yml-chart/pipeline-editor.tsx
Labels: feature, dop

#3516 [draft] Replace preinstall hook to pnpm devPreinstall
  package.json
  pipeline.yml
Labels: cli

#3518 feat(chore): fix ut running error after PR merged
  .github/workflows/codecov.yml
Labels: feature, chore

#3514 feat(dop): show dev workflow
  shell/app/common/components/form-modal/index.tsx
  shell/app/modules/application/pages/repo/components/compare-detail.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/issue-drawer.tsx
  shell/app/modules/project/common/components/workflow/steps/add-flow.tsx
  shell/app/modules/project/common/components/workflow/steps/base-step.tsx
  shell/app/modules/project/pages/settings/components/project-workflow.tsx
Labels: feature, dop

#3520 fix(dop): project pipeline actions operations icons change
  shell/app/modules/project/common/components/pipeline-new/detail/pipeline-node.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: dop, approved, bugfix

#3519 feat: i18n in msp 1%
  shell/app/modules/addonPlatform/pages/common/components/addon-detail-drawer.tsx
  shell/app/modules/cmp/common/addon-detail/detail.tsx
Labels: feature, approved

#3521 fix(dop): project pipeline actions operations icons style optimization
  shell/app/modules/project/common/components/pipeline-new/detail/pipeline-node.scss
  shell/app/modules/project/common/components/pipeline-new/detail/pipeline-node.tsx
Labels: dop, approved, bugfix

#3522 fix(msp): fix msp locale
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-overview/service-list/pages/service-name-select.tsx
Labels: msp, bugfix

#3524 fix(dop): modify the temporary branch naming policy
  shell/app/modules/project/common/components/workflow/mr-workflow.tsx
  shell/app/modules/project/common/components/workflow/steps/add-flow.tsx
Labels: dop, bugfix

#3526 fix(dop): project pipeline actions operations icons tooltip optimization
  shell/app/modules/project/common/components/pipeline-new/detail/pipeline-node.tsx
Labels: dop, approved, bugfix

#3528 fix: marketplace style fix
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/marketplace/pages/detail.tsx
  shell/app/modules/marketplace/pages/index.tsx
  shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx
Labels: bugfix

#3531 fix: when log fallback, keep status
  shell/app/common/stores/common.ts
Labels: dop, approved, bugfix

#3529 feat(dop): hide auto merge
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/workflow/index.tsx
  shell/app/modules/project/common/components/workflow/steps/add-flow.tsx
  shell/app/modules/project/common/components/workflow/steps/code.tsx
  shell/app/modules/project/common/config.ts
  shell/app/modules/project/pages/settings/components/project-workflow.tsx
  shell/app/modules/project/services/project-workflow.ts
Labels: feature, dop, approved

#3532 fix: fix marketplace detail style
  shell/app/modules/marketplace/pages/detail.tsx
Labels: approved, bugfix

#3533 feat(dop): remove two_branch type
  shell/app/modules/project/common/components/workflow/steps/add-flow.tsx
Labels: feature, dop

#3537 fix: markdown editor crash when nesting too many quotes
  shell/app/common/components/edit-field/index.tsx
  shell/app/common/components/markdown-editor/editor.tsx
  shell/app/common/components/markdown-editor/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/issue/comment-box.tsx
Labels: approved, bugfix

#3536 fix(dop): don't query pipeline detail when pipelineId is 0
  shell/app/modules/project/common/components/workflow/steps/pipeline.tsx
Labels: dop, approved, bugfix

#3530 feat: add ticket state workflow / ticket protocol
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/common/components/icon/index.tsx
  shell/app/modules/org/common/config.ts
  shell/app/modules/project/common/components/issue-workflow-setting-modal.tsx
  shell/app/modules/project/common/components/issue/issue-state.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
  shell/app/modules/project/pages/ticket/index.tsx
Labels: feature, dop, approved

#3534 fix(cmp): domain management pagination bug
  shell/app/modules/cmp/pages/domain-manage/index.tsx
Labels: cmp, approved, bugfix

#3538 fix: fix dropdown menu disabled style
  shell/app/common/components/base-list/index.scss
  shell/app/config-page/components/list-new/list/index.scss
Labels: approved, bugfix

#3539 feat(dop): optimize dev workflow style
  shell/app/modules/application/pages/repo/components/compare-detail.tsx
  shell/app/modules/project/common/components/workflow/index.tsx
  shell/app/modules/project/common/components/workflow/issue-workflow.tsx
  shell/app/modules/project/common/components/workflow/steps/base-step.scss
  shell/app/modules/project/common/components/workflow/steps/base-step.tsx
  shell/app/modules/project/common/components/workflow/steps/code.tsx
  shell/app/modules/project/common/components/workflow/steps/index.tsx
  shell/app/modules/project/common/components/workflow/steps/pipeline.tsx
  shell/app/modules/project/common/components/workflow/steps/temp-merge.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, dop, approved

#3540 fix(cmp): fix add-on monitoring chart display error
  shell/app/modules/cmp/pages/middleware-detail/monitor.tsx
Labels: cmp, bugfix

#3545 feat(dop): add flowName field when create flow
  shell/app/modules/project/common/components/workflow/steps/add-flow.tsx
Labels: feature, dop

#3543 fix(dop): issue detail task type bug
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
Labels: dop, bugfix

#3548 feat: add label tip in block network setting
  locales/en.json
  locales/zh.json
  shell/app/modules/org/pages/setting/block-network.tsx
Labels: feature, approved

#3546 fix: fix ticket label render error
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
Labels: bugfix

#3542 fix(dop): runtime detail icon style bug
  shell/app/modules/runtime/pages/overview/components/index.tsx
Labels: dop, approved, bugfix

#3544 feat: app pipeline refactor
  shell/app/common/utils/go-to.tsx
  shell/app/interface/global.d.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/pipeline/config-detail/case-info.tsx
  shell/app/modules/application/pages/pipeline/config-detail/index.tsx
  shell/app/modules/application/pages/pipeline/config-detail/pipeline-editor/index.tsx
  shell/app/modules/application/pages/pipeline/config.tsx
  shell/app/modules/application/pages/pipeline/index.tsx
  shell/app/modules/application/pages/pipeline/pipeline-detail.tsx
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.scss
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/pages/pipeline/run-detail/index.tsx
  shell/app/modules/application/pages/pipeline/run-detail/pipeline-log.scss
  shell/app/modules/application/pages/pipeline/run-detail/pipeline-log.tsx
  shell/app/modules/application/pages/pipeline/scope-config.tsx
  shell/app/modules/application/router.ts
  shell/app/modules/application/stores/build.ts
  shell/app/modules/application/tabs.tsx
  shell/app/modules/project/common/components/pipeline-new/config.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/build-log.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/editor.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/execute.scss
  shell/app/modules/project/common/components/pipeline-new/detail/execute.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/index.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/pipeline-chart/index.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/pipeline-chart/pipeline-node.scss
  shell/app/modules/project/common/components/pipeline-new/detail/pipeline-chart/pipeline-node.tsx
  shell/app/modules/project/common/components/pipeline-new/form.tsx
  shell/app/modules/project/common/components/pipeline-new/list.tsx
  shell/app/modules/project/common/components/pipeline-new/record-detail.scss
  shell/app/modules/project/common/components/pipeline-new/record-detail.tsx
  shell/app/modules/project/common/components/pipeline-new/records.tsx
  shell/app/modules/project/common/components/workflow/steps/pipeline.tsx
Labels: feature, dop, approved

#3553 fix: fix pipeline config path
  shell/app/modules/project/common/components/workflow/index.tsx
Labels: approved, bugfix

#3555 fix: i18n 'critical' to 'serious'
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
Labels: approved, bugfix

#3556 feat(common): introduce i18n plugin
  core/src/i18n.ts
  modules/components/package.json
  package.json
  pnpm-lock.yaml
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/issue/issue-config.tsx
  shell/app/modules/project/common/issue-config.ts
  shell/babel.config.js
  shell/package.json
  shell/vite.config.js
Labels: feature, approved

#3557 feat(msp): MSP safety policy add Access Control Server
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/services/gateway.ts
  shell/app/modules/msp/types/gateway.d.ts
Labels: feature, msp, approved

#3558 fix(common): fix i18n plugin error
  pnpm-lock.yaml
  shell/package.json
Labels: approved, bugfix

#3559 fix(common): fix i18n plugin issue
  pnpm-lock.yaml
  shell/package.json
Labels: approved

#3560 fix(common): fix pipeline hang issue
  pnpm-lock.yaml
  shell/babel.config.js
  shell/package.json
Labels: approved, bugfix

#3562 fix: rollback vite version
  package.json
  pnpm-lock.yaml
Labels: bugfix

#3561 fix(dop): create deploy releases list optimization
  shell/app/modules/project/pages/deploy/add-deploy/release-list.tsx
  shell/app/modules/project/types/deploy.d.ts
Labels: dop, approved, bugfix

#3564 feat: recover app obsoleted pipeline
  shell/app/common/components/table/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/pipeline/index.tsx
  shell/app/modules/application/pages/pipeline/obsoleted-pipeline.scss
  shell/app/modules/application/pages/pipeline/obsoleted-pipeline.tsx
  shell/app/modules/application/router.ts
  shell/app/modules/project/common/components/pipeline-new/detail/execute.scss
  shell/app/modules/project/common/components/pipeline-new/record-detail.tsx
Labels: feature, dop

#3563 fix: fix style issue
  shell/app/modules/msp/env-overview/service-list/pages/transaction.scss
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
  shell/app/styles/antd-extension.scss
Labels: dop, msp, bugfix

#3567 fix: app obsoleted pipeline menu href error
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/pipeline/index.tsx
  shell/app/modules/application/pages/pipeline/obsoleted-pipeline.tsx
  shell/app/modules/application/router.ts
Labels: approved, bugfix

#3566 fix(dop): pipeline action delete bug
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/pipeline-new/detail/pipeline-node.tsx
Labels: dop, approved, bugfix

#3569 feat: recovery app pipeline
  shell/app/common/utils/go-to.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/config-detail/case-info.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/config-detail/index.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/config-detail/pipeline-editor/index.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/config.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/index.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/pipeline-detail.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/run-detail/build-detail.scss
  shell/app/modules/application/pages/obsoleted-pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/run-detail/build-log.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/run-detail/config.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/run-detail/index.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/run-detail/pipeline-chart/index.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/run-detail/pipeline-chart/pipeline-node.scss
  shell/app/modules/application/pages/obsoleted-pipeline/run-detail/pipeline-chart/pipeline-node.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/run-detail/pipeline-log.scss
  shell/app/modules/application/pages/obsoleted-pipeline/run-detail/pipeline-log.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/scope-config.tsx
  shell/app/modules/application/pages/pipeline/index.tsx
  shell/app/modules/application/pages/pipeline/obsoleted-pipeline.scss
  shell/app/modules/application/pages/pipeline/obsoleted-pipeline.tsx
  shell/app/modules/application/tabs.tsx
Labels: feature, dop, approved

#3571 fix: fix container log fallback error
  shell/app/common/stores/common.ts
  shell/app/modules/runtime/common/logs/components/container-log.tsx
Labels: bugfix
