Repository erda-project/erda-ui, pull requests merged in 2022-08, with the labels that each got.

#3721 feat: hide cmp resource menu
  shell/app/menus/cmp.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/machineTabs.tsx
  shell/app/modules/project/pages/resource/components/resource.jsx
Labels: feature, cmp, bugfix

#3722 feat(components): update version
  modules/components/README.md
  modules/components/package.json
Labels: feature, approved

#3724 feat: modify default route path of fdp
  shell/app/common/utils/go-to.tsx
  shell/app/org-home/stores/org.tsx
Labels: feature, approved

#3723 fix(dop): fix pre tag in md issue
  shell/app/common/components/markdown-render/index.tsx
Labels: dop, approved, bugfix

#3725 feat: optimize issue flow
  shell/app/common/components/erda-alert/index.tsx
  shell/app/common/utils/go-to.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/repo/components/compare-detail.tsx
  shell/app/modules/application/pages/repo/components/repo-mr-form.tsx
  shell/app/modules/application/pages/repo/mr-detail.tsx
  shell/app/modules/application/pages/repo/repo-mr-creation.tsx
  shell/app/modules/project/common/components/workflow/add-flow.tsx
  shell/app/modules/project/common/components/workflow/cards/code.tsx
  shell/app/modules/project/common/components/workflow/cards/merge-request.tsx
  shell/app/modules/project/common/components/workflow/cards/merge.tsx
  shell/app/modules/project/common/components/workflow/cards/pipeline.tsx
  shell/app/modules/project/common/components/workflow/config.ts
  shell/app/modules/project/common/components/workflow/index.tsx
  shell/app/modules/project/common/components/workflow/issue-workflow.tsx
  shell/app/modules/project/services/project-workflow.ts
  shell/app/modules/project/types/devops-workflow.d.ts
Labels: feature, dop

#3727 feat: global search style
  locales/en.json
  locales/zh.json
  shell/app/config-page/components/scale-card/scale-card.scss
  shell/app/config-page/components/scale-card/scale-card.spec.d.ts
  shell/app/config-page/components/scale-card/scale-card.tsx
  shell/app/modules/runtime/pages/overview/components/service-card.tsx
  shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
  shell/app/modules/runtime/types/service.d.ts
Labels: feature

#3726 feat: add runtime container dashboard
  shell/app/modules/msp/monitor/monitor-common/components/resource-usage/resource-usage-charts.tsx
Labels: feature, cmp

#3728 fix: add flow optimize
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/repo/repo-mr-creation.tsx
  shell/app/modules/msp/monitor/monitor-common/components/resource-usage/resource-usage-charts.tsx
  shell/app/modules/project/common/components/workflow/add-flow.tsx
Labels: feature, bugfix

#3730 fix: fix create mr error
  shell/app/modules/application/pages/repo/components/repo-mr-form.tsx
Labels: bugfix

#3731 fix: issue detail subscribers
  shell/app/modules/project/common/components/issue/subscribers-selector.tsx
Labels: bugfix

#3732 fix: code test list pagination error
  shell/app/modules/application/pages/test/test-list.tsx
  shell/app/modules/application/stores/test.ts
Labels: bugfix

#3733 fix: fix mr workflow-params
  shell/app/modules/application/pages/repo/components/compare-detail.tsx
  shell/app/modules/project/common/components/workflow/mr-workflow.tsx
  shell/app/modules/project/services/project-workflow.ts
Labels: bugfix

#3734 fix: fix list input to textarea
  shell/app/modules/application/common/components/list-input-group.tsx
Labels: bugfix

#3735 fix: fix avatar load time
  shell/app/antd-overwrite/avatar/index.tsx
Labels: bugfix

#3736 fix: fix backlog add issue style
  shell/app/modules/project/pages/backlog/backlog.tsx
Labels: bugfix

#3739 feat(components): modify components table
  modules/components/__tests__/table/index.test.tsx
  modules/components/docs/components/table/demos/row-action.tsx
  modules/components/package.json
  modules/components/src/table/interface.ts
  modules/components/src/table/style/index.less
  modules/components/src/table/utils.tsx
Labels: feature, approved

#3741 fix: fix issue subscribers
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/issue-drawer.tsx
Labels: bugfix

#3740 feat: runtime pod list
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/runtime/pages/overview/components/service-card.tsx
  shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
  shell/app/modules/runtime/services/runtime.ts
  shell/app/modules/runtime/types/runtime.d.ts
Labels: feature, dop

#3742 feat: add deploy create params
  shell/app/modules/project/pages/deploy/index.tsx
  shell/app/modules/project/services/deploy.ts
Labels: feature

#3743 feat: add cmp dashboard
  shell/app/config-page/components/panel/panel.tsx
  shell/app/modules/addonPlatform/pages/addon-resource/addon-resource.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/machine-detail.tsx
Labels: feature, cmp

#3744 fix: fix dashboard key
  shell/app/modules/dcos/pages/cluster-dashboard/machine-detail.tsx
Labels: cmp, bugfix

#3745 feat: issue detail flow optimize
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/common/components/workflow/add-flow.tsx
  shell/app/modules/project/common/components/workflow/index.tsx
  shell/app/modules/project/common/components/workflow/issue-workflow.tsx
  shell/app/modules/project/pages/backlog/issue-item.tsx
  shell/app/modules/project/services/project-workflow.ts
Labels: feature, dop

#3746 fix: fix deploy get params
  shell/app/modules/project/pages/deploy/add-deploy/index.tsx
  shell/app/modules/project/types/deploy.d.ts
Labels: bugfix

#3747 feat: add ga user id
  shell/app/App.tsx
Labels: feature, dop, bugfix

#3749 fix: fix ga id
  scheduler/src/filters/not-found.filter.ts
  shell/app/App.tsx
  shell/app/interface/global.d.ts
  shell/webpack.config.js
Labels: bugfix

#3751 feat: forbidden linkS request when ak sk not exits
  scheduler/package.json
  shell/app/links-service.ts
Labels: feature, bugfix

#3752 feat: bi refactor
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/cmp/pages/middleware-dashboard/index.tsx
  shell/app/modules/cmp/router.ts
  shell/app/modules/msp/monitor/browser-insight/common/components/biRenderFactory.tsx
  shell/app/modules/msp/monitor/browser-insight/common/components/sort-list/sort-list.scss
  shell/app/modules/msp/monitor/browser-insight/common/components/sort-list/sort-list.tsx
  shell/app/modules/msp/monitor/browser-insight/common/components/sort-list/sort-tab.scss
  shell/app/modules/msp/monitor/browser-insight/common/components/sort-list/sort-tab.tsx
  shell/app/modules/msp/monitor/browser-insight/common/components/sort-list/sortFactory.tsx
  shell/app/modules/msp/monitor/browser-insight/common/components/sort-list/sub-tab.scss
  shell/app/modules/msp/monitor/browser-insight/common/components/sort-list/sub-tab.tsx
  shell/app/modules/msp/monitor/browser-insight/common/utils/index.ts
  shell/app/modules/msp/monitor/browser-insight/pages/ajax/ajax.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/ajax/config/apiConfig.ts
  shell/app/modules/msp/monitor/browser-insight/pages/ajax/config/chartMap.ts
  shell/app/modules/msp/monitor/browser-insight/pages/browser/browser.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/browser/config/apiConfig.ts
  shell/app/modules/msp/monitor/browser-insight/pages/browser/config/chartMap.ts
  shell/app/modules/msp/monitor/browser-insight/pages/domain/config/apiConfig.ts
  shell/app/modules/msp/monitor/browser-insight/pages/domain/config/chartMap.ts
  shell/app/modules/msp/monitor/browser-insight/pages/domain/domain.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/page/config/apiConfig.ts
  shell/app/modules/msp/monitor/browser-insight/pages/page/config/chartMap.ts
  shell/app/modules/msp/monitor/browser-insight/pages/page/page.tsx
  shell/app/modules/msp/monitor/browser-insight/pages/script/config/apiConfig.ts
  shell/app/modules/msp/monitor/browser-insight/pages/script/config/chartMap.ts
  shell/app/modules/msp/monitor/browser-insight/pages/script/script.tsx
  shell/app/modules/msp/monitor/monitor-common/services/monitorChart.ts
  shell/app/modules/msp/monitor/monitor-common/stores/monitorChart.ts
Labels: feature, msp, refactor

#3753 feat: pod list optimize
  shell/app/modules/runtime/pages/overview/components/service-card.tsx
Labels: feature, dop

#3754 fix: fix table config
  shell/app/common/components/table/table-config.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/publisher/pages/artifacts/artifacts-detail.tsx
  shell/app/modules/runtime/pages/overview/components/service-card.tsx
Labels: bugfix

#3756 fix: fix params in dashboard
  shell/app/modules/msp/monitor/browser-insight/pages/ajax/config/apiConfig.ts
  shell/app/modules/msp/monitor/browser-insight/pages/script/config/apiConfig.ts
Labels: bugfix

#3755 fix: delete some chart in api platform
  shell/app/modules/apiManagePlatform/pages/access-manage/detail/authorization-user.tsx
  shell/app/modules/apiManagePlatform/pages/access-manage/detail/index.tsx
Labels: bugfix

#3757 fix: fix runtime style
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/runtime/pages/overview/components/service-card.tsx
Labels: bugfix

#3758 fix: upload zip error in windows
  shell/app/modules/org/pages/projects/import-project-template.tsx
  shell/app/modules/project/pages/release/components/form.tsx
  shell/app/modules/runtime/pages/overview/components/service-card.tsx
Labels: bugfix

#3759 fix: api platform monitor remove
  shell/app/modules/apiManagePlatform/pages/client/detail/index.tsx
  shell/app/modules/application/pages/settings/components/app-info.tsx
Labels: bugfix

#3760 fix: fix issue detail custom field error
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
Labels: bugfix

#3761 fix: remove monitor last 3 month data empty
  shell/app/modules/msp/monitor/status-insight/pages/status/status-detail.tsx
  shell/app/modules/runtime/pages/overview/components/service-card.tsx
Labels: bugfix

#3762 fix: fix issue create error
  shell/app/common/components/pure-log-roller/download-log-modal.tsx
  shell/app/modules/project/pages/backlog/issue-item.tsx
Labels: bugfix

#3763 fix: Update download-log-modal.tsx
  shell/app/common/components/log/download-log-modal.tsx
Labels: bugfix

#3765 fix: fix links
  scheduler/src/filters/not-found.filter.ts
  shell/app/App.tsx
  shell/app/interface/global.d.ts
  shell/app/links-service.ts
  shell/app/org-home/stores/org.tsx
Labels: bug, bugfix

#3764 feat(components): modify table sort text color
  modules/components/package.json
  modules/components/src/table/sorter.tsx
Labels: feature
