Repository erda-project/erda-ui, pull requests merged in 2022-04, with the labels that each got.

#3260 fix(dop): project release detail addons style optimization
  shell/app/modules/project/pages/release/components/addon.tsx
Labels: dop, approved, bugfix

#3259 fix(dop): issue detail edit button style optimization
  shell/app/common/components/edit-field/index.tsx
  shell/app/common/components/tags/index.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
Labels: dop, approved, bugfix

#3261 feat(test): add ConfigurableFilter test case
  .codecov.yml
  shell/app/common/components/configurable-filter/__tests__/config-selector.test.tsx
  shell/app/common/components/configurable-filter/__tests__/index.test.tsx
  shell/app/common/components/configurable-filter/index.tsx
  shell/jest.config.js
Labels: feature, test

#3264 fix(common): table sorter style bug
  shell/app/common/components/table/index.tsx
Labels: dop, bugfix

#3265 fix(cmp): domain list management operation add authority
  shell/app/modules/cmp/pages/domain-manage/index.tsx
  shell/app/modules/cmp/types/domain-manage.d.ts
Labels: cmp, bugfix

#3266 feat(test): add ExternalIte test case
  shell/app/common/components/configurable-filter/__tests__/external-item.test.tsx
  shell/app/common/components/configurable-filter/external-item.tsx
Labels: feature, test

#3267 fix(common): config table progress column optimization
  shell/app/config-page/components/table/render-types.tsx
Labels: bugfix

#3270 fix: fix params config edit error
  shell/app/modules/project/common/components/params-config/index.tsx
Labels: dop, bugfix

#3269 fix(dop): create release upload bug
  shell/app/modules/project/pages/release/components/form.tsx
Labels: dop, bugfix

#3272 feat(test): add EditField test case
  .codecov.yml
  shell/app/common/components/edit-field/__tests__/index.test.tsx
  shell/app/common/components/edit-field/index.tsx
  shell/app/common/test_bak/components/edit-field.test.tsx
Labels: feature, test

#3275 feat(dop): project release detail optimization
  shell/app/modules/project/pages/release/components/project-detail.tsx
  shell/app/modules/project/types/release.d.ts
Labels: feature, dop

#3276 feat(dop): add statistics page to iteration
  shell/app/modules/project/pages/issue/issue-dashboard.tsx
  shell/app/modules/project/pages/issue/statistics.tsx
  shell/app/modules/project/pages/issue/task-summary.tsx
  shell/app/modules/project/router.tsx
  shell/app/modules/project/tabs.tsx
Labels: feature, dop

#3278 feat: sync change iteration/labels to include tasks in issue detail
  shell/app/common/components/edit-field/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.scss
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/services/issue.ts
  shell/app/styles/_color.scss
Labels: feature, dop

#3279 fix: refresh issue detail after relation mr
  shell/app/modules/project/common/components/issue/issue-relation.tsx
Labels: dop, bugfix

#3282 fix(msp): fix table cell minWidth
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
  shell/app/modules/cmp/common/custom-alarm/index.tsx
Labels: msp, bugfix

#3283 fix: fix i18n
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
Labels: dop, bugfix

#3284 feat(test): add unit test case
  .codecov.yml
  shell/app/common/__tests__/use-hook.test.tsx
  shell/app/common/components/markdown-editor/__tests__/index.test.tsx
  shell/app/common/components/markdown-editor/__tests__/upload-plugin.test.tsx
  shell/app/common/test_bak/components/markdown-editor/editor.test.tsx
  shell/app/common/test_bak/components/markdown-editor/index.test.tsx
  shell/app/common/test_bak/components/markdown-editor/upload-plugin.test.tsx
  shell/app/common/test_bak/readme.md
Labels: feature, test

#3289 feat(common): text block info add jump link
  shell/app/common/components/text-block-info/index.tsx
  shell/app/config-page/components/simple-chart/simple-chart.spec.d.ts
  shell/app/config-page/components/simple-chart/simple-chart.tsx
Labels: feature

#3294 fix: fix issue detail i18n
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
Labels: bugfix

#3290 fix: fix compatibility style issue in chrome
  shell/app/common/components/tags-row/index.tsx
  shell/app/common/components/tags/index.tsx
Labels: bugfix

#3292 fix(msp): i18n in custom dashboard
  locales/en.json
  locales/zh.json
  shell/app/modules/cmp/common/custom-dashboard/import-export.tsx
  shell/app/modules/cmp/common/custom-dashboard/index.tsx
Labels: msp, bugfix

#3291 fix(dop): issue detail close bug after interface error
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
Labels: dop, bugfix

#3297 feat: add fold sidebar in devops
  core/src/stores/route.ts
  shell/app/interface/global.d.ts
  shell/app/layout/pages/page-container/components/sidebar/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/project.tsx
  shell/app/modules/application/pages/settings/components/app-merge-description.tsx
  shell/app/modules/dop/router.ts
  shell/app/modules/project/pages/test-env/test-env.tsx
  shell/app/modules/project/router.tsx
Labels: feature, dop

#3298 fix(dop): pipeline build history page size change bug
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/stores/build.ts
Labels: dop, bugfix

#3299 fix(msp): can not get error when parse file
  shell/app/modules/cmp/common/custom-dashboard/import-export.tsx
  shell/app/modules/cmp/common/custom-dashboard/index.tsx
Labels: msp, bugfix

#3293 feat: refactor pipeline code / add execute in pipeline detail
  shell/app/common/components/badge/index.tsx
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/project/common/components/pipeline-new/category.scss
  shell/app/modules/project/common/components/pipeline-new/category.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/editor.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/execute.scss
  shell/app/modules/project/common/components/pipeline-new/detail/execute.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/index.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/info.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/pipeline-node.scss
  shell/app/modules/project/common/components/pipeline-new/detail/pipeline-node.tsx
  shell/app/modules/project/common/components/pipeline-new/form.scss
  shell/app/modules/project/common/components/pipeline-new/form.tsx
  shell/app/modules/project/common/components/pipeline-new/guide.scss
  shell/app/modules/project/common/components/pipeline-new/guide.tsx
  shell/app/modules/project/common/components/pipeline-new/index.scss
  shell/app/modules/project/common/components/pipeline-new/index.tsx
  shell/app/modules/project/common/components/pipeline-new/list.tsx
  shell/app/modules/project/common/components/pipeline-new/records.tsx
  shell/app/modules/project/pages/pipelines/index copy.tsx
  shell/app/modules/project/pages/pipelines/index.tsx
  shell/app/modules/project/router.tsx
  shell/app/modules/project/services/pipeline.tsx
Labels: feature, refactor

#3303 fix(common): Some i18n are not displayed correctly in Chinese
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/settings/app-settings.tsx
  shell/app/modules/dop/pages/projects/apply-unblock-modal.tsx
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/org/pages/projects/create-project.tsx
  shell/app/modules/org/pages/projects/issue-type-manage.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/project/pages/plan-detail/columns/operation.tsx
  shell/app/modules/project/pages/settings/components/project-settings.tsx
  shell/app/modules/project/pages/test-manage/case/columns/more-operation/index.tsx
  shell/app/modules/project/pages/test-manage/case/test-env-drawer/index.tsx
  shell/app/modules/runtime/common/components/deployment-table.tsx
  shell/app/modules/runtime/common/components/instance-table.tsx
  shell/app/modules/runtime/common/components/pod-table.tsx
  shell/app/modules/runtime/common/logs/components/container-log.jsx
  shell/app/modules/runtime/common/logs/components/deploy-log.tsx
  shell/app/modules/runtime/pages/overview/components/activity.tsx
  shell/app/modules/runtime/pages/overview/components/domain-modal.tsx
  shell/app/modules/runtime/pages/overview/components/index.tsx
  shell/app/modules/runtime/pages/overview/components/info.tsx
  shell/app/modules/runtime/pages/overview/components/resource-modal.tsx
  shell/app/modules/runtime/pages/overview/components/rollback-list.tsx
  shell/app/modules/runtime/pages/overview/components/service-card.tsx
  shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
Labels: bugfix

#3307 feat(msp): export tab is set as default tab
  shell/app/modules/cmp/common/custom-dashboard/import-export.tsx
Labels: feature, msp, approved

#3306 fix: fix params config empty tooltip
  shell/app/modules/project/common/components/params-config/list-edit.tsx
Labels: dop, approved, bugfix

#3309 feat(msp): bump @erda-ui/dashboard-configurator from 2.0.12 to 2.0.13
  pnpm-lock.yaml
  shell/package.json
Labels: feature, msp

#3305 fix(msp): compatible with data and refactor code in MSP
  shell/app/modules/cmp/common/alarm-strategy/notify-strategy-select.tsx
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
  shell/app/modules/cmp/common/alarm-strategy/trigger-condition-select.tsx
  shell/app/modules/cmp/services/alarm-strategy.ts
  shell/app/modules/cmp/types/alarm-strategy.d.ts
  shell/app/modules/msp/alarm-manage/alarm-strategy/services/alarm-strategy.ts
Labels: msp, bugfix

#3312 feat(msp): add description filter to the custom dashboard
  shell/app/modules/cmp/common/custom-dashboard/import-export.tsx
  shell/app/modules/cmp/common/custom-dashboard/index.tsx
Labels: feature, msp, approved

#3310 fix(#3287): match key to value in en.json
  locales/en.json
  locales/zh.json
  shell/app/common/components/members-table/index.tsx
  shell/app/common/components/pagination/__tests__/index.test.tsx
  shell/app/common/components/pagination/index.tsx
  shell/app/common/components/user-profile/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/org/pages/setting/notice-channel.tsx
  shell/app/modules/publisher/pages/authenticate/index.tsx
Labels: approved, bugfix

#3314 feat(msp): modify placeholder in filter to search by name
  shell/app/modules/cmp/common/custom-dashboard/index.tsx
Labels: feature, msp, approved

#3311 feat(dop): release labels
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/release/components/application-detail.tsx
  shell/app/modules/project/pages/release/components/form.scss
  shell/app/modules/project/pages/release/components/form.tsx
  shell/app/modules/project/pages/release/components/project-detail.tsx
  shell/app/modules/project/pages/settings/components/project-label.tsx
  shell/app/modules/project/pages/settings/components/project-settings.tsx
  shell/app/modules/project/types/release.d.ts
Labels: feature, dop

#3316 fix(msp): remove useless icon
  pnpm-lock.yaml
  shell/app/modules/cmp/common/custom-dashboard/index.tsx
  shell/package.json
Labels: msp, approved, bugfix

#3315 feat: add in/out params in project pipeline
  shell/app/configForm/nusi-form/form-editor.scss
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/common/types/common.d.ts
  shell/app/modules/application/common/yml-editor/pipeline-editor.tsx
  shell/app/modules/application/pages/pipeline/config-detail/pipeline-editor/index.tsx
  shell/app/modules/application/pages/pipeline/run-detail/pipeline-chart/index.tsx
  shell/app/modules/application/pages/repo/components/add-pipelineyml.tsx
  shell/app/modules/application/types/build.d.ts
  shell/app/modules/project/common/components/pipeline-manage/config-detail/pipeline-editor/index.tsx
  shell/app/modules/project/common/components/pipeline-manage/run-detail/pipeline-chart/index.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/editor.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/execute.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/in-params-form.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/index.tsx
  shell/app/modules/project/common/components/pipeline-new/list.tsx
  shell/app/modules/project/pages/pipelines/components/form.scss
  shell/app/modules/project/pages/pipelines/components/form.tsx
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
  shell/app/modules/project/pages/pipelines/components/records.tsx
  shell/app/modules/project/pages/pipelines/index copy.tsx
  shell/app/modules/project/pages/pipelines/index.scss
  shell/app/modules/project/services/pipeline.tsx
  shell/app/yml-chart/common/out-params-drawer.tsx
  shell/app/yml-chart/config.tsx
  shell/app/yml-chart/nodes/start-node.tsx
Labels: feature, dop, approved

#3319 fix: switch to execute page when pipeline exist
  shell/app/modules/project/common/components/pipeline-new/detail/editor.tsx
Labels: approved, bugfix

#3318 fix(dop): iteration tabs bug
  shell/app/modules/project/tabs.tsx
Labels: dop, bugfix

#3320 fix(msp): display nullDisplay when editing dashboard
  pnpm-lock.yaml
  shell/package.json
Labels: msp, bugfix

#3317 feat(dop): pipeline guides list optimization
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/pipeline-new/form.tsx
  shell/app/modules/project/common/components/pipeline-new/guide.tsx
  shell/app/modules/project/common/components/pipeline-new/index.tsx
  shell/app/modules/project/services/pipeline.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, dop

#3321 feat(msp): add creator in log rule page
  shell/app/modules/msp/services/log-analyze.ts
  shell/app/modules/msp/stores/log-analyze.ts
Labels: feature, msp

#3323 fix(dop): release labels optimization
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/deploy/add-deploy/index.tsx
  shell/app/modules/project/pages/release/components/application-detail.tsx
  shell/app/modules/project/pages/release/components/project-detail.tsx
  shell/app/modules/project/pages/settings/components/project-label.tsx
  shell/app/modules/project/types/release.d.ts
Labels: dop, bugfix

#3325 fix: fix scrollIntoView cause page move
  shell/app/common/components/edit-field/index.tsx
  shell/app/common/components/setting-tabs/index.tsx
  shell/app/common/components/switch-auto-scroll/index.tsx
  shell/app/configForm/form/form.tsx
  shell/app/modules/addonPlatform/pages/common/components/addon-card-list.tsx
  shell/app/modules/addonPlatform/pages/common/components/addon-cards.scss
  shell/app/modules/application/pages/repo/components/file-diff.tsx
  shell/app/modules/cmp/pages/cluster-manage/deploy-cluster-form.tsx
  shell/app/modules/project/common/components/issue/issue-activities.tsx
Labels: bugfix

#3322 fix: fix useUpdateSearch error
  core/src/stores/route.ts
  shell/app/common/__tests__/use-hook.test.tsx
  shell/app/common/use-hooks.tsx
  shell/app/common/utils/go-to.tsx
  shell/app/config-page/index.tsx
  shell/app/modules/project/pages/ticket/index.tsx
Labels: bugfix

#3326 fix: fix runtime domain setting style
  shell/app/modules/runtime/pages/overview/components/domain-modal.tsx
Labels: bugfix

#3328 fix: fix ticket request params error
  shell/app/modules/project/pages/ticket/index.tsx
Labels: dop, approved, bugfix

#3329 fix(dop): domain settings modal optimization
  shell/app/modules/project/pages/release/components/project-detail.tsx
  shell/app/modules/runtime/pages/overview/components/domain-modal.scss
  shell/app/modules/runtime/pages/overview/components/domain-modal.tsx
Labels: dop, approved, bugfix

#3330 fix: fix treemap chart tooltip disappear
  shell/app/config-page/components/chart/chart.tsx
Labels: dop, approved, bugfix

#3331 fix(dop): create release style bug
  shell/app/modules/project/pages/release/components/form.scss
  shell/app/modules/project/pages/release/components/form.tsx
Labels: dop, bugfix

#3332 fix(#3324): fix devlops side menu
  locales/en.json
  locales/zh.json
  shell/app/config-page/components/button/button.spec.d.ts
  shell/app/config-page/components/button/button.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/project.tsx
  shell/app/modules/apiManagePlatform/pages/access-manage/list/index.tsx
  shell/app/modules/project/common/config.js
  shell/app/modules/project/pages/auto-test/index.tsx
  shell/app/modules/project/pages/issue/gantt/index.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
  shell/app/modules/project/router.tsx
Labels: approved, bugfix

#3333 fix: fix breadcrumd error
  shell/app/layout/pages/page-container/components/breadcrumb.tsx
Labels: bugfix

#3335 feat: move init requests to node to optimize first page paint time
  core/src/utils/global-space.ts
  pnpm-lock.yaml
  scheduler/package.json
  scheduler/src/filters/not-found.filter.ts
  scheduler/src/proxy.ts
  scheduler/src/util.ts
  scheduler/tsconfig.json
  shell/app/App-vite.tsx
  shell/app/App.tsx
  shell/app/interface/common.d.ts
  shell/app/layout/pages/page-container/page-container.tsx
  shell/app/layout/stores/layout.ts
  shell/app/org-home/stores/org.tsx
  shell/app/views/index.ejs
Labels: feature, scheduler

#3337 fix(org): fix the org manage page style exception
  shell/app/views/index.ejs
  shell/index.html
Labels: bugfix

#3339 fix: devops side menu Collaboration translation
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/project.tsx
Labels: approved, bugfix

#3341 fix: add test log
  scheduler/src/filters/not-found.filter.ts
Labels: scheduler, approved, chore

#3343 fix: add test log
  scheduler/src/filters/not-found.filter.ts
Labels: feature, scheduler, approved, bugfix

#3345 fix: Invalid value "undefined" for header "cookie"
  scheduler/src/filters/not-found.filter.ts
Labels: scheduler, approved, bugfix

#3346 fix: api should remove orgName part in online mode
  scheduler/src/filters/not-found.filter.ts
Labels: scheduler, bugfix

#3347 fix: fix login referer and remove debug log
  scheduler/src/filters/not-found.filter.ts
Labels: scheduler, bugfix

#3349 chore: run unit test as needed
  .github/workflows/codecov.yml
Labels: approved, chore

#3350 fix(common): display null when src of image is empty in react-markdown
  shell/app/common/components/markdown-render/__tests__/index.test.tsx
  shell/app/common/components/markdown-render/index.tsx
Labels: bugfix

#3353 feat: replace the deprecated property of the progress
  package.json
  shell/app/modules/application/pages/test/test-list.tsx
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/pages/micro-service/overview.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
  shell/app/modules/project/common/components/issue/time-trace.tsx
Labels: feature, dop, msp

#3334 feat(dop): project pipeline edit source
  shell/app/common/components/render-form-item/index.tsx
  shell/app/config-page/components/table/v2/utils.tsx
  shell/app/modules/project/common/components/pipeline-new/form.tsx
  shell/app/modules/project/common/components/pipeline-new/index.tsx
  shell/app/modules/project/common/components/pipeline-new/list.tsx
  shell/app/modules/project/services/pipeline.tsx
Labels: feature, dop

#3344 fix: fix cmp table filter
  locales/en.json
  shell/app/modules/cmp/common/alarm-record/index.tsx
  shell/app/modules/cmp/common/components/cluster-selector.tsx
  shell/app/modules/cmp/pages/domain-manage/index.tsx
  shell/app/modules/cmp/pages/tasks/task-list.tsx
  shell/app/modules/cmp/router.ts
  shell/app/modules/dcos/pages/cluster-dashboard/alarm-record.tsx
  shell/app/modules/dcos/pages/cluster-dashboard/instance-list.tsx
  shell/app/modules/dcos/pages/service-manager/index.jsx
  shell/app/modules/dcos/pages/service-manager/index.tsx
  shell/app/modules/dcos/pages/service-manager/service-list.tsx
Labels: cmp, bugfix

#3356 fix: add special org header and remove debug log
  erda.yml
  scheduler/src/filters/not-found.filter.ts
Labels: scheduler, bugfix

#3354 feat(common): internationalization-optimization
  locales/en.json
  locales/zh.json
  shell/app/antd-overwrite/button/index.tsx
  shell/app/common/components/dropdown-select-new/__tests__/index.test.tsx
  shell/app/common/components/dropdown-select-new/index.tsx
  shell/app/common/components/load-more-selector/index.tsx
  shell/app/common/components/menu/index.tsx
  shell/app/common/components/radio-tabs/__tests__/index.test.tsx
  shell/app/common/components/radio-tabs/index.tsx
  shell/app/common/utils/__tests__/index.test.tsx
  shell/app/common/utils/index.ts
  shell/app/layout/pages/page-container/components/header.tsx
  shell/app/layout/pages/page-container/components/sidebar/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/dop.tsx
  shell/app/modules/apiManagePlatform/pages/access-manage/detail/limit.tsx
  shell/app/modules/apiManagePlatform/pages/access-manage/detail/sla-editor.tsx
  shell/app/modules/apiManagePlatform/pages/access-manage/edit/index.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/components/apply-modal.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/components/asset-modal.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/components/relation.tsx
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
  shell/app/modules/cmp/common/alarm-strategy/trigger-condition-select.tsx
  shell/app/modules/cmp/common/custom-alarm/index.tsx
  shell/app/modules/cmp/common/custom-dashboard/index.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-terminal.tsx
  shell/app/modules/cmp/pages/cluster-manage/index.tsx
  shell/app/modules/cmp/pages/computing/ecs/index.tsx
  shell/app/modules/cmp/router.ts
  shell/app/modules/msp/alarm-manage/index.ts
  shell/app/modules/org/pages/certificate/index.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/org/router.ts
  shell/app/modules/project/common/components/datasource-selector.tsx
  shell/app/modules/project/common/components/params-config/index.tsx
  shell/app/modules/project/common/components/pipeline-manage/config-detail/pipeline-editor/case-tree-selector.tsx
  shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx
  shell/app/modules/project/pages/deploy/deploy-detail/index.tsx
  shell/app/modules/publisher/pages/publisher-manage/publisher-form-modal.tsx
  shell/babel.config.js
Labels: feature, approved

#3359 fix(common): log search params missing
  shell/app/common/components/simple-log/__tests__/simple-log-search.test.tsx
  shell/app/common/components/simple-log/__tests__/simple-log.test.tsx
  shell/app/common/components/simple-log/simple-log-search.tsx
  shell/app/config-page/components/table/v2/utils.tsx
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
Labels: msp, approved, bugfix

#3362 feat(msp): replace antd Pagination with erda Pagination
  shell/app/modules/msp/monitor/error-insight/pages/errors/error-overview.tsx
Labels: feature, msp

#3361 fix: internationalization loss in zh.json
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
Labels: bugfix

#3360 feat(dop): show function classname in unit test result
  shell/app/modules/application/pages/test/test-detail.tsx
Labels: feature, dop

#3357 feat(dop): display all MR types count in MR requests page
  shell/app/modules/application/pages/repo/repo-mr.tsx
  shell/app/modules/application/services/repo.ts
  shell/app/modules/application/stores/repo.ts
  shell/app/modules/application/types/repo.d.ts
Labels: feature, dop

#3342 fix(common): top tabs style bug
  shell/app/common/components/crud-table/index.tsx
  shell/app/common/components/members-table/__tests__/index.test.tsx
  shell/app/common/components/members-table/index.tsx
  shell/app/common/components/menu/__tests__/index.test.tsx
  shell/app/common/components/menu/index.tsx
  shell/app/common/components/top-button-group/__tests__/index.test.tsx
  shell/app/common/components/top-button-group/index.tsx
  shell/app/common/index.ts
  shell/app/config-page/components/container/container.tsx
  shell/app/layout/pages/page-container/components/header.tsx
  shell/app/layout/stores/layout.ts
  shell/app/modules/apiManagePlatform/pages/access-manage/detail/index.tsx
  shell/app/modules/apiManagePlatform/pages/access-manage/list/index.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/design/index.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/detail/index.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/list/index.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/version/index.tsx
  shell/app/modules/application/pages/build/build.tsx
  shell/app/modules/application/pages/problem/problem-list.tsx
  shell/app/modules/application/pages/repo/mr-detail.tsx
  shell/app/modules/application/pages/repo/repo-backup.tsx
  shell/app/modules/application/pages/repo/repo-mr.tsx
  shell/app/modules/application/pages/repo/repo-tag.tsx
  shell/app/modules/application/pages/repo/repo-tree.tsx
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
  shell/app/modules/cmp/common/custom-alarm/index.tsx
  shell/app/modules/cmp/common/custom-dashboard/index.tsx
  shell/app/modules/cmp/pages/alarm-report/index.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-event-log.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-nodes.tsx
  shell/app/modules/cmp/pages/cluster-manage/index.tsx
  shell/app/modules/cmp/pages/computing/ecs/index.tsx
  shell/app/modules/cmp/pages/networks/vpc/index.tsx
  shell/app/modules/msp/alarm-manage/overview/base-overview.tsx
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/env-setting/configuration/index.tsx
  shell/app/modules/msp/monitor/status-insight/pages/status/status.tsx
  shell/app/modules/org/pages/announcement/index.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/org/pages/safety/index.tsx
  shell/app/modules/project/pages/addon/addon-category.tsx
  shell/app/modules/project/pages/apps/app-list.tsx
  shell/app/modules/project/pages/data-source/index.tsx
  shell/app/modules/project/pages/issue/board.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
  shell/app/modules/project/pages/iteration/table.tsx
  shell/app/modules/project/pages/milestone/index.tsx
  shell/app/modules/project/pages/plan-detail/index.tsx
  shell/app/modules/project/pages/release/release-protocol.tsx
  shell/app/modules/project/pages/test-env/test-env.tsx
  shell/app/modules/project/pages/test-plan/test-plan.tsx
  shell/app/modules/project/pages/test-report/create.tsx
  shell/app/modules/project/pages/test-report/download.tsx
  shell/app/modules/project/pages/ticket/index.tsx
  shell/app/modules/publisher/pages/artifacts/index.tsx
  shell/app/modules/publisher/pages/publisher-manage/publisher-list-v2.tsx
  shell/app/modules/runtime/pages/overview/components/info.tsx
  shell/app/styles/util.scss
  shell/app/user/common/perm-editor/perm-editor.tsx
Labels: approved, bugfix

#3358 fix(common): tags tooltip background color optimization
  shell/app/common/components/tags-row/index.scss
  shell/app/common/components/tags/index.scss
Labels: bugfix

#3355 fix(dop): click menu after switch project bug
  shell/app/modules/project/stores/project.tsx
Labels: dop, approved, bugfix

#3363 feat(dop): create release filter add tags
  shell/app/modules/project/pages/release/components/release-select.tsx
Labels: feature, dop, approved

#3366 feat(cmp): force cluster offline
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
  shell/app/modules/cmp/services/machine.ts
Labels: feature, cmp, approved

#3365 fix(msp): compatible with null eventIds
  shell/app/modules/msp/monitor/error-insight/stores/error.ts
Labels: msp, approved, bugfix

#3367 fix: init org access data is wrong
  scheduler/src/filters/not-found.filter.ts
Labels: scheduler, approved, bugfix

#3370 fix(common): table actions color optimization
  shell/app/common/components/table/index.tsx
  shell/app/config-page/components/table/render-types.tsx
  shell/app/config-page/components/table/v2/utils.tsx
Labels: bugfix

#3371 fix: auto redirect to root page bug
  shell/app/org-home/stores/org.tsx
Labels: bugfix

#3369 feat: add dice yml job edit
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/common/components/dice-job-node.scss
  shell/app/modules/application/common/components/dice-job-node.tsx
  shell/app/modules/application/common/components/dice-service-node.scss
  shell/app/modules/application/common/components/dice-service-node.tsx
  shell/app/modules/application/common/components/dice-service-view.tsx
  shell/app/modules/application/common/components/dice-yaml-editor-item.tsx
  shell/app/modules/application/common/components/dice-yaml-editor-type.ts
  shell/app/modules/application/common/components/dice-yaml-editor.tsx
  shell/app/modules/application/common/components/edit-service.scss
  shell/app/modules/application/common/components/edit-service.tsx
  shell/app/modules/application/common/components/edit-stage.tsx
  shell/app/modules/application/common/depends-on-data-filter.ts
  shell/app/modules/application/common/dice-flow-util.ts
  shell/app/modules/application/common/dice-yml-data-convert.tsx
  shell/app/modules/application/pages/repo/components/yml-editor.tsx
Labels: feature, dop, approved

#3372 fix: fix yml file editor file extension error
  shell/app/modules/application/common/yml-editor/pipeline-editor.tsx
  shell/app/yml-chart/pipeline-editor.tsx
Labels: approved, bugfix

#3373 feat(msp): replace antd Pagination with Pagination
  shell/app/common/components/pagination/__tests__/index.test.tsx
  shell/app/common/components/pagination/index.tsx
Labels: feature, msp, approved

#3374 fix: fix runtime detail menu fold icon error
  shell/app/modules/runtime/pages/overview/components/index.tsx
Labels: approved, bugfix

#3368 feat(common): introduce erda-ui components
  pnpm-lock.yaml
  shell/app/App-vite.tsx
  shell/app/App.tsx
  shell/mf.config.js
  shell/package.json
  shell/webpack.config.js
Labels: feature, approved

#3376 fix: fix first login page unLoad
  shell/app/App.tsx
Labels: bugfix

#3377 fix(common): fix vite can't start issue
  shell/app/App-vite.tsx
  shell/vite.config.js
Labels: approved, bugfix

#3379 fix(msp): fix styling issues caused by upgrading TopButtonGroup
  shell/app/modules/msp/alarm-manage/overview/base-overview.tsx
Labels: msp, approved, bugfix

#3383 feat(common): update pkg version
  pnpm-lock.yaml
  shell/package.json
Labels: feature, approved, bugfix

#3380 fix(cmp): get useable k8s clusters interface optimization
  shell/app/modules/cmp/stores/cluster.ts
Labels: cmp, bugfix

#3384 fix: show iteration synchronously tip when update iteration success
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
Labels: bugfix

#3378 feat(dop): replace antdTable with erdaTable
  shell/app/modules/org/pages/announcement/index.tsx
  shell/app/modules/org/pages/projects/issue-field-manage.tsx
  shell/app/modules/org/pages/safety/index.tsx
  shell/app/modules/org/router.ts
Labels: feature, dop, approved

#3385 fix(#3382): fix please enter in i18n
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/config-page/components/api-editor/api-editor.tsx
  shell/app/configForm/nusi-form/form-items/array-obj.tsx
  shell/app/configForm/nusi-form/form-items/inputNumber.tsx
  shell/app/configForm/nusi-form/form-items/map.tsx
  shell/app/configForm/nusi-form/form-items/textarea.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/components/api-resource/resource.tsx
  shell/app/modules/application/pages/repo/components/add-pipelineyml.tsx
  shell/app/modules/application/pages/settings/components/app-info.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-terminal.tsx
  shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
  shell/app/modules/cmp/pages/domain-manage/index.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
  shell/app/modules/org/common/cluster-quota.tsx
  shell/app/modules/org/common/field-options-setting.tsx
  shell/app/modules/org/pages/projects/issue-field-modal.tsx
  shell/app/modules/org/pages/projects/settings/info/index.tsx
  shell/app/modules/project/common/components/issue/text-field-input.tsx
  shell/app/modules/project/common/components/params-config/list-edit.tsx
  shell/app/modules/project/common/components/pipeline-new/form.tsx
  shell/app/modules/project/common/components/workflow-state-form.tsx
  shell/app/modules/project/pages/release/components/application-detail.tsx
  shell/app/modules/project/pages/release/components/form.tsx
  shell/app/modules/project/pages/settings/components/project-info.tsx
  shell/app/modules/publisher/pages/statistics/index.tsx
  shell/app/org-home/pages/land/index.tsx
  shell/app/yml-chart/common/out-params-drawer.tsx
Labels: bugfix

#3389 fix: fix node request header error
  scheduler/src/filters/not-found.filter.ts
Labels: bugfix

#3392 fix(scheduler): fix get org access issue
  scheduler/src/filters/not-found.filter.ts
Labels: scheduler, approved, bugfix

#3390 fix: fix table user type error
  shell/app/config-page/components/table/v2/table.tsx
  shell/app/config-page/components/table/v2/utils.tsx
Labels: approved, bugfix

#3394 feat(dop): add filter_pod_uid for query containerNet
  shell/app/modules/msp/monitor/monitor-common/components/resource-usage/resource-usage-charts.tsx
  shell/app/modules/runtime/types/service.d.ts
Labels: feature, dop

#3395 feat(dop): internationalization optimization in test management
  locales/en.json
  locales/zh.json
  shell/app/common/components/batch-operation/__tests__/index.test.tsx
  shell/app/common/components/batch-operation/index.tsx
  shell/app/common/components/file-editor/index.tsx
  shell/app/common/components/member-selector/index.tsx
  shell/app/common/components/members-table/__tests__/index.test.tsx
  shell/app/config-page/components/base-list/base-list.tsx
  shell/app/config-page/components/table/table.tsx
  shell/app/config-page/components/table/v2/table.tsx
  shell/app/configForm/editor/form-editor.tsx
  shell/app/configForm/nusi-form/form-items/input.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/addonPlatform/pages/common/components/addon-cards.tsx
  shell/app/modules/application/pages/build-detail/pipeline-log.tsx
  shell/app/modules/application/pages/pipeline/run-detail/pipeline-log.tsx
  shell/app/modules/application/pages/pipeline/scope-config.tsx
  shell/app/modules/project/common/components/pipeline-manage/run-detail/pipeline-chart/run-case-node.tsx
  shell/app/modules/project/common/components/pipeline-manage/scope-config.tsx
  shell/app/modules/project/pages/auto-test/import-file.tsx
  shell/app/modules/project/pages/plan-detail/batch-processing/index.tsx
  shell/app/modules/project/pages/plan-detail/common-comp.tsx
  shell/app/modules/project/pages/plan-detail/index.tsx
  shell/app/modules/project/pages/plan-detail/report/basic-info/index.tsx
  shell/app/modules/project/pages/plan-detail/report/index.tsx
  shell/app/modules/project/pages/plan-detail/report/personal-usecase/index.tsx
  shell/app/modules/project/pages/test-env/test-env-detail.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
  shell/app/modules/project/pages/test-manage/case/columns/index.tsx
  shell/app/modules/project/pages/test-manage/case/header/batch-processing/index.tsx
  shell/app/modules/project/pages/test-manage/case/import-export.tsx
  shell/app/modules/project/pages/test-plan/plan-modal.tsx
  shell/app/modules/project/pages/test-plan/test-plan.tsx
  shell/app/yml-chart/nodes/add-node.tsx
Labels: feature, dop, approved

#3396 fix(dop): issue detail style bug
  shell/app/modules/project/pages/backlog/issue-item.tsx
Labels: dop, approved, bugfix

#3398 fix(msp): correct update time with edgeNow in dashboard list
  shell/app/modules/cmp/common/custom-dashboard/index.tsx
Labels: msp, approved, bugfix

#3403 fix: cookie on request maybe undefined
  scheduler/src/filters/not-found.filter.ts
Labels: scheduler, approved, bugfix

#3401 fix: fix avatar img error
  shell/app/antd-overwrite/avatar/index.tsx
Labels: approved, bugfix

#3406 fix: fix support user access error in unjoined org
  scheduler/src/filters/not-found.filter.ts
  shell/app/org-home/stores/org.tsx
Labels: bugfix

#3408 fix: fix iteration sync error
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
Labels: approved, bugfix

#3411 fix: fix support access in vite
  shell/app/App-vite.tsx
Labels: approved, bugfix

#3414 feat(dop): internationalization optimization in project pipeline
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/pipeline-new/form.tsx
  shell/app/modules/project/common/components/pipeline-new/guide.tsx
Labels: feature, dop, approved

#3413 feat(dop): fixed moment locale issue in vite mode
  shell/app/App-vite.tsx
Labels: feature, dop

#3418 fix: fix api test action select style error
  shell/app/modules/dop/pages/form-editor/components/api-test.tsx
Labels: approved, bugfix

#3420 feat(dop): deploy runtime detail breadcrumb optimization
  shell/app/locales/utils.ts
  shell/app/modules/application/router.ts
  shell/app/modules/project/router.tsx
Labels: feature, dop

#3419 feat(dop): project collaboration menu optimization
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/project.tsx
  shell/app/modules/project/router.tsx
  shell/app/modules/project/tabs.tsx
Labels: feature, dop

#3422 fix: fix invite to org error
  shell/app/config-page/components/file-tree/file-tree.tsx
  shell/app/config-page/components/sort-drag-group/pure-sort-drag-group-list/index.tsx
  shell/app/layout/pages/page-container/components/org-selector.tsx
  shell/app/layout/pages/page-container/layout.tsx
  shell/app/org-home/stores/org.tsx
Labels: approved, bugfix

#3424 fix: fix access error when switch org
  shell/app/App.tsx
  shell/app/org-home/stores/org.tsx
  shell/app/user/stores/permission.ts
Labels: approved, bugfix

#3426 fix: fix announcement request timing
  shell/app/App-vite.tsx
  shell/app/App.tsx
  shell/app/org-home/stores/org.tsx
Labels: bugfix

#3428 fix: table sort not work
  shell/app/common/components/details-panel/index.tsx
  shell/app/common/components/table/__tests__/index.test.tsx
  shell/app/common/components/table/index.tsx
Labels: bugfix

#3410 feat(dop): create deploy add tags filter
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/modules/project/pages/deploy/add-deploy/add-release.scss
  shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx
  shell/app/modules/project/pages/deploy/add-deploy/release-list.tsx
  shell/app/modules/project/pages/release/components/release-select.tsx
Labels: feature, dop, approved

#3433 feat: update issue template
  shell/app/modules/project/common/issue-config.ts
Labels: feature

#3417 Feature/create project release filter optimization
  shell/app/modules/project/pages/release/components/release-select.tsx
  shell/app/modules/project/services/release.ts
  shell/app/modules/project/stores/release.ts
Labels: approved

#3437 fix(dop): fix setting page collapse
  shell/app/common/utils/i18n-replace-link.tsx
  shell/app/modules/application/pages/settings/app-settings.tsx
  shell/app/modules/org/pages/projects/settings/member/index.tsx
  shell/app/modules/org/pages/setting/org-setting.tsx
  shell/app/modules/project/pages/release/components/release-select.tsx
  shell/app/modules/project/pages/settings/components/project-settings.tsx
Labels: dop, approved, bugfix

#3438 fix: links duplicate & links translation miss "[]"
  locales/zh.json
  shell/app/modules/application/pages/settings/app-settings.tsx
  shell/app/modules/org/pages/projects/settings/member/index.tsx
  shell/app/modules/org/pages/setting/org-setting.tsx
  shell/app/modules/project/pages/settings/components/project-settings.tsx
Labels: approved, bugfix

#3439 feat(dop): create deploy release list add tags
  shell/app/modules/project/pages/deploy/add-deploy/release-list.tsx
  shell/app/modules/project/types/deploy.d.ts
Labels: feature, dop, approved

#3440 fix: run erda-ui i18n
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
Labels: bugfix
