Repository erda-project/erda-ui, pull requests merged in 2022-07, with the labels that each got.

#3652 feat: devops workflow setting refactor
  locales/en.json
  locales/zh.json
  shell/app/common/components/empty-holder/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/workflow/add-flow.tsx
  shell/app/modules/project/common/components/workflow/index.tsx
  shell/app/modules/project/common/components/workflow/issue-workflow.tsx
  shell/app/modules/project/pages/backlog/issue-item.tsx
  shell/app/modules/project/pages/deploy/index.tsx
  shell/app/modules/project/pages/settings/components/project-settings.tsx
  shell/app/modules/project/pages/settings/components/project-workflow.tsx
  shell/app/modules/project/pages/settings/components/workflow-setting/branch-policy-card.tsx
  shell/app/modules/project/pages/settings/components/workflow-setting/branch-policy.tsx
  shell/app/modules/project/pages/settings/components/workflow-setting/devops-workflow-drawer.tsx
  shell/app/modules/project/pages/settings/components/workflow-setting/devops-workflow.tsx
  shell/app/modules/project/pages/settings/components/workflow-setting/line.tsx
  shell/app/modules/project/services/project-workflow.ts
  shell/app/modules/project/types/devops-workflow.d.ts
Labels: feature, dop, refactor

#3653 feat(dop): elastic sacaling
  core/src/service/index.ts
  modules/components/src/form/index.tsx
  modules/components/src/form/utils.tsx
  modules/components/src/table/index.tsx
  modules/components/src/table/interface.ts
  modules/components/src/table/utils.tsx
  pnpm-lock.yaml
  shell/app/modules/runtime/pages/overview/components/elastic-scaling.scss
  shell/app/modules/runtime/pages/overview/components/elastic-scaling.tsx
  shell/app/modules/runtime/pages/overview/components/service-card.tsx
  shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
  shell/app/modules/runtime/services/runtime.ts
  shell/app/modules/runtime/types/runtime.d.ts
  shell/app/modules/runtime/types/service.d.ts
  shell/package.json
Labels: feature, dop, approved

#3654 fix: hide loading when asyncAtInit in Config-page
  shell/app/config-page/index.tsx
Labels: bugfix

#3657 fix: fix branch policy valid error
  shell/app/modules/project/pages/settings/components/workflow-setting/branch-policy-card.tsx
  shell/app/modules/project/pages/settings/components/workflow-setting/branch-policy.tsx
Labels: bugfix

#3656 feat(shell): pipeline node show config info
  locales/en.json
  locales/zh.json
  shell/app/common/types/pipeline.d.ts
  shell/app/modules/application/pages/obsoleted-pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/run-detail/build-log.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/run-detail/pipeline-chart/pipeline-node.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/build-log.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/execute.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/pipeline-chart/pipeline-node.tsx
  shell/app/modules/runtime/pages/overview/components/elastic-scaling.tsx
  shell/app/modules/runtime/pages/overview/components/service-card.tsx
  shell/app/modules/runtime/services/runtime.ts
Labels: feature, approved

#3658 fix(dop): minor fix for elastic scale
  shell/app/modules/runtime/pages/overview/components/elastic-scaling.tsx
Labels: dop, approved, bugfix

#3659 feat: add devops workflow mr step
  shell/app/common/utils/go-to.tsx
  shell/app/modules/project/common/components/issue/add-mr-relation.tsx
  shell/app/modules/project/common/components/issue/issue-activities.tsx
  shell/app/modules/project/common/components/workflow/add-flow.tsx
  shell/app/modules/project/common/components/workflow/cards/base.tsx
  shell/app/modules/project/common/components/workflow/cards/code.tsx
  shell/app/modules/project/common/components/workflow/cards/merge-request.tsx
  shell/app/modules/project/common/components/workflow/cards/merge.tsx
  shell/app/modules/project/common/components/workflow/cards/pipeline.tsx
  shell/app/modules/project/common/components/workflow/index.tsx
  shell/app/modules/project/types/devops-workflow.d.ts
Labels: feature, dop

#3661 fix(dop): elastic scale issue fix
  modules/components/src/form/utils.tsx
  shell/app/modules/runtime/pages/overview/components/elastic-scaling.tsx
Labels: dop, approved, bugfix

#3662 fix(dop): fix elastic scale issue
  shell/app/modules/runtime/pages/overview/components/elastic-scaling.tsx
Labels: dop, approved, bugfix

#3660 feat(dop): optimize devops workflow setting
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/workflow/add-flow.tsx
  shell/app/modules/project/common/components/workflow/cards/merge.tsx
  shell/app/modules/project/pages/settings/components/workflow-setting/branch-policy.tsx
  shell/app/modules/project/pages/settings/components/workflow-setting/devops-workflow.tsx
Labels: feature, dop

#3663 feat(dop): i18n for elastic scale
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/runtime/pages/overview/components/elastic-scaling.tsx
Labels: feature, dop, approved

#3664 fix(uc): fix uc redirect url / redirect safety
  modules/uc/src/common/utils.tsx
  modules/uc/src/index.js
  modules/uc/src/ory/index.tsx
  modules/uc/src/pages/login/index.tsx
  scheduler/src/filters/not-found.filter.ts
  shell/app/App-vite.tsx
  shell/app/user/stores/index.ts
  shell/app/user/types/user.d.ts
Labels: bugfix

#3665 feat(msp): add log regexp parse service
  shell/app/modules/msp/services/log-analyze.ts
Labels: feature, msp

#3666 fix(dop): fix elastic scale form issue
  shell/app/modules/runtime/pages/overview/components/elastic-scaling.scss
  shell/app/modules/runtime/pages/overview/components/elastic-scaling.tsx
Labels: dop, approved, bugfix

#3667 feat(dop): optimize elastic scale
  locales/en.json
  locales/zh.json
  modules/components/src/form/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/runtime/pages/overview/components/elastic-scaling.tsx
Labels: feature, dop

#3668 fix(dop): fix devops commit empty error
  shell/app/modules/project/common/components/workflow/add-flow.tsx
  shell/app/modules/project/common/components/workflow/cards/merge-request.tsx
  shell/app/modules/project/common/components/workflow/cards/merge.tsx
  shell/app/modules/project/common/components/workflow/cards/pipeline.tsx
Labels: dop, approved, bugfix

#3669 fix(dop): enable disable node func
  modules/market/src/pages/download.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/obsoleted-pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/run-detail/pipeline-chart/pipeline-node.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/execute.tsx
  shell/app/modules/runtime/pages/overview/components/elastic-scaling.tsx
Labels: dop, approved, bugfix

#3670 fix: fix timespan refresh when init
  shell/app/modules/cmp/pages/cluster-container/cluster-nodes-detail.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-pod-detail.tsx
  shell/app/modules/publisher/pages/statistics/detail.tsx
  shell/app/modules/publisher/pages/statistics/index.tsx
Labels: bugfix

#3672 feat: add pipeline in build page
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/config-page/components/base-list/base-list.tsx
  shell/app/config-page/components/dropdown/dropdown.tsx
  shell/app/config-page/components/list-new/list/list-item.tsx
  shell/app/config-page/components/list/list.tsx
  shell/app/config-page/components/table/render-types.tsx
  shell/app/config-page/components/table/table.tsx
  shell/app/config-page/components/table/v2/table.tsx
  shell/app/config-page/components/table/v2/utils.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/common/yml-flow-util.ts
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/common/components/pipeline-new/form.scss
  shell/app/modules/project/common/components/pipeline-new/form.tsx
  shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx
Labels: feature

#3673 fix: fix pipeline create error
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/pipeline-new/form.tsx
Labels: bugfix

#3674 feat(common): add tab & pop component hook
  shell/app/common/use-hooks.tsx
  shell/app/common/utils/go-to.tsx
  shell/app/modules/application/pages/problem/problem-list.tsx
  shell/app/modules/application/pages/quality/entry.tsx
  shell/app/modules/application/pages/quality/index.scss
  shell/app/modules/application/pages/quality/index.tsx
  shell/app/modules/application/pages/test/test-list.tsx
Labels: feature, approved

#3675 feat(dop): show target brach base on branch policy
  shell/app/modules/application/pages/repo/components/source-target-select.tsx
Labels: feature, dop, approved

#3676 feat(dop): devops workflow optimize
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/workflow/add-flow.tsx
  shell/app/modules/project/common/components/workflow/index.scss
  shell/app/modules/project/common/components/workflow/index.tsx
  shell/app/modules/project/pages/settings/components/workflow-setting/branch-policy-card.tsx
  shell/app/modules/project/pages/settings/components/workflow-setting/branch-policy.tsx
  shell/app/modules/project/pages/settings/components/workflow-setting/devops-workflow-drawer.tsx
Labels: feature, dop

#3678 fix: fix pipeline record params
  shell/app/modules/project/common/components/pipeline-new/list.tsx
  shell/app/modules/project/services/pipeline.tsx
Labels: dop, bugfix

#3677 feat: add string auto formatter
  shell/app/common/utils/index.ts
  shell/app/config-page/components/table/render-types.tsx
  shell/app/config-page/components/table/v2/utils.tsx
Labels: feature

#3680 fix: fix pipeline record params
  shell/app/modules/project/common/components/pipeline-new/list.tsx
Labels: dop, bugfix

#3679 feat(dop): add cron editor
  locales/en.json
  locales/zh.json
  modules/components/src/form/interface.ts
  modules/components/src/form/utils.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/runtime/pages/overview/components/elastic-scaling.tsx
  shell/app/modules/runtime/types/runtime.d.ts
Labels: feature, dop, approved

#3681 fix: fix pipeline create form init error
  shell/app/modules/project/common/components/pipeline-new/form.tsx
Labels: bugfix

#3682 fix: fix time format
  shell/app/common/utils/index.ts
Labels: bugfix

#3683 fix: firefox popover style compatible
  shell/app/modules/project/pages/settings/components/workflow-setting/devops-workflow.tsx
Labels: bugfix

#3685 fix: fix api orgs header
  scheduler/src/filters/not-found.filter.ts
Labels: approved, bugfix

#3686 fix: fix org joined list
  shell/app/App-vite.tsx
  shell/app/common/utils/__tests__/index.test.tsx
  shell/app/common/utils/index.ts
  shell/app/org-home/pages/land/index.tsx
  shell/app/org-home/services/org.tsx
  shell/app/org-home/stores/org.tsx
Labels: approved, bugfix

#3687 fix(dop): fix cron issue
  scheduler/src/controllers/linkS-token.controller.ts
  scheduler/src/filters/not-found.filter.ts
  shell/app/App.tsx
  shell/app/links-service.ts
  shell/app/modules/runtime/pages/overview/components/elastic-scaling.tsx
  shell/app/org-home/stores/org.tsx
Labels: dop, approved, bugfix

#3688 feat(common): add csp for links
  shell/app/views/index.ejs
Labels: feature, approved

#3689 fix(common): add 'unsafe-inline'
  shell/app/views/index.ejs
Labels: approved, bugfix

#3690 fix(common): add csp policy
  shell/app/views/index.ejs
Labels: approved, bugfix

#3691 fix(common): add csp policy
  shell/app/views/index.ejs
Labels: approved, bugfix

#3692 fix(common): add csp policy
  shell/app/views/index.ejs
Labels: approved, bugfix

#3693 feat: add pipeline trigger info
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/types/build.d.ts
  shell/app/modules/project/common/components/pipeline-new/detail/execute.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/info.tsx
  shell/app/modules/project/common/components/pipeline-new/list.tsx
  shell/app/modules/project/common/components/pipeline-new/record-detail.tsx
  shell/app/modules/project/services/pipeline.tsx
Labels: feature, dop, bugfix

#3695 fix: api domain header
  scheduler/src/filters/not-found.filter.ts
Labels: bugfix

#3694 fix(common): fix logger crash issue
  shell/app/common/components/pure-log-roller/__tests__/log-roller.test.tsx
  shell/app/common/components/pure-log-roller/index.ts
  shell/app/common/components/pure-log-roller/log-roller.tsx
  shell/app/links-service.ts
  shell/app/org-home/stores/org.tsx
Labels: approved, bugfix

#3696 fix: fix domain header in proxy
  scheduler/src/proxy.ts
Labels: bugfix

#3698 fix: fix local domain header
  scheduler/src/proxy.ts
Labels: bugfix

#3697 feat(dop): add elastic sacling text
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/backlog/backlog.tsx
  shell/app/modules/project/pages/backlog/iteration-item.tsx
  shell/app/modules/project/pages/issue/board.tsx
  shell/app/modules/project/pages/issue/gantt/index.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
  shell/app/modules/project/pages/milestone/index.tsx
  shell/app/modules/runtime/pages/overview/components/service-card.tsx
  shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
Labels: feature, dop, approved

#3699 fix: fix openapi addr
  erda.yml
Labels: approved, bugfix

#3700 feat: add flow records
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/flow/records.tsx
  shell/app/modules/project/router.tsx
Labels: feature, dop, approved

#3703 fix(common): support 360 browser
  core/package.json
  modules/market/package.json
  modules/uc/package.json
  pnpm-lock.yaml
  shell/package.json
Labels: approved, bugfix

#3702 feat: optimize service-generator
  cli/lib/service-generator.ts
Labels: feature

#3704 feat(dop): change links api
  shell/app/links-service.ts
Labels: feature, dop, approved

#3706 fix: addon key duplicate
  shell/app/common/components/cards-layout/index.tsx
  shell/app/modules/addonPlatform/pages/common/components/addon-cards.tsx
Labels: dop, bugfix

#3705 feat: issue table row highlight
  shell/app/common/components/table/index.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
Labels: feature, dop

#3707 fix: fix admin joined org error
  scheduler/src/filters/not-found.filter.ts
Labels: bugfix

#3708 feat(dop): add k8s Restriction for elastic scale
  shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
Labels: feature, dop

#3710 feat: add requirement flow in todolist
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/pages/backlog/issue-item.scss
  shell/app/modules/project/pages/backlog/issue-item.tsx
Labels: feature, dop

#3711 feat(dop): avoid mistake close editing content
  shell/app/common/components/edit-field/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/pages/issue/board.tsx
Labels: feature, dop, approved

#3712 fix: fix pipeline record refresh
  shell/app/common/utils/index.ts
  shell/app/modules/project/common/components/pipeline-new/list.tsx
Labels: dop, bugfix

#3713 fix: fix cmp addon data empty error
  shell/app/modules/cmp/pages/middleware-dashboard/usage-chart.tsx
Labels: cmp, bugfix

#3714 fix: fix requirement flow request error
  shell/app/modules/project/pages/backlog/issue-item.tsx
Labels: dop, bugfix

#3715 fix: fix pipeline input group form value type
  shell/app/modules/application/common/components/list-input-group.tsx
Labels: dop, bugfix

#3716 fix: fix pipeline list input group change
  shell/app/modules/application/common/components/list-input-group.tsx
Labels: dop, bugfix

#3717 feat(dop): i18n
  locales/en.json
  locales/zh.json
Labels: feature, dop

#3718 fix(market): remove jingxuan
  modules/market/src/pages/download.tsx
Labels: approved, bugfix

#3720 fix: fix issue properties empty error
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
Labels: dop, approved, bugfix
