Repository erda-project/erda-ui, pull requests merged in 2022-03, with the labels that each got.

#3027 fix(dop): subscribers selector endless loop bug
  shell/app/modules/project/common/components/issue/subscribers-selector.tsx
Labels: dop, approved, bugfix

#3033 fix: fix k8s terminal line error
  shell/app/modules/cmp/common/cluster-terminal/xterm-binary.tsx
  shell/app/modules/cmp/common/cluster-terminal/xterm-channel.tsx
Labels: cmp, bugfix

#3031 feat: add audit tamplate for releaseRule
  shell/app/modules/org/common/audit-templates.json
Labels: feature

#3030 fix(dop): fix land page org list error
  shell/app/common/utils/__tests__/index.test.tsx
  shell/app/common/utils/index.ts
  shell/app/org-home/pages/land/index.tsx
  shell/app/org-home/services/org.tsx
  shell/app/org-home/stores/org.tsx
Labels: dop, bugfix

#3035 feat: add app deploy
  shell/app/common/utils/go-to.tsx
  shell/app/interface/global.d.ts
  shell/app/modules/application/router.ts
  shell/app/modules/application/tabs.tsx
  shell/app/modules/project/pages/deploy/index.tsx
  shell/app/modules/project/services/deploy.ts
  shell/app/modules/project/tabs.tsx
  shell/app/modules/runtime/stores/runtime.ts
Labels: feature, dop

#3040 fix: fix app deploy scenario key
  shell/app/modules/project/pages/deploy/index.tsx
Labels: dop, approved, bugfix

#3032 fix(cmp): i18n dashboard in O&M report
  pnpm-lock.yaml
  shell/app/modules/cmp/pages/alarm-report/report-records/index.tsx
  shell/package.json
Labels: cmp, bugfix

#3044 fix: fix app deploy filter style
  shell/app/modules/project/pages/deploy/index.tsx
Labels: dop, approved, bugfix

#3039 fix(dop): create release remove groups number limit
  shell/app/modules/project/pages/release/components/release-select.tsx
Labels: dop, approved, bugfix

#3043 fix: fix configurable filter only external fields
  shell/app/common/components/configurable-filter/index.tsx
Labels: approved, bugfix

#3048 fix: fix duplicate appId in deploy
  shell/app/modules/project/pages/deploy/index.tsx
Labels: dop, approved, bugfix

#3038 fix(common): configurable filter input value display bug
  shell/app/common/components/configurable-filter/index.tsx
Labels: approved, bugfix

#3049 fix: fix base list state update
  shell/app/config-page/components/base-list/base-list.tsx
Labels: approved, bugfix

#3055 feat: add org in land page for community
  shell/app/agent.js
  shell/app/common/utils/axios-config.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/org-home/pages/land/index.tsx
  shell/app/org-home/services/org.tsx
Labels: feature, approved

#3045 fix(msp): compatibility with old deployment center links
  shell/app/modules/msp/alarm-manage/alert-list/notification/base-notification-detail.tsx
  shell/app/modules/msp/alarm-manage/index.ts
Labels: msp, approved, bugfix

#3052 fix(dop): application list mr icon optimization
  shell/app/common/components/erda-icon/index.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: dop, approved, bugfix

#3053 fix(dop): project pipeline running number display bug after batch run
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
Labels: dop, approved, bugfix

#3057 fix: fix app pipeline refresh error
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
Labels: dop, approved, bugfix

#3060 fix(dop): update load-more-selector style
  shell/app/common/components/load-more-selector/index.scss
  shell/app/common/components/load-more-selector/index.tsx
Labels: dop, approved, bugfix

#3072 fix: fix community add org type
  shell/app/org-home/pages/land/index.tsx
Labels: approved, bugfix

#3071 fix(dop): update issue detail style
  shell/app/common/components/edit-field/index.tsx
  shell/app/common/components/table/interface.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
  shell/app/modules/project/common/components/issue/issue-testCase-relation.tsx
Labels: dop, approved, bugfix

#3074 feat(test): update jest config && add test case
  shell/app/common/components/addon-settings/__tests__/__snapshots__/index.test.tsx.snap
  shell/app/common/components/addon-settings/__tests__/index.test.tsx
  shell/app/common/components/circle-progress/index.scss
  shell/app/common/components/circle-progress/index.tsx
  shell/app/common/components/config-layout/__tests__/index.test.tsx
  shell/app/common/components/confirm-delete/index.tsx
  shell/app/common/components/delete-confirm/__tests__/index.test.tsx
  shell/app/common/components/error-boundary/__tests__/index.test.tsx
  shell/app/common/components/members-table/__tests__/__snapshots__/index.test.tsx.snap
  shell/app/common/components/menu/__tests__/index.test.tsx
  shell/app/common/components/simple-panel/__tests__/index.test.tsx
  shell/app/common/components/tags/__tests__/index.test.tsx
  shell/app/common/components/tags/index.tsx
  shell/app/common/components/time-select/__tests__/utils.test.tsx
  shell/app/common/components/time-select/time-select.tsx
  shell/app/common/components/time-select/utils.ts
  shell/app/common/components/title/__tests__/__snapshots__/index.test.tsx.snap
  shell/app/common/components/title/__tests__/index.test.tsx
  shell/app/common/components/user-info/__tests__/user-info.test.tsx
  shell/app/common/index.ts
  shell/app/common/stores/monitorCommon.ts
  shell/app/common/test_bak/components/compact-select.test.tsx
  shell/app/common/test_bak/components/delete-confirm.test.tsx
  shell/app/common/test_bak/components/error-boundary.test.tsx
  shell/app/common/test_bak/components/tiled-filter.test.tsx
  shell/app/common/test_bak/components/time-select/time-select.test.tsx
  shell/app/common/utils/__tests__/browser.test.tsx
  shell/app/config-page/components/tiled-filter/tiled-filter-comp.tsx
  shell/app/config-page/components/tiled-filter/tiled-filter.scss
  shell/app/config-page/components/tiled-filter/tiled-filter.tsx
  shell/app/modules/cmp/common/custom-dashboard/custom-dashboard.tsx
  shell/app/modules/cmp/stores/_common-custom-dashboard.ts
  shell/app/modules/extra/entry.js
  shell/app/modules/msp/components/card-list.tsx
  shell/app/modules/msp/components/time-select.tsx
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/env-overview/service-list/pages/transaction-detail.tsx
  shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx
  shell/app/modules/org/common/cluster-quota.tsx
  shell/app/modules/org/common/compact-select/index.scss
  shell/app/modules/org/common/compact-select/index.tsx
  shell/babel.config.js
  shell/jest.config.js
  shell/package.json
  shell/test/setupJest.ts
  shell/tsconfig-jest.json
Labels: feature, test

#3079 fix(dop): revert load more selector style
  shell/app/common/components/load-more-selector/index.scss
  shell/app/modules/extra/entry.js
Labels: dop, approved, bugfix

#3076 fix(dop): project pipeline id decoding mode change
  shell/app/modules/project/pages/pipelines/components/form.tsx
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
Labels: dop, approved, bugfix

#3077 fix(common): pipeline action and announcement scroll optimization
  shell/app/layout/pages/page-container/components/announcement/index.tsx
  shell/app/modules/application/pages/pipeline/run-detail/pipeline-chart/pipeline-node.scss
Labels: approved, bugfix

#3075 fix: fix avatar img load timeout。
  shell/app/antd-overwrite/avatar/index.tsx
  shell/app/config-page/mock/crud.mock.ts
  shell/app/layout/pages/page-container/components/navigation/user-menu.tsx
  shell/babel.config.js
  shell/mf.config.js
Labels: approved, bugfix

#3081 fix(dop): revert load more selector style (#3079)
  shell/app/common/components/load-more-selector/index.scss
Labels: dop, bugfix

#3085 feat(dop): update issue detail drawer style
  locales/en.json
  locales/zh.json
  shell/app/common/components/batch-operation/index.tsx
  shell/app/common/components/edit-field/index.scss
  shell/app/common/components/edit-field/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/issue/add-mr-relation.tsx
  shell/app/modules/project/common/components/issue/comment-box.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
  shell/app/modules/project/common/components/issue/issue-activities.scss
  shell/app/modules/project/common/components/issue/issue-activities.tsx
  shell/app/modules/project/common/components/issue/issue-drawer.scss
  shell/app/modules/project/common/components/issue/issue-drawer.tsx
  shell/app/modules/project/common/components/issue/issue-icon.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/common/components/issue/subscribers-selector.tsx
  shell/app/modules/project/pages/backlog/issue-item.tsx
  shell/app/styles/_color.scss
  shell/app/theme-color.mjs
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, dop, approved

#3084 fix(common): project setting quota table reload bug
  shell/app/modules/project/pages/settings/components/project-cluster.tsx
Labels: dop, approved, bugfix

#3087 fix(dop): update issue detail style
  shell/app/common/components/contractive-filter/index.tsx
  shell/app/common/components/edit-field/index.scss
  shell/app/common/components/edit-field/index.tsx
  shell/app/common/components/simple-tabs/index.scss
  shell/app/modules/project/common/components/issue/add-mr-relation.tsx
  shell/app/modules/project/common/components/issue/comment-box.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
  shell/app/modules/project/common/components/issue/issue-activities.tsx
  shell/app/modules/project/common/components/issue/issue-drawer.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/common/components/issue/issue-testCase-relation.tsx
  shell/app/modules/project/common/components/issue/subscribers-selector.tsx
  shell/app/modules/project/common/components/issue/text-field-input.tsx
  shell/app/modules/project/common/components/issue/time-input.scss
  shell/app/modules/project/common/components/issue/time-input.tsx
  shell/app/modules/project/pages/backlog/backlog.tsx
  shell/app/modules/project/pages/backlog/iteration-item.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, dop, bugfix

#3088 fix(dop): issue create relation style
  shell/app/common/components/edit-field/index.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/issue-drawer.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/pages/backlog/issue-item.tsx
Labels: dop, approved, bugfix

#3089 feat: update app tab order
  shell/app/modules/application/tabs.tsx
  shell/package.json
Labels: feature, approved

#3092 fix: fix list-my-application params error
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/common/app-list-protocol.tsx
  shell/app/modules/application/common/app-selector.tsx
  shell/app/modules/dop/pages/projects/block-comp.tsx
  shell/app/modules/project/common/components/issue/add-mr-relation.tsx
  shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx
  shell/app/modules/project/pages/deploy/deploy-config/index.tsx
  shell/app/user/services/user.ts
  shell/app/user/stores/index.ts
Labels: dop, approved, bugfix

#3054 fix(dop): project release detail back list optimization
  shell/app/common/utils/go-to.tsx
  shell/app/interface/global.d.ts
  shell/app/modules/project/pages/release/components/application-detail.tsx
  shell/app/modules/project/pages/release/components/form.tsx
  shell/app/modules/project/pages/release/components/project-detail.tsx
  shell/app/modules/project/router.tsx
Labels: dop, approved, bugfix

#3090 fix(dop): project release table reference release operation optimization
  shell/app/modules/project/pages/release/release-protocol.tsx
Labels: dop, approved, bugfix

#3094 fix(dop): pipeline action page error
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/yml-chart/common/pipeline-node-drawer.tsx
Labels: dop, approved, bugfix

#3093 feat(dop): project release detail add addons
  shell/app/modules/project/pages/release/components/addon.scss
  shell/app/modules/project/pages/release/components/addon.tsx
  shell/app/modules/project/pages/release/components/project-detail.tsx
  shell/app/modules/project/types/release.d.ts
Labels: dop, approved, bugfix

#3097 fix(dop): dop application list router remove
  shell/app/modules/dop/router.ts
Labels: dop, approved, bugfix

#3098 fix(common): fix title display exception
  shell/app/config-page/components/table/v2/utils.tsx
Labels: approved, bugfix

#3099 fix(dop): project release tabs change bug
  shell/app/modules/project/pages/release/release-protocol.tsx
Labels: dop, approved, bugfix

#3100 fix: fix cmp pods chart style
  shell/app/config-page/components/pie-chart/pie-chart.tsx
Labels: cmp, approved, bugfix

#3101 fix: Tree component support node item draggable
  shell/app/config-page/components/file-tree/file-tree.spec.d.ts
  shell/app/config-page/components/file-tree/file-tree.tsx
Labels: dop, approved, bugfix

#3086 feat: add config page parallel load
  shell/app/config-page/config-page.d.ts
  shell/app/config-page/index.tsx
  shell/app/config-page/page-render.tsx
Labels: feature, approved

#3102 feat(dop): issue detail v2 released :tada:
  locales/en.json
  locales/zh.json
  shell/app/antd-default-props.tsx
  shell/app/common/components/edit-field/index.scss
  shell/app/common/components/edit-field/index.tsx
  shell/app/common/components/markdown-editor/index.scss
  shell/app/common/components/markdown-editor/index.tsx
  shell/app/common/components/user-info/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/issue/add-mr-relation.tsx
  shell/app/modules/project/common/components/issue/comment-box.scss
  shell/app/modules/project/common/components/issue/comment-box.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/issue-activities.scss
  shell/app/modules/project/common/components/issue/issue-activities.tsx
  shell/app/modules/project/common/components/issue/issue-config.tsx
  shell/app/modules/project/common/components/issue/issue-drawer.scss
  shell/app/modules/project/common/components/issue/issue-drawer.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/pages/homepage/index.scss
  shell/app/modules/project/pages/homepage/readme-markdown.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, dop, approved

#3091 fix: update backend url tip and default value
  cli/lib/init.ts
  cli/package.json
Labels: cli, approved, bugfix

#3104 feat: update issue detail style
  shell/app/common/components/markdown-editor/index.scss
  shell/app/common/components/markdown-editor/index.tsx
  shell/app/modules/project/common/components/issue/add-mr-relation.tsx
  shell/app/modules/project/common/components/issue/comment-box.scss
  shell/app/modules/project/common/components/issue/comment-box.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
  shell/app/modules/project/common/components/issue/issue-activities.scss
  shell/app/modules/project/common/components/issue/issue-activities.tsx
  shell/app/modules/project/common/components/issue/issue-config.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/pages/backlog/issue-item.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, approved

#3103 feat: create release filter optimization
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/release/components/form.tsx
  shell/app/modules/project/pages/release/components/release-select.scss
  shell/app/modules/project/pages/release/components/release-select.tsx
  shell/app/modules/project/services/release.ts
  shell/app/modules/project/types/release.d.ts
Labels: feature, dop, approved

#3106 fix(common): table columns text with tags width adjustment
  .github/workflows/codecov.yml
  shell/app/common/components/tags-row/index.scss
  shell/app/config-page/components/table/table.scss
Labels: approved, bugfix

#3107 fix(dop): project release table double scroll bar bug
  shell/app/modules/project/pages/release/release-protocol.tsx
Labels: dop, approved, bugfix

#3105 fix(dop): pipeline action interface params add appId
  shell/app/yml-chart/common/action-config-form.tsx
Labels: dop, approved, bugfix

#3108 fix: fix icon tj1 is not exist
  shell/app/common/components/erda-icon/index.tsx
  shell/app/common/components/tags-row/__tests__/index.test.tsx
  shell/app/common/components/tags-row/index.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/project/pages/deploy/index.tsx
  shell/app/modules/project/pages/release/release-protocol.tsx
  shell/app/yml-chart/nodes/add-node.tsx
Labels: bugfix

#3110 fix(dop): create release empty image change
  shell/app/images/empty-white-bg.svg
  shell/app/modules/project/pages/release/components/release-select.tsx
Labels: dop, approved, bugfix

#3109 fix(common): configurable filter initial value bug
  shell/app/common/components/configurable-filter/index.tsx
Labels: dop, approved, bugfix

#3111 feat(dop): issue detail v3
  locales/en.json
  locales/zh.json
  shell/app/common/components/edit-field/index.scss
  shell/app/common/components/edit-field/index.tsx
  shell/app/common/components/markdown-editor/editor.tsx
  shell/app/common/components/markdown-editor/index.scss
  shell/app/common/components/markdown-editor/index.tsx
  shell/app/layout/stores/layout.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/issue/add-mr-relation.tsx
  shell/app/modules/project/common/components/issue/comment-box.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
  shell/app/modules/project/common/components/issue/issue-activities.scss
  shell/app/modules/project/common/components/issue/issue-activities.tsx
  shell/app/modules/project/common/components/issue/issue-config.tsx
  shell/app/modules/project/common/components/issue/issue-drawer.scss
  shell/app/modules/project/common/components/issue/issue-drawer.tsx
  shell/app/modules/project/common/components/issue/issue-relation.scss
  shell/app/modules/project/common/components/issue/issue-relation.tsx
Labels: feature, dop, approved

#3116 fix(dop): deploy detail applications display bug
  shell/app/modules/project/pages/release/components/release-select.tsx
Labels: dop, approved, bugfix

#3114 fix(common): configurable filter color optimization
  shell/app/common/components/configurable-filter/config-selector.scss
  shell/app/common/components/configurable-filter/config-selector.tsx
  shell/app/common/components/configurable-filter/index.scss
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
Labels: dop, bugfix

#3115 fix(dop): apply for deployment modal style bug
  shell/app/modules/application/common/app-selector.tsx
Labels: dop, bugfix

#3113 feat(common): remove expose port of enterprise-ui
  erda.yml
Labels: feature, approved, chore

#3118 feat(dop): update issue detail v3.1
  shell/app/common/components/edit-field/index.scss
  shell/app/common/components/edit-field/index.tsx
  shell/app/common/components/markdown-editor/index.scss
  shell/app/common/components/markdown-editor/index.tsx
  shell/app/common/components/markdown-render/index.scss
  shell/app/common/components/markdown-render/index.tsx
  shell/app/interface/global.d.ts
  shell/app/layout/stores/layout.ts
  shell/app/modules/project/common/components/issue/add-mr-relation.tsx
  shell/app/modules/project/common/components/issue/comment-box.scss
  shell/app/modules/project/common/components/issue/comment-box.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
  shell/app/modules/project/common/components/issue/issue-activities.scss
  shell/app/modules/project/common/components/issue/issue-activities.tsx
  shell/app/modules/project/common/components/issue/issue-drawer.scss
  shell/app/modules/project/common/components/issue/issue-drawer.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/common/components/issue/issue-testCase-relation.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, dop, approved

#3121 fix(cmp): fix alertRule option key
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
Labels: cmp, approved, bugfix

#3119 feat(test): add unit test cases
  shell/app/common/components/dropdown-select/__tests__/index.test.tsx
  shell/app/common/components/erda-alert/__tests__/index.test.tsx
  shell/app/common/components/filter-select/index.scss
  shell/app/common/components/filter-select/index.tsx
  shell/app/common/components/pure-log-roller/__tests__/log-content.test.tsx
  shell/app/common/components/simple-log/__tests__/index.test.tsx
  shell/app/common/components/simple-log/__tests__/simple-log-roller.test.tsx
  shell/app/common/components/simple-log/__tests__/simple-log-search.test.tsx
  shell/app/common/components/simple-log/__tests__/simple-log.test.tsx
  shell/app/common/components/tree-category/edit-category.tsx
  shell/app/common/components/tree-category/tree.scss
  shell/app/common/components/tree-category/tree.tsx
  shell/app/common/components/tree-category/utils.tsx
  shell/app/common/index.ts
  shell/app/common/test_bak/components/filter-select.test.tsx
  shell/app/modules/application/pages/pipeline/config-detail/index.tsx
  shell/app/modules/application/pages/pipeline/index.tsx
  shell/app/modules/application/pages/pipeline/pipeline-detail.tsx
  shell/app/modules/application/pages/pipeline/run-detail/index.tsx
  shell/app/modules/project/common/components/pipeline-manage/config-detail/pipeline-editor/case-tree-selector.tsx
  shell/app/modules/project/common/components/pipeline-manage/file-tree.tsx
  shell/app/modules/project/pages/pipelines/components/logs.tsx
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
  shell/app/modules/project/services/file-tree.tsx
  shell/app/modules/project/stores/file-tree.tsx
  shell/jest.config.js
Labels: feature, approved, test

#3122 fix(dop): configurable filter text color bug
  shell/app/common/components/configurable-filter/index.scss
Labels: dop, approved, bugfix

#3123 fix(dop): dop table optimization
  shell/app/common/components/configurable-filter/index.scss
  shell/app/modules/project/pages/backlog/backlog.tsx
  shell/app/modules/project/pages/backlog/iteration-item.tsx
  shell/app/modules/project/pages/ticket/index.tsx
Labels: dop, approved, bugfix

#3112 feat(dop): issue detail relation table filter optimization
  shell/app/common/components/configurable-filter/index.scss
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
Labels: feature, dop, approved

#3095 feat: add useUpdateSearch hooks / migrate config page urlQuery
  core/src/index.tsx
  core/src/stores/route.ts
  shell/app/common/__tests__/use-hook.test.tsx
  shell/app/common/use-hooks.tsx
  shell/app/config-page/config-page.d.ts
  shell/app/config-page/index.tsx
  shell/app/config-page/utils.tsx
  shell/app/modules/addonPlatform/pages/mysql/account.tsx
  shell/app/modules/addonPlatform/pages/mysql/consumer.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-event-log.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-nodes.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-pods.tsx
  shell/app/modules/cmp/pages/cluster-container/cluster-workload.tsx
  shell/app/modules/project/pages/auto-test/scenes.tsx
  shell/app/modules/project/pages/deploy/index.tsx
  shell/app/modules/project/pages/issue/board.tsx
  shell/app/modules/project/pages/issue/gantt/index.tsx
  shell/app/modules/project/pages/issue/issue-dashboard.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
  shell/app/modules/project/pages/issue/task-summary.tsx
  shell/app/modules/project/pages/release/release-protocol.tsx
  shell/app/modules/project/pages/statistics/code-coverage.tsx
  shell/app/modules/project/pages/statistics/test-dashboard.tsx
  shell/app/modules/project/pages/test-report/index.tsx
Labels: feature, dop, approved

#3124 fix(dop): auto test case pagination optimization
  shell/app/config-page/components/list/list.tsx
Labels: dop, approved, bugfix

#3127 test: add dropdown selector test case
  shell/app/common/components/dropdown-select-new/__tests__/index.test.tsx
  shell/app/common/components/dropdown-select-new/index.scss
  shell/app/common/components/dropdown-select-new/index.tsx
Labels: approved, test

#3125 fix(dop): remove project any
  shell/app/modules/project/pages/backlog/backlog.tsx
  shell/app/modules/project/pages/backlog/issue-item.tsx
  shell/app/modules/project/pages/backlog/iteration-item.tsx
  shell/app/modules/project/pages/data-source/index.tsx
  shell/app/modules/project/pages/deploy/deploy-config/index.tsx
  shell/app/modules/project/pages/deploy/deploy-config/list-edit.tsx
  shell/app/modules/project/pages/deploy/deploy-config/text-edit.tsx
  shell/app/modules/project/pages/issue/board.tsx
  shell/app/modules/project/pages/issue/component/table-view.tsx
  shell/app/modules/project/pages/issue/gantt/index.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
  shell/app/modules/project/pages/iteration/table.tsx
  shell/app/modules/project/pages/milestone/index.tsx
  shell/app/modules/project/pages/milestone/milestone-group.tsx
  shell/app/modules/project/pages/milestone/milestone-item.tsx
  shell/app/modules/project/pages/plan-detail/index.tsx
Labels: dop, approved, bugfix

#3128 refactor(msp): remove any type in msp
  shell/app/modules/application/types/application.d.ts
  shell/app/modules/msp/alarm-manage/notify-group/index.tsx
  shell/app/modules/msp/components/card-list.tsx
  shell/app/modules/msp/config.tsx
  shell/app/modules/msp/env-overview/service-list/pages/anomaly.tsx
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/env-overview/service-list/pages/overview.tsx
  shell/app/modules/msp/env-overview/service-list/pages/process.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx
  shell/app/modules/msp/monitor/api-insight/pages/delay/config/chartMap.ts
  shell/app/modules/msp/monitor/api-insight/pages/delay/index.tsx
  shell/app/modules/msp/monitor/api-insight/pages/request/config/chartMap.ts
  shell/app/modules/msp/monitor/api-insight/pages/request/index.tsx
  shell/app/modules/msp/monitor/trace-insight/common/utils/traceConvert.ts
  shell/app/modules/msp/monitor/trace-insight/types/index.d.ts
  shell/app/modules/msp/stores/gateway.ts
  shell/app/modules/msp/types/config-center.d.ts
  shell/app/modules/msp/types/gateway.d.ts
  shell/app/modules/msp/types/monitor.d.ts
Labels: msp, refactor, approved

#3134 feat(dop): support show issue title and update style
  shell/app/common/components/edit-field/index.scss
  shell/app/common/components/edit-field/index.tsx
  shell/app/common/components/tags/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/issue/comment-box.scss
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
  shell/app/modules/project/common/components/issue/issue-config.tsx
  shell/app/modules/project/common/components/issue/issue-drawer.scss
  shell/app/modules/project/common/components/issue/issue-drawer.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
Labels: feature, dop, approved

#3138 fix(dop): issue detail page crash
  shell/app/common/components/edit-field/index.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
  shell/app/modules/project/common/components/issue/issue-activities.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/pages/backlog/issue-item.scss
Labels: dop, approved, bugfix

#3139 feat(test): add some unit test case
  shell/app/common/components/cards-layout/__tests__/index.test.tsx
  shell/app/common/components/key-value-list/__tests__/__snapshots__/index.test.tsx.snap
  shell/app/common/components/key-value-list/__tests__/index.test.tsx
  shell/app/common/components/key-value-table/__tests__/index.test.tsx
  shell/app/common/components/key-value-table/index.tsx
  shell/app/common/components/key-value-textarea/__tests__/index.test.tsx
  shell/app/common/components/readonly-form/__tests__/__snapshots__/index.test.tsx.snap
  shell/app/common/components/readonly-form/__tests__/index.test.tsx
  shell/app/common/index.ts
  shell/app/common/test_bak/components/key-value-list.test.tsx
  shell/app/common/test_bak/components/key-value-table.test.tsx
  shell/app/common/test_bak/components/key-value-textarea.test.tsx
  shell/app/common/test_bak/components/sort-drag-list.test.tsx
  shell/app/config-page/components/sort-drag-group/pure-sort-drag-group-list/index.scss
  shell/app/config-page/components/sort-drag-group/pure-sort-drag-group-list/index.tsx
  shell/app/config-page/components/sort-drag-group/sort-drag-group.tsx
Labels: feature, approved, test

#3130 feat: remove qiankun
  cli/lib/build-enterprise-online.ts
  cli/lib/build-enterprise.ts
  cli/lib/check-build-status.ts
  cli/lib/util/i18n-config.ts
  core/src/index.tsx
  cspell.json
  docs/introduction_en.md
  docs/introduction_zh.md
  pipeline.yml
  pnpm-lock.yaml
  scheduler/src/proxy.ts
  shell/package.json
  shell/vite.config.js
Labels: feature, fdp, refactor, approved

#3129 fix(common): save the display status of table columns
  shell/app/common/components/members-table/index.tsx
  shell/app/common/components/table/index.tsx
  shell/app/common/components/table/interface.ts
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/application/pages/settings/components/app-notify/notify-config.tsx
  shell/app/modules/project/common/components/branch-rule.tsx
  shell/app/modules/project/common/components/scan-rule.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
  shell/app/modules/project/pages/iteration/table.tsx
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
  shell/app/modules/project/pages/release/release-protocol.tsx
  shell/app/modules/project/pages/settings/components/project-cluster.tsx
  shell/app/modules/project/pages/settings/components/project-settings.tsx
  shell/app/modules/project/pages/test-env/test-env.tsx
  shell/app/modules/project/pages/test-plan/test-plan-protocol.tsx
  shell/app/modules/project/pages/test-plan/test-plan.tsx
  shell/app/modules/project/pages/test-report/index.tsx
  shell/app/modules/project/pages/ticket/index.tsx
Labels: approved, bugfix

#3137 fix(dop): config page table batch selection bug
  shell/app/common/components/table/index.tsx
Labels: dop, approved, bugfix

#3136 feat(dop): project pipeline edit pipeline name
  shell/app/config-page/components/table/v2/utils.tsx
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
  shell/app/modules/project/services/pipeline.tsx
Labels: feature, dop, approved

#3144 feat(common): upgrade node version
  Dockerfile
  scheduler/src/proxy.ts
Labels: feature, approved, chore

#3143 fix(dop): type in issue share link cause wrong filter item
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/subscribers-selector.tsx
  shell/app/modules/project/common/components/workflow-state-form.tsx
  shell/app/modules/project/pages/backlog/backlog.tsx
  shell/app/modules/project/pages/backlog/iteration-item.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
  shell/app/modules/project/stores/issues.ts
Labels: dop, bugfix

#3148 fix: fix event hub once prevent duplicate register
  core/src/utils/event-hub.ts
Labels: approved, bugfix

#3146 fix(dop): select warm optimization when options do not match value type
  shell/app/common/components/render-form-item/index.tsx
Labels: dop, bugfix

#3147 fix(common): configurable filter style bug
  shell/app/common/components/configurable-filter/index.tsx
Labels: dop, bugfix

#3150 feat(test): add some test case
  shell/app/common/components/k-v-pair/__tests__/index.test.tsx
  shell/app/common/components/key-value-editor/__tests__/index.test.tsx
  shell/app/common/components/log-roller/__tests__/index.test.tsx
  shell/app/common/components/simple-panel/__tests__/index.test.tsx
  shell/app/common/index.ts
  shell/app/common/test_bak/components/edit-list/edit-list.test.tsx
  shell/app/common/test_bak/components/key-value-editor.test.tsx
  shell/app/common/test_bak/components/kv-pair/kv-pair.test.tsx
  shell/app/common/test_bak/containers/log-roller.test.tsx
  shell/app/config-page/components/api-editor/api-editor.tsx
  shell/app/config-page/components/edit-list/edit-list.tsx
  shell/app/config-page/components/edit-list/pure-edit-list.scss
  shell/app/config-page/components/edit-list/pure-edit-list.tsx
Labels: feature, test

#3157 fix(dop): fix cannot create issue
  shell/app/modules/project/pages/issue/issue-protocol.tsx
Labels: dop, approved, bugfix

#3159 fix(dop): fix cannot open issue from sharelink
  shell/app/modules/project/pages/issue/issue-protocol.tsx
Labels: dop, approved, bugfix

#3145 refactor: migrate crud table to erda table
  locales/en.json
  locales/zh.json
  shell/app/common/components/crud-table/index.tsx
  shell/app/common/utils/go-to.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/orgCenter.tsx
  shell/app/modules/application/pages/settings/components/app-certificate-reference.tsx
  shell/app/modules/application/pages/settings/components/app-library-reference.tsx
  shell/app/modules/cmp/pages/cloud-accounts/index.tsx
  shell/app/modules/cmp/pages/computing/ecs/index.tsx
  shell/app/modules/cmp/pages/networks/vpc/index.tsx
  shell/app/modules/cmp/pages/networks/vsw/index.tsx
  shell/app/modules/cmp/pages/storage/oss/index.tsx
  shell/app/modules/cmp/router.ts
  shell/app/modules/org/pages/approval/index.tsx
  shell/app/modules/org/pages/certificate/index.tsx
  shell/app/modules/org/router.ts
Labels: refactor

#3161 feat(msp): drill down to the service in the topology
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/env-overview/service-list/pages/transaction-detail.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/index.scss
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/index.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/services-node.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/index.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, msp

#3164 fix(dop): pipeline action link bug
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
Labels: dop, approved, bugfix

#3165 fix(dop): fix issue share link and not refresh relations list in ticket
  core/src/utils/event-hub.ts
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/common/components/issue/subscribers-selector.tsx
  shell/app/modules/project/pages/backlog/backlog.tsx
  shell/app/modules/project/pages/backlog/issue-item.tsx
  shell/app/modules/project/pages/backlog/iteration-item.tsx
  shell/app/modules/project/pages/issue/all.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
  shell/app/org-home/stores/org.tsx
Labels: approved, bugfix

#3162 feat(msp): upgrade dashboard to unified style of charts
  pnpm-lock.yaml
  shell/app/common/components/time-select/time-select.tsx
  shell/app/modules/cmp/common/custom-dashboard/custom-dashboard.tsx
  shell/app/modules/cmp/pages/middleware-dashboard/index.tsx
  shell/app/modules/cmp/types/dashboard-model.d.ts
  shell/package.json
Labels: feature, msp, cmp, approved

#3168 fix: file tree expand error after drag node
  shell/app/config-page/components/file-tree/file-tree.tsx
Labels: approved, bugfix

#3163 refactor(msp): remove useless pages in MSP
  shell/app/modules/msp/alarm-manage/alarm-record/index.ts
  shell/app/modules/msp/alarm-manage/alarm-record/pages/detail.tsx
  shell/app/modules/msp/alarm-manage/alarm-record/pages/index.tsx
  shell/app/modules/msp/alarm-manage/index.ts
  shell/app/modules/msp/env-overview/router.ts
  shell/app/modules/msp/monitor/external-insight/common/components/eiRenderFactory.tsx
  shell/app/modules/msp/monitor/external-insight/common/components/error-track-panel.tsx
  shell/app/modules/msp/monitor/external-insight/common/components/slow-track-panel.scss
  shell/app/modules/msp/monitor/external-insight/common/components/slow-track-panel.tsx
  shell/app/modules/msp/monitor/external-insight/common/components/tab-right.scss
  shell/app/modules/msp/monitor/external-insight/common/components/tab-right.tsx
  shell/app/modules/msp/monitor/external-insight/common/components/track-expand-table.tsx
  shell/app/modules/msp/monitor/external-insight/pages/affairs/affairs.tsx
  shell/app/modules/msp/monitor/external-insight/pages/affairs/config/apiConfig.ts
  shell/app/modules/msp/monitor/external-insight/pages/affairs/config/chartMap.ts
  shell/app/modules/msp/monitor/external-insight/router.ts
  shell/app/modules/msp/monitor/external-insight/services/index.ts
  shell/app/modules/msp/monitor/external-insight/stores/affairs.ts
  shell/app/modules/msp/monitor/external-insight/types/index.d.ts
  shell/app/modules/msp/monitor/monitor-overview/common/components/monitor-panel.scss
  shell/app/modules/msp/monitor/monitor-overview/common/components/monitor-panel.tsx
  shell/app/modules/msp/monitor/monitor-overview/pages/overview/overview-types.scss
  shell/app/modules/msp/monitor/monitor-overview/pages/overview/overview-types.tsx
  shell/app/modules/msp/monitor/monitor-overview/pages/overview/overview.scss
  shell/app/modules/msp/monitor/monitor-overview/pages/overview/overview.tsx
  shell/app/modules/msp/monitor/monitor-overview/pages/overview/summary.tsx
  shell/app/modules/msp/monitor/monitor-overview/router.ts
  shell/app/modules/msp/monitor/monitor-overview/services/monitor-overview.ts
  shell/app/modules/msp/monitor/monitor-overview/stores/monitor-overview.ts
  shell/app/modules/msp/monitor/monitor-overview/types/index.d.ts
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-detail.scss
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-detail.tsx
  shell/app/modules/msp/monitor/trace-insight/router.ts
Labels: msp, refactor

#3170 fix(dop): referenced ticket page is not found
  shell/app/common/components/pagination/index.tsx
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/pages/ticket/index.tsx
Labels: approved, bugfix

#3174 fix(dop): fix state filed show number in issue filter
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
Labels: dop, approved, bugfix

#3172 feat(dop): project pipeline types list
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/pipelines/components/form.tsx
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
  shell/app/modules/project/pages/pipelines/index.scss
  shell/app/modules/project/pages/pipelines/index.tsx
  shell/app/modules/project/services/pipeline.tsx
Labels: feature, dop, approved

#3175 feat(msp): search for applications or services when create alarm stra…
  shell/app/modules/cmp/common/alarm-strategy/trigger-condition-select.tsx
Labels: feature, msp, approved

#3173 feat(dop): export api asset
  locales/en.json
  locales/zh.json
  shell/app/common/utils/index.ts
  shell/app/modules/apiManagePlatform/pages/access-manage/list/index.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/components/export-record.scss
  shell/app/modules/apiManagePlatform/pages/api-market/components/export-record.tsx
  shell/app/modules/apiManagePlatform/pages/api-market/list/index.tsx
  shell/app/modules/apiManagePlatform/pages/client/list/index.tsx
  shell/app/modules/apiManagePlatform/services/api-export.ts
  shell/app/modules/apiManagePlatform/types/api-market.d.ts
Labels: feature, dop, approved

#3177 feat(dop): fix table sort
  shell/app/common/components/table/__tests__/index.test.tsx
  shell/app/common/components/table/index.tsx
  shell/test/extend-expect.d.ts
  shell/test/extend-expect.ts
Labels: feature, dop

#3178 fix(dop): fix ut detail style
  shell/app/common/components/markdown-editor/editor.tsx
  shell/app/modules/application/pages/repo/repo-commit.tsx
  shell/app/modules/application/pages/test/test-detail.scss
  shell/app/modules/application/pages/test/test-detail.tsx
  shell/app/modules/application/stores/repo.ts
Labels: dop, bugfix

#3179 feat(dop): add job type in artifact
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/runtime/common/components/instance-table.tsx
  shell/app/modules/runtime/pages/overview/components/index.tsx
  shell/app/modules/runtime/pages/overview/components/service-card.tsx
  shell/app/modules/runtime/types/service.d.ts
Labels: feature, dop, approved

#3180 feat(dop): project pipeline guides list
  shell/app/modules/project/pages/pipelines/components/form.tsx
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
  shell/app/modules/project/pages/pipelines/index.scss
  shell/app/modules/project/pages/pipelines/index.tsx
  shell/app/modules/project/services/pipeline.tsx
Labels: feature, dop, approved

#3184 fix: fix config-sheet request loop
  shell/app/modules/project/common/components/pipeline-manage/config-detail/index.tsx
  shell/app/modules/project/common/components/pipeline-manage/config-detail/pipeline-editor/case-yml-graphic-editor.tsx
Labels: dop, approved, bugfix

#3183 fix(dop): domain names are deleted in the wrong order
  shell/app/modules/runtime/pages/overview/components/domain-modal.tsx
Labels: dop, approved, bugfix

#3182 feat(test): add unit test cast
  shell/app/common/components/add-member-modal/__tests__/add-member-modal.test.tsx
  shell/app/common/components/add-member-modal/__tests__/index.test.tsx
  shell/app/common/components/authorize-member-modal/__tests__/index.test.tsx
  shell/app/common/components/batch-authorize-member-modal/__tests__/index.test.tsx
  shell/app/common/components/form-modal/__tests__/index.test.tsx
  shell/app/common/test_bak/components/add-member-modal/index.test.tsx
  shell/app/common/test_bak/components/authorize-member-modal/index.test.tsx
Labels: feature, approved, test

#3188 fix(msp): textMap is undefined in line option
  pnpm-lock.yaml
  shell/package.json
Labels: msp, bugfix

#3187 fix: fix project pipeline style
  shell/app/modules/application/pages/build-detail/index.scss
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.scss
  shell/app/modules/project/common/components/pipeline-manage/run-detail/index.scss
  shell/app/modules/project/common/components/pipeline-new/execute.scss
  shell/app/modules/project/common/components/pipeline-new/index.tsx
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
Labels: dop, bugfix

#3190 fix(dop): runtime page collapse
  shell/app/modules/runtime/pages/overview/components/domain-modal.tsx
Labels: dop, approved, bugfix

#3192 fix(msp): textMap is undefined in line option
  pnpm-lock.yaml
  shell/package.json
Labels: msp, bugfix

#3195 fix(msp): fix topology tip's style
  shell/app/common/components/contractive-filter/index.tsx
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/index.scss
  shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/services-node.tsx
Labels: msp, approved, bugfix

#3194 feat: redirect sub org domain to root domain
  scheduler/src/middlewares/guard.middleware.ts
Labels: feature, scheduler, approved

#3189 fix: fix scheduler crash caused by write after end error
  scheduler/src/proxy.ts
  shell/app/modules/application/pages/test/test-detail.tsx
Labels: scheduler, approved, bugfix

#3193 fix: fix project pipeline init mode error
  shell/app/modules/project/common/components/pipeline-new/index.tsx
Labels: dop, approved, bugfix

#3196 fix: fix config sheet request loop
  shell/app/modules/project/common/components/pipeline-manage/common/tree-category/tree.tsx
  shell/app/modules/project/common/components/pipeline-manage/config-detail/pipeline-editor/index.tsx
Labels: dop, approved, bugfix

#3197 fix(msp): modify z-index to display tooltip
  shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search-detail.scss
Labels: msp, approved, bugfix

#3200 fix: pick of fix scheduler crash caused by write after end error
  scheduler/src/proxy.ts
Labels: bugfix

#3205 feat(dop): fix export record sort
  shell/app/modules/apiManagePlatform/pages/api-market/components/export-record.tsx
Labels: approved

#3206 fix: fix project pipeline file changed
  shell/app/modules/project/common/components/pipeline-new/index.tsx
Labels: dop, approved, bugfix

#3208 fix(dop): project pipeline action link bug
  shell/app/modules/project/common/components/pipeline-new/execute.tsx
Labels: dop, approved, bugfix

#3207 fix: fix pipeline popover placement error
  shell/app/modules/application/pages/build-detail/pipeline-chart/pipeline-node.tsx
  shell/app/modules/application/pages/pipeline/run-detail/pipeline-chart/pipeline-node.tsx
  shell/app/modules/project/common/components/pipeline-manage/run-detail/pipeline-chart/run-case-node.tsx
Labels: dop, bugfix

#3209 fix(dop): project pipeline guides list optimization
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/pipelines/index.tsx
Labels: dop, approved, bugfix

#3203 fix(dop): clear filter when types are switched
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
  shell/app/modules/project/pages/pipelines/index.tsx
Labels: dop, approved, bugfix

#3212 fix(dop): pipeline guides list text optimization
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/pipelines/index.tsx
Labels: dop, approved, bugfix

#3215 fix: fix domain redirect error
  scheduler/src/middlewares/guard.middleware.ts
Labels: approved, bugfix

#3210 fix: add project pipeline editor delete
  shell/app/modules/project/common/components/pipeline-new/editor.tsx
  shell/app/modules/project/common/components/pipeline-new/pipeline-node.scss
  shell/app/modules/project/common/components/pipeline-new/pipeline-node.tsx
Labels: dop, approved, bugfix

#3214 feat(dop): remove apiId & version name
  shell/app/modules/apiManagePlatform/pages/api-market/components/export-record.tsx
Labels: feature, dop

#3213 fix(common): erda table td padding style optimization
  shell/app/common/components/table/index.scss
Labels: bugfix

#3211 feat(test): add unit test case
  shell/app/common/components/crud-table/__tests__/index.test.tsx
  shell/app/common/components/ellipsis/__tests__/index.test.tsx
  shell/app/common/components/filter/__tests__/base-filter.test.tsx
  shell/app/common/components/filter/__tests__/index.test.tsx
  shell/app/common/components/filter/base-filter.tsx
  shell/app/common/components/filter/index.tsx
  shell/app/common/components/render-pure-form/__tests__/index.test.tsx
  shell/app/common/test_bak/components/crud-table.test.tsx
  shell/test/extend-expect.ts
Labels: feature, test

#3216 feat(dop): add field `valid` to check whether a file exists
  locales/en.json
  locales/zh.json
  shell/app/common/components/table/index.tsx
  shell/app/common/components/table/interface.ts
  shell/app/modules/apiManagePlatform/pages/api-market/components/export-record.tsx
  shell/app/modules/apiManagePlatform/types/api-market.d.ts
Labels: feature, dop

#3204 feat: add last search when back to up
  core/src/framework/regist-router.tsx
  core/src/stores/route.ts
  core/src/types/shell.d.ts
  shell/app/layout/pages/page-container/components/header.tsx
Labels: feature

#3219 fix(dop): project pipeline types list optimization
  shell/app/modules/project/pages/pipelines/index.tsx
Labels: dop, approved, bugfix

#3221 feat: add pipeline refresh in project pipeline
  shell/app/modules/project/common/components/pipeline-new/execute.tsx
Labels: feature, dop, bugfix

#3222 fix(scheduler): fix server crash when handling proxy error issue
  .erda/pipelines/ci-build-ce.yml
  cli/package.json
  cspell.json
  pipeline.yml
  scheduler/src/proxy.ts
Labels: scheduler, approved, bugfix

#3225 fix: fix pipeline execute detail spinning
  shell/app/modules/project/common/components/pipeline-new/execute.tsx
Labels: dop, approved, bugfix

#3228 feat(dop): create deploy add modes
  shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx
  shell/app/modules/project/pages/deploy/add-deploy/index.tsx
  shell/app/modules/project/pages/deploy/index.tsx
  shell/app/modules/project/pages/release/components/form.tsx
  shell/app/modules/project/services/deploy.ts
  shell/app/modules/project/types/deploy.d.ts
  shell/app/modules/project/types/release.d.ts
Labels: feature, dop, approved

#3231 fix(common): unified management of the visibility of milestones
  shell/app/common/constants.ts
  shell/app/modules/org/common/config.ts
  shell/app/modules/project/stores/issue-workflow.ts
  shell/app/modules/project/tabs.tsx
Labels: approved, bugfix

#3233 feat(dop): project release detail add modes
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/release/components/form.tsx
Labels: feature, dop, approved

#3235 feat: sonar action setting
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/settings/app-settings.tsx
  shell/app/modules/application/pages/settings/components/sonar-config.tsx
  shell/app/modules/application/types/application.d.ts
Labels: feature, dop, approved

#3236 fix: fix external repo app update error
  shell/app/modules/application/pages/settings/components/sonar-config.tsx
  shell/app/modules/application/types/application.d.ts
Labels: dop, approved, bugfix

#3234 fix(dop): edit release page display speed optimization
  shell/app/modules/project/pages/release/components/update.tsx
Labels: dop, approved, bugfix

#3239 fix: fix project pipeline update search
  shell/app/modules/project/pages/pipelines/index.tsx
Labels: dop, approved, bugfix

#3240 fix: fix base 64 convert not match api in project pipeline
  shell/app/modules/project/common/components/pipeline-new/index.tsx
Labels: dop, approved, bugfix

#3242 fix: fix params config list edit add empty key error
  shell/app/modules/project/common/components/params-config/list-edit.tsx
Labels: dop, approved, bugfix

#3241 feat(dop): project pipeline guides list add delete button
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
  shell/app/modules/project/pages/pipelines/index.scss
  shell/app/modules/project/pages/pipelines/index.tsx
  shell/app/modules/project/services/pipeline.tsx
Labels: feature, dop, approved

#3238 feat: edit issue relation list in issue-detail
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/pages/backlog/issue-item.tsx
  shell/app/modules/project/pages/issue/component/table-view.tsx
Labels: feature, dop, approved

#3243 fix(dop): create deploy optimization
  shell/app/modules/project/pages/deploy/add-deploy/index.tsx
  shell/app/modules/project/pages/deploy/index.tsx
  shell/app/modules/project/pages/release/components/form.tsx
  shell/app/modules/project/types/deploy.d.ts
Labels: dop, approved, bugfix

#3237 feat(dop): issue iteration fast switch
  shell/app/common/components/load-more-selector/index.scss
  shell/app/modules/application/common/app-selector.tsx
  shell/app/modules/project/common/components/iteration-selector.scss
  shell/app/modules/project/common/components/iteration-selector.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
  shell/app/modules/project/tabs.tsx
Labels: feature, dop, approved

#3245 feat(dop): fixed edit button in issue detail
  shell/app/common/components/edit-field/index.tsx
Labels: feature, dop, approved

#3247 feat(test): add unit test case
  .codecov.yml
  shell/app/common/components/batch-operation/index.tsx
  shell/app/common/components/common-range-picker/__tests__/index.test.tsx
  shell/app/common/components/filter-group/__tests__/index.test.tsx
  shell/app/common/components/form-modal/index.tsx
  shell/app/common/components/member-selector/__tests__/index.test.tsx
  shell/app/common/components/members-table/__tests__/__snapshots__/index.test.tsx.snap
  shell/app/common/components/members-table/__tests__/index.test.tsx
  shell/app/common/stores/_member.ts
  shell/app/common/test_bak/components/common-range-picker.test.tsx
  shell/app/common/test_bak/components/filter-group/filter-group.test.tsx
  shell/app/common/test_bak/components/member-selector.test.tsx
  shell/package.json
  shell/vite.config.js
Labels: approved

#3246 fix(dop): deploy runtime websocket bug
  shell/app/layout/stores/layout.ts
Labels: dop, approved, bugfix

#3248 fix(dop): correct the count of committed MR
  shell/app/modules/application/stores/repo.ts
Labels: dop, approved, bugfix

#3249 fix(dop): create deploy bug
  shell/app/modules/project/pages/deploy/add-deploy/index.tsx
  shell/app/modules/project/pages/deploy/index.tsx
Labels: dop, approved, bugfix
