Repository erda-project/erda-ui, pull requests merged in 2022-06, with the labels that each got.

#3579 fix: i18n DingTalk work notice translation
  locales/en.json
Labels: bugfix

#3576 fix(common): downgrade translation to free call when secret file not provided
  core/src/i18n.ts
  pnpm-lock.yaml
  shell/package.json
Labels: approved

#3580 feat: hold head menu position
  shell/app/modules/application/router.ts
  shell/app/modules/application/stores/application.tsx
  shell/app/modules/application/tabs.tsx
  shell/app/modules/project/common/components/iteration-selector.tsx
  shell/app/modules/project/router.tsx
  shell/app/modules/project/tabs.tsx
Labels: feature, dop

#3581 feat(common): add branch hint for deployment
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/deploy/index.tsx
  shell/babel.config.js
Labels: feature, approved

#3582 feat: add pipeline detail history
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/pipeline-new/detail/editor.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/execute.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/index.tsx
  shell/app/modules/project/common/components/pipeline-new/list.tsx
  shell/app/modules/project/common/components/pipeline-new/record-detail.tsx
  shell/app/modules/project/services/pipeline.tsx
Labels: feature, dop

#3583 feat: add fallback log download
  shell/app/common/components/log-roller/index.tsx
  shell/app/common/components/pure-log-roller/download-log-modal.tsx
  shell/app/common/components/pure-log-roller/log-roller.tsx
  shell/app/modules/runtime/common/logs/components/container-log.tsx
Labels: feature, dop

#3584 fix: fix dataTask menu
  shell/app/modules/application/router.ts
Labels: bugfix

#3585 fix: fix dataTask menu in 2.1
  shell/app/modules/application/router.ts
Labels: bugfix

#3586 fix(msp): safety policy config text optimization
  shell/app/locales/en.json
  shell/app/locales/zh.json
Labels: msp, bugfix

#3588 fix: disabled fallback log download
  shell/app/common/components/log-roller/index.tsx
  shell/app/common/components/pure-log-roller/log-roller.tsx
Labels: bugfix

#3587 fix(dop): fix env style issue
  shell/app/modules/project/pages/deploy/index.tsx
Labels: dop, approved, bugfix

#3589 fix: fix empty pipeline record
  shell/app/modules/project/common/components/pipeline-new/list.tsx
Labels: bugfix

#3590 feat(common): enlarge upload limit size
  shell/app/modules/publisher/pages/artifacts/upload-modal.tsx
Labels: feature, approved

#3592 fix(dop): fix yankuang publisher issue
  shell/app/common/components/image-upload/index.tsx
  shell/app/modules/publisher/pages/artifacts/artifacts-form-modal.tsx
  shell/app/modules/publisher/pages/artifacts/artifacts-info.tsx
Labels: dop, approved, bugfix

#3593 feat(common): add dingding User-Agent to show title in dingding link
  scheduler/src/filters/not-found.filter.ts
Labels: feature, approved

#3595 feat(scheduler): update dingtalk ua
  scheduler/src/filters/not-found.filter.ts
Labels: feature, scheduler, approved

#3578 fix: image width not fit container width in markdown render
  shell/app/common/components/markdown-render/__tests__/index.test.tsx
  shell/app/common/components/markdown-render/index.tsx
Labels: bugfix

#3594 fix: fix pipeline record params error
  shell/app/modules/project/common/components/pipeline-new/list.tsx
  shell/app/modules/project/services/pipeline.tsx
Labels: bugfix

#3577 feat: add i18n-easy-edit
  core/src/i18n.ts
  scheduler/src/filters/not-found.filter.ts
  shell/app/common/utils/__tests__/index.test.tsx
  shell/app/common/utils/index.ts
  shell/app/i18n-easy-edit/config.ts
  shell/app/i18n-easy-edit/index.ts
  shell/app/i18n-easy-edit/pages/edit-modal/index.tsx
  shell/app/i18n-easy-edit/pages/fixed-widget/index.tsx
  shell/app/i18n-easy-edit/pages/i18n-wrapper/index.less
  shell/app/i18n-easy-edit/pages/i18n-wrapper/index.tsx
  shell/app/i18n-easy-edit/pages/index.tsx
  shell/app/i18n-easy-edit/pages/publish-modal/index.tsx
  shell/app/i18n-easy-edit/store/index.ts
  shell/app/i18n-easy-edit/utils/cache.ts
  shell/app/i18n-easy-edit/utils/index.ts
  shell/app/i18n-easy-edit/utils/mergedJSON.ts
  shell/app/i18n-easy-edit/utils/overwrite-i18n.tsx
  shell/app/i18n.ts
  shell/app/layout/pages/page-container/components/header.tsx
  shell/app/layout/pages/page-container/components/navigation/index.tsx
  shell/app/layout/pages/page-container/components/shell/index.tsx
  shell/app/styles/util.scss
  shell/app/user/common/perm-editor/perm-export.tsx
  shell/app/user/common/perm-editor/utils.tsx
Labels: feature, approved

#3597 fix: duplicate i18n-wrapper bug
  shell/app/i18n-easy-edit/utils/overwrite-i18n.tsx
  shell/app/i18n.ts
Labels: approved, bugfix

#3598 fix: unit test warning log
  README.md
  shell/app/common/components/cards-layout/index.tsx
  shell/app/common/components/configurable-filter/__tests__/external-item.test.tsx
  shell/app/common/components/contractive-filter/__tests__/index.test.tsx
  shell/app/common/components/form-modal/index.tsx
  shell/app/common/components/k-v-pair/__tests__/index.test.tsx
  shell/app/common/components/render-form-item/index.tsx
  shell/app/modules/project/common/components/workflow/steps/pipeline.tsx
  shell/app/modules/project/common/components/workflow/steps/temp-merge.tsx
Labels: bugfix, test

#3599 feat: close links for not ready yet
  shell/app/views/index.ejs
Labels: feature

#3601 fix: withdraw side menu item :before z-index=-1 & collaboration go to ticket and open modal
  shell/app/common/utils/go-to.tsx
  shell/app/styles/util.scss
Labels: approved

#3600 fix: delete noEditSuffix in i18n-easy-edit & rewrite overwrite-antd-input
  shell/app/antd-overwrite/button/index.tsx
  shell/app/i18n-easy-edit/config.ts
Labels: bugfix

#3602 feat(dop): redirect legacy pipeline to new router
  scheduler/src/controllers/legacy-route.controller.ts
  shell/app/modules/publisher/pages/artifacts/artifacts-form-modal.tsx
Labels: feature, dop

#3603 feat: refactor issue workflow
  shell/app/common/utils/go-to.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/repo/components/compare-detail.tsx
  shell/app/modules/project/common/components/workflow/add-flow.tsx
  shell/app/modules/project/common/components/workflow/index.tsx
  shell/app/modules/project/common/components/workflow/issue-workflow.tsx
  shell/app/modules/project/pages/settings/components/project-workflow.tsx
  shell/app/modules/project/services/project-workflow.ts
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, dop

#3606 fix: fix issue detail markdown expand error
  shell/app/common/components/edit-field/index.tsx
Labels: bugfix

#3605 fix: fix pipeline template add error
  shell/app/modules/application/pages/repo/components/add-pipelineyml.tsx
Labels: bugfix

#3607 fix: fix markdown html tag render
  pnpm-lock.yaml
  shell/app/common/components/markdown-render/index.tsx
  shell/package.json
Labels: bugfix

#3608 feat: add gallery enable config
  erda.yml
  shell/app/layout/pages/page-container/components/navigation/index.tsx
Labels: feature, bugfix

#3611 fix: hide workflow in create MR & in branch compare
  shell/app/modules/application/pages/repo/branch-compare-detail.tsx
  shell/app/modules/application/pages/repo/components/compare-detail.tsx
  shell/app/modules/application/pages/repo/repo-mr-creation.tsx
Labels: approved, bugfix

#3612 fix: gallery default config
  erda.yml
Labels: bugfix

#3609 fix: disable merge when tempBranch is not exist
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/workflow/index.tsx
Labels: bugfix

#3613 fix: gallery entry config
  shell/vite.config.js
  shell/webpack.config.js
Labels: bugfix

#3610 fix: after formModal uploaded image, set ok-btn disabled to false
  shell/app/modules/application/pages/settings/components/app-info.tsx
  shell/app/modules/project/common/components/section-info-edit.tsx
Labels: approved, bugfix

#3614 fix: get gallery entry config in runtime env
  scheduler/src/filters/not-found.filter.ts
  shell/app/interface/global.d.ts
  shell/app/layout/pages/page-container/components/navigation/index.tsx
  shell/vite.config.js
  shell/webpack.config.js
Labels: bugfix

#3615 feat: delete useless in workflow
  shell/app/modules/project/common/components/workflow/index.tsx
  shell/app/modules/project/common/components/workflow/steps/base-step.scss
  shell/app/modules/project/common/components/workflow/steps/base-step.tsx
  shell/app/modules/project/common/components/workflow/steps/code.tsx
  shell/app/modules/project/common/components/workflow/steps/index.tsx
  shell/app/modules/project/common/components/workflow/steps/pipeline.tsx
  shell/app/modules/project/common/components/workflow/steps/temp-merge.tsx
Labels: feature, approved

#3616 fix: once dropdown labels, get latest labels
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
Labels: approved, bugfix

#3617 fix: fix issue request params error
  shell/app/modules/project/common/components/issue/issue-relation.tsx
Labels: bugfix

#3618 fix: log fallback download
  shell/app/common/components/log-roller/index.tsx
  shell/app/common/components/pure-log-roller/log-roller.tsx
Labels: bugfix

#3620 fix: fix uc redirect url
  scheduler/src/filters/not-found.filter.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
Labels: bugfix

#3622 fix: fix uc redirect url error
  scheduler/src/filters/not-found.filter.ts
Labels: bugfix

#3624 feat: add fallback log type and tip
  shell/app/common/components/pure-log-roller/log-roller.scss
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/runtime/common/logs/components/container-log.tsx
Labels: feature

#3623 feat(scheduler): add links entry
  pnpm-lock.yaml
  scheduler/package.json
  scheduler/src/app.module.ts
  scheduler/src/controllers/linkS-token.controller.ts
  shell/app/App.tsx
  shell/app/views/index.ejs
Labels: feature, scheduler, approved

#3626 feat(common): add ga
  pnpm-lock.yaml
  shell/app/App.tsx
  shell/app/common/utils/go-to.tsx
  shell/package.json
  shell/webpack.config.js
Labels: feature, approved

#3627 fix(common): typo
  shell/app/App.tsx
Labels: bugfix

#3628 fix: add custom click goto in config-page
  shell/app/config-page/page-render.tsx
  shell/app/modules/project/pages/release/components/application-detail.tsx
Labels: bugfix

#3630 fix(common): typo package
  pnpm-lock.yaml
  shell/package.json
Labels: approved, bugfix

#3631 fix: fix fallback log download params error
  shell/app/common/components/pure-log-roller/download-log-modal.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/runtime/common/logs/components/container-log.tsx
Labels: bugfix

#3633 fix: fix project workflow tips
  shell/app/modules/project/pages/settings/components/project-workflow.tsx
Labels: approved, bugfix

#3635 fix: fix trace request params error
  shell/app/modules/msp/monitor/trace-insight/stores/trace-querier.ts
Labels: approved, bugfix

#3637 fix: fix pipeline history params error
  shell/app/modules/project/common/components/pipeline-new/list.tsx
  shell/app/modules/project/services/pipeline.tsx
Labels: dop, approved, bugfix

#3639 fix(ui): adjust enterprise-ui resource
  erda.yml
Labels: bugfix

#3640 fix: fix table render style
  shell/app/config-page/components/table/render-types.tsx
Labels: bugfix

#3632 refactor: migrate from yankuang market/download page
  modules/market/craco.config.js
  modules/market/package.json
  modules/market/src/pages/download-pc.scss
  modules/market/src/pages/download-pc.tsx
  modules/market/src/pages/download.scss
  modules/market/src/pages/download.tsx
  modules/market/src/pages/utils.ts
  modules/market/src/react-app-env.d.ts
  modules/market/src/styles/_util.scss
  modules/market/src/styles/_variable.scss
Labels: refactor

#3642 fix(common): fix missing lock file
  pnpm-lock.yaml
Labels: approved, bugfix

#3643 fix: api error in market/download
  modules/market/src/pages/download.tsx
Labels: approved, bugfix

#3644 fix: fix issue measure refresh error
  shell/app/config-page/components/simple-chart/simple-chart.tsx
  shell/app/modules/project/pages/issue/issue-dashboard.tsx
  shell/app/modules/project/pages/issue/statistics.tsx
  shell/app/modules/project/pages/issue/task-summary.tsx
Labels: bugfix

#3647 feat(common): change var name
  shell/webpack.config.js
Labels: feature, approved

#3646 fix(repo): encode # before get request
  shell/app/common/components/menu/__tests__/index.test.tsx
  shell/app/common/components/menu/index.tsx
  shell/app/common/utils/__tests__/index.test.tsx
  shell/app/common/utils/go-to.tsx
  shell/app/common/utils/index.ts
  shell/app/modules/application/pages/repo/components/branch-compare.tsx
  shell/app/modules/application/pages/repo/components/repo-breadcrumb.tsx
  shell/app/modules/application/pages/repo/components/repo-nav.tsx
  shell/app/modules/application/pages/repo/repo-branch.tsx
  shell/app/modules/application/pages/repo/repo-commit.tsx
  shell/app/modules/application/pages/repo/repo-tree.tsx
  shell/app/modules/application/services/repo.ts
  shell/app/modules/application/tabs.tsx
Labels: approved, bugfix

#3648 fix(common): hide Links
  modules/market/src/pages/download.tsx
  shell/app/App.tsx
Labels: bugfix

#3649 fix: fix notify dingtalk api path
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
Labels: bugfix

#3650 fix: delete cmp report history pagination
  shell/app/interface/global.d.ts
  shell/app/modules/cmp/pages/alarm-report/report-records/index.tsx
  shell/app/modules/cmp/router.ts
Labels: bugfix

#3651 fix: fix branch with hash tab error
  shell/app/modules/application/pages/repo/repo-tree.tsx
  shell/app/modules/application/services/repo.ts
Labels: bugfix
