Repository erda-project/erda-ui, pull requests merged in 2022-02, with the labels that each got.

#2860 fix(common): config page list operations bug
  shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
Labels: approved, bugfix

#2858 fix(common): project edit save button disabled by default
  shell/app/common/components/render-pure-form/index.tsx
  shell/app/modules/org/pages/projects/settings/info/index.tsx
  shell/app/modules/project/common/components/section-info-edit.tsx
Labels: approved, bugfix

#2863 feat: update loading animation
  shell/app/modules/msp/pages/micro-service/overview.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: feature

#2864 fix(core): make antd singleton in module feduration
  core/src/index.tsx
  core/webpack.config.js
  shell/app/App-vite.tsx
  shell/app/App.tsx
  shell/app/antd-default-props.tsx
  shell/mf.config.js
Labels: core, bugfix

#2825 feat: support configuration filter external field
  shell/app/common/components/configurable-filter/config-selector.scss
  shell/app/common/components/configurable-filter/config-selector.tsx
  shell/app/common/components/configurable-filter/external-item.scss
  shell/app/common/components/configurable-filter/external-item.tsx
  shell/app/common/components/configurable-filter/index.scss
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/common/components/render-form-item/index.tsx
  shell/app/views/index.ejs
  shell/index.html
Labels: feature, approved

#2869 fix(common): project edit bug
  shell/app/modules/org/pages/projects/settings/info/index.tsx
Labels: approved, bugfix

#2862 fix(dop): get options when opening issue detail
  shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
  shell/app/modules/project/stores/issues.ts
Labels: dop, approved, bugfix

#2871 fix(common): left menu background color bug
  shell/app/layout/pages/page-container/components/sidebar/index.scss
Labels: approved, bugfix

#2873 fix(dop): hide milestone
  shell/app/modules/project/tabs.tsx
Labels: dop, approved, bugfix

#2874 fix(dop): notify edit display bug
  shell/app/common/components/render-form-item/index.tsx
  shell/app/modules/application/pages/settings/components/app-notify/notify-config.tsx
Labels: approved, bugfix

#2872 fix(dop): notify table operation optimization
  shell/app/modules/application/pages/settings/components/app-notify/notify-config.tsx
Labels: dop, approved, bugfix

#2868 style: remove shadow in some page
  shell/app/common/components/card-container/index.scss
  shell/app/common/components/card-list/index.tsx
  shell/app/common/components/user-profile/index.tsx
  shell/app/modules/msp/env-overview/service-list/pages/index.tsx
  shell/app/modules/msp/env-overview/service-list/pages/overview.tsx
  shell/app/modules/msp/pages/micro-service/overview.tsx
  shell/app/modules/project/pages/issue/task-summary.tsx
  shell/app/modules/project/pages/resource/components/service-list.scss
  shell/app/org-home/pages/active-rank/index.tsx
  shell/app/org-home/pages/personal-contribute/index.tsx
Labels: dop, msp, approved

#2866 feat: update project initialization process and readme
  README.md
  cli/lib/init-online.ts
  cli/lib/init.ts
  cli/package.json
Labels: feature, cli, approved, chore

#2875 feat: remove useless scripts
  shell/bash/login-ssh.sh
  shell/package.json
  shell/tools/locale-babel.js
  shell/tools/manage-iconfont.js
  shell/tools/temp-variable-iconfont.json
Labels: feature, chore

#2877 fix: fix filter style in select dropdown
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/common/components/render-form-item/index.tsx
  shell/app/styles/antd-extension.scss
Labels: dop, approved, bugfix

#2865 refactor(dop): replace application table
  shell/app/common/components/table/index.tsx
  shell/app/common/index.ts
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/pages/problem/problem-list.tsx
  shell/app/modules/application/pages/test/test-list.tsx
  shell/app/modules/application/router.ts
Labels: dop, refactor, approved

#2878 fix(common): change Chinese translation of backlog
  shell/app/config-page/components/table/render-types.tsx
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/issue/subscribers-selector.tsx
Labels: approved, bugfix

#2876 feat: refactor import export in issue/test case
  locales/en.json
  locales/zh.json
  shell/app/common/components/simple-tabs/index.scss
  shell/app/common/components/simple-tabs/index.tsx
  shell/app/common/components/table/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/org/pages/projects/import-project-template.tsx
  shell/app/modules/org/pages/projects/operation-project-record.tsx
  shell/app/modules/org/pages/projects/project-list.tsx
  shell/app/modules/org/services/project-list.ts
  shell/app/modules/org/types/import-export-file-list.d.ts
  shell/app/modules/project/pages/backlog/backlog.tsx
  shell/app/modules/project/pages/backlog/iteration-item.tsx
  shell/app/modules/project/pages/issue/board.tsx
  shell/app/modules/project/pages/issue/component/import-file.tsx
  shell/app/modules/project/pages/issue/import-export.scss
  shell/app/modules/project/pages/issue/import-export.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
  shell/app/modules/project/pages/test-manage/case/header/export-file.tsx
  shell/app/modules/project/pages/test-manage/case/header/import-export-record.tsx
  shell/app/modules/project/pages/test-manage/case/header/import-file.scss
  shell/app/modules/project/pages/test-manage/case/header/import-file.tsx
  shell/app/modules/project/pages/test-manage/case/import-export.scss
  shell/app/modules/project/pages/test-manage/case/import-export.tsx
  shell/app/modules/project/pages/test-manage/case/manual-test.tsx
  shell/app/modules/project/services/issue.ts
  shell/app/modules/project/stores/issues.ts
  shell/app/modules/project/stores/test-case.ts
  shell/app/modules/project/types/test.d.ts
Labels: feature, dop, approved

#2880 fix: add pipeline update loading
  shell/app/modules/application/pages/pipeline/config-detail/index.tsx
  shell/app/modules/application/pages/pipeline/config-detail/pipeline-editor/index.tsx
  shell/app/modules/project/common/components/pipeline-manage/config-detail/index.tsx
  shell/app/modules/project/common/components/pipeline-manage/config-detail/pipeline-editor/index.tsx
  shell/app/yml-chart/pipeline-editor.tsx
Labels: dop, approved, bugfix

#2879 fix(dop): release version name checking rule change
  shell/app/modules/project/pages/release/components/form.tsx
Labels: dop, approved, bugfix

#2881 fix: fix filter style
  shell/app/common/components/configurable-filter/config-selector.tsx
  shell/app/common/components/configurable-filter/index.scss
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
Labels: dop, approved, bugfix

#2885 fix: fix configurable filter value sort error
  shell/app/common/components/configurable-filter/index.tsx
Labels: dop, approved, bugfix

#2886 fix: disable markdown editor underline plugin
  shell/app/common/components/markdown-editor/editor.tsx
  shell/app/styles/antd-extension.scss
Labels: bugfix

#2884 fix(common): table reload and config button add hover style
  shell/app/common/components/table/index.scss
  shell/app/config-page/components/table/table.tsx
Labels: bugfix

#2887 fix: always position to today after filter in gantt
  shell/app/config-page/components/gantt/components/gantt/gantt.tsx
  shell/app/config-page/components/gantt/gantt.tsx
  shell/app/config-page/components/gantt/types/public-types.ts
  shell/app/config-page/index.tsx
  shell/app/modules/project/pages/issue/gantt/index.tsx
Labels: dop, approved, bugfix

#2888 fix: repo file is notfound when refresh page
  scheduler/src/filters/not-found.filter.ts
Labels: scheduler, approved, bugfix

#2889 fix: fix filter input focus transition
  shell/app/common/components/configurable-filter/external-item.scss
Labels: approved, bugfix

#2890 fix: update alert icon and pagination button radius
  locales/en.json
  locales/zh.json
  shell/app/common/components/configurable-filter/external-item.scss
  shell/app/common/components/erda-alert/index.tsx
  shell/app/common/components/pagination/index.scss
  shell/app/common/components/pagination/index.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/msp/pages/micro-service/overview.tsx
  shell/app/modules/project/pages/release/components/form.tsx
Labels: approved, bugfix

#2892 fix(dop): export issue not pass filter params in kanban page
  shell/app/modules/project/pages/issue/board.tsx
Labels: dop, approved, bugfix

#2896 chore: change npm mirror domain from npm.taobao.org to npmmirror.com
  .npmrc
  cli/.npmrc
  core/.npmrc
  pnpm-lock.yaml
  shell/.npmrc
Labels: chore

#2900 fix(dop): addon switch environment page error
  shell/app/common/components/cards-layout/index.tsx
  shell/app/modules/addonPlatform/pages/common/components/addon-cards.tsx
Labels: dop, bugfix

#2899 fix(dop): pipeline build detail release link change to project releas…
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
Labels: dop, bugfix

#2903 fix: rename list-item class to prevent misused with tailwind
  shell/app/config-page/components/kanban/kanban.scss
  shell/app/config-page/components/kanban/kanban.tsx
  shell/app/modules/application/pages/build/build.scss
  shell/app/modules/application/pages/build/build.tsx
  shell/app/modules/org/pages/projects/issue-field-setting-modal.tsx
  shell/app/modules/project/common/components/issue/issue-drawer.scss
Labels: bugfix

#2897 fix: card component crashed in gallery page
  shell/app/config-page/components/card/card.mock.ts
  shell/app/config-page/components/card/card.tsx
  shell/app/modules/project/router.tsx
Labels: bugfix

#2906 fix: line break in markdown render code block
  shell/app/common/components/markdown-render/index.tsx
Labels: bugfix

#2898 feat(dop): project release add group
  shell/app/common/__tests__/components/list-select/list-select.test.tsx
  shell/app/common/index.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/release/components/form.tsx
  shell/app/modules/project/pages/release/components/release-select.scss
  shell/app/modules/project/pages/release/components/release-select.tsx
Labels: feature, dop, approved

#2908 fix(common): configurable filter delete config bug
  shell/app/common/components/configurable-filter/config-selector.tsx
  shell/app/common/components/render-form-item/index.tsx
Labels: approved, bugfix

#2910 fix(dop): project release group add bug
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/release/components/release-select.tsx
Labels: dop, approved, bugfix

#2911 fix(common): configurable filter tags select scroll bar style bug
  shell/app/common/components/render-form-item/index.tsx
Labels: approved, bugfix

#2917 fix(common): tagsSelect supports radio selection
  shell/app/common/components/render-form-item/index.tsx
Labels: bugfix

#2916 fix(dop): create project release style bug
  shell/app/modules/project/pages/release/components/form.tsx
  shell/app/modules/project/pages/release/components/release-select.scss
  shell/app/modules/project/pages/release/components/release-select.tsx
Labels: dop, bugfix

#2920 fix(dop): project release group edit bug
  shell/app/modules/project/pages/release/components/form.tsx
  shell/app/modules/project/pages/release/components/release-select.tsx
Labels: dop, bugfix

#2919 fix(msp): fixed tips not be fully displayed
  shell/app/charts/utils/formatter.js
  shell/app/modules/msp/alarm-manage/overview/base-overview.tsx
Labels: msp, bugfix

#2918 fix: fix config file upload params
  shell/app/modules/application/pages/settings/components/app-variable-config.tsx
  shell/app/modules/application/pages/settings/components/variable-config-form.tsx
Labels: dop, bugfix

#2925 fix: fix import export record params error
  shell/app/modules/org/services/project-list.ts
  shell/app/modules/project/pages/issue/import-export.tsx
Labels: dop, approved, bugfix

#2928 fix(dop): project release group style bug
  shell/app/modules/project/pages/release/components/form.tsx
Labels: dop, approved, bugfix

#2929 feat(msp): adjust alarm router
  locales/en.json
  locales/zh.json
  shell/app/common/utils/go-to.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/cmp.tsx
  shell/app/modules/cmp/router.ts
  shell/app/modules/msp/alarm-manage/alarm-strategy/index.js
  shell/app/modules/msp/alarm-manage/index.ts
  shell/app/modules/msp/config.tsx
  shell/app/modules/msp/types/index.d.ts
Labels: feature, msp

#2932 fix: fix member selector dropdown width error
  shell/app/common/components/load-more-selector/index.tsx
Labels: dop, approved, bugfix

#2934 fix(dop): project release filter empty groups
  shell/app/modules/project/pages/release/components/form.tsx
Labels: dop, approved, bugfix

#2935 fix(common): load more selector icon change
  shell/app/common/components/load-more-selector/index.tsx
Labels: bugfix

#2937 fix(msp): modify params & remove page wrapper
  shell/app/modules/msp/alarm-manage/alarm-record/index.ts
  shell/app/modules/msp/alarm-manage/alarm-strategy/index.js
  shell/app/modules/msp/alarm-manage/index.ts
  shell/app/modules/msp/alarm-manage/overview/index.tsx
Labels: msp, bugfix

#2939 feat: update pipeline
  pipeline.yml
Labels: feature

#2948 fix(msp): fix sort key
  shell/app/config-page/components/table/v2/table.tsx
Labels: msp, bugfix

#2943 feat(dop): project release add resource
  shell/app/modules/project/pages/release/components/application-detail.tsx
Labels: approved

#2944 feat: add create project in project list
  locales/en.json
  locales/zh.json
  shell/app/modules/dop/pages/projects/project-list-protocol.tsx
Labels: feature, dop, approved

#2947 feat: add gantt import export
  shell/app/modules/project/pages/issue/gantt/index.tsx
  shell/app/modules/project/pages/issue/import-export.tsx
Labels: feature, dop, approved

#2949 fix(dop): repo tree table columns width optimization
  shell/app/modules/application/pages/repo/repo-tree.tsx
Labels: dop, approved, bugfix

#2950 fix(msp): add inParams into forceUpdate
  shell/app/modules/msp/alarm-manage/alert-list/events/base-event-detail.tsx
Labels: msp, approved, bugfix

#2941 feat: Do not drill down at the application level and change the menu to tabs
  locales/en.json
  locales/zh.json
  shell/app/common/components/configurable-filter/config-selector.tsx
  shell/app/common/components/configurable-filter/index.tsx
  shell/app/common/components/erda-alert/index.tsx
  shell/app/common/components/markdown-render/index.tsx
  shell/app/common/components/menu/index.tsx
  shell/app/common/components/radio-tabs/index.tsx
  shell/app/common/types/route.d.ts
  shell/app/common/utils/go-to.tsx
  shell/app/interface/global.d.ts
  shell/app/layout/pages/page-container/components/header.scss
  shell/app/layout/pages/page-container/components/header.tsx
  shell/app/layout/pages/tab/tab.tsx
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/application.tsx
  shell/app/menus/index.ts
  shell/app/modules/application/common/app-selector.tsx
  shell/app/modules/application/entry.js
  shell/app/modules/application/pages/problem/index.tsx
  shell/app/modules/application/pages/problem/problem-detail.scss
  shell/app/modules/application/pages/problem/problem-detail.tsx
  shell/app/modules/application/pages/problem/problem-form.tsx
  shell/app/modules/application/pages/problem/problem-list.tsx
  shell/app/modules/application/pages/quality/entry.tsx
  shell/app/modules/application/pages/quality/index.tsx
  shell/app/modules/application/pages/repo/repo-branch.tsx
  shell/app/modules/application/pages/repo/repo-mr.tsx
  shell/app/modules/application/pages/test/test-detail-container.tsx
  shell/app/modules/application/pages/test/test-detail.tsx
  shell/app/modules/application/pages/test/test-list.tsx
  shell/app/modules/application/router.ts
  shell/app/modules/application/services/problem.ts
  shell/app/modules/application/stores/application.tsx
  shell/app/modules/application/stores/problem.ts
  shell/app/modules/application/stores/repo.ts
  shell/app/modules/application/stores/test.ts
  shell/app/modules/application/tabs.tsx
  shell/app/modules/project/router.tsx
  shell/app/user/stores/_perm-app.ts
Labels: feature, dop, refactor, approved

#2951 fix: remove duplicate const variable
  shell/app/modules/dop/pages/projects/project-list-protocol.tsx
Labels: approved, bugfix

#2953 fix(msp): remove noWrapper from the alarm strategy
  shell/app/modules/msp/alarm-manage/alarm-strategy/index.js
Labels: msp, approved, bugfix

#2952 feat(msp): replace Tag with Badge in MSP project list
  shell/app/modules/msp/pages/micro-service/overview.tsx
Labels: feature, msp, approved

#2954 fix(common): empty holder scroll bar bug
  shell/app/common/components/empty-holder/index.tsx
Labels: approved, bugfix

#2956 fix(dop): project selector style optimization
  shell/app/common/components/load-more-selector/index.tsx
Labels: dop, approved, bugfix

#2957 feat: remove unused application level release and deploy files
  shell/app/interface/global.d.ts
  shell/app/modules/application/entry.js
  shell/app/modules/application/pages/deploy/deploy.scss
  shell/app/modules/application/pages/deploy/deploy.tsx
  shell/app/modules/application/pages/deploy/env-card.scss
  shell/app/modules/application/pages/deploy/env-card.tsx
  shell/app/modules/application/pages/deploy/runtime-box.scss
  shell/app/modules/application/pages/deploy/runtime-box.tsx
  shell/app/modules/application/pages/release/components/release-detail-edit.tsx
  shell/app/modules/application/pages/release/components/release-detail-info.tsx
  shell/app/modules/application/pages/release/components/release-detail-yml.tsx
  shell/app/modules/application/pages/release/components/release-detail.scss
  shell/app/modules/application/pages/release/components/release-detail.tsx
  shell/app/modules/application/pages/release/components/release-item.scss
  shell/app/modules/application/pages/release/components/release-item.tsx
  shell/app/modules/application/pages/release/release-list.scss
  shell/app/modules/application/pages/release/release-list.tsx
  shell/app/modules/application/router.ts
  shell/app/modules/application/services/deploy.ts
  shell/app/modules/application/services/release.ts
  shell/app/modules/application/stores/deploy.ts
  shell/app/modules/application/stores/release.ts
  shell/app/modules/publisher/pages/artifacts/version-form-modal.tsx
  shell/app/modules/runtime/router.ts
Labels: feature, dop, refactor

#2958 feat: Unify application level page title to "application"
  locales/en.json
  locales/zh.json
  shell/app/common/types/route.d.ts
  shell/app/interface/global.d.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/common/app-selector.tsx
  shell/app/modules/application/router.ts
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
  shell/app/modules/runtime/stores/runtime.ts
Labels: feature, dop, approved

#2960 feat: update list batch operation icon data
  shell/app/config-page/components/base-list/base-list.tsx
  shell/app/config-page/components/common.spec.d.ts
Labels: feature, dop, approved

#2962 fix(dop): problem detail style bug
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/problem/problem-detail.tsx
Labels: dop, bugfix

#2961 fix(msp): fix datePicker validate
  shell/app/configForm/nusi-form/form-items/date-picker.tsx
Labels: msp, bugfix

#2959 feat: update back style in tab
  shell/app/common/components/menu/index.tsx
  shell/app/interface/global.d.ts
  shell/app/modules/application/router.ts
  shell/app/modules/application/tabs.tsx
  shell/app/modules/project/router.tsx
  shell/app/modules/project/tabs.tsx
Labels: feature

#2963 fix: update application jump link to project level page
  shell/app/common/utils/go-to.tsx
  shell/app/config-page/mock/crud.mock.ts
  shell/app/modules/addonPlatform/pages/common/components/addon-detail-drawer.tsx
  shell/app/modules/application/common/app-list-protocol.tsx
  shell/app/modules/application/pages/build-detail/index.tsx
  shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
  shell/app/modules/application/pages/problem/problem-list.tsx
  shell/app/modules/application/pages/quality/entry.tsx
  shell/app/modules/application/pages/quality/index.tsx
  shell/app/modules/application/pages/repo/repo-tree.tsx
  shell/app/modules/application/tabs.tsx
  shell/app/modules/cmp/common/addon-detail/detail.tsx
  shell/app/modules/cmp/pages/domain-manage/index.tsx
  shell/app/modules/cmp/pages/tasks/task-list.tsx
  shell/app/modules/org/common/audit-templates.json
  shell/app/modules/project/pages/deploy/add-deploy/index.tsx
  shell/app/modules/project/pages/deploy/deploy-config/index.tsx
  shell/app/modules/project/pages/deploy/index.tsx
  shell/app/modules/project/router.tsx
Labels: dop, bugfix

#2966 fix: fix create project style in project list
  locales/en.json
  locales/zh.json
  shell/app/modules/dop/pages/projects/project-list-protocol.tsx
Labels: dop, approved, bugfix

#2967 fix: fix kanban request twice when switch type
  shell/app/modules/project/pages/issue/board.tsx
Labels: approved, bugfix

#2968 fix: return to first page after filter value change
  shell/app/modules/application/pages/problem/problem-list.tsx
Labels: dop, approved, bugfix

#2965 feat: add issue relation on create mr
  shell/app/modules/application/pages/repo/components/repo-mr-form.scss
  shell/app/modules/application/pages/repo/components/repo-mr-form.tsx
  shell/app/modules/application/pages/repo/components/source-target-select.tsx
  shell/app/modules/application/pages/repo/repo-mr-creation.tsx
  shell/app/modules/application/router.ts
  shell/app/modules/application/stores/repo.ts
  shell/app/modules/application/types/repo.d.ts
  shell/app/modules/project/common/components/issue/issue-relation.tsx
  shell/app/modules/project/services/issue.ts
  shell/app/modules/project/types/issue.d.ts
  shell/app/styles/util.scss
Labels: feature, dop, approved

#2971 fix: change to check and redirect tab key
  shell/app/modules/application/tabs.tsx
Labels: approved, bugfix

#2973 fix: problem detail not refresh after comment or close
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/problem/problem-detail.tsx
  shell/app/modules/application/pages/problem/problem-form.tsx
  shell/app/modules/application/pages/problem/problem-list.tsx
Labels: approved, bugfix

#2976 fix: deploy env config can not switch
  shell/app/modules/project/pages/deploy/deploy-config/index.tsx
  shell/app/modules/project/router.tsx
  shell/app/modules/runtime/pages/overview/components/index.tsx
  shell/app/modules/runtime/pages/overview/components/info.tsx
Labels: bugfix

#2977 fix(dop): application release edit optimization
  shell/app/modules/project/pages/release/components/application-detail.tsx
Labels: dop, approved, bugfix

#2978 fix(dop): tab info should disable click
  shell/app/common/components/menu/index.tsx
  shell/app/layout/pages/page-container/components/header.scss
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/router.ts
  shell/app/modules/application/tabs.tsx
  shell/app/modules/project/tabs.tsx
Labels: dop, bugfix

#2980 fix(dop): application release detail resource bug
  shell/app/modules/project/pages/release/components/application-detail.tsx
Labels: dop, approved, bugfix

#2983 fix: fix deploy runtime tab click error
  shell/app/modules/project/tabs.tsx
Labels: dop, approved, bugfix

#2984 feat(dop): update project deploy app list
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/deploy/add-deploy/index.tsx
  shell/app/modules/project/pages/deploy/deploy-detail/index.tsx
  shell/app/modules/project/pages/release/components/form.tsx
  shell/app/modules/project/pages/release/components/release-select.scss
  shell/app/modules/project/pages/release/components/release-select.tsx
  shell/app/modules/project/types/deploy.d.ts
Labels: feature, dop, approved

#2981 chore: update build community image pipeline yml
  .erda/pipelines/ci-build-ce.yml
  pipeline.yml
Labels: approved, chore

#2987 fix: fix apply unblock params type
  shell/app/modules/dop/pages/projects/project-list-protocol.tsx
Labels: dop, approved, bugfix

#2990 chore: update staging domain in auto test
  shell/auto_test/README.md
  shell/auto_test/login.spec.ts
  shell/auto_test/tests/admin/audit.spec.ts
  shell/auto_test/tests/admin/cluster-manage.spec.ts
  shell/auto_test/tests/admin/global-config.spec.ts
  shell/auto_test/tests/admin/org-manage.spec.ts
  shell/auto_test/tests/admin/user-manage.spec.ts
  shell/auto_test/tests/dop/add-ticket.spec.ts
  shell/auto_test/tests/dop/deploy.spec.ts
  shell/auto_test/tests/dop/history.spec.ts
  shell/auto_test/tests/dop/layout.spec.ts
  shell/auto_test/tests/dop/pipeline.spec.ts
  shell/auto_test/tests/dop/repo.spec.ts
  shell/auto_test/tests/org/audit-log.spec.ts
  shell/auto_test/tests/org/mobile-development-management.spec.ts
  shell/auto_test/tests/org/organization-information.spec.ts
  shell/package.json
Labels: approved, test

#2989 fix: missing build_cmd in pipeline yml
  .erda/pipelines/ci-build-ce.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, bugfix

#2992 ci: add tag version & remove useless push hack
  .github/workflows/git-sync.yml
  pipeline.yml
Labels: approved

#2996 fix: fix deploy runtime tab title
  shell/app/modules/project/tabs.tsx
Labels: dop, approved, bugfix

#2993 chore: update staging domain to daily
  .github/PULL_REQUEST_TEMPLATE.md
  shell/app/modules/project/pages/deploy/deploy-detail/index.tsx
  shell/app/modules/project/types/deploy.d.ts
  shell/auto_test/README.md
  shell/auto_test/login.spec.ts
  shell/auto_test/tests/admin/audit.spec.ts
  shell/auto_test/tests/admin/cluster-manage.spec.ts
  shell/auto_test/tests/admin/global-config.spec.ts
  shell/auto_test/tests/admin/org-manage.spec.ts
  shell/auto_test/tests/admin/user-manage.spec.ts
  shell/auto_test/tests/dop/add-ticket.spec.ts
  shell/auto_test/tests/dop/deploy.spec.ts
  shell/auto_test/tests/dop/history.spec.ts
  shell/auto_test/tests/dop/layout.spec.ts
  shell/auto_test/tests/dop/pipeline.spec.ts
  shell/auto_test/tests/dop/repo.spec.ts
  shell/auto_test/tests/org/audit-log.spec.ts
  shell/auto_test/tests/org/mobile-development-management.spec.ts
  shell/auto_test/tests/org/organization-information.spec.ts
  shell/package.json
Labels: approved, chore

#2991 fix(dop): fix placeholder style
  shell/app/common/components/load-more-selector/index.scss
Labels: dop, approved, bugfix

#2994 feat(msp): add filter by name and ruleCount column for alert config
  locales/en.json
  locales/zh.json
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/application/types/common-notify-group.d.ts
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
  shell/app/modules/cmp/common/custom-alarm/index.tsx
  shell/app/modules/cmp/types/alarm-strategy.d.ts
  shell/app/modules/cmp/types/custom-alarm.d.ts
Labels: feature, msp, approved

#3000 fix(dop): fix tabs not display when there is too much content
  shell/app/modules/project/pages/release/components/application-detail.tsx
  shell/app/modules/project/pages/release/components/form.scss
Labels: dop, approved, bugfix

#3001 fix(dop): fix button disable judgment logic
  shell/app/modules/project/pages/deploy/add-deploy/index.tsx
  shell/app/modules/project/types/deploy.d.ts
Labels: dop, approved, bugfix

#2995 fix(dop): fix user avatar
  shell/app/common/components/user-info/index.tsx
  shell/app/config-page/components/table/v2/utils.tsx
  shell/app/modules/application/pages/repo/common.tsx
  shell/app/modules/application/pages/repo/components/repo-mr-table.tsx
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/project/common/components/issue/issue-activities.tsx
  shell/app/modules/project/pages/backlog/issue-item.tsx
  shell/app/modules/project/pages/plan-detail/common-comp.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/case-meta.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
  shell/app/modules/runtime/pages/overview/components/activity.tsx
Labels: dop, approved, bugfix

#2998 feat(dop): project pipeline table add yml file
  shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
Labels: feature, dop, approved

#2997 fix(common): configurable filter bug when form items depend on each other
  shell/app/common/components/configurable-filter/index.tsx
Labels: approved, bugfix

#3005 fix(dop): fix user avatar (#2995)
  shell/app/common/components/user-info/index.tsx
  shell/app/config-page/components/table/v2/utils.tsx
  shell/app/modules/application/pages/repo/common.tsx
  shell/app/modules/application/pages/repo/components/repo-mr-table.tsx
  shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
  shell/app/modules/project/common/components/issue/issue-activities.tsx
  shell/app/modules/project/pages/backlog/issue-item.tsx
  shell/app/modules/project/pages/plan-detail/common-comp.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/case-meta.tsx
  shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
  shell/app/modules/runtime/pages/overview/components/activity.tsx
Labels: dop, bugfix

#3006 fix: fix date picker value update error
  shell/app/config-page/components/date-picker/date-picker.tsx
Labels: dop, approved, bugfix

#3010 fix(msp): fix time format
  shell/app/charts/utils/formatter.js
Labels: msp, bugfix

#3009 feat: create release add latest filter
  shell/app/modules/project/pages/release/components/form.tsx
Labels: feature, dop, approved

#3012 fix: fix deploy runtime loading img
  shell/app/images/default-loading.gif
Labels: dop, approved, bugfix

#3013 fix: create release style bug in firefox
  shell/app/modules/project/pages/release/components/form.tsx
Labels: dop, approved, bugfix

#3019 fix(dop): create release style bug
  shell/app/modules/project/pages/release/components/release-select.tsx
Labels: dop, approved, bugfix

#3023 fix(common): configurable filter required form item remove the clear button
  shell/app/common/components/configurable-filter/index.tsx
Labels: approved, bugfix

#3021 fix(dop): create release application filter bug
  shell/app/modules/project/pages/release/components/form.tsx
Labels: dop, approved, bugfix

#3022 fix(dop): fix pipeline popover
  shell/app/modules/application/pages/build-detail/pipeline-chart/pipeline-node.tsx
  shell/app/modules/application/pages/pipeline/run-detail/pipeline-chart/pipeline-node.tsx
  shell/app/modules/project/common/components/pipeline-manage/run-detail/pipeline-chart/run-case-node.tsx
  shell/app/yml-chart/chart/yml-chart.tsx
Labels: dop, approved, bugfix

#2964 feat(msp): replace antd table with erdaTable
  shell/app/modules/msp/monitor/api-insight/common/components/apiDelayPanel.tsx
  shell/app/modules/msp/monitor/api-insight/common/components/apiSizePanel.tsx
  shell/app/modules/msp/monitor/api-insight/common/components/topPVPanel.tsx
  shell/app/modules/msp/monitor/monitor-common/components/chartFactory.tsx
  shell/app/modules/msp/query-analysis/custom-dashboard/index.ts
  shell/app/modules/msp/router.ts
  shell/app/modules/msp/types/gateway.d.ts
Labels: feature, msp, approved
