Repository erda-project/erda-ui, pull requests merged in 2023-05, with the labels that each got.

#3817 feat: add ticket import
  shell/app/modules/project/pages/ticket/index.tsx
Labels: feature

#3818 feat: Sustained performance analysis
  pnpm-lock.yaml
  shell/app/common/stores/monitorCommon.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/msp.tsx
  shell/app/modules/addonPlatform/pages/common/components/addon-cards.tsx
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
  shell/app/modules/cmp/common/custom-alarm/index.tsx
  shell/app/modules/msp/monitor/api-insight/pages/delay/index.tsx
  shell/app/modules/msp/monitor/api-insight/pages/indices/config/apiConfig.ts
  shell/app/modules/msp/monitor/api-insight/pages/request/index.tsx
  shell/app/modules/msp/monitor/api-insight/pages/transport/index.tsx
  shell/app/modules/msp/monitor/browser-insight/common/components/sort-list/sortFactory.tsx
  shell/app/modules/msp/monitor/gateway-ingress/common/components/domain-selector.tsx
  shell/app/modules/msp/monitor/gateway-ingress/pages/latency/latency.tsx
  shell/app/modules/msp/monitor/gateway-ingress/pages/qps/qps.tsx
  shell/app/modules/msp/monitor/gateway-ingress/pages/traffic/traffic.tsx
  shell/app/modules/msp/monitor/monitor-common/components/chartFactory.tsx
  shell/app/modules/msp/monitor/monitor-common/components/sort-list/sortFactory.tsx
  shell/package.json
  shell/tsconfig-webpack.json
  shell/tsconfig.json
  shell/vite.config.js
  shell/webpack.config.js
Labels: feature

#3819 feat: sustained performance analysis
  pnpm-lock.yaml
  shell/app/App-vite.tsx
  shell/app/App.tsx
  shell/app/common/stores/monitorCommon.ts
  shell/app/layout/stores/layout.ts
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/menus/appCenter.tsx
  shell/app/menus/msp.tsx
  shell/app/modules/addonPlatform/pages/common/components/addon-cards.tsx
  shell/app/modules/cmp/common/alarm-strategy/index.tsx
  shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
  shell/app/modules/cmp/common/custom-alarm/index.tsx
  shell/app/modules/extra/entry.js
  shell/app/modules/msp/monitor/api-insight/pages/delay/index.tsx
  shell/app/modules/msp/monitor/api-insight/pages/indices/config/apiConfig.ts
  shell/app/modules/msp/monitor/api-insight/pages/request/index.tsx
  shell/app/modules/msp/monitor/api-insight/pages/transport/index.tsx
  shell/app/modules/msp/monitor/browser-insight/common/components/sort-list/sortFactory.tsx
  shell/app/modules/msp/monitor/gateway-ingress/common/components/domain-selector.tsx
  shell/app/modules/msp/monitor/gateway-ingress/pages/latency/latency.tsx
  shell/app/modules/msp/monitor/gateway-ingress/pages/qps/qps.tsx
  shell/app/modules/msp/monitor/gateway-ingress/pages/traffic/traffic.tsx
  shell/app/modules/msp/monitor/monitor-common/components/chartFactory.tsx
  shell/app/modules/msp/monitor/monitor-common/components/sort-list/sortFactory.tsx
  shell/package.json
  shell/tsconfig-webpack.json
  shell/tsconfig.json
  shell/vite.config.js
  shell/webpack.config.js
Labels: feature

#3820 fix: update erda-pyroscope
  pnpm-lock.yaml
  shell/package.json
Labels: bugfix

#3822 fix: update erda-pyroscope
  pnpm-lock.yaml
  shell/package.json
Labels: bugfix

#3823 fix: dependency version conflict
  core/src/index.tsx
  modules/market/src/App.tsx
  modules/uc/src/router.tsx
Labels: bugfix

#3824 fix: sustained performance analysis display bug
  pnpm-lock.yaml
  shell/package.json
Labels: bugfix

#3825 fix: pnpm run build-online bug
  modules/market/src/App.tsx
  modules/uc/src/router.tsx
Labels: bugfix

#3826 fix: build online bug
  modules/market/src/App.tsx
  modules/market/src/pages/download-pc.tsx
  modules/market/src/pages/download.tsx
  modules/uc/src/router.tsx
  shell/package.json
Labels: bugfix

#3827 fix: update pnpm-pock
  pnpm-lock.yaml
Labels: bugfix

#3828 fix: org setting style bug
  shell/app/styles/antd-extension.scss
Labels: bugfix

#3832 fix: pyroscope timeline select bug
  package.json
  pipeline.yml
  pnpm-lock.yaml
  shell/package.json
Labels: approved, bugfix

#3833 fix: update pyroscope version
  package.json
  pipeline.yml
  pnpm-lock.yaml
  shell/package.json
Labels: bugfix

#3834 feat: iteration add work hours
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/pages/iteration/iteration-modal.tsx
  shell/app/modules/project/pages/iteration/table.tsx
Labels: feature

#3835 fix: update pyroscope version
  package.json
  pnpm-lock.yaml
  shell/package.json
Labels: bugfix

#3837 fix: iteration work hours bug
  package.json
  pnpm-lock.yaml
  shell/app/locales/zh.json
  shell/app/modules/project/pages/iteration/iteration-modal.tsx
  shell/package.json
Labels: bugfix

#3836 fix: index page layout bug
  core/src/framework/regist-router.tsx
Labels: bugfix

#3838 feat: all issues add import button
  shell/app/modules/project/pages/issue/import-export.tsx
  shell/app/modules/project/pages/issue/issue-protocol.tsx
Labels: feature

#3839 fix: iteration work hours validator bug
  shell/app/config-page/components/line-graph/index.tsx
  shell/app/modules/project/pages/iteration/iteration-modal.tsx
Labels: approved, bugfix
