Repository erda-project/erda-ui, pull requests merged in 2023-12, with the labels that each got.

#3963 fix: log analyze console url application_id missing `dice` prefix
  shell/app/modules/runtime/pages/overview/components/index.tsx
Labels: approved, bugfix

#3964 fix: mr ai comment user display bug
  shell/app/modules/application/pages/repo/components/mr-comments.tsx
  shell/app/modules/dop/pages/report/index.tsx
Labels: bugfix

#3965 fix: mr ai comment type error
  shell/app/modules/application/types/repo.d.ts
Labels: bugfix

#3968 fix: ai code block level code review optimization
  shell/app/modules/application/pages/repo/components/file-diff.tsx
Labels: bugfix

#3969 fix: ai code block level code review single check bug
  shell/app/modules/application/pages/repo/components/file-diff.tsx
Labels: bugfix

#3970 fix: ai file level code review bug
  shell/app/modules/application/pages/repo/components/file-diff.tsx
Labels: bugfix

#3971 fix: only one code comment is allowed
  shell/app/modules/application/pages/repo/components/file-diff.tsx
Labels: bugfix

#3972 fix: ai code review regenerate bug
  locales/en.json
  locales/zh.json
  shell/app/modules/application/pages/repo/components/file-diff.tsx
Labels: bugfix

#3973 fix: closed mr disable review
  locales/en.json
  locales/zh.json
  shell/app/modules/application/pages/repo/components/file-diff.tsx
Labels: approved, bugfix

#3975 fix: mr ai review optimization
  shell/app/modules/application/pages/repo/components/file-diff.tsx
Labels: approved, bugfix

#3976 fix: mr review show style change bug
  shell/app/modules/application/pages/repo/components/file-diff.tsx
Labels: bugfix

#3980 feat: update version
  VERSION
Labels: feature, approved

#3982 fix: mr review comments line index display optimization
  shell/app/modules/application/pages/repo/components/file-diff.tsx
  shell/app/modules/application/types/repo.d.ts
Labels: bugfix

#3984 fix: mr file review style optimization
  shell/app/modules/application/pages/repo/components/file-diff.tsx
Labels: bugfix
