Repository erda-project/erda-ui, pull requests merged in 2023-06, with the labels that each got.

#3840 feat: issue estimated time required
  shell/app/locales/en.json
  shell/app/locales/zh.json
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
Labels: feature

#3841 fix: issue estimated time bug
  shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
  shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
Labels: bugfix

#3842 fix: iteration work hours optimization
  shell/app/modules/project/common/components/issue/time-input.tsx
  shell/app/modules/project/pages/iteration/iteration-modal.tsx
Labels: bugfix

#3845 fix: market download page bug
  modules/market/src/pages/download.tsx
Labels: bugfix

#3847 fix: fix typo
  shell/app/locales/zh.json
Labels: bugfix

#3850 feat: translate in msp
  shell/app/locales/en.json
  shell/app/locales/zh.json
Labels: feature

#3852 fix: service monitoring charts click bug
  shell/app/charts/components/echarts.jsx
Labels: bugfix

#3853 fix: service monitoring charts click bug test
  shell/app/charts/components/echarts.jsx
Labels: approved

#3854 feat: service monitoring chart click bug
  shell/app/charts/components/echarts.jsx
  shell/app/modules/dop/services/index.ts
Labels: feature

#3855 fix: trace search log bug
  shell/app/common/components/menu/index.tsx
  shell/app/common/components/pure-log-roller/log-content.tsx
  shell/app/common/components/pure-log-roller/log-roller.tsx
Labels: bugfix

#3856 fix: breadcrumb menu click bug
  shell/app/common/components/menu/index.tsx
Labels: approved, bugfix

#3857 fix: service monitoring charts select optimization
  shell/app/charts/components/echarts.jsx
Labels: bugfix

#3858 fix: charts remove brush tool
  shell/app/charts/components/echarts.jsx
Labels: bugfix
