Repository erda-project/erda-ui, pull requests merged in 2023-11, with the labels that each got.

#3939 fix: pipeline history internationalization bug
  locales/en.json
  locales/zh.json
  shell/app/modules/application/pages/build-detail/config.tsx
  shell/app/modules/application/pages/obsoleted-pipeline/run-detail/config.tsx
  shell/app/modules/project/common/components/pipeline-manage/run-detail/config.ts
  shell/app/modules/project/common/components/pipeline-new/config.tsx
Labels: bugfix

#3941 fix: issues iteration table work hours optimization
  shell/app/modules/project/common/components/issue/time-input.tsx
  shell/app/modules/project/pages/iteration/table.tsx
Labels: bugfix

#3942 fix: project menus load time optimization
  shell/app/modules/project/stores/project.tsx
Labels: bugfix

#3943 fix: project report detail reopen rate page jump optimization
  shell/app/modules/dop/pages/report/index.tsx
Labels: bugfix

#3944 fix: project info edit labels bug
  shell/app/modules/org/pages/projects/settings/info/index.tsx
  shell/app/modules/project/common/components/section-info-edit.tsx
Labels: bugfix

#3945 fix: backlog table add issue style bug
  shell/app/modules/project/pages/backlog/issue-item.scss
  shell/app/modules/project/pages/backlog/issue-item.tsx
Labels: bugfix

#3951 fix: iteration add form work hours validate optimization
  shell/app/modules/project/common/components/issue/time-input.tsx
Labels: bugfix

#3952 fix: add missing params let cmp container download logs from apiserver
  shell/app/modules/cmp/pages/cluster-container/cluster-terminal.tsx
Labels: bugfix

#3953 fix: namespace param typo in log file url
  shell/app/modules/cmp/pages/cluster-container/cluster-terminal.tsx
Labels: approved, bugfix

#3954 fix: ai test requirement list optimization
  shell/app/layout/pages/page-container/components/chat-GPT/functional-test-cases/requirements-list.tsx
Labels: bugfix

#3955 feat: workbench personal report optimization
  locales/en.json
  locales/zh.json
Labels: feature

#3956 fix: clusters history table pagination bug
  shell/app/modules/cmp/pages/cluster-manage/operation-history.tsx
Labels: bugfix

#3958 fix: ai test requirement list bug in msp
  shell/app/layout/pages/page-container/components/chat-GPT/functional-test-cases/requirements-list.tsx
Labels: bugfix

#3959 fix: project pipeline logs interface params optimization
  shell/app/modules/project/common/components/pipeline-new/detail/build-log.tsx
  shell/app/modules/project/common/components/pipeline-new/detail/execute.tsx
Labels: bugfix

#3960 fix: ai test system prompt optimization
  shell/app/layout/pages/page-container/components/chat-GPT/functional-test-cases/desc-list.tsx
  shell/app/layout/pages/page-container/components/chat-GPT/functional-test-cases/index.tsx
  shell/app/layout/services/ai-test.ts
Labels: approved, bugfix

#3961 feat: ai test optimization
  locales/en.json
  locales/zh.json
  shell/app/layout/pages/page-container/components/chat-GPT/functional-test-cases/desc-list.tsx
  shell/app/layout/services/ai-test.ts
Labels: feature

#3962 feat: ai file level code review
  locales/en.json
  locales/zh.json
  shell/app/modules/application/pages/repo/components/compare-detail.tsx
  shell/app/modules/application/pages/repo/components/file-diff.tsx
  shell/app/modules/application/pages/repo/components/mr-comments.tsx
  shell/app/modules/application/services/repo.ts
  shell/app/modules/application/types/repo.d.ts
Labels: feature
